/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.Andre.TateChartMap
import TemperedFundamentalGroups.Andre.TateCrossingField
import TemperedFundamentalGroups.SemistableReduction.W10Assembly

/-!
# The Tate model over `O'` presented over `O` (Blueprint §10.3.8, `v(q) = 1`, B3b)

Let `K'/K` be a finite extension, `O' ⊆ K'` a DVR over `O` generated by `θ₁, …, θ_r` over `O`, and
`π, b₄, b₆ ∈ O'` Tate data. The projective `O'`-model `projModelCode O' (coords)` of the Tate
function field `L = TateField π b₄ b₆` is isomorphic to the projective `O`-model of the family
`(θ_s · coords)` (`modelIsoO`, from `ProjScheme.baseChangeIsoFin`). For a ring `T` with
`O' → T` and a point of the Tate curve, `jO : Spec T ⟶` (`O`-model) is the chart point `jChart`
transported along this isomorphism; it lies over `O` (`jO_toSpec`).
-/

universe u

open CategoryTheory AlgebraicGeometry SemistableReduction.ProjScheme

namespace TemperedFundamentalGroups.TateRestrict

noncomputable section

variable (O : Type u) [CommRing O] {K' : Type u} [Field K']
  {O' : ValuationSubring K'} [IsDiscreteValuationRing O'] [Algebra O O']
  (π b₄ b₆ : O') [Fact (Squarefree (TateNormal.dpoly π b₄ b₆))]

local notation "L" => TateNormal.TateField π b₄ b₆


variable {r : ℕ} (θ : Fin r → O') (hθ0 : ∀ s, (θ s : K') ≠ 0)

/-- The generators in the function field. -/
def θL : Fin r → L := fun s ↦ algebraMap O' L (θ s)

omit [IsDiscreteValuationRing O'] [Fact (Squarefree (TateNormal.dpoly π b₄ b₆))] in
include hθ0 in
lemma θL_ne_zero (s : Fin r) : θL π b₄ b₆ θ s ≠ 0 := by
  intro h
  exact hθ0 s (congrArg Subtype.val (TateNormal.algebraMap_O_injective π b₄ b₆
    (h.trans (map_zero _).symm)))

variable (hθint : ∀ s, IsIntegral O (θ s))
  (hθgen : ∀ y : O', y ∈ Subring.closure (((algebraMap O O').range : Set O') ∪ Set.range θ))

omit [IsDiscreteValuationRing O'] [Fact (Squarefree (TateNormal.dpoly π b₄ b₆))] in
include hθint in
lemma θL_isIntegral (s : Fin r) : IsIntegral O (θL π b₄ b₆ θ s) :=
  IsIntegral.map_of_comp_eq (RingHom.id O) (algebraMap O' L)
    (by ext o; simp [IsScalarTower.algebraMap_apply O O' L]) (hθint s)

omit [IsDiscreteValuationRing O'] [Fact (Squarefree (TateNormal.dpoly π b₄ b₆))] in
include hθgen in
lemma range_le_closure :
    (algebraMap O' L).range ≤ Subring.closure
      (((algebraMap O L).range : Set L) ∪ Set.range (θL π b₄ b₆ θ)) := by
  rintro _ ⟨y, rfl⟩
  have h : algebraMap O' L y ∈ (Subring.closure _).map (algebraMap O' L) :=
    Subring.mem_map.2 ⟨_, hθgen y, rfl⟩
  rw [RingHom.map_closure, Set.image_union] at h
  refine Subring.closure_mono (Set.union_subset_union ?_ ?_) h
  · rintro _ ⟨_, ⟨o, rfl⟩, rfl⟩
    exact ⟨o, (IsScalarTower.algebraMap_apply O O' L o).symm⟩
  · rintro _ ⟨_, ⟨s, rfl⟩, rfl⟩
    exact ⟨s, rfl⟩

omit [IsDiscreteValuationRing O'] [Fact (Squarefree (TateNormal.dpoly π b₄ b₆))] in
lemma range_le_range : (algebraMap O L).range ≤ (algebraMap O' L).range := by
  rintro _ ⟨o, rfl⟩
  exact ⟨algebraMap O O' o, (IsScalarTower.algebraMap_apply O O' L o).symm⟩

variable (hπ0 : π ≠ 0)

/-- **The Tate model over `O'`, presented over `O`.** -/
abbrev modelO : TemperedFundamentalGroups.ModelCode O :=
  projModelCode O (thetasFamily_ne_zero (θL_ne_zero π b₄ b₆ θ hθ0)
    (TateNormal.hcoords π b₄ b₆ hπ0))

/-- `modelO ≅ projModelCode O' (coords)`. -/
def modelIsoO : (modelO O π b₄ b₆ θ hθ0 hπ0).scheme ≅
    (projModelCode O' (TateNormal.hcoords π b₄ b₆ hπ0)).scheme :=
  baseChangeIsoFin rfl rfl (θL_ne_zero π b₄ b₆ θ hθ0) (θL_isIntegral O π b₄ b₆ θ hθint)
    (fun s ↦ ⟨θ s, rfl⟩) (range_le_closure O π b₄ b₆ θ hθgen) (range_le_range O π b₄ b₆)
    (TateNormal.hcoords π b₄ b₆ hπ0)

lemma modelIsoO_toSpec :
    (modelIsoO O π b₄ b₆ θ hθ0 hθint hθgen hπ0).hom ≫
        (projModelCode O' (TateNormal.hcoords π b₄ b₆ hπ0)).toSpec ≫
        Spec.map (CommRingCat.ofHom (algebraMap O O')) =
      (modelO O π b₄ b₆ θ hθ0 hπ0).toSpec :=
  baseChangeIsoFin_toSpec _ _ _ _ _ _ _ _

variable {T : Type u} [CommRing T] (φ : O' →+* T) {x y : T}
  (heq : y ^ 2 + x * y = x ^ 3 + φ (π ^ 2 * b₄) * x + φ (π ^ 2 * b₆)) (hπ : IsUnit (φ π))

/-- **The point `Spec T ⟶ modelO`.** -/
def jO : Spec (CommRingCat.of T) ⟶ (modelO O π b₄ b₆ θ hθ0 hπ0).scheme :=
  TateNormal.jChart π b₄ b₆ φ heq hπ hπ0 ≫ (modelIsoO O π b₄ b₆ θ hθ0 hθint hθgen hπ0).inv

lemma jO_toSpec :
    jO O π b₄ b₆ θ hθ0 hθint hθgen hπ0 φ heq hπ ≫ (modelO O π b₄ b₆ θ hθ0 hπ0).toSpec =
      Spec.map (CommRingCat.ofHom (φ.comp (algebraMap O O'))) := by
  rw [jO, Category.assoc, ← modelIsoO_toSpec O π b₄ b₆ θ hθ0 hθint hθgen hπ0,
    Iso.inv_hom_id_assoc, reassoc_of% TateNormal.jChart_toSpec, ← Spec.map_comp]
  rfl

end

end TemperedFundamentalGroups.TateRestrict
