/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.Abhyankar
import TemperedFundamentalGroups.SemistableReduction.RootOfUnit

/-!
# Abhyankar's lemma for the whole base change `L ⊗_K K'`

Blueprint §9.2 (i). `Abhyankar.etale` treats one field `F = L[y]`, `y ^ e = ϖ`. Here we treat the
whole base change: with `O' = O[Y] ⧸ (Y ^ e - ϖ)` and `K' = Frac O'`, the algebra
`L ⊗_K K' ≅ L[Y] ⧸ (Y ^ e - ϖ)` is a finite reduced `L`-algebra generated by the image of `Y`,
hence a finite product of fields `F_i = L[y_i]`, `y_i ^ e = ϖ`. The integral closure of `O'` in a
finite product is the product of the integral closures, and étale is stable under finite
products, so:

* `Abhyankar.etale_integralClosure`: for a commutative `L`-algebra `A` which is an
  `O'`-algebra (compatibly with `O`), reduced, finite over `L` and generated over `L` by the
  image of `Y`, the integral closure of `O'` in `A` is étale over `O'`;
* `Abhyankar.etale_integralClosure_adjoinRoot`: the case `A = L[Y] ⧸ (Y ^ e - ϖ)` (which is
  `L ⊗_K K'`).

Auxiliary results of independent interest:

* `isIntegral_pi`: an element of a finite product is integral iff all its components are;
* `integralClosurePiEquiv`: `integralClosure R (Π i, A i) ≃ₐ[R] Π i, integralClosure R (A i)`;
* `Abhyankar.etale_of_algebraMap_root`: `Abhyankar.etale` for an arbitrary `O'`-algebra
  structure on `B'` sending `Y` to the chosen root (instead of the one built by `rootAlgebra`).
-/

open Polynomial IsLocalRing

namespace SemistableReduction

section Pi

variable {R ι : Type*} [CommRing R] {A : ι → Type*} [∀ i, CommRing (A i)] [∀ i, Algebra R (A i)]

/-- An element of a finite product of `R`-algebras is integral iff all its components are. -/
theorem isIntegral_pi [Finite ι] (x : Π i, A i) : IsIntegral R x ↔ ∀ i, IsIntegral R (x i) := by
  classical
  refine ⟨fun h i ↦ h.map (Pi.evalAlgHom R A i), fun h ↦ ?_⟩
  have := Fintype.ofFinite ι
  choose p hp using h
  refine ⟨∏ i, p i, monic_prod_of_monic _ _ fun i _ ↦ (hp i).1, ?_⟩
  rw [← aeval_def]
  funext i
  change Pi.evalAlgHom R A i (aeval x (∏ i, p i)) = 0
  rw [← aeval_algHom_apply, Pi.evalAlgHom_apply, map_prod]
  exact Finset.prod_eq_zero (Finset.mem_univ i) (by rw [aeval_def]; exact (hp i).2)

/-- The integral closure in a finite product is the product of the integral closures. -/
noncomputable def integralClosurePiEquiv [Finite ι] :
    integralClosure R (Π i, A i) ≃ₐ[R] Π i, integralClosure R (A i) :=
  AlgEquiv.ofBijective
    (AlgHom.pi fun i ↦ (Pi.evalAlgHom R A i).mapIntegralClosure)
    ⟨fun _ _ h ↦ Subtype.ext <| funext fun i ↦ congrArg Subtype.val (congrFun h i),
      fun y ↦ ⟨⟨fun i ↦ (y i).1, (isIntegral_pi _).2 fun i ↦ (y i).2⟩, rfl⟩⟩

end Pi

namespace Abhyankar

section Variant

variable {O K L F B B' : Type*}
  [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]
  [Field K] [Algebra O K] [IsFractionRing O K]
  [Field L] [Algebra K L] [Algebra O L] [IsScalarTower O K L]
  [FiniteDimensional K L] [Algebra.IsSeparable K L]
  [CommRing B] [IsDomain B] [Algebra O B] [Algebra B L] [IsScalarTower O B L]
  [IsIntegralClosure B O L]
  [Field F] [Algebra K F] [Algebra L F] [Algebra O F] [IsScalarTower K L F] [IsScalarTower O L F]
  [CommRing B'] [IsDomain B'] [Algebra O B'] [Algebra B' F] [IsScalarTower O B' F]
  [IsIntegralClosure B' O F]

include K L B in
/-- `Abhyankar.etale` for a given `O'`-algebra structure on `B'` (compatible with `O`) sending
`Y` to `yB'`. -/
theorem etale_of_algebraMap_root {ϖ : O} (hϖ : Irreducible ϖ) {e : ℕ} (he : IsUnit (e : O))
    [Algebra (RootOfUniformizer.Ring ϖ e) B'] [IsScalarTower O (RootOfUniformizer.Ring ϖ e) B']
    (yB' : B') (hroot : algebraMap (RootOfUniformizer.Ring ϖ e) B' (AdjoinRoot.root _) = yB')
    (hF : Algebra.adjoin L {algebraMap B' F yB'} = ⊤)
    (htame : ∀ (𝔓 : Ideal B) [𝔓.IsPrime] [𝔓.LiesOver (maximalIdeal O)],
      𝔓.ramificationIdx O ∣ e ∧ Algebra.IsSeparable (O ⧸ maximalIdeal O) (B ⧸ 𝔓)) :
    Algebra.Etale (RootOfUniformizer.Ring ϖ e) B' := by
  have hyB' : yB' ^ e = algebraMap O B' ϖ := by
    rw [← hroot, ← map_pow, RootOfUniformizer.root_pow, ← IsScalarTower.algebraMap_apply]
  have h := etale (K := K) (B := B) hϖ he yB' hyB' hF htame
  have heq : ‹Algebra (RootOfUniformizer.Ring ϖ e) B'› = rootAlgebra yB' hyB' := by
    refine Algebra.algebra_ext _ _ fun r ↦ ?_
    have := AdjoinRoot.algHom_ext (g₁ := IsScalarTower.toAlgHom O _ B')
      (g₂ := AdjoinRoot.liftAlgHom (RootOfUniformizer.poly ϖ e) (Algebra.ofId O B') yB'
        (by simp [hyB']))
      (by rw [AdjoinRoot.liftAlgHom_root]; exact hroot)
    exact DFunLike.congr_fun this r
  rw [heq]
  exact h

end Variant

section Product

variable {O K L B A : Type*}
  [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]
  [Field K] [Algebra O K] [IsFractionRing O K]
  [Field L] [Algebra K L] [Algebra O L] [IsScalarTower O K L]
  [FiniteDimensional K L] [Algebra.IsSeparable K L]
  [CommRing B] [IsDomain B] [Algebra O B] [Algebra B L] [IsScalarTower O B L]
  [IsIntegralClosure B O L]
  [CommRing A] [Algebra L A] [Algebra K A] [Algebra O A] [IsScalarTower K L A]
  [IsScalarTower O L A]

omit [IsDomain O] [IsDiscreteValuationRing O] in
/-- If `O'` is integral over `O`, the integral closure of `O'` in `F` is also the integral closure
of `O` in `F`. -/
lemma isIntegralClosure_restrictScalars {O' F : Type*} [CommRing O'] [Algebra O O']
    [Algebra.IsIntegral O O'] [CommRing F] [Algebra O F] [Algebra O' F] [IsScalarTower O O' F] :
    IsIntegralClosure (integralClosure O' F) O F where
  algebraMap_injective := Subtype.val_injective
  isIntegral_iff {x} :=
    ⟨fun hx ↦ ⟨⟨x, hx.tower_top⟩, rfl⟩, fun ⟨y, hy⟩ ↦ hy ▸ isIntegral_trans _ y.2⟩

include K B in
/-- **Abhyankar's lemma for `L ⊗_K K'`.** Let `O` be a DVR with uniformizer `ϖ`, `L / K` a
finite separable extension of its fraction field, tame at every maximal ideal of the integral
closure `B` of `O` in `L` with ramification indices dividing `e ∈ O^×`, and
`O' = O[Y] ⧸ (Y ^ e - ϖ)`. Let `A` be a commutative `L`-algebra and `O'`-algebra (compatibly with
`O`) which is reduced, finite over `L` and generated over `L` by the image `y` of `Y` (for
instance `A = L[Y] ⧸ (Y ^ e - ϖ) ≅ L ⊗_K K'`, `K' = Frac O'`). Then the integral closure of `O'`
in `A` is étale over `O'`.

Proof: `A` is a reduced Artinian ring, hence the product of the fields `F = A ⧸ 𝔪`, each generated
over `L` by the image of `y`; the integral closure of `O'` in `A` is the product of the integral
closures of `O'` (equivalently of `O`) in the `F`, each étale over `O'` by `Abhyankar.etale`. -/
theorem etale_integralClosure {ϖ : O} (hϖ : Irreducible ϖ) {e : ℕ} (he : IsUnit (e : O))
    [Algebra (RootOfUniformizer.Ring ϖ e) A] [IsScalarTower O (RootOfUniformizer.Ring ϖ e) A]
    [Module.Finite L A] [IsReduced A]
    (hgen : Algebra.adjoin L {algebraMap (RootOfUniformizer.Ring ϖ e) A (AdjoinRoot.root _)} = ⊤)
    (htame : ∀ (𝔓 : Ideal B) [𝔓.IsPrime] [𝔓.LiesOver (maximalIdeal O)],
      𝔓.ramificationIdx O ∣ e ∧ Algebra.IsSeparable (O ⧸ maximalIdeal O) (B ⧸ 𝔓)) :
    Algebra.Etale (RootOfUniformizer.Ring ϖ e) (integralClosure (RootOfUniformizer.Ring ϖ e) A) :=
  by
  set O' := RootOfUniformizer.Ring ϖ e
  have he0 : 0 < e := Nat.pos_of_ne_zero (by rintro rfl; simp at he)
  haveI : Module.Finite O O' := RootOfUniformizer.finite he0
  haveI : IsArtinianRing A := IsArtinianRing.of_finite L A
  -- each factor `A ⧸ 𝔪` contributes an étale integral closure
  have hfac : ∀ I : MaximalSpectrum A,
      Algebra.Etale O' (integralClosure O' (A ⧸ I.asIdeal)) := by
    intro I
    letI : Field (A ⧸ I.asIdeal) := Ideal.Quotient.field _
    haveI := isIntegralClosure_restrictScalars (O := O) (O' := O') (F := A ⧸ I.asIdeal)
    set y : A ⧸ I.asIdeal := algebraMap O' _ (AdjoinRoot.root _)
    have hyint : IsIntegral O' y := isIntegral_algebraMap
    refine etale_of_algebraMap_root (K := K) (L := L) (B := B)
      (F := A ⧸ I.asIdeal) hϖ he ⟨y, hyint⟩ rfl ?_ htame
    have hsurj : Function.Surjective (Ideal.Quotient.mkₐ L I.asIdeal) :=
      Ideal.Quotient.mkₐ_surjective L _
    rw [eq_top_iff]
    rintro x -
    obtain ⟨x, rfl⟩ := hsurj x
    have hx : x ∈ Algebra.adjoin L {algebraMap O' A (AdjoinRoot.root _)} := by
      rw [hgen]; trivial
    have : Ideal.Quotient.mkₐ L I.asIdeal x ∈
        (Algebra.adjoin L {algebraMap O' A (AdjoinRoot.root _)}).map
          (Ideal.Quotient.mkₐ L I.asIdeal) := Subalgebra.mem_map.2 ⟨x, hx, rfl⟩
    rw [← Algebra.adjoin_image, Set.image_singleton] at this
    exact this
  let eA : A ≃ₐ[O'] Π I : MaximalSpectrum A, A ⧸ I.asIdeal :=
    (IsArtinianRing.equivPi A).restrictScalars O'
  let e₁ : integralClosure O' A ≃ₐ[O'] integralClosure O' (Π I : MaximalSpectrum A,
      A ⧸ I.asIdeal) :=
    AlgEquiv.ofBijective eA.toAlgHom.mapIntegralClosure
      ⟨fun x y h ↦ Subtype.ext (eA.injective (congrArg Subtype.val h)),
        fun y ↦ ⟨⟨eA.symm y, y.2.map eA.symm.toAlgHom⟩, Subtype.ext (eA.apply_symm_apply _)⟩⟩
  exact Algebra.Etale.of_equiv (e₁.trans integralClosurePiEquiv).symm

omit [IsDomain O] [IsDiscreteValuationRing O] [Algebra K A] [IsScalarTower K L A]
  [IsScalarTower O L A] in
/-- In `L[Y] ⧸ (Y ^ e - ϖ)`, the root satisfies `y ^ e = ϖ`. -/
lemma adjoinRoot_root_pow (ϖ : O) (e : ℕ) :
    AdjoinRoot.root (X ^ e - C (algebraMap O L ϖ)) ^ e =
      algebraMap O (AdjoinRoot (X ^ e - C (algebraMap O L ϖ))) ϖ := by
  have := AdjoinRoot.eval₂_root (X ^ e - C (algebraMap O L ϖ))
  rw [eval₂_sub, eval₂_X_pow, eval₂_C, sub_eq_zero] at this
  rw [this]
  rfl

omit [Algebra K A] [IsScalarTower K L A] [IsScalarTower O L A] in
include K B in
/-- **Abhyankar's lemma for `L ⊗_K K' = L[Y] ⧸ (Y ^ e - ϖ)`.** In the situation of
`etale_integralClosure`, the integral closure of `O' = O[Y] ⧸ (Y ^ e - ϖ)` in
`L[Y] ⧸ (Y ^ e - ϖ)` (an `O'`-algebra via `Y ↦ Y`) is étale over `O'`. (Since `O'` is free over
`O`, `L[Y] ⧸ (Y ^ e - ϖ) = L ⊗_O O' = L ⊗_K K'` with `K' = Frac O' = K[Y] ⧸ (Y ^ e - ϖ)`.) -/
theorem etale_integralClosure_adjoinRoot {ϖ : O} (hϖ : Irreducible ϖ) {e : ℕ}
    (he : IsUnit (e : O))
    (htame : ∀ (𝔓 : Ideal B) [𝔓.IsPrime] [𝔓.LiesOver (maximalIdeal O)],
      𝔓.ramificationIdx O ∣ e ∧ Algebra.IsSeparable (O ⧸ maximalIdeal O) (B ⧸ 𝔓)) :
    letI := rootAlgebra _ (adjoinRoot_root_pow (L := L) ϖ e)
    Algebra.Etale (RootOfUniformizer.Ring ϖ e)
      (integralClosure (RootOfUniformizer.Ring ϖ e)
        (AdjoinRoot (X ^ e - C (algebraMap O L ϖ)))) := by
  letI := rootAlgebra _ (adjoinRoot_root_pow (L := L) ϖ e)
  haveI := rootAlgebra_isScalarTower _ (adjoinRoot_root_pow (L := L) ϖ e)
  have he0 : e ≠ 0 := by rintro rfl; simp at he
  have hOL : Function.Injective (algebraMap O L) := by
    rw [IsScalarTower.algebraMap_eq O K L]
    exact (algebraMap K L).injective.comp (IsFractionRing.injective O K)
  have hϖL : IsUnit (algebraMap O L ϖ) :=
    isUnit_iff_ne_zero.2 fun h ↦ hϖ.ne_zero (hOL (h.trans (map_zero _).symm))
  have heL : IsUnit (e : L) := by simpa using he.map (algebraMap O L)
  haveI := RootOfUnit.etale hϖL heL
  haveI := Algebra.FormallyUnramified.isReduced_of_field L
    (AdjoinRoot (X ^ e - C (algebraMap O L ϖ)))
  haveI : Module.Finite L (AdjoinRoot (X ^ e - C (algebraMap O L ϖ))) :=
    (monic_X_pow_sub_C (algebraMap O L ϖ) he0).finite_adjoinRoot
  refine etale_integralClosure (K := K) (L := L) (B := B)
    (A := AdjoinRoot (X ^ e - C (algebraMap O L ϖ))) hϖ he ?_ htame
  rw [rootAlgebra_algebraMap_root]
  exact AdjoinRoot.adjoinRoot_eq_top

end Product

end Abhyankar

end SemistableReduction
