/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib

/-!
# The local Kummer step of Abhyankar's lemma

Let `R → S` be a local homomorphism of discrete valuation rings, `π` a uniformizer of `R`, `u` a
unit of `R`, `n` invertible in `R` and `0 < m`. Suppose `y, z ∈ S` satisfy `z ^ n = u` and
`y ^ m = π z`, and that every element of `S` becomes an element of `R[y]` after multiplication by
a nonzero element of `R` (i.e. `S` is a localization of a subring of `Frac R (y)`).

Then `y` is a uniformizer of `S` and the residue field extension of `S / R` is separable
(`Abhyankar.maximalIdeal_eq_span`, `Abhyankar.isSeparable_residueField`).

This is the heart of Abhyankar's lemma (Blueprint §9.2): if `e(𝔓) = n` and `ϖ = u π ^ n` in
`R = B_𝔓`, adjoining `y = ϖ ^ (1 / (n m))` to `Frac R` gives `z = y ^ m / π` with `z ^ n = u`, so
the extension becomes unramified over `O[y]`.

The proof avoids henselization. Let `D = R[y, z] ⊆ S`. Modulo `y` (which divides `π`), every
element of `D` is a polynomial in `z` over `κ(R)`, and `z̄` is a root of the separable polynomial
`X ^ n - ū`; hence if `d ∈ D ∩ 𝔪_S` then `d t ∈ y D` for some `t ∈ D` that is a unit in `S`
(`Abhyankar.exists_mul_mem_of_residue_eq_zero`). Descending on the valuation of `S`, every
nonzero `d ∈ D` is `y ^ k` times a unit of `S`, up to a unit of `S` lying in `D`
(`Abhyankar.exists_mul_eq_pow_mul`). Since `S` is generated by `D` as a localization, every
nonzero element of `S` is associated to a power of `y`, and residues of units of `S` lie in
`κ(R)(z̄)`.
-/

open Polynomial IsLocalRing

namespace SemistableReduction

namespace Abhyankar

section CommRing

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] {π u : R} {n m : ℕ} {y z : S}

lemma y_mem : y ∈ Algebra.adjoin R ({y, z} : Set S) :=
  Algebra.subset_adjoin (by simp)

lemma z_mem : z ∈ Algebra.adjoin R ({y, z} : Set S) :=
  Algebra.subset_adjoin (by simp)

lemma aeval_z_mem (p : R[X]) : aeval z p ∈ Algebra.adjoin R ({y, z} : Set S) :=
  Algebra.adjoin_mono (by simp) (aeval_mem_adjoin_singleton R z)

/-- Every element of `R[y, z]` is a polynomial in `z` modulo `y R[y, z]`. -/
lemma exists_eq_aeval_add (d : S) (hd : d ∈ Algebra.adjoin R ({y, z} : Set S)) :
    ∃ p : R[X], ∃ d₁ ∈ Algebra.adjoin R ({y, z} : Set S), d = aeval z p + y * d₁ := by
  induction hd using Algebra.adjoin_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact ⟨0, 1, Subalgebra.one_mem _, by simp⟩
    · exact ⟨X, 0, Subalgebra.zero_mem _, by simp⟩
  | algebraMap r => exact ⟨C r, 0, Subalgebra.zero_mem _, by simp⟩
  | add a b _ _ ha hb =>
    obtain ⟨p, a₁, ha₁, rfl⟩ := ha
    obtain ⟨q, b₁, hb₁, rfl⟩ := hb
    exact ⟨p + q, a₁ + b₁, Subalgebra.add_mem _ ha₁ hb₁, by rw [map_add]; ring⟩
  | mul a b _ _ ha hb =>
    obtain ⟨p, a₁, ha₁, rfl⟩ := ha
    obtain ⟨q, b₁, hb₁, rfl⟩ := hb
    refine ⟨p * q, a₁ * aeval z q + aeval z p * b₁ + y * a₁ * b₁, ?_, by rw [map_mul]; ring⟩
    have := aeval_z_mem (R := R) (y := y) (z := z)
    exact Subalgebra.add_mem _ (Subalgebra.add_mem _ (Subalgebra.mul_mem _ ha₁ (this q))
      (Subalgebra.mul_mem _ (this p) hb₁))
      (Subalgebra.mul_mem _ (Subalgebra.mul_mem _ y_mem ha₁) hb₁)

/-- `π ∈ y R[y, z]`: `π = y ^ m z ^ (n - 1) u⁻¹`. -/
lemma exists_algebraMap_eq_mul (hu : IsUnit u) (hn : n ≠ 0) (hm : 0 < m)
    (hz : z ^ n = algebraMap R S u) (hy : y ^ m = algebraMap R S π * z) :
    ∃ d ∈ Algebra.adjoin R ({y, z} : Set S), algebraMap R S π = y * d := by
  obtain ⟨v, rfl⟩ := hu
  refine ⟨y ^ (m - 1) * z ^ (n - 1) * algebraMap R S (v⁻¹ : Rˣ), ?_, ?_⟩
  · exact Subalgebra.mul_mem _ (Subalgebra.mul_mem _ (Subalgebra.pow_mem _ y_mem _)
      (Subalgebra.pow_mem _ z_mem _)) (Subalgebra.algebraMap_mem _ _)
  · have h1 : y * y ^ (m - 1) = y ^ m := by rw [← pow_succ', Nat.sub_add_cancel hm]
    have h2 : z * z ^ (n - 1) = z ^ n := by
      rw [← pow_succ', Nat.sub_add_cancel (Nat.pos_of_ne_zero hn)]
    have h3 : algebraMap R S (v : R) * algebraMap R S (v⁻¹ : Rˣ) = 1 := by
      rw [← map_mul, Units.mul_inv, map_one]
    calc algebraMap R S π = algebraMap R S π * (z * z ^ (n - 1)) * algebraMap R S (v⁻¹ : Rˣ) := by
          rw [h2, hz, mul_assoc, h3, mul_one]
      _ = y * (y ^ (m - 1) * z ^ (n - 1) * algebraMap R S (v⁻¹ : Rˣ)) := by
          rw [← mul_assoc y, ← mul_assoc y, h1, hy]; ring

end CommRing

section Local

variable {R S : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  [CommRing S] [IsDomain S] [IsDiscreteValuationRing S] [Algebra R S]
  [IsLocalHom (algebraMap R S)] {π u : R} {n m : ℕ} {y z : S}

omit [IsDomain R] [IsDiscreteValuationRing R] in
/-- `y` lies in the maximal ideal of `S`. -/
lemma y_mem_maximalIdeal (hπ : Irreducible π)
    (hy : y ^ m = algebraMap R S π * z) : y ∈ maximalIdeal S := by
  rw [mem_maximalIdeal, mem_nonunits_iff]
  intro h
  have h1 : IsUnit (y ^ m) := h.pow m
  rw [hy] at h1
  exact hπ.not_isUnit (isUnit_of_map_unit (algebraMap R S) π (isUnit_of_mul_isUnit_left h1))

lemma residue_aeval (p : R[X]) (x : S) :
    residue S (aeval x p) = aeval (residue S x) (p.map (residue R)) := by
  have h1 := Polynomial.aeval_algHom_apply (IsScalarTower.toAlgHom R S (ResidueField S)) x p
  have h2 := Polynomial.aeval_map_algebraMap (ResidueField R) (residue S x) p
  simp only [IsScalarTower.coe_toAlgHom', ResidueField.algebraMap_eq] at h1 h2
  rw [h2, h1]

/-- **The fiber step.** If `d ∈ R[y, z]` lies in the maximal ideal of `S`, then `d t ∈ y R[y, z]`
for some `t ∈ R[y, z]` that is a unit of `S`. This uses that `z̄` is a root of the separable
polynomial `X ^ n - ū` over `κ(R)`. -/
lemma exists_mul_mem_of_residue_eq_zero (hπ : Irreducible π) (hu : IsUnit u)
    (hn : IsUnit (n : R)) (hm : 0 < m)
    (hz : z ^ n = algebraMap R S u) (hy : y ^ m = algebraMap R S π * z)
    {d : S} (hd : d ∈ Algebra.adjoin R ({y, z} : Set S)) (hd0 : residue S d = 0) :
    ∃ t ∈ Algebra.adjoin R ({y, z} : Set S), IsUnit t ∧
      ∃ d₁ ∈ Algebra.adjoin R ({y, z} : Set S), d * t = y * d₁ := by
  classical
  have hn0 : n ≠ 0 := by rintro rfl; simp at hn
  obtain ⟨p, d₁, hd₁, rfl⟩ := exists_eq_aeval_add d hd
  obtain ⟨dπ, hdπ, hπeq⟩ := exists_algebraMap_eq_mul hu hn0 hm hz hy
  set zb := residue S z
  set g : (ResidueField R)[X] := X ^ n - C (residue R u) with hg_def
  have hnR : (n : ResidueField R) ≠ 0 := by
    have := hn.map (residue R)
    rw [map_natCast] at this
    exact this.ne_zero
  have huR : residue R u ≠ 0 := (hu.map (residue R)).ne_zero
  have hg : g.Separable := separable_X_pow_sub_C _ hnR huR
  have hgz : aeval zb g = 0 := by
    simp only [hg_def, map_sub, map_pow, aeval_X, aeval_C, zb,
      ResidueField.algebraMap_residue]
    rw [← map_pow, hz, sub_self]
  have hgm : g.Monic := monic_X_pow_sub_C _ hn0
  have hint : IsIntegral (ResidueField R) zb := ⟨g, hgm, hgz⟩
  set q := minpoly (ResidueField R) zb
  obtain ⟨r, hr⟩ : q ∣ g := minpoly.dvd _ _ hgz
  have hcop : IsCoprime q r := (hr ▸ hg).isCoprime
  have hyres : residue S y = 0 := (residue_eq_zero_iff y).2 (y_mem_maximalIdeal hπ hy)
  have hpz : aeval zb (p.map (residue R)) = 0 := by
    have := hd0
    rwa [map_add, map_mul, hyres, zero_mul, add_zero, residue_aeval] at this
  have hqp : q ∣ p.map (residue R) := minpoly.dvd _ _ hpz
  obtain ⟨h, hh⟩ : g ∣ p.map (residue R) * r := by rw [hr]; exact mul_dvd_mul_right hqp r
  obtain ⟨r', rfl⟩ := Polynomial.map_surjective (residue R) residue_surjective r
  obtain ⟨h', rfl⟩ := Polynomial.map_surjective (residue R) residue_surjective h
  have hmax : maximalIdeal R = Ideal.span {π} :=
    (IsDiscreteValuationRing.irreducible_iff_uniformizer π).1 hπ
  have hdiv : C π ∣ p * r' - (X ^ n - C u) * h' := by
    rw [C_dvd_iff_dvd_coeff]
    intro i
    rw [← Ideal.mem_span_singleton, ← hmax, ← residue_eq_zero_iff, ← coeff_map,
      Polynomial.map_sub, Polynomial.map_mul, Polynomial.map_mul, hh]
    simp [g]
  obtain ⟨k, hk⟩ := hdiv
  refine ⟨aeval z r', aeval_z_mem r', ?_, ?_⟩
  · rw [← residue_ne_zero_iff_isUnit, residue_aeval]
    intro h0
    exact minpoly.not_isUnit _ _ (hcop.isUnit_of_dvd' dvd_rfl (minpoly.dvd _ _ h0))
  · have key : aeval z p * aeval z r' = algebraMap R S π * aeval z k := by
      have := congrArg (aeval z) hk
      simp only [map_sub, map_mul, map_pow, aeval_X, aeval_C, hz, sub_self, zero_mul,
        sub_zero] at this
      exact this
    refine ⟨dπ * aeval z k + d₁ * aeval z r', ?_, ?_⟩
    · exact Subalgebra.add_mem _ (Subalgebra.mul_mem _ hdπ (aeval_z_mem k))
        (Subalgebra.mul_mem _ hd₁ (aeval_z_mem r'))
    · rw [add_mul, key, hπeq]
      ring

omit [IsDomain R] [IsDiscreteValuationRing R] in
lemma y_ne_zero (hπ : Irreducible π) (hu : IsUnit u) (hn : n ≠ 0)
    (hinj : Function.Injective (algebraMap R S))
    (hz : z ^ n = algebraMap R S u) (hy : y ^ m = algebraMap R S π * z) : y ≠ 0 := by
  rintro rfl
  have hzu : IsUnit z := (isUnit_pow_iff hn).1 (hz ▸ hu.map (algebraMap R S))
  have h0 : algebraMap R S π * z = 0 := by
    rw [← hy, zero_pow]
    rintro rfl
    exact hπ.not_isUnit (isUnit_of_map_unit (algebraMap R S) π 
      (IsUnit.of_mul_eq_one z (by simpa using hy.symm)))
  rcases mul_eq_zero.1 h0 with h | h
  · exact hπ.ne_zero (hinj (h.trans (map_zero _).symm))
  · exact hzu.ne_zero h

/-- **Descent on the valuation.** Every nonzero `d ∈ R[y, z]` satisfies `d t = y ^ k w` with
`t, w ∈ R[y, z]` units of `S`. -/
lemma exists_mul_eq_pow_mul (hπ : Irreducible π) (hu : IsUnit u)
    (hn : IsUnit (n : R)) (hm : 0 < m) (hinj : Function.Injective (algebraMap R S))
    (hz : z ^ n = algebraMap R S u) (hy : y ^ m = algebraMap R S π * z)
    {d : S} (hd : d ∈ Algebra.adjoin R ({y, z} : Set S)) (hd0 : d ≠ 0) :
    ∃ k : ℕ, ∃ t ∈ Algebra.adjoin R ({y, z} : Set S), IsUnit t ∧
      ∃ w ∈ Algebra.adjoin R ({y, z} : Set S), IsUnit w ∧ d * t = y ^ k * w := by
  have hn0 : n ≠ 0 := by rintro rfl; simp at hn
  have hy0 : y ≠ 0 := y_ne_zero hπ hu hn0 hinj hz hy
  have hyv : IsDiscreteValuationRing.addVal S y ≠ 0 := by
    rw [Ne, IsDiscreteValuationRing.addVal_eq_zero_iff, ← mem_nonunits_iff, ← mem_maximalIdeal]
    exact y_mem_maximalIdeal hπ hy
  obtain ⟨N, hN⟩ : ∃ N : ℕ, (N : ℕ∞) = IsDiscreteValuationRing.addVal S d :=
    ENat.ne_top_iff_exists.mp (by rwa [Ne, IsDiscreteValuationRing.addVal_eq_top_iff])
  induction N using Nat.strong_induction_on generalizing d with
  | _ N ih =>
  by_cases hdu : IsUnit d
  · exact ⟨0, 1, Subalgebra.one_mem _, isUnit_one, d, hd, hdu, by simp⟩
  have hd0' : residue S d = 0 := (residue_eq_zero_iff d).2 ((mem_maximalIdeal _).2 hdu)
  obtain ⟨t, ht, htu, d₁, hd₁, he⟩ := exists_mul_mem_of_residue_eq_zero hπ hu hn hm hz hy hd hd0'
  have hd₁0 : d₁ ≠ 0 := by
    rintro rfl
    rw [mul_zero, mul_eq_zero] at he
    exact he.elim hd0 htu.ne_zero
  obtain ⟨N₁, hN₁⟩ : ∃ N₁ : ℕ, (N₁ : ℕ∞) = IsDiscreteValuationRing.addVal S d₁ :=
    ENat.ne_top_iff_exists.mp (by rwa [Ne, IsDiscreteValuationRing.addVal_eq_top_iff])
  have hlt : N₁ < N := by
    have h := congrArg (IsDiscreteValuationRing.addVal S) he
    rw [IsDiscreteValuationRing.addVal_mul, IsDiscreteValuationRing.addVal_mul,
      (IsDiscreteValuationRing.addVal_eq_zero_iff).2 htu, add_zero, ← hN, ← hN₁] at h
    obtain ⟨b, hb⟩ : ∃ b : ℕ, (b : ℕ∞) = IsDiscreteValuationRing.addVal S y :=
      ENat.ne_top_iff_exists.mp (by rwa [Ne, IsDiscreteValuationRing.addVal_eq_top_iff])
    rw [← hb] at h hyv
    have h' : N = b + N₁ := by exact_mod_cast h
    have : b ≠ 0 := by exact_mod_cast hyv
    omega
  obtain ⟨k, t₁, ht₁, ht₁u, w, hw, hwu, he₁⟩ := ih N₁ hlt hd₁ hd₁0 hN₁
  refine ⟨k + 1, t * t₁, Subalgebra.mul_mem _ ht ht₁, htu.mul ht₁u, w, hw, hwu, ?_⟩
  calc d * (t * t₁) = y * (d₁ * t₁) := by rw [← mul_assoc, he, mul_assoc]
    _ = y ^ (k + 1) * w := by rw [he₁, pow_succ']; ring

/-- Under the generation hypothesis, every nonzero `x ∈ S` satisfies `x y ^ j c = y ^ i c'` with
`c, c' ∈ R[y, z]` units of `S`. -/
lemma exists_mul_pow_mul_eq (hπ : Irreducible π) (hu : IsUnit u)
    (hn : IsUnit (n : R)) (hm : 0 < m) (hinj : Function.Injective (algebraMap R S))
    (hz : z ^ n = algebraMap R S u) (hy : y ^ m = algebraMap R S π * z)
    (hgen : ∀ x : S, ∃ b : R, b ≠ 0 ∧ algebraMap R S b * x ∈ Algebra.adjoin R {y})
    {x : S} (hx : x ≠ 0) :
    ∃ i j : ℕ, ∃ c ∈ Algebra.adjoin R ({y, z} : Set S), IsUnit c ∧
      ∃ c' ∈ Algebra.adjoin R ({y, z} : Set S), IsUnit c' ∧ x * y ^ j * c = y ^ i * c' := by
  obtain ⟨b, hb0, hbx⟩ := hgen x
  have hbD : algebraMap R S b ∈ Algebra.adjoin R ({y, z} : Set S) := Subalgebra.algebraMap_mem _ _
  have haD : algebraMap R S b * x ∈ Algebra.adjoin R ({y, z} : Set S) :=
    Algebra.adjoin_mono (by simp) hbx
  have hb0' : algebraMap R S b ≠ 0 := fun h ↦ hb0 (hinj (h.trans (map_zero _).symm))
  obtain ⟨i, ta, hta, htau, wa, hwa, hwau, hea⟩ :=
    exists_mul_eq_pow_mul hπ hu hn hm hinj hz hy haD (mul_ne_zero hb0' hx)
  obtain ⟨j, tb, htb, htbu, wb, hwb, hwbu, heb⟩ :=
    exists_mul_eq_pow_mul hπ hu hn hm hinj hz hy hbD hb0'
  refine ⟨i, j, wb * ta, Subalgebra.mul_mem _ hwb hta, hwbu.mul htau, wa * tb,
    Subalgebra.mul_mem _ hwa htb, hwau.mul htbu, ?_⟩
  calc x * y ^ j * (wb * ta) = x * (y ^ j * wb) * ta := by ring
    _ = algebraMap R S b * x * ta * tb := by rw [← heb]; ring
    _ = y ^ i * (wa * tb) := by rw [hea]; ring

/-- **Abhyankar, local Kummer step: `y` is a uniformizer.** -/
theorem maximalIdeal_eq_span (hπ : Irreducible π) (hu : IsUnit u)
    (hn : IsUnit (n : R)) (hm : 0 < m) (hinj : Function.Injective (algebraMap R S))
    (hz : z ^ n = algebraMap R S u) (hy : y ^ m = algebraMap R S π * z)
    (hgen : ∀ x : S, ∃ b : R, b ≠ 0 ∧ algebraMap R S b * x ∈ Algebra.adjoin R {y}) :
    maximalIdeal S = Ideal.span {y} := by
  refine le_antisymm (fun x hx ↦ ?_) ((Ideal.span_singleton_le_iff_mem _).2
    (y_mem_maximalIdeal hπ hy))
  rcases eq_or_ne x 0 with rfl | hx0
  · exact Ideal.zero_mem _
  rw [mem_maximalIdeal, mem_nonunits_iff] at hx
  obtain ⟨i, j, c, -, hcu, c', -, hc'u, he⟩ := exists_mul_pow_mul_eq hπ hu hn hm hinj hz hy hgen hx0
  have hy0 : y ≠ 0 := y_ne_zero hπ hu (by rintro rfl; simp at hn) hinj hz hy
  rcases le_or_gt i j with hij | hij
  · exfalso
    obtain ⟨l, rfl⟩ := Nat.exists_eq_add_of_le hij
    have h1 : x * y ^ l * c = c' := by
      apply mul_left_cancel₀ (pow_ne_zero i hy0)
      rw [← he]; ring
    exact hx (isUnit_of_mul_isUnit_left (isUnit_of_mul_isUnit_left (h1 ▸ hc'u)))
  · obtain ⟨l, rfl⟩ := Nat.exists_eq_add_of_lt hij
    have h1 : x * c = y * (y ^ l * c') := by
      apply mul_left_cancel₀ (pow_ne_zero j hy0)
      rw [← mul_assoc, mul_comm _ x, he]; ring
    rw [Ideal.mem_span_singleton]
    obtain ⟨v, rfl⟩ := hcu
    exact ⟨y ^ l * c' * ↑v⁻¹, by rw [← mul_assoc, ← h1, mul_assoc, Units.mul_inv, mul_one]⟩

/-- `z̄` is separable over `κ(R)`: it is a root of `X ^ n - ū`. -/
lemma isSeparable_residue (hu : IsUnit u) (hn : IsUnit (n : R))
    (hz : z ^ n = algebraMap R S u) : IsSeparable (ResidueField R) (residue S z) := by
  have hnR : (n : ResidueField R) ≠ 0 := by
    have := hn.map (residue R)
    rw [map_natCast] at this
    exact this.ne_zero
  have hg := separable_X_pow_sub_C _ hnR (hu.map (residue R)).ne_zero
  refine hg.of_dvd (minpoly.dvd _ _ ?_)
  simp only [map_sub, map_pow, aeval_X, aeval_C, ResidueField.algebraMap_residue]
  rw [← map_pow, hz, sub_self]

/-- Residues of elements of `R[y, z]` lie in `κ(R)(z̄)`. -/
lemma residue_mem_adjoin (hπ : Irreducible π) (hy : y ^ m = algebraMap R S π * z)
    {d : S} (hd : d ∈ Algebra.adjoin R ({y, z} : Set S)) :
    residue S d ∈ IntermediateField.adjoin (ResidueField R) {residue S z} := by
  obtain ⟨p, d₁, -, rfl⟩ := exists_eq_aeval_add d hd
  rw [map_add, map_mul, (residue_eq_zero_iff y).2 (y_mem_maximalIdeal hπ hy), zero_mul,
    add_zero, residue_aeval]
  exact IntermediateField.algebra_adjoin_le_adjoin _ _ (aeval_mem_adjoin_singleton _ _)

/-- **Abhyankar, local Kummer step: the residue extension is separable**; in fact
`κ(S) = κ(R)(z̄)` with `z̄ ^ n = ū`. -/
theorem isSeparable_residueField (hπ : Irreducible π) (hu : IsUnit u)
    (hn : IsUnit (n : R)) (hm : 0 < m) (hinj : Function.Injective (algebraMap R S))
    (hz : z ^ n = algebraMap R S u) (hy : y ^ m = algebraMap R S π * z)
    (hgen : ∀ x : S, ∃ b : R, b ≠ 0 ∧ algebraMap R S b * x ∈ Algebra.adjoin R {y}) :
    Algebra.IsSeparable (ResidueField R) (ResidueField S) := by
  haveI := (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable (ResidueField R)
    (ResidueField S)).2
    (isSeparable_residue hu hn hz)
  refine ⟨fun xb ↦ ?_⟩
  obtain ⟨x, rfl⟩ := residue_surjective xb
  refine IntermediateField.isSeparable_of_mem_isSeparable (ResidueField R) (ResidueField S)
    (L := IntermediateField.adjoin (ResidueField R) {residue S z}) ?_
  by_cases hx : IsUnit x
  swap
  · rw [(residue_eq_zero_iff x).2 ((mem_maximalIdeal _).2 hx)]
    exact IntermediateField.zero_mem _
  have hx0 : x ≠ 0 := hx.ne_zero
  obtain ⟨i, j, c, hc, hcu, c', hc', hc'u, he⟩ :=
    exists_mul_pow_mul_eq hπ hu hn hm hinj hz hy hgen hx0
  have hy0 : y ≠ 0 := y_ne_zero hπ hu (by rintro rfl; simp at hn) hinj hz hy
  have hyn : ¬ IsUnit y := (mem_maximalIdeal _).1 (y_mem_maximalIdeal hπ hy)
  have hxc : x * c = c' := by
    rcases lt_trichotomy i j with hij | rfl | hij
    · exfalso
      obtain ⟨l, rfl⟩ := Nat.exists_eq_add_of_lt hij
      have h1 : x * (y * (y ^ l * c)) = c' := by
        apply mul_left_cancel₀ (pow_ne_zero i hy0)
        rw [← he]; ring
      exact hyn (isUnit_of_mul_isUnit_left (isUnit_of_mul_isUnit_right (h1 ▸ hc'u)))
    · exact mul_left_cancel₀ (pow_ne_zero i hy0) (by rw [← he]; ring)
    · exfalso
      obtain ⟨l, rfl⟩ := Nat.exists_eq_add_of_lt hij
      have h1 : x * c = y * (y ^ l * c') := by
        apply mul_left_cancel₀ (pow_ne_zero j hy0)
        rw [← mul_assoc, mul_comm _ x, he]; ring
      exact hyn (isUnit_of_mul_isUnit_left (h1 ▸ hx.mul hcu))
  have hrc : residue S c ≠ 0 := residue_ne_zero_iff_isUnit _ |>.2 hcu
  have : residue S x = residue S c' * (residue S c)⁻¹ := by
    rw [← hxc, map_mul, mul_assoc, mul_inv_cancel₀ hrc, mul_one]
  rw [this]
  exact IntermediateField.mul_mem _ (residue_mem_adjoin hπ hy hc')
    (IntermediateField.inv_mem _ (residue_mem_adjoin hπ hy hc))

end Local

section DVR

open IsDiscreteValuationRing

variable {O R S : Type*} [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]
  [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  [CommRing S] [IsDomain S] [IsDiscreteValuationRing S]
  [Algebra O R] [Algebra R S] [Algebra O S] [IsScalarTower O R S]
  [IsLocalHom (algebraMap O R)] [IsLocalHom (algebraMap R S)]

/-- **Abhyankar's lemma for a local map of discrete valuation rings.** Let `O → R → S` be local
injective maps of DVRs, `ϖ` a uniformizer of `O` with `ϖ = u π ^ n` in `R` (`n` the ramification
index of `R / O`, i.e. the valuation of `ϖ` in `R`), `n ∣ e` with `e` invertible in `O`, and
`y ∈ S` with `y ^ e = ϖ`, such that `S` is generated by `R[y]` up to denominators from `R`.
Then `y` is a uniformizer of `S` and `κ(S) / κ(R)` is separable. -/
theorem maximalIdeal_eq_span_and_isSeparable_of_pow_eq {ϖ : O} (hϖ : Irreducible ϖ) {e n : ℕ}
    (he : IsUnit (e : O)) (hn : addVal R (algebraMap O R ϖ) = n) (hne : n ∣ e)
    (hinjO : Function.Injective (algebraMap O R)) (hinj : Function.Injective (algebraMap R S))
    {y : S} (hy : y ^ e = algebraMap O S ϖ)
    (hgen : ∀ x : S, ∃ b : R, b ≠ 0 ∧ algebraMap R S b * x ∈ Algebra.adjoin R {y}) :
    IsLocalRing.maximalIdeal S = Ideal.span {y} ∧
      Algebra.IsSeparable (ResidueField R) (ResidueField S) := by
  obtain ⟨π, hπ⟩ := exists_irreducible R
  have hϖR : algebraMap O R ϖ ≠ 0 := fun h ↦ hϖ.ne_zero (hinjO (h.trans (map_zero _).symm))
  obtain ⟨n', u, hu⟩ := eq_unit_mul_pow_irreducible hϖR hπ
  have hn' : n' = n := by
    have := addVal_def' u hπ n'
    rw [← hu, hn] at this
    exact_mod_cast this.symm
  subst hn'
  have hn0 : n' ≠ 0 := by
    rintro rfl
    rw [pow_zero, mul_one] at hu
    exact hϖ.not_isUnit (isUnit_of_map_unit (algebraMap O R) ϖ (hu ▸ u.isUnit))
  obtain ⟨m, rfl⟩ := hne
  have hm : 0 < m := by
    rcases Nat.eq_zero_or_pos m with rfl | h
    · simp at he
    · exact h
  have hnR : IsUnit (n' : R) := by
    have h1 : IsUnit ((n' * m : ℕ) : R) := by
      simpa using he.map (algebraMap O R)
    exact isUnit_of_dvd_unit (Nat.cast_dvd_cast (dvd_mul_right n' m)) h1
  -- `y ^ m` and `π` are associated in `S`
  have hπS : algebraMap R S π ≠ 0 := fun h ↦ hπ.ne_zero (hinj (h.trans (map_zero _).symm))
  have hyϖ : (y ^ m) ^ n' = algebraMap R S (u : R) * algebraMap R S π ^ n' := by
    rw [← pow_mul, mul_comm, hy, IsScalarTower.algebraMap_apply O R S, hu, map_mul, map_pow]
  have hval : addVal S (y ^ m) = addVal S (algebraMap R S π) := by
    have h1 := congrArg (addVal S) hyϖ
    rw [addVal_mul, addVal_pow (y ^ m) n', addVal_pow _ n',
      (addVal_eq_zero_iff).2 ((u.isUnit).map (algebraMap R S)), zero_add] at h1
    obtain ⟨a, ha⟩ : ∃ a : ℕ, (a : ℕ∞) = addVal S (y ^ m) :=
      ENat.ne_top_iff_exists.mp (by
        rw [Ne, addVal_eq_top_iff]
        intro h0
        rw [h0, zero_pow hn0] at hyϖ
        exact mul_ne_zero ((u.isUnit).map (algebraMap R S)).ne_zero (pow_ne_zero n' hπS)
          hyϖ.symm)
    obtain ⟨b, hb⟩ : ∃ b : ℕ, (b : ℕ∞) = addVal S (algebraMap R S π) :=
      ENat.ne_top_iff_exists.mp (by rwa [Ne, addVal_eq_top_iff])
    rw [← ha, ← hb] at h1 ⊢
    have : n' * a = n' * b := by
      simp only [nsmul_eq_mul] at h1
      exact_mod_cast h1
    rw [Nat.eq_of_mul_eq_mul_left (Nat.pos_of_ne_zero hn0) this]
  obtain ⟨w, hw⟩ := (addVal_eq_iff_associated _ _).1 hval
  set z : S := ↑w⁻¹
  have hyz : y ^ m = algebraMap R S π * z := by
    rw [← hw, mul_assoc, Units.mul_inv, mul_one]
  have hz : z ^ n' = algebraMap R S (u : R) := by
    apply mul_left_cancel₀ (pow_ne_zero n' hπS)
    rw [← mul_pow, ← hyz, mul_comm _ (algebraMap R S (u : R)), ← hyϖ]
  exact ⟨maximalIdeal_eq_span hπ u.isUnit hnR hm hinj hz hyz hgen,
    isSeparable_residueField hπ u.isUnit hnR hm hinj hz hyz hgen⟩

end DVR

end Abhyankar

end SemistableReduction
