/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.DVRDescentChoice

/-!
# Uniform descent of node points (O1, the W10-facing form)

Blueprint §9.12, O1. Let `G / C(x)` be finite, generated by a finite set `T`, and `c ∈ C` with
`0 < |c| < 1`. There is a finite set `S ⊆ C` of constants such that for **every** complete
discretely valued `E` with an isometric `φ : E → C` whose image contains `S`, and every
`F₀ / E(x)` with `χ : F₀ → G` compatible with `ratFuncMap φ`, of the same degree and with
`T ⊆ χ(F₀)`, every ordinary double point `P'` of the normalized node chart `Rint c G` over the
node descends to a semistable point of the integral closure `B_E` of `O_E[x, c₀/x]` in `F₀`
(**`exists_finset_forall_isSemistableAt`**). The properties of `E` used (D3c/D3d, the descended
elements, the rational residues) only depend on finitely many constants lying in `φ(E)` and on
finitely many elements of `G` lying in `χ(F₀)`.
-/

open NNReal Polynomial IsLocalRing Valuation

namespace SemistableReduction

namespace DVRDescent

open GaussTube FundamentalInequality GaussStability GaussFibre ZariskiModel

universe u v w

/-! ### The family of subfields generated by constants, `x` and `T` -/

section Family

variable {C : Type u} [NontriviallyNormedField C] {G : Type*} [Field G]
  [Algebra (RatFunc C) G] [Algebra C G] [IsScalarTower C (RatFunc C) G]

/-- The subfield of `G` generated by the constants in `S`, `x` and `T`. -/
noncomputable def famT (T : Finset G) (S : Set C) : Subfield G :=
  Subfield.closure (algebraMap C G '' S ∪ ({xF C G} ∪ (T : Set G)))

omit [IsScalarTower C (RatFunc C) G] in
lemma famT_mono (T : Finset G) {S S' : Set C} (h : S ⊆ S') : famT T S ≤ famT T S' :=
  Subfield.closure_mono (Set.union_subset_union_left _ (Set.image_mono h))

omit [IsScalarTower C (RatFunc C) G] in
lemma xF_mem_famT (T : Finset G) (S : Set C) : xF C G ∈ famT T S :=
  Subfield.subset_closure (Set.mem_union_right _ (Set.mem_union_left _ rfl))

omit [IsScalarTower C (RatFunc C) G] in
lemma mem_famT_of_mem (T : Finset G) (S : Set C) {t : G} (ht : t ∈ T) : t ∈ famT T S :=
  Subfield.subset_closure (Set.mem_union_right _ (Set.mem_union_right _ ht))

omit [IsScalarTower C (RatFunc C) G] in
lemma algebraMap_mem_famT (T : Finset G) {S : Set C} {e : C} (he : e ∈ S) :
    algebraMap C G e ∈ famT T S :=
  Subfield.subset_closure (Set.mem_union_left _ ⟨e, he, rfl⟩)

/-- **The family covers `G`**: every element of `G = C(x)[T]` lies in `famT T S` for a finite
set `S` of constants. -/
lemma exists_finset_mem_famT {T : Finset G} (hT : Algebra.adjoin (RatFunc C) (T : Set G) = ⊤)
    (y : G) : ∃ S : Finset C, y ∈ famT T (S : Set C) := by
  classical
  have hy : y ∈ Algebra.adjoin (RatFunc C) (T : Set G) := by rw [hT]; exact Algebra.mem_top
  induction hy using Algebra.adjoin_induction with
  | mem t ht => exact ⟨∅, mem_famT_of_mem T _ ht⟩
  | algebraMap f =>
    refine ⟨f.num.coeffs ∪ f.denom.coeffs, algebraMap_ratFunc_mem _ f (fun j ↦ ?_)
      (xF_mem_famT T _)⟩
    have hmem : ∀ q : C[X], q.coeffs ⊆ f.num.coeffs ∪ f.denom.coeffs →
        algebraMap C G (q.coeff j) ∈
          famT T ((f.num.coeffs ∪ f.denom.coeffs : Finset C) : Set C) := by
      intro q hq
      by_cases h0 : q.coeff j = 0
      · rw [h0, map_zero]; exact zero_mem _
      · exact algebraMap_mem_famT T (Finset.mem_coe.mpr (hq (Polynomial.coeff_mem_coeffs h0)))
    exact ⟨hmem _ Finset.subset_union_left, hmem _ Finset.subset_union_right⟩
  | add a b _ _ ha hb =>
    obtain ⟨S, hS⟩ := ha
    obtain ⟨S', hS'⟩ := hb
    exact ⟨S ∪ S', add_mem (famT_mono T (by simp) hS) (famT_mono T (by simp) hS')⟩
  | mul a b _ _ ha hb =>
    obtain ⟨S, hS⟩ := ha
    obtain ⟨S', hS'⟩ := hb
    exact ⟨S ∪ S', mul_mem (famT_mono T (by simp) hS) (famT_mono T (by simp) hS')⟩

/-- `famT T S ⊆ χ(F₀)` when the constants `S` come from `E` and `T ⊆ χ(F₀)`. -/
lemma famT_le_fieldRange {E : Type*} [NontriviallyNormedField E] {φ : E →+* C}
    {F₀ : Type*} [Field F₀] [Algebra (RatFunc E) F₀] {χ : F₀ →+* G} (hχ : IsCompat φ χ)
    {T : Finset G} (hTχ : (T : Set G) ⊆ Set.range χ) {S : Set C} (hS : S ⊆ Set.range φ) :
    famT T S ≤ χ.fieldRange := by
  refine Subfield.closure_le.mpr ?_
  rintro _ (⟨e, he, rfl⟩ | h | h)
  · obtain ⟨e', rfl⟩ := hS he
    refine ⟨algebraMap (RatFunc E) F₀ (algebraMap E (RatFunc E) e'), ?_⟩
    rw [hχ, ratFuncMap_algebraMap_C, ← IsScalarTower.algebraMap_apply]
  · rw [Set.mem_singleton_iff] at h
    subst h
    refine ⟨algebraMap (RatFunc E) F₀ RatFunc.X, ?_⟩
    rw [hχ, ratFuncMap_X]
  · obtain ⟨f, hf⟩ := hTχ h
    exact ⟨f, hf⟩

end Family

/-! ### A primitive element mapping to a generator -/

section Primitive

variable {C : Type u} [NontriviallyNormedField C] {G : Type*} [Field G] [Algebra (RatFunc C) G]
  {E : Type*} [NontriviallyNormedField E] {φ : E →+* C}
  {F₀ : Type*} [Field F₀] [Algebra (RatFunc E) F₀] [FiniteDimensional (RatFunc E) F₀]
  [Algebra.IsSeparable (RatFunc E) F₀] {χ : F₀ →+* G}

/-- A primitive element of `F₀ / E(x)` maps to a generator of `G / C(x)` if `T ⊆ χ(F₀)`. -/
lemma exists_primitive_χ (hχ : IsCompat φ χ) {T : Finset G}
    (hT : Algebra.adjoin (RatFunc C) (T : Set G) = ⊤) (hTχ : (T : Set G) ⊆ Set.range χ) :
    ∃ θ₀ : F₀, Algebra.adjoin (RatFunc C) {χ θ₀} = ⊤ := by
  obtain ⟨α, hα⟩ := Field.exists_primitive_element (RatFunc E) F₀
  refine ⟨α, eq_top_iff.mpr ?_⟩
  rw [← hT, Algebra.adjoin_le_iff]
  intro t ht
  obtain ⟨f, rfl⟩ := hTχ ht
  have hint : IsIntegral (RatFunc E) α := Algebra.IsIntegral.isIntegral α
  have hf : f ∈ Algebra.adjoin (RatFunc E) {α} := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hint.isAlgebraic, hα]
    trivial
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hf
  obtain ⟨P, rfl⟩ := hf
  change χ (aeval α P) ∈ _
  rw [← aeval_map_χ hχ]
  exact Polynomial.aeval_mem_adjoin_singleton _ _

end Primitive

/-! ### Descent at one ordinary double point -/

section Point

variable {C : Type u} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
  {G : Type v} [Field G] [Algebra (RatFunc C) G] [Algebra C G]
  [IsScalarTower C (RatFunc C) G] [FiniteDimensional (RatFunc C) G]

attribute [local instance] isCurveFunctionField DiscreteCoefficients.isAlgClosed_residueField

local notation "𝓀" => ResidueField (HenselComplete.integers C)

set_option maxHeartbeats 4000000 in
-- the assembly instantiates the descent over `E` (many large terms)
include hp hp1 in
/-- **Uniform descent at one ordinary double point**: a finite set of constants `S` such that
every admissible `E ⊇ S` descends `P'` to a semistable point. -/
theorem exists_finset_isSemistableAt {T : Finset G}
    (hT : Algebra.adjoin (RatFunc C) (T : Set G) = ⊤) {c : C} (hc : ‖c‖ < 1) (hc0 : c ≠ 0)
    (P' : Ideal (Rint c G)) [P'.IsMaximal]
    (hP' : P'.comap (algebraMap (nodeRing c) (Rint c G)) = tubeIdeal c)
    (hODP : IsNodeODP hc hc0 P') :
    ∃ S : Finset C, ∀ {E F₀ : Type w} [NontriviallyNormedField E] [IsUltrametricDist E]
      [IsDiscreteValuationRing (HenselComplete.integers E)] (φ : E →+* C)
      (_hφ : ∀ e, ‖φ e‖ = ‖e‖) (_hS : (S : Set C) ⊆ Set.range φ)
      (_halg : letI := φ.toAlgebra; Algebra.IsAlgebraic E C)
      [Field F₀] [Algebra (RatFunc E) F₀] [FiniteDimensional (RatFunc E) F₀]
      [Algebra.IsSeparable (RatFunc E) F₀] (χ : F₀ →+* G) (_hχ : IsCompat φ χ)
      (_hdeg : Module.finrank (RatFunc E) F₀ = Module.finrank (RatFunc C) G)
      (_hTχ : (T : Set G) ⊆ Set.range χ) (c₀ : E) (_hcc : φ c₀ = c)
      (ι : BE F₀ c₀ →+* Rint c G) (_hι : ∀ y, (ι y : G) = χ y)
      {ϖ : HenselComplete.integers E} (_hϖ : Irreducible ϖ),
      letI := algO F₀ c₀
      IsSemistableAt ϖ (P'.comap ι) := by
  classical
  obtain ⟨b₁, -, hb₁, -⟩ := id hODP
  obtain ⟨b₂, hb₂, hfp, hP₁, hP₂⟩ := exists_cData hc hc0 hODP hb₁
  obtain ⟨t₀, ht₀, ht₀o, ht₀i⟩ := exists_killer hp hp1 hc hc0 hP' hb₁ hb₂
  obtain ⟨⟨yu, hyu₁, hyu₂⟩, ⟨yv, hyv₂, hyv₁⟩⟩ := exists_params hc hc0 hfp hP₁ hP₂
  obtain ⟨N, r, hr⟩ := exists_spanning hc hc0 b₁.1 b₂.1
  choose κ hκ using fun j ↦ residue_surjective (placeHom hc b₁.1 b₁.2.2 (r j))
  -- the family of subfields
  have hLmono : Monotone fun S : Finset C ↦ famT T (S : Set C) :=
    fun S S' h ↦ famT_mono T (Finset.coe_subset.mpr h)
  have hLcov : ∀ y : G, ∃ S : Finset C, y ∈ famT T (S : Set C) := exists_finset_mem_famT hT
  obtain ⟨T₁, hT₁⟩ := exists_injOn_adjoin hp hp1 _ hLmono hLcov
  obtain ⟨T₂, hT₂⟩ := exists_injOn_adjoin (F' := Inv c hc0 G) hp hp1
    (fun S : Finset C ↦ (famT T (S : Set C) : Subfield G)) hLmono hLcov
  -- the elements to descend
  obtain ⟨ys, hys⟩ : ∃ ys : Finset (Rint c G),
      ys = {t₀, yu, yv, xR c, yR c} ∪ Finset.univ.image r := ⟨_, rfl⟩
  choose Ty hTy using fun y : Rint c G ↦ hLcov (y : G)
  refine ⟨T₁ ∪ T₂ ∪ ys.biUnion Ty ∪ Finset.univ.image fun j ↦ (κ j : C), ?_⟩
  intro E F₀ _ _ _ φ hφ hS halg _ _ _ _ χ hχ hdeg hTχ c₀ hcc ι hι ϖ hϖ
  have hleS : ∀ S' : Finset C, (∀ t ∈ S', t ∈ T₁ ∪ T₂ ∪ ys.biUnion Ty ∪
      Finset.univ.image fun j ↦ (κ j : C)) → famT T (S' : Set C) ≤ χ.fieldRange :=
    fun S' hS' ↦ famT_le_fieldRange hχ hTχ fun t ht ↦ hS (Finset.mem_coe.mpr (hS' t ht))
  obtain ⟨θ₀, hθ₀⟩ := exists_primitive_χ hχ hT hTχ
  have hc₀ : c₀ ≠ 0 := fun h ↦ hc0 (by rw [← hcc, h, map_zero])
  have hc₀1 : ‖c₀‖ ≤ 1 := by rw [← hφ, hcc]; exact hc.le
  -- `e = 1` and linear disjointness at the outer vertices
  obtain ⟨hinj₁, hgen₁⟩ := hT₁ _ (hleS T₁ fun t ht ↦ by simp [ht])
  have hinj := hinj_of_injOn χ hinj₁
  have hgen := fun W ↦ hgen_of_adjoin χ W (hgen₁ W)
  have heo := exists_valuation_eq hp hp1 hφ hχ hdeg hinj hgen
  have hLD₁ : letI := kEAlgebra φ
      ConstantDescent.LinDisj (kE φ) 𝓀 (resE χ b₁.1) :=
    linDisj_resE hp hp1 hφ hχ hdeg hinj hgen b₁.1
  subst hcc
  -- the inner vertices, through the inversion
  haveI : CharZero E := φ.charZero
  haveI : Algebra.IsSeparable (RatFunc E) (Inv c₀ hc₀ F₀) :=
    Algebra.IsAlgebraic.isSeparable_of_perfectField
  have hχI := isCompat_χI hc₀ hc0 hχ
  have hdegI : Module.finrank (RatFunc E) (Inv c₀ hc₀ F₀) =
      Module.finrank (RatFunc C) (Inv (φ c₀) hc0 G) := by
    rw [finrank_inv, finrank_inv, hdeg]
  have hM₂ : (famT T (T₂ : Set C) : Subfield G) ≤ (χI hc₀ hc0 χ).fieldRange :=
    hleS T₂ fun t ht ↦ by simp [ht]
  obtain ⟨hinj₂, hgen₂⟩ := hT₂ _ hM₂
  have hinjI := hinj_of_injOn (χI hc₀ hc0 χ) hinj₂
  have hgenI := fun W ↦ hgen_of_adjoin (χI hc₀ hc0 χ) W (hgen₂ W)
  have heoI := exists_valuation_eq hp hp1 hφ hχI hdegI hinjI hgenI
  have hLD₂ : letI := kEAlgebra φ
      ConstantDescent.LinDisj (kE φ) 𝓀 (resE (χI hc₀ hc0 χ) b₂.1) :=
    linDisj_resE hp hp1 hφ hχI hdegI hinjI hgenI b₂.1
  -- descending the finitely many elements
  have hdesc : ∀ y ∈ ys, ∃ b, ι b = y := by
    intro y hy
    have h1 : (y : G) ∈ χ.fieldRange := hleS (Ty y) (fun t ht ↦ by
      simp only [Finset.mem_union, Finset.mem_biUnion]
      exact Or.inl (Or.inr ⟨y, hy, ht⟩)) (hTy y)
    obtain ⟨f, hf⟩ := h1
    have hfB : f ∈ BE F₀ c₀ :=
      mem_BE_of_χ hφ hχ hdeg hθ₀ hc₀ hc₀1 (by rw [hf]; exact y.2)
    exact ⟨⟨f, hfB⟩, Subtype.ext (by rw [hι]; exact hf)⟩
  have hmem5 : ∀ y ∈ ({t₀, yu, yv, xR (φ c₀), yR (φ c₀)} : Finset _),
      y ∈ ys := fun y hy ↦ by rw [hys]; exact Finset.mem_union_left _ hy
  have hin5 : ∀ {y}, y = t₀ ∨ y = yu ∨ y = yv ∨ y = xR (φ c₀) ∨
      y = yR (φ c₀) → y ∈ ys := fun h ↦ hmem5 _ (by
    simp only [Finset.mem_insert, Finset.mem_singleton]; exact h)
  obtain ⟨t₀', ht₀'⟩ := hdesc t₀ (hin5 (by tauto))
  obtain ⟨yu', hyu'⟩ := hdesc yu (hin5 (by tauto))
  obtain ⟨yv', hyv'⟩ := hdesc yv (hin5 (by tauto))
  have hxrange : xR (φ c₀) ∈ ι.range := hdesc _ (hin5 (by tauto))
  have hyrange : yR (φ c₀) ∈ ι.range := hdesc _ (hin5 (by tauto))
  have hrrange' : ∀ j, r j ∈ ι.range := fun j ↦ hdesc _
    (by rw [hys]; exact Finset.mem_union_right _ (Finset.mem_image_of_mem _ (Finset.mem_univ j)))
  refine isSemistableAt_of_descentData hp hp1 hφ hχ hdeg hθ₀ rfl hc hc0 hP' hODP hb₁ hb₂ ι hι
    ?_ ?_ ?_ ?_ t₀' ?_ ?_ ?_ yu' ?_ ?_ yv' ?_ ?_ ?_ ?_ ?_ hϖ
  · exact heo
  · exact fun v f ↦ heoI (toInvExt hc0 v) f
  · exact hLD₁
  · exact hLD₂
  · rw [ht₀']; exact ht₀
  · rw [ht₀']; exact ht₀o
  · rw [ht₀']; exact ht₀i
  · rw [hyu']; exact hyu₁
  · rw [hyu']; exact hyu₂
  · rw [hyv']; exact hyv₂
  · rw [hyv']; exact hyv₁
  · exact hr ι.range hrrange' hxrange hyrange
  · refine exists_residue_of_span hφ hχ hc hc0 hP₁ (xR_mem hP') (yR_mem hP') ι hι hLD₁ r hr
      hrrange' hxrange hyrange fun j ↦ ?_
    obtain ⟨e, he⟩ := hS (Finset.mem_coe.mpr (Finset.mem_union_right _
      (Finset.mem_image_of_mem _ (Finset.mem_univ j))))
    refine ⟨e, by rw [← hφ, he]; exact (HenselComplete.mem_integers_iff _).1 (κ j).2, ?_⟩
    rw [← hκ j]
    congr 1
    exact Subtype.ext he.symm
  · exact isAlgebraic_kE φ halg

include hp hp1 in
/-- **Uniform descent of node points** (O1, W10-facing form): a finite set of constants `S` such
that for every admissible `E ⊇ S`, every ordinary double point over the node of the normalized
node chart descends to a semistable point of `B_E`. -/
theorem exists_finset_forall_isSemistableAt {T : Finset G}
    (hT : Algebra.adjoin (RatFunc C) (T : Set G) = ⊤) {c : C} (hc : ‖c‖ < 1) (hc0 : c ≠ 0) :
    ∃ S : Finset C, ∀ {E F₀ : Type w} [NontriviallyNormedField E] [IsUltrametricDist E]
      [IsDiscreteValuationRing (HenselComplete.integers E)] (φ : E →+* C)
      (_hφ : ∀ e, ‖φ e‖ = ‖e‖) (_hS : (S : Set C) ⊆ Set.range φ)
      (_halg : letI := φ.toAlgebra; Algebra.IsAlgebraic E C)
      [Field F₀] [Algebra (RatFunc E) F₀] [FiniteDimensional (RatFunc E) F₀]
      [Algebra.IsSeparable (RatFunc E) F₀] (χ : F₀ →+* G) (_hχ : IsCompat φ χ)
      (_hdeg : Module.finrank (RatFunc E) F₀ = Module.finrank (RatFunc C) G)
      (_hTχ : (T : Set G) ⊆ Set.range χ) (c₀ : E) (_hcc : φ c₀ = c)
      (ι : BE F₀ c₀ →+* Rint c G) (_hι : ∀ y, (ι y : G) = χ y)
      {ϖ : HenselComplete.integers E} (_hϖ : Irreducible ϖ)
      (P' : Ideal (Rint c G)) [P'.IsMaximal]
      (_hP' : P'.comap (algebraMap (nodeRing c) (Rint c G)) = tubeIdeal c)
      (_hODP : IsNodeODP hc hc0 P'),
      letI := algO F₀ c₀
      IsSemistableAt ϖ (P'.comap ι) := by
  classical
  haveI := finite_ext (F := G) hp hp1
  letI : Fintype (OuterBranch C G) := Fintype.ofFinite _
  let Sb : OuterBranch C G → Finset C := fun b ↦
    if h : (placeIdeal hc b.1 b.2.2).comap (algebraMap (nodeRing c) (Rint c G)) =
        tubeIdeal c ∧ IsNodeODP hc hc0 (placeIdeal hc b.1 b.2.2) then
      haveI := placeIdeal_isMaximal hc b.1 b.2.2
      Classical.choose (exists_finset_isSemistableAt.{u, v, w} hp hp1 hT hc hc0
        (placeIdeal hc b.1 b.2.2) h.1 h.2)
    else ∅
  refine ⟨Finset.univ.biUnion Sb, ?_⟩
  intro E F₀ _ _ _ φ hφ hS halg _ _ _ _ χ hχ hdeg hTχ c₀ hcc ι hι ϖ hϖ P' _ hP' hODP
  obtain ⟨b₁, -, hb₁, -⟩ := id hODP
  obtain ⟨-, -, -, hP₁, -⟩ := exists_cData hc hc0 hODP hb₁
  subst hP₁
  have h : (placeIdeal hc b₁.1 b₁.2.2).comap (algebraMap (nodeRing c) (Rint c G)) =
      tubeIdeal c ∧ IsNodeODP hc hc0 (placeIdeal hc b₁.1 b₁.2.2) := ⟨hP', hODP⟩
  have hsub : Sb b₁ ⊆ Finset.univ.biUnion Sb := Finset.subset_biUnion_of_mem Sb (Finset.mem_univ _)
  simp only [Sb, dif_pos h] at hsub
  exact Classical.choose_spec (exists_finset_isSemistableAt.{u, v, w} hp hp1 hT hc hc0
    (placeIdeal hc b₁.1 b₁.2.2) h.1 h.2) φ hφ
    ((Finset.coe_subset.mpr hsub).trans hS) halg χ hχ hdeg hTχ c₀ hcc ι hι hϖ

end Point

end DVRDescent

end SemistableReduction
