/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.LocalStability
import TemperedFundamentalGroups.SemistableReduction.LocalGlobal

/-!
# W4: stability of Gauss-valued rational function fields

Blueprint §9.4, G4 (**W4**, mixed characteristic). Let `C` be an algebraically closed
non-archimedean field of characteristic `0` with `‖p‖ < 1`, `v` its norm valuation and
`w = w_{a,r}` the Gauss valuation on `C(X)` (`Gauss.gaussRat`) with `r = ‖c‖` in the value group.
For every finite separable `F' / C(X)`:

`Σ_{w' | w} e(w' | w) f(w' | w) = [F' : C(X)]`

(`finsum_ramificationIdx_mul_inertiaDeg_eq`, the sum over the real valuations `w'` of `F'`
restricting to `w`; `finsum_ramificationIdx_mul_inertiaDeg_eq_withAbs` in terms of the normed
field `GaussField a r = WithAbs w`).

Proof: B4 (`LocalGlobal.finsum_ramificationIdx_mul_inertiaDeg_completion`) reduces to the
defectlessness of the finite extensions of the completion `\hat F` of `C(X)`, which is G3 since
`\hat F` is Gauss-complete, generated by `(X - a) / c` (`isGaussComplete_gen`).
-/

open Polynomial IsLocalRing Valuation NNReal UniformSpace
open scoped IntermediateField

namespace SemistableReduction

open FundamentalInequality DenseCompletion KummerNormalForm DiscreteCoefficients
  InertiallyGenerated NormedTower NoImmediate LocalStability LocalGlobal Gauss

namespace GaussStability

local notation "κ" X => ResidueField (HenselComplete.integers X)

universe u

variable {C : Type u} [NontriviallyNormedField C] [IsUltrametricDist C] (a : C) (r : ℝ≥0ˣ)

/-- The rational function field `C(X)` with the Gauss norm of radius `r` around `a`. -/
abbrev GaussField : Type u :=
  WithAbs (gaussRat (NormedField.valuation (K := C)) a r).toAbsoluteValue

lemma norm_gaussField (x : GaussField a r) :
    ‖x‖ = gaussRat (NormedField.valuation (K := C)) a r x.ofAbs := rfl

lemma norm_algebraMap_gaussField (c : C) : ‖algebraMap C (GaussField a r) c‖ = ‖c‖ := by
  rw [norm_gaussField, WithAbs.algebraMap_right_apply, WithAbs.ofAbs_toAbs, gaussRat_algebraMap_C,
    NormedField.valuation_apply, coe_nnnorm]

noncomputable instance : NormedAlgebra C (GaussField a r) where
  norm_smul_le c x := le_of_eq (by rw [Algebra.smul_def, norm_mul, norm_algebraMap_gaussField])

noncomputable instance : NontriviallyNormedField (GaussField a r) where
  __ : NormedField (GaussField a r) := inferInstance
  non_trivial :=
    let ⟨x, hx⟩ := NontriviallyNormedField.non_trivial (α := C)
    ⟨algebraMap C _ x, by rwa [norm_algebraMap_gaussField]⟩

variable {a r} {c : C} (hc : NormedField.valuation c = (r : ℝ≥0))

/-- The generator `(X - a) / c` of `C(X)`. -/
noncomputable def gen (c : C) : GaussField a r :=
  WithAbs.toAbs _ (algebraMap C[X] (RatFunc C) (gaussLin a c))

include hc in
lemma norm_aeval_gen (Q : C[X]) :
    ‖aeval (gen (a := a) (r := r) c) Q‖ = Gauss.sup (NormedField.valuation (K := C)) 1 Q := by
  rw [norm_gaussField]
  have : (aeval (gen (a := a) (r := r) c) Q).ofAbs =
      aeval (algebraMap C[X] (RatFunc C) (gaussLin a c)) Q :=
    (aeval_algHom_apply (WithAbs.algEquiv C _).toAlgHom (gen c) Q).symm
  rw [this, gaussRat_aeval_gaussLin hc]

/-- The generator `(X - a) / c` in the completion. -/
noncomputable def genK (c : C) : Completion (GaussField a r) :=
  algebraMap (GaussField a r) (Completion (GaussField a r)) (gen c)

include hc in
lemma norm_aeval_genK (Q : C[X]) :
    ‖aeval (genK (a := a) (r := r) c) Q‖ = Gauss.sup (NormedField.valuation (K := C)) 1 Q := by
  rw [genK, aeval_algebraMap_apply]
  erw [algebraMap_completion, Completion.norm_coe]
  exact norm_aeval_gen hc Q

/-- Every element of `C(X)` is a rational function in `(X - a) / c`. -/
lemma algebraMap_mem_adjoin_genK (hc0 : c ≠ 0) (f : GaussField a r) :
    algebraMap (GaussField a r) (Completion (GaussField a r)) f ∈
      C⟮genK (a := a) (r := r) c⟯ := by
  set ℓ := gaussLin a c
  have hσ : (Polynomial.C c * X + Polynomial.C a).comp ℓ = X := by
    simp only [ℓ, gaussLin, add_comp, mul_comp, C_comp, X_comp]
    rw [← mul_assoc, ← C_mul, mul_inv_cancel₀ hc0, C_1, one_mul, sub_add_cancel]
  have hpoly : ∀ q : C[X], algebraMap (GaussField a r) (Completion (GaussField a r))
      (WithAbs.toAbs _ (algebraMap C[X] (RatFunc C) q)) ∈ C⟮genK (a := a) (r := r) c⟯ := by
    intro q
    have hq : algebraMap C[X] (RatFunc C) q =
        aeval (algebraMap C[X] (RatFunc C) ℓ) (q.comp (Polynomial.C c * X + Polynomial.C a)) := by
      rw [aeval_algebraMap_apply, ← comp_eq_aeval, comp_assoc, hσ, comp_X]
    have h2 : WithAbs.toAbs (gaussRat (NormedField.valuation (K := C)) a r).toAbsoluteValue
        (algebraMap C[X] (RatFunc C) q) =
        aeval (gen (a := a) (r := r) c) (q.comp (Polynomial.C c * X + Polynomial.C a)) := by
      rw [hq]
      exact (aeval_algHom_apply (WithAbs.algEquiv C
        (gaussRat (NormedField.valuation (K := C)) a r).toAbsoluteValue).symm.toAlgHom
        (algebraMap C[X] (RatFunc C) ℓ) _).symm
    rw [h2, ← aeval_algebraMap_apply]
    exact IntermediateField.algebra_adjoin_le_adjoin _ _ (aeval_mem_adjoin_singleton _ _)
  obtain ⟨φ, rfl⟩ :=
    WithAbs.toAbs_surjective (gaussRat (NormedField.valuation (K := C)) a r).toAbsoluteValue f
  rw [← RatFunc.num_div_denom φ, WithAbs.toAbs_div, map_div₀]
  exact div_mem (hpoly _) (hpoly _)

include hc in
/-- The completion of `C(X)` for the Gauss valuation is Gauss-complete, generated by
`(X - a) / c` (W1: the Gauss norm of `Q((X - a) / c)` is `maxᵢ ‖Qᵢ‖`). -/
theorem isGaussComplete_genK : IsGaussComplete C (genK (a := a) (r := r) c) := by
  have hc0 : c ≠ 0 := by
    rintro rfl
    exact r.ne_zero (hc.symm.trans (map_zero _))
  set x := genK (a := a) (r := r) c
  have hx1 : ‖x‖ = 1 := by
    have := norm_aeval_genK (a := a) hc X
    rwa [aeval_X, sup_X, Units.val_one, NNReal.coe_one] at this
  refine ⟨hx1.le, ?_, ?_⟩
  · rintro ⟨Pbar, hPbar0, hroot⟩
    obtain ⟨P, rfl⟩ :=
      Polynomial.map_surjective _ (residue_surjective (R := HenselComplete.integers C)) Pbar
    set y : HenselComplete.integers (Completion (GaussField a r)) :=
      ⟨x, (HenselComplete.mem_integers_iff _).2 hx1.le⟩
    have hy : rd x = residue _ y := rd_coe y
    rw [hy, ← ValuationResidue.residue_aeval] at hroot
    have hlt := (HenselComplete.mem_maximalIdeal_iff_norm_lt_one _).1
      ((residue_eq_zero_iff _).1 hroot)
    rw [ValuationResidue.coe_aeval, norm_aeval_genK (a := a) hc,
      Gauss.sup_one_map_eq P hPbar0] at hlt
    simp at hlt
  · refine eq_top_iff.2 fun y _ ↦ ?_
    change y ∈ closure ((C⟮x⟯).toSubfield : Set (Completion (GaussField a r)))
    refine closure_mono ?_ (denseRange_algebraMap_completion (GaussField a r) y)
    rintro _ ⟨f, rfl⟩
    exact algebraMap_mem_adjoin_genK hc0 f

section RatFunc

variable (a r) (F' : Type*) [Field F'] [Algebra (RatFunc C) F']

/-- The real valuations of `F'` extending the Gauss valuation `w_{a,r}` of `C(X)`. -/
def GaussExtension : Type _ :=
  {w : Valuation F' ℝ≥0 //
    w.comap (algebraMap (RatFunc C) F') = gaussRat (NormedField.valuation (K := C)) a r}

instance (w : GaussExtension a r F') :
    (gaussRat (NormedField.valuation (K := C)) a r).HasExtension w.1 :=
  hasExtension_of_comap_eq w.2

variable {a r F'}

lemma algebraMap_gaussField_apply (x : GaussField a r) :
    algebraMap (GaussField a r) F' x = algebraMap (RatFunc C) F' x.ofAbs := rfl

lemma comap_gaussField (w : Valuation F' ℝ≥0) :
    w.comap (algebraMap (GaussField a r) F') = NormedField.valuation (K := GaussField a r) ↔
      w.comap (algebraMap (RatFunc C) F') = gaussRat (NormedField.valuation (K := C)) a r := by
  constructor
  · intro h
    ext y
    have := congrArg (fun v : Valuation (GaussField a r) ℝ≥0 ↦ v (WithAbs.toAbs _ y)) h
    simp only [comap_apply, algebraMap_gaussField_apply, valuation_withAbs] at this
    rw [comap_apply, this]
  · intro h
    ext x
    have := congrArg (fun v : Valuation (RatFunc C) ℝ≥0 ↦ v x.ofAbs) h
    simp only [comap_apply] at this
    rw [comap_apply, algebraMap_gaussField_apply, valuation_withAbs, this]

/-- The extensions of the Gauss valuation are the extensions of the Gauss norm. -/
def gaussExtensionEquiv : GaussExtension a r F' ≃ Extension (GaussField a r) F' where
  toFun w := ⟨w.1, (comap_gaussField w.1).2 w.2⟩
  invFun w := ⟨w.1, (comap_gaussField w.1).1 w.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

lemma ramificationIdx_gaussField (w : Valuation F' ℝ≥0) :
    ramificationIdx (GaussField a r) w = ramificationIdx (RatFunc C) w := by
  have h : valueGroup (w.comap (algebraMap (GaussField a r) F')) =
      valueGroup (w.comap (algebraMap (RatFunc C) F')) := by
    ext g
    exact ⟨fun ⟨x, hx⟩ ↦ ⟨x.ofAbs, hx⟩, fun ⟨y, hy⟩ ↦ ⟨WithAbs.toAbs _ y, hy⟩⟩
  rw [ramificationIdx, ramificationIdx, h]

lemma inertiaDeg_gaussField (w : GaussExtension a r F') :
    inertiaDeg (NormedField.valuation (K := GaussField a r)) (gaussExtensionEquiv w).1 =
      inertiaDeg (gaussRat (NormedField.valuation (K := C)) a r) w.1 := by
  set v := gaussRat (NormedField.valuation (K := C)) a r
  let e : (NormedField.valuation (K := GaussField a r)).valuationSubring ≃+* v.valuationSubring :=
    { toFun := fun x ↦ ⟨x.1.ofAbs, by
        have := x.2
        rwa [mem_valuationSubring_iff, valuation_withAbs] at this⟩
      invFun := fun y ↦ ⟨WithAbs.toAbs _ y.1, by
        rw [mem_valuationSubring_iff, valuation_withAbs]
        exact y.2⟩
      left_inv := fun _ ↦ rfl
      right_inv := fun _ ↦ rfl
      map_mul' := fun _ _ ↦ rfl
      map_add' := fun _ _ ↦ rfl }
  refine Algebra.finrank_eq_of_equiv_equiv (IsLocalRing.ResidueField.mapEquiv e)
    (RingEquiv.refl _) ?_
  ext r
  obtain ⟨x, rfl⟩ := residue_surjective r
  simp only [RingHom.coe_comp, Function.comp_apply, RingEquiv.toRingHom_eq_coe,
    RingEquiv.coe_toRingHom, IsLocalRing.ResidueField.mapEquiv_apply,
    IsLocalRing.ResidueField.map_residue]
  rw [HasExtension.algebraMap_residue_eq_residue_algebraMap,
    HasExtension.algebraMap_residue_eq_residue_algebraMap]
  rfl

end RatFunc

section W4

variable [IsAlgClosed C] [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
include hp hp1 hc

/-- **W4** (normed form, Blueprint §9.4 G4): for the rational function field `F = C(X)` with
the Gauss norm `w_{a,r}` (`r = ‖c‖`) and a finite separable `F' / F`, the extensions `w'` of the
Gauss valuation to `F'` satisfy `Σ_{w'} e(w' | w) f(w' | w) = [F' : F]`. -/
theorem finsum_ramificationIdx_mul_inertiaDeg_eq_withAbs {F' : Type*} [Field F']
    [Algebra (GaussField a r) F'] [FiniteDimensional (GaussField a r) F']
    [Algebra.IsSeparable (GaussField a r) F'] :
    ∑ᶠ w : Extension (GaussField a r) F', ramificationIdx (GaussField a r) w.1 *
        inertiaDeg (NormedField.valuation (K := GaussField a r)) w.1 =
      Module.finrank (GaussField a r) F' :=
  finsum_ramificationIdx_mul_inertiaDeg_completion fun L _ _ _ _ ↦ by
    obtain ⟨he, hf⟩ := LocalStability.ramificationIdx_eq_one_and_inertiaDeg_eq hp hp1
      (isGaussComplete_genK (a := a) hc) L
    rw [he, hf, one_mul]

/-- **W4** (Blueprint §9.3/§9.4, mixed characteristic). Let `C` be algebraically closed of
characteristic `0` with `‖p‖ < 1`, `w = w_{a,r}` the Gauss valuation on `C(X)` with `r = ‖c‖`,
and `F' / C(X)` finite separable. Then `Σ_{w' | w} e(w' | w) f(w' | w) = [F' : C(X)]`, the sum
over the real valuations `w'` of `F'` extending `w`. -/
theorem finsum_ramificationIdx_mul_inertiaDeg_eq {F' : Type*} [Field F'] [Algebra (RatFunc C) F']
    [FiniteDimensional (RatFunc C) F'] [Algebra.IsSeparable (RatFunc C) F'] :
    ∑ᶠ w : GaussExtension a r F', ramificationIdx (RatFunc C) w.1 *
        inertiaDeg (gaussRat (NormedField.valuation (K := C)) a r) w.1 =
      Module.finrank (RatFunc C) F' := by
  have h := finsum_ramificationIdx_mul_inertiaDeg_eq_withAbs (a := a) hc hp hp1 (F' := F')
  have hdeg : Module.finrank (GaussField a r) F' = Module.finrank (RatFunc C) F' :=
    Algebra.finrank_eq_of_equiv_equiv (WithAbs.equiv _) (RingEquiv.refl F') (by ext; rfl)
  rw [← hdeg, ← h, ← finsum_comp_equiv gaussExtensionEquiv]
  refine finsum_congr fun w ↦ ?_
  rw [inertiaDeg_gaussField, ← ramificationIdx_gaussField (a := a) (r := r)]
  rfl

end W4

end GaussStability

end SemistableReduction
