/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.Gauss
import TemperedFundamentalGroups.SemistableReduction.ZariskiModel

/-!
# The projective line of a Gauss valuation

Blueprint §9.6 (W5), layer M2. Let `v` be a valuation on `K` with valuation subring `O`, and
`F = K(y)` a rational function field on which `w` is the Gauss valuation in the coordinate `y`:
`w(Q(y)) = max_i v(Qᵢ)` (`IsGaussCoord v w y`). The model `ℙ¹_O` with coordinate `y`
(`ZariskiModel.line v y`, charts `O[y]` and `O[y⁻¹]`) is a proper separated Zariski model of
finite type whose vertex set is `{O_w}`:

* `mem_polyChart_iff`: `O[y]` consists of the `Q(y)` with `max_i v(Qᵢ) ≤ 1`;
* `IsGaussCoord.localAt_polyChart`: the local ring of `O[y]` at the generic point of the special
  fibre is the valuation ring of `w`;
* `IsGaussCoord.eq_of_localAt_eq`: conversely, a valuation subring `W` of `F` over `O` which is a
  local ring of `O[y]` is the valuation ring of `w` (other points of the special fibre have
  local rings which are not valuation rings: at a closed point, the maximal ideal contains a
  prime element `q(y)` and `ϖ ∈ 𝔪_O` which divide neither each other);
* `line_isProper`, `line_isSeparated`, `line_isFiniteType`, `line_vertexSet`.

For the Gauss valuation `w_{a,r}` of `K(X)` (`gaussRat v a r`, W1) the coordinate is
`t = (X - a)/c` with `v(c) = r` (`isGaussCoord_gaussLin`), and `gaussModel v a c` is the model of
`K(X)` with vertex set `{O_{w_{a,r}}}` (`gaussModel_vertexSet`).
-/

open Polynomial IntermediateField

namespace SemistableReduction

open Gauss

variable {K : Type*} [Field K] {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
  {F : Type*} [Field F] [Algebra K F]

/-! ### Polynomial charts -/

section Chart

variable (v : Valuation K Γ₀)

lemma sup_neg (Q : K[X]) : Gauss.sup v 1 (-Q) = Gauss.sup v 1 Q := by
  rw [show -Q = C (-1) * Q by simp, Gauss.sup_mul, sup_C, Valuation.map_neg, map_one, one_mul]

/-- The chart `O[y] ⊆ F`, generated by the image of `O` and `y`. -/
def polyChart (y : F) : Subring F :=
  Subring.closure ((baseRing F v.valuationSubring : Set F) ∪ {y})

/-- The subring of `F` of all `Q(y)` with integral coefficients. -/
def integralEval (y : F) : Subring F where
  carrier := {x | ∃ Q : K[X], Gauss.sup v 1 Q ≤ 1 ∧ aeval y Q = x}
  mul_mem' := by
    rintro _ _ ⟨P, hP, rfl⟩ ⟨Q, hQ, rfl⟩
    exact ⟨P * Q, by rw [Gauss.sup_mul]; exact mul_le_one' hP hQ, map_mul _ _ _⟩
  one_mem' := ⟨1, by rw [← C_1, sup_C, map_one], map_one _⟩
  add_mem' := by
    rintro _ _ ⟨P, hP, rfl⟩ ⟨Q, hQ, rfl⟩
    exact ⟨P + Q, (sup_add_le P Q).trans (max_le hP hQ), map_add _ _ _⟩
  zero_mem' := ⟨0, by rw [sup_zero]; exact zero_le, map_zero _⟩
  neg_mem' := by
    rintro _ ⟨P, hP, rfl⟩
    exact ⟨-P, by rwa [sup_neg], map_neg _ _⟩

variable {v}

lemma coeff_le_one_of_sup_le_one {Q : K[X]} (hQ : Gauss.sup v 1 Q ≤ 1) (i : ℕ) :
    v (Q.coeff i) ≤ 1 := by
  simpa [term] using (term_le_sup (v := v) (r := 1) Q i).trans hQ

/-- **`O[y]` consists of the `Q(y)` with `max_i v(Qᵢ) ≤ 1`.** -/
theorem mem_polyChart_iff {y x : F} :
    x ∈ polyChart v y ↔ ∃ Q : K[X], Gauss.sup v 1 Q ≤ 1 ∧ aeval y Q = x := by
  constructor
  · intro hx
    refine (Subring.closure_le (t := integralEval v y)).2 ?_ hx
    rintro _ (⟨o, ho, rfl⟩ | h)
    · exact ⟨C o, by rw [sup_C]; exact ho, aeval_C _ _⟩
    · rw [Set.mem_singleton_iff.1 h]
      exact ⟨X, by rw [sup_X, Units.val_one], aeval_X _⟩
  · rintro ⟨Q, hQ, rfl⟩
    rw [aeval_eq_sum_range]
    refine Subring.sum_mem _ fun i _ ↦ ?_
    rw [Algebra.smul_def]
    have h₁ : algebraMap K F (Q.coeff i) ∈ polyChart v y :=
      Subring.subset_closure (Or.inl ⟨Q.coeff i, coeff_le_one_of_sup_le_one hQ i, rfl⟩)
    have h₂ : y ∈ polyChart v y := Subring.subset_closure (Or.inr (Set.mem_singleton y))
    exact Subring.mul_mem _ h₁ (Subring.pow_mem _ h₂ i)

lemma baseRing_le_polyChart (y : F) : baseRing F v.valuationSubring ≤ polyChart v y :=
  fun _ hx ↦ Subring.subset_closure (Or.inl hx)

lemma self_mem_polyChart (y : F) : y ∈ polyChart v y :=
  Subring.subset_closure (Or.inr rfl)

/-- A subring containing the base ring and `y` contains `O[y]`. -/
lemma polyChart_le {y : F} {A : Subring F} (hA : baseRing F v.valuationSubring ≤ A)
    (hy : y ∈ A) : polyChart v y ≤ A :=
  Subring.closure_le.2 (Set.union_subset hA (Set.singleton_subset_iff.2 hy))

end Chart

/-! ### Gauss coordinates -/

lemma valuationSubring_valuation_eq_one_iff {w : Valuation F Γ₀} {x : F} :
    w.valuationSubring.valuation x = 1 ↔ w x = 1 :=
  (Valuation.isEquiv_valuation_valuationSubring w).eq_one_iff_eq_one.symm

/-- `y` is a **Gauss coordinate** for `w` over `v`: `F = K(y)` and `w` is the Gauss valuation of
radius `1` in the coordinate `y`, `w(Q(y)) = max_i v(Qᵢ)`. -/
structure IsGaussCoord (v : Valuation K Γ₀) (w : Valuation F Γ₀) (y : F) : Prop where
  eq_sup : ∀ Q : K[X], w (aeval y Q) = Gauss.sup v 1 Q
  adjoin_eq_top : K⟮y⟯ = ⊤

namespace IsGaussCoord

variable {v : Valuation K Γ₀} {w : Valuation F Γ₀} {y : F} (h : IsGaussCoord v w y)
include h

lemma valuation_algebraMap (c : K) : w (algebraMap K F c) = v c := by
  rw [← aeval_C y c, h.eq_sup, sup_C]

lemma valuation_self : w y = 1 := by
  rw [← aeval_X (R := K) y, h.eq_sup, sup_X, Units.val_one]

lemma ne_zero : y ≠ 0 := by
  rintro rfl
  simpa using h.valuation_self

lemma aeval_eq_zero_iff {Q : K[X]} : aeval y Q = 0 ↔ Q = 0 := by
  refine ⟨fun hQ ↦ ?_, fun hQ ↦ by rw [hQ, map_zero]⟩
  rw [← sup_eq_zero_iff (v := v) (r := 1), ← h.eq_sup, hQ, map_zero]

lemma aeval_injective : Function.Injective (aeval (R := K) y) := by
  intro P Q hPQ
  rw [← sub_eq_zero, ← h.aeval_eq_zero_iff, map_sub, hPQ, sub_self]

/-- `w` restricts to `v` on `K`. -/
lemma comap_valuationSubring :
    w.valuationSubring.comap (algebraMap K F) = v.valuationSubring := by
  ext c
  rw [ValuationSubring.mem_comap, Valuation.mem_valuationSubring_iff,
    Valuation.mem_valuationSubring_iff, h.valuation_algebraMap]

lemma polyChart_le_valuationSubring : polyChart v y ≤ w.valuationSubring.toSubring := by
  intro x hx
  obtain ⟨Q, hQ, rfl⟩ := mem_polyChart_iff.1 hx
  change w (aeval y Q) ≤ 1
  rw [h.eq_sup]
  exact hQ

omit h in
/-- A nonzero polynomial is a scalar multiple of one with `max_i v(Qᵢ) = 1`. -/
lemma exists_sup_eq_one {v : Valuation K Γ₀} {Q : K[X]} (hQ : Q ≠ 0) :
    ∃ d : K, d ≠ 0 ∧ Gauss.sup v 1 (C d * Q) = 1 := by
  obtain ⟨j, hj⟩ := exists_term_eq_sup (v := v) (r := 1) Q
  have hvj : v (Q.coeff j) = Gauss.sup v 1 Q := by simpa [term] using hj
  have hj0 : Q.coeff j ≠ 0 := by
    intro h0
    rw [h0, map_zero, eq_comm, sup_eq_zero_iff] at hvj
    exact hQ hvj
  refine ⟨(Q.coeff j)⁻¹, inv_ne_zero hj0, ?_⟩
  rw [Gauss.sup_mul, sup_C, ← hvj, map_inv₀, inv_mul_cancel₀ (by simpa using hj0)]

/-- Every element of `F` is a quotient `P(y) / Q(y)` with `max_i v(Qᵢ) = 1`. -/
lemma exists_eq_div (x : F) :
    ∃ P Q : K[X], Gauss.sup v 1 Q = 1 ∧ x = aeval y P / aeval y Q := by
  have hx : x ∈ K⟮y⟯ := h.adjoin_eq_top ▸ IntermediateField.mem_top
  obtain ⟨P, Q, hPQ⟩ := (mem_adjoin_simple_iff K x).1 hx
  rcases eq_or_ne Q 0 with rfl | hQ
  · refine ⟨0, 1, by rw [← C_1, sup_C, map_one], ?_⟩
    simpa using hPQ
  obtain ⟨d, hd, hdQ⟩ := exists_sup_eq_one (v := v) hQ
  refine ⟨C d * P, C d * Q, hdQ, ?_⟩
  rw [hPQ, map_mul, map_mul, aeval_C, mul_div_mul_left]
  simpa using hd


/-- **The generic point of the special fibre of `O[y]`**: the local ring of `O[y]` at the center of
`w` is the valuation ring of `w`. -/
theorem localAt_polyChart :
    localAt (polyChart v y) w.valuationSubring = w.valuationSubring.toSubring := by
  refine le_antisymm (localAt_le h.polyChart_le_valuationSubring) fun x hx ↦ ?_
  obtain ⟨P, Q, hQ, rfl⟩ := h.exists_eq_div x
  have hQ0 : aeval y Q ≠ 0 := by
    rw [Ne, h.aeval_eq_zero_iff]
    rintro rfl
    simp [sup_zero] at hQ
  refine ⟨aeval y Q, mem_polyChart_iff.2 ⟨Q, hQ.le, rfl⟩,
    valuationSubring_valuation_eq_one_iff.2 (by rw [h.eq_sup, hQ]), ?_⟩
  rw [div_mul_cancel₀ _ hQ0]
  refine mem_polyChart_iff.2 ⟨P, ?_, rfl⟩
  have hx' : w (aeval y P / aeval y Q) ≤ 1 := hx
  rwa [map_div₀, h.eq_sup, h.eq_sup, hQ, div_one] at hx'

/-- Inverting a Gauss coordinate gives a Gauss coordinate. -/
theorem inv : IsGaussCoord v w y⁻¹ := by
  have hy := h.ne_zero
  refine ⟨fun Q ↦ ?_, ?_⟩
  · letI : Invertible y⁻¹ := invertibleOfNonzero (inv_ne_zero hy)
    have e := eval₂_reverse_mul_pow (algebraMap K F) y⁻¹ Q
    rw [invOf_eq_inv, inv_inv] at e
    rw [aeval_def, ← e, ← aeval_def, map_mul, h.eq_sup, map_pow, map_inv₀, h.valuation_self,
      inv_one, one_pow, mul_one]
    refine le_antisymm (sup_le_iff.2 fun i ↦ ?_) (sup_le_iff.2 fun i ↦ ?_)
    · rw [term, coeff_reverse]
      simpa [term] using term_le_sup (v := v) (r := 1) Q (revAt Q.natDegree i)
    · rw [term, ← revAt_invol (N := Q.natDegree) (i := i), ← coeff_reverse]
      simpa [term] using term_le_sup (v := v) (r := 1) Q.reverse (revAt Q.natDegree i)
  · rw [eq_top_iff, ← h.adjoin_eq_top, adjoin_simple_le_iff]
    have := inv_mem (mem_adjoin_simple_self K y⁻¹)
    rwa [inv_inv] at this

variable {W : ValuationSubring F} (hW : W.comap (algebraMap K F) = v.valuationSubring)
  (hAW : polyChart v y ≤ W.toSubring)

omit h in
include hW hAW in
/-- A `W`-unit of `O[y]` has Gauss valuation `1`, when `W ∩ K = O`. -/
lemma sup_eq_one_of_valuation_eq_one {S : K[X]} (hS : Gauss.sup v 1 S ≤ 1)
    (hSW : W.valuation (aeval y S) = 1) : Gauss.sup v 1 S = 1 := by
  refine le_antisymm hS (not_lt.1 fun hlt ↦ ?_)
  have hy : W.valuation y ≤ 1 := (W.valuation_le_one_iff y).2 (hAW (self_mem_polyChart y))
  have hc (i : ℕ) : W.valuation (algebraMap K F (S.coeff i)) < 1 := by
    have hvi : v (S.coeff i) < 1 := by
      have := term_le_sup (v := v) (r := 1) S i
      simp only [term, Units.val_one, one_pow, mul_one] at this
      exact this.trans_lt hlt
    rcases eq_or_ne (S.coeff i) 0 with h0 | h0
    · simp [h0]
    refine valuation_lt_one_of_comap_eq hW hvi.le ?_
    rw [Valuation.mem_valuationSubring_iff, map_inv₀, not_le]
    exact one_lt_inv_iff₀.2 ⟨zero_lt_iff.2 (by simpa using h0), hvi⟩
  refine (lt_irrefl (1 : W.ValueGroup)) ?_
  calc (1 : W.ValueGroup) = W.valuation (aeval y S) := hSW.symm
    _ < 1 := by
      rw [aeval_eq_sum_range]
      refine W.valuation.map_sum_lt one_ne_zero fun i _ ↦ ?_
      rw [Algebra.smul_def, map_mul, map_pow]
      calc W.valuation (algebraMap K F (S.coeff i)) * W.valuation y ^ i
          ≤ W.valuation (algebraMap K F (S.coeff i)) * 1 :=
            mul_le_mul_right (pow_le_one' hy i) _
        _ < 1 := by rw [mul_one]; exact hc i

include hW hAW in
/-- If `W ∩ K = O` and `W` is a local ring of `O[y]`, then `O_w` is a coarsening of `W`. -/
lemma le_valuationSubring_of_localAt_eq (hloc : localAt (polyChart v y) W = W.toSubring) :
    W ≤ w.valuationSubring := by
  intro x hx
  have hx' : x ∈ localAt (polyChart v y) W := by rw [hloc]; exact hx
  obtain ⟨s, hs, hsW, hxs⟩ := hx'
  obtain ⟨S, hS, rfl⟩ := mem_polyChart_iff.1 hs
  obtain ⟨P, hP, hPx⟩ := mem_polyChart_iff.1 hxs
  have hS1 := sup_eq_one_of_valuation_eq_one hW hAW hS hsW
  change w x ≤ 1
  have hS0 : aeval y S ≠ 0 := by
    rw [Ne, h.aeval_eq_zero_iff]
    rintro rfl
    simp [sup_zero] at hS1
  have : x = aeval y P / aeval y S := by rw [hPx, mul_div_cancel_right₀ _ hS0]
  rw [this, map_div₀, h.eq_sup, h.eq_sup, hS1, div_one]
  exact hP

omit h in
include hW in
/-- The units of `O` are `W`-units. -/
lemma valuation_algebraMap_eq_one {e : K} (he : v e = 1) :
    W.valuation (algebraMap K F e) = 1 := by
  have he0 : e ≠ 0 := by
    rintro rfl
    simp at he
  refine valuation_eq_one_of_comap_eq hW he0 he.le ?_
  rw [Valuation.mem_valuationSubring_iff, map_inv₀, he, inv_one]

include hW hAW in
/-- If `W ∩ K = O`, `v` is nontrivial and `W` is a local ring of `O[y]`, then every `Q(y)` with
`max_i v(Qᵢ) = 1` is a `W`-unit. -/
lemma valuation_aeval_eq_one (hv : ∃ ϖ : K, ϖ ≠ 0 ∧ v ϖ < 1)
    (hloc : localAt (polyChart v y) W = W.toSubring) :
    ∀ (n : ℕ) (Q : K[X]), Q.natDegree = n → Gauss.sup v 1 Q = 1 →
      W.valuation (aeval y Q) = 1 := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro Q hn hQ
  have hle : W.valuation (aeval y Q) ≤ 1 :=
    (W.valuation_le_one_iff _).2 (hAW (mem_polyChart_iff.2 ⟨Q, hQ.le, rfl⟩))
  have hQ0 : Q ≠ 0 := by
    rintro rfl
    simp [sup_zero] at hQ
  by_cases hirr : Irreducible Q
  · by_contra hne
    have hlt : W.valuation (aeval y Q) < 1 := lt_of_le_of_ne hle hne
    obtain ⟨ϖ, hϖ0, hϖ⟩ := hv
    have hq0 : aeval y Q ≠ 0 := by rwa [Ne, h.aeval_eq_zero_iff]
    have hϖF : algebraMap K F ϖ ≠ 0 := by simpa using hϖ0
    rcases W.mem_or_inv_mem (algebraMap K F ϖ / aeval y Q) with hmem | hmem
    · have hmem' : algebraMap K F ϖ / aeval y Q ∈ localAt (polyChart v y) W := by
        rw [hloc]; exact hmem
      obtain ⟨s, hs, hsW, hxs⟩ := hmem'
      obtain ⟨S, hS, rfl⟩ := mem_polyChart_iff.1 hs
      obtain ⟨P, -, hP⟩ := mem_polyChart_iff.1 hxs
      have heq : C ϖ * S = Q * P := by
        apply h.aeval_injective
        rw [map_mul, map_mul, aeval_C, hP]
        field_simp
      have hdvd : Q ∣ C ϖ * S := ⟨P, heq⟩
      rcases hirr.prime.dvd_or_dvd hdvd with hd | ⟨H, rfl⟩
      · exact hirr.not_isUnit (isUnit_of_dvd_unit hd (isUnit_C.2 (Ne.isUnit hϖ0)))
      · have hH : Gauss.sup v 1 H ≤ 1 := by
          rw [Gauss.sup_mul, hQ, one_mul] at hS
          exact hS
        have hHW : W.valuation (aeval y H) ≤ 1 :=
          (W.valuation_le_one_iff _).2 (hAW (mem_polyChart_iff.2 ⟨H, hH, rfl⟩))
        rw [map_mul, map_mul] at hsW
        have : W.valuation (aeval y Q) * W.valuation (aeval y H) < 1 :=
          (mul_le_of_le_one_right' hHW).trans_lt hlt
        rw [hsW] at this
        exact lt_irrefl _ this
    · have hle' := h.le_valuationSubring_of_localAt_eq hW hAW hloc hmem
      change w (algebraMap K F ϖ / aeval y Q)⁻¹ ≤ 1 at hle'
      rw [map_inv₀, map_div₀, h.valuation_algebraMap, h.eq_sup, hQ, div_one] at hle'
      have hϖpos : 0 < v ϖ := zero_lt_iff.2 (by simpa using hϖ0)
      exact absurd hle' (not_le.2 (one_lt_inv_iff₀.2 ⟨hϖpos, hϖ⟩))
  · by_cases hu : IsUnit Q
    · obtain ⟨e, he, rfl⟩ := Polynomial.isUnit_iff.1 hu
      rw [sup_C] at hQ
      rw [aeval_C]
      exact valuation_algebraMap_eq_one hW hQ
    · obtain ⟨A, B, rfl, hA, hB⟩ : ∃ A B, Q = A * B ∧ ¬IsUnit A ∧ ¬IsUnit B := by
        rw [irreducible_iff] at hirr
        push Not at hirr
        obtain ⟨A, B, hAB, hA, hB⟩ := hirr hu
        exact ⟨A, B, hAB, hA, hB⟩
      have hA0 : A ≠ 0 := left_ne_zero_of_mul hQ0
      have hB0 : B ≠ 0 := right_ne_zero_of_mul hQ0
      have hAd : 0 < A.natDegree :=
        natDegree_pos_iff_degree_pos.2 (degree_pos_of_ne_zero_of_nonunit hA0 hA)
      have hBd : 0 < B.natDegree :=
        natDegree_pos_iff_degree_pos.2 (degree_pos_of_ne_zero_of_nonunit hB0 hB)
      rw [natDegree_mul hA0 hB0] at hn
      obtain ⟨dA, hdA, hA1⟩ := exists_sup_eq_one (v := v) hA0
      obtain ⟨dB, hdB, hB1⟩ := exists_sup_eq_one (v := v) hB0
      have hAW' := ih _ (by omega) (C dA * A) (natDegree_C_mul hdA) hA1
      have hBW' := ih _ (by omega) (C dB * B) (natDegree_C_mul hdB) hB1
      have hsplit : A * B = C (dA * dB)⁻¹ * ((C dA * A) * (C dB * B)) := by
        rw [show C (dA * dB)⁻¹ * ((C dA * A) * (C dB * B)) =
          C ((dA * dB)⁻¹ * (dA * dB)) * (A * B) by simp only [C_mul]; ring,
          inv_mul_cancel₀ (mul_ne_zero hdA hdB), C_1, one_mul]
      have he : v (dA * dB)⁻¹ = 1 := by
        have := hQ
        rw [hsplit, Gauss.sup_mul, Gauss.sup_mul, hA1, hB1, sup_C, mul_one, mul_one] at this
        exact this
      rw [hsplit, map_mul, map_mul, map_mul, aeval_C,
        valuation_algebraMap_eq_one hW he, map_mul, hAW', hBW', mul_one, one_mul]

include hW hAW in
/-- **Uniqueness of the vertex of `O[y]`.** If `v` is nontrivial, a valuation subring `W` of `F`
with `W ∩ K = O` which is the local ring of `O[y]` at its center is the valuation ring of `w`. -/
theorem eq_of_localAt_eq (hv : ∃ ϖ : K, ϖ ≠ 0 ∧ v ϖ < 1)
    (hloc : localAt (polyChart v y) W = W.toSubring) : W = w.valuationSubring := by
  refine le_antisymm (h.le_valuationSubring_of_localAt_eq hW hAW hloc) fun x hx ↦ ?_
  obtain ⟨P, Q, hQ, rfl⟩ := h.exists_eq_div x
  have hQ0 : aeval y Q ≠ 0 := by
    rw [Ne, h.aeval_eq_zero_iff]
    rintro rfl
    simp [sup_zero] at hQ
  have hQW := h.valuation_aeval_eq_one hW hAW hv hloc _ Q rfl hQ
  have hP : Gauss.sup v 1 P ≤ 1 := by
    have hx' : w (aeval y P / aeval y Q) ≤ 1 := hx
    rwa [map_div₀, h.eq_sup, h.eq_sup, hQ, div_one] at hx'
  rw [div_eq_mul_inv]
  refine W.mul_mem _ _ (hAW (mem_polyChart_iff.2 ⟨P, hP, rfl⟩)) ?_
  rw [← W.valuation_le_one_iff, map_inv₀, hQW, inv_one]

end IsGaussCoord

/-! ### The model `ℙ¹_O` -/

namespace ZariskiModel

open scoped Classical in
/-- The projective line `ℙ¹_O` with coordinate `y`: the charts `O[y]` and `O[y⁻¹]`. -/
noncomputable def line (v : Valuation K Γ₀) (y : F) : ZariskiModel (baseRing F v.valuationSubring)
    where
  charts := {polyChart v y, polyChart v y⁻¹}
  le_chart A hA := by
    rw [Finset.mem_insert, Finset.mem_singleton] at hA
    rcases hA with rfl | rfl <;> exact baseRing_le_polyChart _

variable {v : Valuation K Γ₀} {y : F}

lemma mem_line_charts {A : Subring F} :
    A ∈ (line v y).charts ↔ A = polyChart v y ∨ A = polyChart v y⁻¹ := by
  classical
  simp [line]

theorem line_isProper : (line v y).IsProper := by
  intro W hW
  rcases W.mem_or_inv_mem y with hy | hy
  · exact ⟨_, mem_line_charts.2 (.inl rfl), polyChart_le hW hy⟩
  · exact ⟨_, mem_line_charts.2 (.inr rfl), polyChart_le hW hy⟩

theorem line_isFiniteType : (line v y).IsFiniteType := by
  intro A hA
  rcases mem_line_charts.1 hA with rfl | rfl
  · exact ⟨{y}, by simp [polyChart]⟩
  · exact ⟨{y⁻¹}, by simp [polyChart]⟩

theorem line_isSeparated : (line v y).IsSeparated := by
  intro A hA B hB W hAW hBW
  have key : ∀ z : F, polyChart v z ≤ W.toSubring → polyChart v z⁻¹ ≤ W.toSubring →
      polyChart v z⁻¹ ≤ localAt (polyChart v z) W := by
    intro z hz hz'
    rcases eq_or_ne z 0 with rfl | hz0
    · rw [inv_zero]
      exact le_localAt
    have h₁ : z ∈ W := hz (self_mem_polyChart z)
    have h₂ : z⁻¹ ∈ W := hz' (self_mem_polyChart z⁻¹)
    have hz1 : W.valuation z = 1 := by
      rw [← W.valuation_le_one_iff] at h₁ h₂
      rw [map_inv₀] at h₂
      exact le_antisymm h₁ (one_le_of_inv_le_one (by simpa using hz0) h₂)
    refine polyChart_le ((baseRing_le_polyChart z).trans le_localAt) ?_
    exact inv_mem_localAt (self_mem_polyChart z) hz1
  rcases mem_line_charts.1 hA with rfl | rfl <;> rcases mem_line_charts.1 hB with rfl | rfl
  · exact le_localAt
  · exact key y hAW hBW
  · have := key y⁻¹ hAW (by rwa [inv_inv])
    rwa [inv_inv] at this
  · exact le_localAt

/-- The specialization of a valuation subring containing `y` is computed in `O[y]`. -/
theorem line_center {W : ValuationSubring F} (hW : baseRing F v.valuationSubring ≤ W.toSubring)
    (hy : y ∈ W) : (line v y).center line_isProper W hW = localAt (polyChart v y) W :=
  center_eq _ line_isSeparated hW (mem_line_charts.2 (.inl rfl)) (polyChart_le hW hy)

variable {w : Valuation F Γ₀}

/-- **The vertex set of `ℙ¹_O` with Gauss coordinate `y` is `{O_w}`** (for nontrivial `v`). -/
theorem line_vertexSet (h : IsGaussCoord v w y) (hv : ∃ ϖ : K, ϖ ≠ 0 ∧ v ϖ < 1) :
    (line v y).vertexSet = {w.valuationSubring} := by
  ext W
  rw [Set.mem_singleton_iff]
  constructor
  · rintro ⟨hW, A, hA, W', hAW', hloc⟩
    have hAW : A ≤ W.toSubring := hloc ▸ le_localAt
    have hloc' := localAt_eq_of_localAt_eq hAW' hloc
    rcases mem_line_charts.1 hA with rfl | rfl
    · exact h.eq_of_localAt_eq hW hAW hv hloc'
    · exact h.inv.eq_of_localAt_eq hW hAW hv hloc'
  · rintro rfl
    exact mem_vertexSet_of_localAt_eq h.comap_valuationSubring (mem_line_charts.2 (.inl rfl))
      h.polyChart_le_valuationSubring h.localAt_polyChart

end ZariskiModel

/-! ### Gauss valuations on `K(X)` -/

section RatFunc

variable (v : Valuation K Γ₀) {a c : K} {r : Γ₀ˣ}

/-- The coordinate `(X - a) / c` of `K(X)`. -/
noncomputable def gaussCoord (a c : K) : RatFunc K :=
  algebraMap K[X] (RatFunc K) (gaussLin a c)

variable {v}

lemma X_eq_gaussCoord (hc : c ≠ 0) :
    RatFunc.X = algebraMap K (RatFunc K) c * gaussCoord a c + algebraMap K (RatFunc K) a := by
  have e (b : K) : algebraMap K[X] (RatFunc K) (C b) = algebraMap K (RatFunc K) b := by
    rw [IsScalarTower.algebraMap_apply K K[X] (RatFunc K), Polynomial.algebraMap_eq]
  rw [gaussCoord, gaussLin, map_mul, map_sub, e, e, RatFunc.algebraMap_X, ← mul_assoc, ← map_mul,
    mul_inv_cancel₀ hc, map_one, one_mul, sub_add_cancel]

/-- `(X - a) / c` is a Gauss coordinate for the Gauss valuation `w_{a, r}` when `v(c) = r`. -/
theorem isGaussCoord_gaussCoord (hc : v c = r) :
    IsGaussCoord v (gaussRat v a r) (gaussCoord a c) := by
  have hc0 : c ≠ 0 := by
    rintro rfl
    exact r.ne_zero (by simp [← hc])
  refine ⟨fun Q ↦ gaussRat_aeval_gaussLin hc Q, ?_⟩
  rw [eq_top_iff, ← RatFunc.adjoin_X, adjoin_simple_le_iff, X_eq_gaussCoord hc0]
  exact add_mem (mul_mem (IntermediateField.algebraMap_mem _ c) (mem_adjoin_simple_self K _))
    (IntermediateField.algebraMap_mem _ a)

variable (v) in
/-- The model `ℙ¹_O` of `K(X)` with coordinate `(X - a) / c`. -/
noncomputable def gaussModel (a c : K) : ZariskiModel (baseRing (RatFunc K) v.valuationSubring) :=
  ZariskiModel.line v (gaussCoord a c)

theorem gaussModel_isProper : (gaussModel v a c).IsProper :=
  ZariskiModel.line_isProper

theorem gaussModel_isSeparated : (gaussModel v a c).IsSeparated :=
  ZariskiModel.line_isSeparated

theorem gaussModel_isFiniteType : (gaussModel v a c).IsFiniteType :=
  ZariskiModel.line_isFiniteType

/-- **(W5, base case)** The model `ℙ¹_O` with coordinate `(X - a) / c`, `v(c) = r`, has vertex set
`{O_{w_{a,r}}}`: its special fibre is irreducible with generic point the Gauss valuation. -/
theorem gaussModel_vertexSet (hc : v c = r) (hv : ∃ ϖ : K, ϖ ≠ 0 ∧ v ϖ < 1) :
    (gaussModel v a c).vertexSet = {(gaussRat v a r).valuationSubring} :=
  ZariskiModel.line_vertexSet (isGaussCoord_gaussCoord hc) hv

end RatFunc

end SemistableReduction
