/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.DiscreteCoefficients

/-!
# Inertially generated fields and lifted Frobenius-closed bases

Blueprint §9.4, F2 (Kuhlmann, *Elimination of ramification I*, Lemmas 4.9–4.11, mixed
characteristic). Let `C ⊆ M` be non-archimedean normed fields (`C` algebraically closed of
characteristic `0` with residue characteristic `p`, `M` complete), `z ∈ M` with `‖z‖ ≤ 1` and
residue `z̄` transcendental over the residue field `k` of `C`, and `M₁ = genClosure C z` the
closure of `C(z)` in `M`.

* `nnnorm_aeval_eq`: the norm on `C[z]` is the Gauss norm `‖r(z)‖ = maxᵢ ‖rᵢ‖` (A1);
* `residueSubfield_genClosure`: the residue field of `M₁` is `k(z̄)`.

`M` is **inertially generated** (`IsInertiallyGenerated C z`) if moreover `M / M₁` is finite and
unramified: `κ_M / κ_{M₁}` is finite separable and `[M : M₁] ≤ [κ_M : κ_{M₁}]`.

**F2** (`nonempty_liftedFrobeniusBasis`): an inertially generated `M` carries a lifted
Frobenius-closed basis (`KummerNormalForm.LiftedFrobeniusBasis`). Proof: take a discretely valued
`K₀ ⊆ C` with full residue field (F1), `K₁ = K₀(z)` (discrete by the Gauss norm), a primitive
element `ȳ` of `κ_M / k(z̄)` and a Hensel lift `y'` of `ȳ` along a lift of its minimal
polynomial to `K₁`, `F₀ = K₁(y')`: a discretely valued subfield with residue field `κ_M`.
Lifts `u_q ∈ F₀` of a Frobenius-closed basis (E2) span a dense subspace:
elements of norm `≤ 1` of `F₀` are `p`-adic limits of `K₀`-combinations of the `bᵢ`
(discreteness), so the closure `D` of the `C`-span contains `F₀` and the closure of the
`C`-algebra generated by `F₀`, which is a closed subfield (geometric series, values in `‖C^×‖`)
containing `M₁` and `y'`; and `M = M₁[y']` since the `y'^j` are `M₁`-independent (A1) and
`[M : M₁] ≤ [κ_M : κ_{M₁}]`.
-/

open Polynomial IsLocalRing

namespace SemistableReduction

open KummerNormalForm DiscreteCoefficients

namespace InertiallyGenerated

variable {C M : Type*} [NormedField C] [IsUltrametricDist C] [NormedField M]
  [IsUltrametricDist M] [NormedAlgebra C M]

local notation "𝒪C" => HenselComplete.integers C
local notation "𝒪M" => HenselComplete.integers M

variable (C) in
/-- The closure `\widehat{C(z)}` of `C(z)` in `M`. -/
noncomputable def genClosure (z : M) : Subfield M :=
  (IntermediateField.adjoin C {z}).toSubfield.topologicalClosure

variable (C) in
/-- **Inertially generated fields** (Kuhlmann §2.4; Blueprint §9.4 F): `z ∈ M` has norm `≤ 1`
and residue transcendental over the residue field of `C`, and `M` is a finite unramified
extension of the closure `M₁` of `C(z)`: `κ_M / κ_{M₁}` is finite separable and
`[M : M₁] ≤ [κ_M : κ_{M₁}]`. -/
structure IsInertiallyGenerated (z : M) : Prop where
  norm_le_one : ‖z‖ ≤ 1
  transcendental : Transcendental (ResidueField 𝒪C) (rd z)
  finiteDimensional : FiniteDimensional (genClosure C z) M
  finiteDimensional_residue :
    FiniteDimensional (residueSubfield (genClosure C z)) (ResidueField 𝒪M)
  isSeparable : Algebra.IsSeparable (residueSubfield (genClosure C z)) (ResidueField 𝒪M)
  finrank_le : Module.finrank (genClosure C z) M ≤
    Module.finrank (residueSubfield (genClosure C z)) (ResidueField 𝒪M)

omit [IsUltrametricDist C] [IsUltrametricDist M] in
lemma algebraMap_mem_genClosure (z : M) (c : C) : algebraMap C M c ∈ genClosure C z :=
  Subfield.le_topologicalClosure _ ((IntermediateField.adjoin C {z}).algebraMap_mem c)

omit [IsUltrametricDist C] [IsUltrametricDist M] in
lemma mem_genClosure_self (z : M) : z ∈ genClosure C z :=
  Subfield.le_topologicalClosure _ (IntermediateField.mem_adjoin_simple_self C z)

section Gauss

variable {z : M} (hz : ‖z‖ ≤ 1)
include hz

/-- **The Gauss norm** (A1): `‖r(z)‖ = maxᵢ ‖rᵢ‖`. -/
theorem nnnorm_aeval_eq (htr : Transcendental (ResidueField 𝒪C) (rd z)) (r : C[X]) :
    ‖aeval z r‖₊ = (Finset.range (r.natDegree + 1)).sup fun i ↦ ‖r.coeff i‖₊ := by
  set x : ℕ → 𝒪M := fun i ↦ ⟨z ^ i, (HenselComplete.mem_integers_iff _).2 (by
    rw [norm_pow]; exact pow_le_one₀ (norm_nonneg _) hz)⟩
  have hx : LinearIndependent (ResidueField 𝒪C) (fun i ↦ residue 𝒪M (x i)) := by
    have hfun : (fun i ↦ residue 𝒪M (x i)) = fun i ↦ rd z ^ i := by
      ext i
      rw [← rd_coe]
      exact rd_pow hz i
    rw [hfun]
    exact linearIndependent_pow_of_transcendental htr
  have h := FundamentalInequality.valuation_sum_eq_sup (v := NormedField.valuation (K := C))
    (w := NormedField.valuation (K := M)) hx (Finset.range (r.natDegree + 1)) (fun i ↦ r.coeff i)
  rw [NormedField.valuation_apply] at h
  rw [aeval_eq_sum_range]
  simp_rw [Algebra.smul_def]
  rw [h]
  congr 1
  ext i
  rw [NormedField.valuation_apply, nnnorm_algebraMap']

lemma norm_coeff_le_norm_aeval (htr : Transcendental (ResidueField 𝒪C) (rd z)) (r : C[X])
    (i : ℕ) : ‖r.coeff i‖ ≤ ‖aeval z r‖ := by
  by_cases hi : i ≤ r.natDegree
  · rw [← coe_nnnorm, ← coe_nnnorm (aeval z r), NNReal.coe_le_coe, nnnorm_aeval_eq hz htr]
    exact Finset.le_sup (f := fun i ↦ ‖r.coeff i‖₊) (Finset.mem_range.2 (Nat.lt_succ_of_le hi))
  · rw [coeff_eq_zero_of_natDegree_lt (not_le.1 hi), norm_zero]
    exact norm_nonneg _

lemma exists_coeff_norm_eq (htr : Transcendental (ResidueField 𝒪C) (rd z)) (r : C[X]) :
    ∃ i, ‖aeval z r‖ = ‖r.coeff i‖ := by
  obtain ⟨i, -, hi⟩ := (Finset.range (r.natDegree + 1)).exists_mem_eq_sup
    ⟨0, Finset.mem_range.2 (Nat.succ_pos _)⟩ fun i ↦ ‖r.coeff i‖₊
  refine ⟨i, ?_⟩
  rw [← coe_nnnorm, nnnorm_aeval_eq hz htr, hi, coe_nnnorm]

lemma rd_aeval_mem (r : C[X]) (hr : ∀ i, ‖r.coeff i‖ ≤ 1) :
    rd (aeval z r) ∈ (IntermediateField.adjoin (ResidueField 𝒪C) {rd z}).toSubfield := by
  have hterm (i : ℕ) : ‖algebraMap C M (r.coeff i) * z ^ i‖ ≤ 1 := by
    rw [norm_mul, norm_algebraMap', norm_pow]
    exact mul_le_one₀ (hr i) (by positivity) (pow_le_one₀ (norm_nonneg _) hz)
  rw [aeval_eq_sum_range]
  simp_rw [Algebra.smul_def]
  rw [rd_sum _ _ fun i _ ↦ hterm i]
  refine Subfield.sum_mem _ fun i _ ↦ ?_
  rw [rd_mul (by rw [norm_algebraMap']; exact hr i)
      (by rw [norm_pow]; exact pow_le_one₀ (norm_nonneg _) hz),
    LiftedFrobeniusFamily.rd_algebraMap (hr i), rd_pow hz]
  exact Subfield.mul_mem _ (IntermediateField.algebraMap_mem _ _)
    (Subfield.pow_mem _ (IntermediateField.mem_adjoin_simple_self _ _) _)

/-- The residue field of `\widehat{C(z)}` is contained in `k(z̄)`. -/
theorem residueSubfield_genClosure_le (htr : Transcendental (ResidueField 𝒪C) (rd z)) :
    residueSubfield (genClosure C z) ≤
      (IntermediateField.adjoin (ResidueField 𝒪C) {rd z}).toSubfield := by
  rintro _ ⟨x, hx, hx1, rfl⟩
  rcases hx1.lt_or_eq with hlt | heq
  · rw [rd_eq_zero hlt]
    exact Subfield.zero_mem _
  obtain ⟨y, hy, hxy⟩ := Metric.mem_closure_iff.1 hx 1 one_pos
  rw [dist_eq_norm] at hxy
  have hy1 : ‖y‖ = 1 := by
    rw [← heq]
    exact DenseCompletion.norm_eq_of_norm_sub_lt (by rw [norm_sub_rev, heq]; exact hxy)
  rw [rd_eq_of_norm_sub_lt_one hx1 hy1.le hxy]
  obtain ⟨r, s, rfl⟩ := (IntermediateField.mem_adjoin_simple_iff C y).1 hy
  have hs0 : aeval z s ≠ 0 := by
    intro h
    rw [h, div_zero, norm_zero] at hy1
    exact zero_ne_one hy1
  obtain ⟨j, hj⟩ := exists_coeff_norm_eq hz htr s
  have hd0 : s.coeff j ≠ 0 := by
    intro h
    rw [h, norm_zero, norm_eq_zero] at hj
    exact hs0 hj
  set d := s.coeff j
  set r' := Polynomial.C d⁻¹ * r
  set s' := Polynomial.C d⁻¹ * s
  have hs' : aeval z s' = algebraMap C M d⁻¹ * aeval z s := by simp [s']
  have hr' : aeval z r' = algebraMap C M d⁻¹ * aeval z r := by simp [r']
  have hs'n : ‖aeval z s'‖ = 1 := by
    rw [hs', norm_mul, norm_algebraMap', hj, norm_inv, inv_mul_cancel₀ (norm_ne_zero_iff.2 hd0)]
  have hquot : aeval z r / aeval z s = aeval z r' / aeval z s' := by
    rw [hs', hr', mul_div_mul_left _ _ ((_root_.map_ne_zero _).2 (inv_ne_zero hd0))]
  have hr'n : ‖aeval z r'‖ = 1 := by
    have : ‖aeval z r'‖ = ‖aeval z r / aeval z s‖ * ‖aeval z s'‖ := by
      rw [hquot, norm_div, div_mul_cancel₀ _ (by rw [hs'n]; exact one_ne_zero)]
    rw [this, hy1, hs'n, one_mul]
  rw [hquot, div_eq_mul_inv, rd_mul hr'n.le (by rw [norm_inv, hs'n, inv_one]), rd_inv hs'n]
  exact Subfield.mul_mem _
    (rd_aeval_mem hz r' fun i ↦ (norm_coeff_le_norm_aeval hz htr r' i).trans hr'n.le)
    (Subfield.inv_mem _
      (rd_aeval_mem hz s' fun i ↦ (norm_coeff_le_norm_aeval hz htr s' i).trans hs'n.le))

/-- `k(z̄)` is contained in the residue field of `\widehat{C(z)}`. -/
theorem le_residueSubfield_genClosure :
    (IntermediateField.adjoin (ResidueField 𝒪C) {rd z}).toSubfield ≤
      residueSubfield (genClosure C z) := by
  intro x hx
  have hE : ∀ a, algebraMap (ResidueField 𝒪C) (ResidueField 𝒪M) a ∈
      residueSubfield (genClosure C z) := fun a ↦ by
    obtain ⟨c, rfl⟩ := IsLocalRing.residue_surjective a
    have h1 := rd_coe (K := C) c
    have h2 := LiftedFrobeniusFamily.rd_algebraMap (M := M) (HenselComplete.norm_le_one c)
    rw [h1] at h2
    rw [← h2]
    refine rd_mem_residueSubfield ?_ ?_
    · exact algebraMap_mem_genClosure z (c : C)
    · exact (norm_algebraMap' M (c : C)).trans_le (HenselComplete.norm_le_one c)
  have hle : IntermediateField.adjoin (ResidueField 𝒪C) {rd z} ≤
      (residueSubfield (genClosure C z)).toIntermediateField hE :=
    IntermediateField.adjoin_simple_le_iff.2 (rd_mem_residueSubfield (mem_genClosure_self z) hz)
  have hx' : x ∈ IntermediateField.adjoin (ResidueField 𝒪C) {rd z} := hx
  exact hle hx'

/-- **The residue field of `\widehat{C(z)}` is `k(z̄)`.** -/
theorem residueSubfield_genClosure (htr : Transcendental (ResidueField 𝒪C) (rd z)) :
    residueSubfield (genClosure C z) =
      (IntermediateField.adjoin (ResidueField 𝒪C) {rd z}).toSubfield :=
  le_antisymm (residueSubfield_genClosure_le hz htr) (le_residueSubfield_genClosure hz)

end Gauss

section Tools

variable {F : Type*} [NormedField F] [IsUltrametricDist F]

local notation "𝒪" => HenselComplete.integers F

lemma norm_aeval_le_one {K : Subfield F} {g : K[X]} (hg1 : ∀ i, ‖((g.coeff i : K) : F)‖ ≤ 1)
    {x : F} (hx : ‖x‖ ≤ 1) : ‖aeval x g‖ ≤ 1 := by
  rw [aeval_eq_sum_range]
  refine IsUltrametricDist.norm_sum_le_of_forall_le_of_nonneg zero_le_one fun i _ ↦ ?_
  rw [Algebra.smul_def, norm_mul, norm_pow]
  exact mul_le_one₀ (hg1 i) (by positivity) (pow_le_one₀ (norm_nonneg _) hx)

/-- Reduction commutes with evaluation, for a polynomial over a subfield with integral
coefficients. -/
lemma rd_aeval_eq {K : Subfield F} {g : K[X]} {gbar : (residueSubfield K)[X]}
    (hg1 : ∀ i, ‖((g.coeff i : K) : F)‖ ≤ 1)
    (hgr : ∀ i, rd ((g.coeff i : K) : F) = ((gbar.coeff i : residueSubfield K) : ResidueField 𝒪))
    {x : F} (hx : ‖x‖ ≤ 1) : rd (aeval x g) = aeval (rd x) gbar := by
  set N := g.natDegree + gbar.natDegree + 1
  have hterm (i : ℕ) : ‖g.coeff i • x ^ i‖ ≤ 1 := by
    rw [Algebra.smul_def, norm_mul, norm_pow]
    exact mul_le_one₀ (hg1 i) (by positivity) (pow_le_one₀ (norm_nonneg _) hx)
  rw [aeval_eq_sum_range' (n := N) (by omega), aeval_eq_sum_range' (n := N) (by omega),
    rd_sum _ _ fun i _ ↦ hterm i]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [Algebra.smul_def, Algebra.smul_def]
  change rd (((g.coeff i : K) : F) * x ^ i) =
    ((gbar.coeff i : residueSubfield K) : ResidueField 𝒪) * rd x ^ i
  rw [rd_mul (hg1 i) (by rw [norm_pow]; exact pow_le_one₀ (norm_nonneg _) hx), rd_pow hx, hgr]

/-- A lift of the minimal polynomial of a residue to a monic polynomial with integral
coefficients over the subfield. -/
lemma exists_lift_minpoly {K : Subfield F} {x : ResidueField 𝒪}
    (hint : IsIntegral (residueSubfield K) x) :
    ∃ g : K[X], g.Monic ∧ g.natDegree = (minpoly (residueSubfield K) x).natDegree ∧
      (∀ i, ‖((g.coeff i : K) : F)‖ ≤ 1) ∧
      ∀ i, rd ((g.coeff i : K) : F) =
        (((minpoly (residueSubfield K) x).coeff i : residueSubfield K) : ResidueField 𝒪) := by
  classical
  set R := residueSubfield K
  set m := minpoly R x
  set n := m.natDegree
  have hlift : ∀ i, ∃ c ∈ K, ‖c‖ ≤ 1 ∧ rd c = ((m.coeff i : R) : ResidueField 𝒪) :=
    fun i ↦ (m.coeff i).2
  choose c hcK hc1 hcrd using hlift
  set g : K[X] := X ^ n + ∑ i : Fin n, C (⟨c i, hcK i⟩ : K) * X ^ (i : ℕ) with hg
  have hdeg : (∑ i : Fin n, C (⟨c i, hcK i⟩ : K) * X ^ (i : ℕ)).degree < (n : WithBot ℕ) :=
    degree_sum_fin_lt _
  have hgn : g.natDegree = n := by
    rw [hg, natDegree_add_eq_left_of_degree_lt (by rwa [degree_X_pow]), natDegree_X_pow]
  have hcoeff (j : ℕ) : ((g.coeff j : K) : F) =
      if j = n then 1 else if j < n then c j else 0 := by
    rw [hg, coeff_add, coeff_X_pow, finsetSum_coeff]
    simp only [coeff_C_mul_X_pow]
    rw [Fin.sum_univ_eq_sum_range (fun i ↦ if j = i then (⟨c i, hcK i⟩ : K) else 0) n,
      Finset.sum_ite_eq]
    by_cases hjn : j = n
    · subst hjn
      simp
    · by_cases hj : j < n
      · simp [hjn, hj]
      · simp [hjn, hj]
  have hmonic : m.Monic := minpoly.monic hint
  refine ⟨g, monic_X_pow_add hdeg, hgn, fun j ↦ ?_, fun j ↦ ?_⟩
  · rw [hcoeff]
    split_ifs
    · simp
    · exact hc1 j
    · simp
  · rw [hcoeff]
    split_ifs with h1 h2
    · subst h1
      rw [rd_one, hmonic.coeff_natDegree]
      rfl
    · exact hcrd j
    · rw [coeff_eq_zero_of_natDegree_lt (by omega), DiscreteCoefficients.rd_zero]
      rfl

/-- Transcendence over a subfield of the image of `k`. -/
lemma transcendental_of_le_range {k κ : Type*} [Field k] [Field κ] [Algebra k κ]
    {R : Subfield κ} (hR : ∀ y ∈ R, ∃ a : k, algebraMap k κ a = y) {x : κ}
    (hx : Transcendental k x) : Transcendental R x := by
  classical
  rw [transcendental_iff] at hx ⊢
  intro P hP
  choose f hf using fun i ↦ hR _ (P.coeff i).2
  set Q : k[X] := ∑ i ∈ Finset.range (P.natDegree + 1), C (f i) * X ^ i
  have hQ : aeval x Q = 0 := by
    have h1 : aeval x Q = ∑ i ∈ Finset.range (P.natDegree + 1), ((P.coeff i : R) : κ) * x ^ i := by
      simp only [Q, map_sum, _root_.map_mul, aeval_C, _root_.map_pow, aeval_X, hf]
    have h2 : aeval x P = ∑ i ∈ Finset.range (P.natDegree + 1), ((P.coeff i : R) : κ) * x ^ i := by
      rw [aeval_eq_sum_range]
      rfl
    rw [h1, ← h2, hP]
  have hQ0 := hx Q hQ
  refine Polynomial.ext fun i ↦ ?_
  rw [coeff_zero]
  by_cases hi : i ≤ P.natDegree
  · have := congrArg (fun q ↦ coeff q i) hQ0
    simp only [Q, finsetSum_coeff, coeff_C_mul_X_pow, coeff_zero] at this
    rw [Finset.sum_ite_eq, if_pos (Finset.mem_range.2 (Nat.lt_succ_of_le hi))] at this
    apply Subtype.val_injective
    rw [← hf, this, map_zero]
    rfl
  · exact coeff_eq_zero_of_natDegree_lt (not_le.1 hi)

end Tools

section Density

variable [CompleteSpace M] {p : ℕ}

omit [IsUltrametricDist C] [IsUltrametricDist M] [CompleteSpace M] in
/-- **`p`-adic expansions**: if every element of norm `≤ 1` of a subfield `F₀` with values in
`‖p‖ ^ ℤ` is congruent modulo elements of norm `< 1` to an element of `S ∩ F₀`, then `F₀` lies in
the closure of the `C`-submodule `S`. -/
theorem mem_topologicalClosure_of_isDiscrete (hp0 : (p : M) ≠ 0) (hp1 : ‖(p : M)‖ < 1)
    {F₀ : Subfield M} (hF₀ : IsDiscrete F₀ (p : M)) {S : Submodule C M}
    (hS : ∀ f ∈ F₀, ‖f‖ ≤ 1 → ∃ s ∈ S, s ∈ F₀ ∧ ‖f - s‖ < 1) :
    ∀ f ∈ F₀, f ∈ S.topologicalClosure := by
  classical
  have hpn : 0 < ‖(p : M)‖ := norm_pos_iff.2 hp0
  have hgap : ∀ x ∈ F₀, ‖x‖ < 1 → ‖x‖ ≤ ‖(p : M)‖ := by
    intro x hx hx1
    by_cases hx0 : x = 0
    · rw [hx0, norm_zero]
      exact hpn.le
    obtain ⟨m, hm⟩ := hF₀ x hx hx0
    rw [hm] at hx1 ⊢
    have hm0 : 0 < m := (zpow_lt_one_iff_right_of_lt_one₀ hpn hp1).1 hx1
    calc ‖(p : M)‖ ^ m ≤ ‖(p : M)‖ ^ (1 : ℤ) :=
          zpow_le_zpow_right_of_le_one₀ hpn hp1.le (by omega)
      _ = ‖(p : M)‖ := zpow_one _
  have hpC (j : ℕ) (s : M) (hs : s ∈ S) : (p : M) ^ j * s ∈ S := by
    have : (p : M) ^ j * s = ((p : C) ^ j) • s := by
      rw [Algebra.smul_def, _root_.map_pow, map_natCast]
    rw [this]
    exact S.smul_mem _ hs
  choose! sel hselS hselF hsel using hS
  have hball : ∀ f ∈ F₀, ‖f‖ ≤ 1 → f ∈ S.topologicalClosure := by
    intro f hf hf1
    set T : M → M := fun x ↦ (x - sel x) / p with hT
    have hTF : ∀ x ∈ F₀, ‖x‖ ≤ 1 → T x ∈ F₀ ∧ ‖T x‖ ≤ 1 := by
      intro x hx hx1
      refine ⟨F₀.div_mem (F₀.sub_mem hx (hselF x hx hx1)) (natCast_mem F₀ p), ?_⟩
      rw [hT, norm_div]
      exact (div_le_one hpn).2 (hgap _ (F₀.sub_mem hx (hselF x hx hx1)) (hsel x hx hx1))
    set seq : ℕ → M := fun k ↦ T^[k] f with hseq
    have hseqF : ∀ k, seq k ∈ F₀ ∧ ‖seq k‖ ≤ 1 := by
      intro k
      induction k with
      | zero => exact ⟨hf, hf1⟩
      | succ k ih =>
        rw [hseq]
        dsimp only
        rw [Function.iterate_succ_apply']
        exact hTF _ ih.1 ih.2
    set P : ℕ → M := fun k ↦ ∑ j ∈ Finset.range k, (p : M) ^ j * sel (seq j) with hP
    have hPf : ∀ k, f = P k + (p : M) ^ k * seq k := by
      intro k
      induction k with
      | zero => simp [hP, hseq]
      | succ k ih =>
        have hs : seq (k + 1) = T (seq k) := by
          simp only [hseq]
          rw [Function.iterate_succ_apply']
        rw [show P (k + 1) = P k + (p : M) ^ k * sel (seq k) from Finset.sum_range_succ _ _, hs]
        simp only [hT]
        rw [ih]
        field_simp
        ring
    have hPS : ∀ k, P k ∈ S := fun k ↦
      S.sum_mem fun j _ ↦ hpC j _ (hselS _ (hseqF j).1 (hseqF j).2)
    have hlim : Filter.Tendsto P Filter.atTop (nhds f) := by
      rw [tendsto_iff_norm_sub_tendsto_zero]
      refine squeeze_zero (fun _ ↦ norm_nonneg _) (fun k ↦ ?_)
        (tendsto_pow_atTop_nhds_zero_of_lt_one (norm_nonneg _) hp1)
      rw [show P k - f = -((p : M) ^ k * seq k) by rw [hPf k]; ring, norm_neg, norm_mul,
        norm_pow]
      exact mul_le_of_le_one_right (by positivity) (hseqF k).2
    rw [← SetLike.mem_coe, Submodule.topologicalClosure_coe]
    exact mem_closure_of_tendsto hlim (Filter.Eventually.of_forall hPS)
  intro f hf
  by_cases hf0 : f = 0
  · rw [hf0]
    exact Submodule.zero_mem _
  obtain ⟨m, hm⟩ := hF₀ f hf hf0
  have hf' : (p : M) ^ (-m) * f ∈ F₀ := F₀.mul_mem (F₀.zpow_mem (natCast_mem F₀ p) _) hf
  have hf'1 : ‖(p : M) ^ (-m) * f‖ ≤ 1 := by
    rw [norm_mul, norm_zpow, hm, ← zpow_add₀ hpn.ne', neg_add_cancel, zpow_zero]
  have := Submodule.smul_mem _ ((p : C) ^ m) (hball _ hf' hf'1)
  rwa [Algebra.smul_def, map_zpow₀, map_natCast, ← mul_assoc, ← zpow_add₀ hp0,
    add_neg_cancel, zpow_zero, one_mul] at this

omit [IsUltrametricDist C] [CompleteSpace M] in
/-- **The closure of an algebra is a field**, if its nonzero elements have norms in `‖C^×‖` and
its elements of norm `≤ 1` realize all residues (geometric series). -/
theorem inv_mem_topologicalClosure {A : Subalgebra C M}
    (hval : ∀ x ∈ A.topologicalClosure, x ≠ 0 → ∃ c : C, c ≠ 0 ∧ ‖x‖ = ‖c‖)
    (hres : ∀ a : ResidueField 𝒪M, ∃ s ∈ A, ‖s‖ ≤ 1 ∧ rd s = a) :
    ∀ x ∈ A.topologicalClosure, x ≠ 0 → x⁻¹ ∈ A.topologicalClosure := by
  intro x hx hx0
  obtain ⟨c, hc0, hc⟩ := hval x hx hx0
  set x' := algebraMap C M c⁻¹ * x with hx'
  have hx'A : x' ∈ A.topologicalClosure := Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ _) hx
  have hx'n : ‖x'‖ = 1 := by
    rw [hx', norm_mul, norm_algebraMap', norm_inv, hc, inv_mul_cancel₀ (norm_ne_zero_iff.2 hc0)]
  have hrd0 : rd x' ≠ 0 := by
    rw [Ne, rd_eq_zero_iff hx'n.le, hx'n]
    exact lt_irrefl 1
  obtain ⟨s, hsA, hs1, hsrd⟩ := hres (rd x')⁻¹
  have hsn : ‖s‖ = 1 := norm_eq_one_of_rd_ne_zero hs1 (by rw [hsrd]; exact inv_ne_zero hrd0)
  have hs0 : s ≠ 0 := by
    intro h
    rw [h, norm_zero] at hsn
    exact zero_ne_one hsn
  set t := 1 - x' * s with ht
  have htA : t ∈ A.topologicalClosure :=
    Subalgebra.sub_mem _ (Subalgebra.one_mem _)
      (Subalgebra.mul_mem _ hx'A (A.le_topologicalClosure hsA))
  have ht1 : ‖t‖ < 1 := by
    have hle : ‖t‖ ≤ 1 := (PthPower.norm_sub_le_max' _ _).trans (by
      rw [norm_one, norm_mul, hx'n, hsn, one_mul, max_self])
    rw [← rd_eq_zero_iff hle, ht, rd_sub (by simp) (by rw [norm_mul, hx'n, hsn, one_mul]),
      rd_one, rd_mul hx'n.le hs1, hsrd, mul_inv_cancel₀ hrd0, sub_self]
  have hgeom := hasSum_geometric_of_norm_lt_one ht1
  have hinvA : (1 - t)⁻¹ ∈ A.topologicalClosure :=
    (A.isClosed_topologicalClosure).mem_of_tendsto hgeom.tendsto_sum_nat
      (Filter.Eventually.of_forall fun n ↦
        Subalgebra.sum_mem _ fun i _ ↦ Subalgebra.pow_mem _ htA _)
  have hxinv : x⁻¹ = algebraMap C M c⁻¹ * s * (1 - t)⁻¹ := by
    have hc' : algebraMap C M c ≠ 0 := (_root_.map_ne_zero _).2 hc0
    rw [ht, sub_sub_cancel, hx', map_inv₀]
    field_simp
  rw [hxinv]
  exact Subalgebra.mul_mem _ (Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ _)
    (A.le_topologicalClosure hsA)) hinvA

end Density

section Construction

variable [IsAlgClosed C] [CharZero C] [CompleteSpace M] {p : ℕ}

/-- **F2: lifted Frobenius-closed bases.** If `C` is algebraically closed of characteristic `0`
with `‖p‖ < 1` and `M` is inertially generated over `C` (by `z`), then `M` carries a lifted
Frobenius-closed basis: lifts `u_q` of a Frobenius-closed basis of `κ_M / k` such that the
`C`-span of `{1} ⊔ {u_q ^ p ^ n}` is dense in `M`. -/
theorem nonempty_liftedFrobeniusBasis (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1) {z : M}
    (hM : IsInertiallyGenerated C z) : Nonempty (LiftedFrobeniusBasis C M p) := by
  classical
  haveI := Fact.mk hp
  have hz := hM.norm_le_one
  have htr := hM.transcendental
  have hpM1 : ‖(p : M)‖ < 1 := by rwa [LiftedFrobeniusBasis.norm_natCast_eq (C := C)]
  have hpM0 : (p : M) ≠ 0 := by
    rw [← map_natCast (algebraMap C M)]
    exact (_root_.map_ne_zero _).2 (Nat.cast_ne_zero.2 hp.ne_zero)
  set M₁ := genClosure C z with hM₁
  -- F1: a discretely valued coefficient field, mapped to `M`
  obtain ⟨K₀, hK₀, hK₀top⟩ := exists_isDiscrete_residueSubfield_eq_top (F := C) hp hp1
  set K₀M : Subfield M := K₀.map (algebraMap C M) with hK₀M_def
  have hK₀M : IsDiscrete K₀M (p : M) := by
    rintro x hx hx0
    obtain ⟨c, hc, rfl⟩ := Subfield.mem_map.1 hx
    obtain ⟨n, hn⟩ := hK₀ c hc (by rintro rfl; exact hx0 (map_zero _))
    exact ⟨n, by
      rw [norm_algebraMap', hn, ← LiftedFrobeniusBasis.norm_natCast_eq (C := C) (M := M)]⟩
  have hK₀res : ∀ a : ResidueField 𝒪C, ∃ c ∈ K₀, ‖c‖ ≤ 1 ∧ rd c = a := fun a ↦ by
    have : a ∈ residueSubfield K₀ := hK₀top ▸ Subfield.mem_top a
    exact this
  have hrange : ∀ a : ResidueField 𝒪C,
      algebraMap _ (ResidueField 𝒪M) a ∈ residueSubfield K₀M := fun a ↦ by
    obtain ⟨c, hc, hc1, rfl⟩ := hK₀res a
    rw [← LiftedFrobeniusFamily.rd_algebraMap hc1]
    exact rd_mem_residueSubfield (Subfield.mem_map.2 ⟨c, hc, rfl⟩)
      ((norm_algebraMap' M c).trans_le hc1)
  have hsub : ∀ y ∈ residueSubfield K₀M, ∃ a : ResidueField 𝒪C, algebraMap _ _ a = y := by
    rintro _ ⟨y, hy, hy1, rfl⟩
    obtain ⟨c, -, rfl⟩ := Subfield.mem_map.1 hy
    have hc1 : ‖c‖ ≤ 1 := by rwa [norm_algebraMap'] at hy1
    exact ⟨rd c, (LiftedFrobeniusFamily.rd_algebraMap hc1).symm⟩
  have hK₀MM₁ : K₀M ≤ M₁ := by
    intro x hx
    obtain ⟨c, -, rfl⟩ := Subfield.mem_map.1 hx
    exact algebraMap_mem_genClosure z c
  -- `K₁ = K₀(z)`
  set K₁ := adjoin K₀M z with hK₁_def
  have hK₁ : IsDiscrete K₁ (p : M) :=
    isDiscrete_adjoin_of_transcendental hpM0 hK₀M hz (transcendental_of_le_range hsub htr)
  have hK₁M₁ : K₁ ≤ M₁ := by
    have hE : ∀ x : K₀M, algebraMap K₀M M x ∈ M₁ := fun x ↦ hK₀MM₁ x.2
    have : IntermediateField.adjoin K₀M {z} ≤ M₁.toIntermediateField hE :=
      IntermediateField.adjoin_simple_le_iff.2 (mem_genClosure_self z)
    exact fun x hx ↦ this hx
  have hresK₁ : residueSubfield K₁ = residueSubfield M₁ := by
    refine le_antisymm (residueSubfield_mono hK₁M₁) ?_
    rw [hM₁, residueSubfield_genClosure hz htr]
    intro x hx
    have hE : ∀ a : ResidueField 𝒪C, algebraMap _ (ResidueField 𝒪M) a ∈ residueSubfield K₁ :=
      fun a ↦ residueSubfield_mono (le_adjoin K₀M z) (hrange a)
    have hle : IntermediateField.adjoin (ResidueField 𝒪C) {rd z} ≤
        (residueSubfield K₁).toIntermediateField hE :=
      IntermediateField.adjoin_simple_le_iff.2
        (rd_mem_residueSubfield (mem_adjoin_self K₀M z) hz)
    exact hle hx
  -- a primitive element of the residue extension and its Hensel lift
  set R := residueSubfield K₁ with hR_def
  have hfd : FiniteDimensional R (ResidueField 𝒪M) := by
    have := hM.finiteDimensional_residue
    rwa [← hresK₁] at this
  have hsepR : Algebra.IsSeparable R (ResidueField 𝒪M) := by
    have := hM.isSeparable
    rwa [← hresK₁] at this
  obtain ⟨ybar, hybar⟩ := Field.exists_primitive_element R (ResidueField 𝒪M)
  have hint : IsIntegral R ybar := Algebra.IsIntegral.isIntegral ybar
  have hsepy : (minpoly R ybar).Separable := Algebra.IsSeparable.isSeparable R ybar
  set n := (minpoly R ybar).natDegree with hn
  have hfinrank : Module.finrank R (ResidueField 𝒪M) = n := by
    rw [← IntermediateField.finrank_top', ← hybar, IntermediateField.adjoin.finrank hint]
  obtain ⟨g, hgm, hgn, hg1, hgr⟩ := exists_lift_minpoly hint
  obtain ⟨y₀, hy₀⟩ := IsLocalRing.residue_surjective ybar
  have hy₀1 : ‖(y₀ : M)‖ ≤ 1 := HenselComplete.norm_le_one y₀
  have hy₀rd : rd (y₀ : M) = ybar := by rw [rd_coe, hy₀]
  set f := g.map (algebraMap K₁ M) with hf_def
  have hfm : f.Monic := hgm.map _
  have hfc : ∀ i, ‖f.coeff i‖ ≤ 1 := fun i ↦ by rw [hf_def, coeff_map]; exact hg1 i
  have hfev (x : M) : f.eval x = aeval x g := eval_map_algebraMap _ _
  have hf0 : ‖f.eval (y₀ : M)‖ < 1 := by
    rw [hfev, ← rd_eq_zero_iff (norm_aeval_le_one hg1 hy₀1), rd_aeval_eq hg1 hgr hy₀1, hy₀rd]
    exact minpoly.aeval R ybar
  have hnat : ∀ i : ℕ, ‖(i : M) + 1‖ ≤ 1 := fun i ↦ by
    have := IsUltrametricDist.norm_natCast_le_one M (i + 1)
    push_cast at this
    exact this
  have hdg1 : ∀ i, ‖(((derivative g).coeff i : K₁) : M)‖ ≤ 1 := fun i ↦ by
    rw [coeff_derivative]
    push_cast
    rw [norm_mul]
    exact mul_le_one₀ (hg1 _) (norm_nonneg _) (hnat i)
  have hdgr : ∀ i, rd (((derivative g).coeff i : K₁) : M) =
      (((derivative (minpoly R ybar)).coeff i : R) : ResidueField 𝒪M) := fun i ↦ by
    rw [coeff_derivative, coeff_derivative]
    push_cast
    rw [rd_mul (hg1 _) (hnat i), hgr]
    congr 1
    have := rd_natCast (F := M) (i + 1)
    push_cast at this
    rw [this]
  have hf1 : ‖f.derivative.eval (y₀ : M)‖ = 1 := by
    rw [hf_def, derivative_map, eval_map_algebraMap]
    refine norm_eq_one_of_rd_ne_zero (norm_aeval_le_one hdg1 hy₀1) ?_
    rw [rd_aeval_eq hdg1 hdgr hy₀1, hy₀rd]
    exact hsepy.aeval_derivative_ne_zero (minpoly.aeval R ybar)
  obtain ⟨y', hy'0, hy'y₀⟩ := PthPower.exists_root hfm hfc hy₀1 hf0 hf1
  have hy'1 : ‖y'‖ ≤ 1 := by
    have := IsUltrametricDist.norm_add_le_max (y' - y₀) (y₀ : M)
    rw [sub_add_cancel] at this
    exact this.trans (max_le hy'y₀.le hy₀1)
  have hy'rd : rd y' = ybar := (rd_eq_of_norm_sub_lt_one hy'1 hy₀1 hy'y₀).trans hy₀rd
  have hgy' : aeval y' g = 0 := by rw [← hfev]; exact hy'0
  -- `F₀ = K₁(y')`
  set F₀ := adjoin K₁ y' with hF₀_def
  have hF₀ : IsDiscrete F₀ (p : M) := isDiscrete_adjoin_of_root hK₁ hy'1 hgm hgy' (by
    rw [hgn, hy'rd]
    exact linearIndependent_pow ybar)
  have hF₀res : residueSubfield F₀ = ⊤ := by
    have hE : ∀ r : R, algebraMap R (ResidueField 𝒪M) r ∈ residueSubfield F₀ :=
      fun r ↦ residueSubfield_mono (le_adjoin K₁ y') r.2
    have hle : IntermediateField.adjoin R {ybar} ≤ (residueSubfield F₀).toIntermediateField hE :=
      IntermediateField.adjoin_simple_le_iff.2
        (hy'rd ▸ rd_mem_residueSubfield (mem_adjoin_self K₁ y') hy'1)
    rw [hybar] at hle
    exact eq_top_iff.2 fun x _ ↦ hle (IntermediateField.mem_top (x := x))
  have hK₀MF₀ : K₀M ≤ F₀ := (le_adjoin K₀M z).trans (le_adjoin K₁ y')
  have hzF₀ : z ∈ F₀ := le_adjoin K₁ y' (mem_adjoin_self K₀M z)
  have hy'F₀ : y' ∈ F₀ := mem_adjoin_self K₁ y'
  -- the Frobenius-closed basis and its lifts in `F₀`
  haveI : CharP (ResidueField 𝒪C) p := charP_residueField hp hp1
  haveI : IsAlgClosed (ResidueField 𝒪C) := isAlgClosed_residueField
  haveI : IsCurveFunctionField (ResidueField 𝒪C) (ResidueField 𝒪M) := ⟨⟨rd z, htr, by
    have := hM.finiteDimensional_residue
    rw [residueSubfield_genClosure hz htr] at this
    exact this⟩⟩
  obtain ⟨B⟩ := nonempty_frobeniusBasis (ResidueField 𝒪C) (ResidueField 𝒪M) p
  have hlift : ∀ q, ∃ u ∈ F₀, ‖u‖ ≤ 1 ∧ rd u = B.u q := fun q ↦ by
    have : B.u q ∈ residueSubfield F₀ := hF₀res ▸ Subfield.mem_top (B.u q)
    exact this
  choose u huF hu1 hurd using hlift
  set FF : LiftedFrobeniusFamily C M p := ⟨B, u, hu1, hurd⟩ with hFF
  have hbF : ∀ i, FF.b i ∈ F₀ := by
    rintro (_ | ⟨m, q⟩)
    · exact F₀.one_mem
    · exact F₀.pow_mem (huF q) _
  set D := (Submodule.span C (Set.range FF.b)).topologicalClosure with hD_def
  -- `F₀ ⊆ D` by `p`-adic expansion
  have hF₀D : ∀ f ∈ F₀, f ∈ D := by
    refine mem_topologicalClosure_of_isDiscrete hpM0 hpM1 hF₀ fun f hf hf1 ↦ ?_
    set r := B.basis.repr (rd f)
    have hco : ∀ i, ∃ c ∈ K₀, ‖c‖ ≤ 1 ∧ rd c = r i := fun i ↦ hK₀res (r i)
    choose c hcK hc1 hcrd using hco
    set s := ∑ i ∈ r.support, algebraMap C M (c i) * FF.b i with hs
    have hterm (i : Option (ℕ × B.ι)) : ‖algebraMap C M (c i) * FF.b i‖ ≤ 1 := by
      rw [norm_mul, norm_algebraMap']
      exact mul_le_one₀ (hc1 i) (norm_nonneg _) (FF.norm_b_le i)
    have hs1 : ‖s‖ ≤ 1 :=
      IsUltrametricDist.norm_sum_le_of_forall_le_of_nonneg zero_le_one fun i _ ↦ hterm i
    have hsrd : rd s = rd f := by
      rw [hs, rd_sum _ _ fun i _ ↦ hterm i]
      conv_rhs => rw [← B.basis.linearCombination_repr (rd f), Finsupp.linearCombination_apply,
        Finsupp.sum]
      refine Finset.sum_congr rfl fun i _ ↦ ?_
      rw [rd_mul ((norm_algebraMap' M (c i)).trans_le (hc1 i)) (FF.norm_b_le i),
        LiftedFrobeniusFamily.rd_algebraMap (hc1 i), hcrd, FF.rd_b, Algebra.smul_def]
    refine ⟨s, Submodule.sum_mem _ fun i _ ↦ ?_, F₀.sum_mem fun i _ ↦
      F₀.mul_mem (hK₀MF₀ (Subfield.mem_map.2 ⟨c i, hcK i, rfl⟩)) (hbF i), ?_⟩
    · rw [← Algebra.smul_def]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)
    · have hle : ‖f - s‖ ≤ 1 := (PthPower.norm_sub_le_max' _ _).trans (max_le hf1 hs1)
      rw [← rd_eq_zero_iff hle, rd_sub hf1 hs1, hsrd, sub_self]
  -- the closure of the `C`-algebra generated by `F₀` lies in `D`
  set A := Algebra.adjoin C (F₀ : Set M) with hA_def
  have hFA : ∀ x ∈ F₀, x ∈ A := fun x hx ↦ Algebra.subset_adjoin hx
  have hAD : ∀ x ∈ A, x ∈ D := by
    intro x hx
    have hx' : x ∈ Subalgebra.toSubmodule A := hx
    rw [hA_def, Algebra.adjoin_eq_span, show (Submonoid.closure (F₀ : Set M) : Set M) = F₀ from
      congrArg SetLike.coe (Submonoid.closure_eq F₀.toSubmonoid)] at hx'
    exact (Submodule.span_le.2 fun y hy ↦ hF₀D y hy) hx'
  have hDclosed : IsClosed (D : Set M) := Submodule.isClosed_topologicalClosure _
  have hAbarD : ∀ x ∈ A.topologicalClosure, x ∈ D := by
    intro x hx
    rw [← SetLike.mem_coe, Subalgebra.topologicalClosure_coe] at hx
    exact closure_minimal (fun y hy ↦ hAD y hy) hDclosed hx
  -- values and residues
  have hval : ∀ x ∈ A.topologicalClosure, x ≠ 0 → ∃ c : C, c ≠ 0 ∧ ‖x‖ = ‖c‖ := by
    intro x hx hx0
    have hxD := hAbarD x hx
    rw [← SetLike.mem_coe, Submodule.topologicalClosure_coe] at hxD
    obtain ⟨y, hy, hxy⟩ := Metric.mem_closure_iff.1 hxD ‖x‖ (norm_pos_iff.2 hx0)
    rw [dist_eq_norm] at hxy
    obtain ⟨c, rfl⟩ := Finsupp.mem_span_range_iff_exists_finsupp.1 hy
    rw [← Finsupp.linearCombination_apply] at hxy
    have heq : ‖FF.val c‖ = ‖x‖ :=
      DenseCompletion.norm_eq_of_norm_sub_lt (by rw [norm_sub_rev]; exact hxy)
    have hc : c ≠ 0 := by
      rintro rfl
      rw [LiftedFrobeniusFamily.val_zero, norm_zero] at heq
      exact hx0 (norm_eq_zero.1 heq.symm)
    obtain ⟨i, hi, hi'⟩ := FF.exists_coeff_eq c hc
    exact ⟨c i, hi, by rw [← heq, hi']⟩
  have hres : ∀ a : ResidueField 𝒪M, ∃ s ∈ A, ‖s‖ ≤ 1 ∧ rd s = a := fun a ↦ by
    have : a ∈ residueSubfield F₀ := hF₀res ▸ Subfield.mem_top a
    obtain ⟨s, hs, hs1, hsa⟩ := this
    exact ⟨s, hFA s hs, hs1, hsa⟩
  have hinv := inv_mem_topologicalClosure hval hres
  -- the closure of `A` is a closed subfield
  set Afield : Subfield M :=
    { A.topologicalClosure.toSubring with
      inv_mem' := fun x hx ↦ by
        by_cases hx0 : x = 0
        · rw [hx0, inv_zero]
          exact A.topologicalClosure.zero_mem
        · exact hinv x hx hx0 } with hAfield
  have hmemA : ∀ x, x ∈ Afield ↔ x ∈ A.topologicalClosure := fun x ↦ Iff.rfl
  have hAclosed : IsClosed (Afield : Set M) := A.isClosed_topologicalClosure
  have hFAfield : ∀ x ∈ F₀, x ∈ Afield := fun x hx ↦
    (hmemA x).2 (A.le_topologicalClosure (hFA x hx))
  have hM₁A : M₁ ≤ Afield := by
    have hE : ∀ c : C, algebraMap C M c ∈ Afield := fun c ↦
      (hmemA _).2 (A.topologicalClosure.algebraMap_mem c)
    have hle : IntermediateField.adjoin C {z} ≤ Afield.toIntermediateField hE :=
      IntermediateField.adjoin_simple_le_iff.2 (hFAfield z hzF₀)
    exact Subfield.topologicalClosure_minimal _ (fun x hx ↦ hle hx) hAclosed
  -- `M = M₁[y']`
  haveI := hM.finiteDimensional
  have hLI : LinearIndependent M₁ fun j : Fin n ↦ y' ^ (j : ℕ) := by
    have hind : LinearIndependent (residueSubfield M₁) fun j : Fin n ↦ rd (y' ^ (j : ℕ)) := by
      have h : LinearIndependent R fun j : Fin n ↦ ybar ^ (j : ℕ) := linearIndependent_pow ybar
      have key : ∀ S : Subfield (ResidueField 𝒪M), S = R →
          LinearIndependent S fun j : Fin n ↦ ybar ^ (j : ℕ) := by
        rintro S rfl
        exact h
      convert key _ hresK₁.symm using 2 with j
      rw [rd_pow hy'1, hy'rd]
    rw [linearIndependent_iff']
    intro s g hg j hj
    have hsum := norm_sum_eq_sup' M₁ (x := fun j : Fin n ↦ y' ^ (j : ℕ))
      (fun j ↦ by rw [norm_pow]; exact pow_le_one₀ (norm_nonneg _) hy'1) hind ⟨j, hj⟩
      (c := fun j ↦ (g j : M)) fun i _ ↦ (g i).2
    have hzero : ∑ i ∈ s, (g i : M) * y' ^ (i : ℕ) = 0 := by
      rw [← hg]
      rfl
    rw [hzero, norm_zero] at hsum
    have := s.le_sup' (fun i ↦ ‖(g i : M)‖) hj
    rw [← hsum] at this
    exact Subtype.ext (norm_eq_zero.1 (le_antisymm this (norm_nonneg _)))
  have hn0 : 0 < n := minpoly.natDegree_pos hint
  haveI : Nonempty (Fin n) := ⟨⟨0, hn0⟩⟩
  have hcard : Fintype.card (Fin n) = Module.finrank M₁ M := by
    refine le_antisymm ?_ ?_
    · exact hLI.fintype_card_le_finrank
    · rw [Fintype.card_fin, ← hfinrank, hresK₁]
      exact hM.finrank_le
  have hspan := hLI.span_eq_top_of_card_eq_finrank hcard
  have hall : ∀ x : M, x ∈ Afield := by
    intro x
    have hx : x ∈ Submodule.span M₁ (Set.range fun j : Fin n ↦ y' ^ (j : ℕ)) := by
      rw [hspan]
      exact Submodule.mem_top
    induction hx using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨j, rfl⟩ := hy
      exact Afield.pow_mem (hFAfield y' hy'F₀) _
    | zero => exact Afield.zero_mem
    | add y w _ _ hy hw => exact Afield.add_mem hy hw
    | smul a y _ hy => exact Afield.mul_mem (hM₁A a.2) hy
  -- conclusion
  have hDtop : D = ⊤ := eq_top_iff.2 fun x _ ↦ hAbarD x ((hmemA x).1 (hall x))
  exact ⟨⟨FF, Submodule.dense_iff_topologicalClosure_eq_top.2 hDtop⟩⟩

end Construction

end InertiallyGenerated

end SemistableReduction
