/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.ChangeOfGenerator

/-!
# Local stability: finite extensions of `\widehat{C(x)}` are defectless

Blueprint §9.4, G3 (mixed characteristic). Let `C` be algebraically closed of characteristic `0`
with `‖p‖ < 1` and `K = \widehat{C(x)}` Gauss-complete (`NoImmediate.IsGaussComplete`). Every
finite extension `L / K` is defectless: `e(L | K) = 1` and `f(L | K) = [L : K]`
(`ramificationIdx_eq_one_and_inertiaDeg_eq`, `ramificationIdx_mul_inertiaDeg_eq`, for any
valuation of `L` extending that of `K`).

* `IsGaussFinite C B`: `B` is finite over the closure of `C(z)` for some `z` with `‖z‖ ≤ 1` and
  `z̄` transcendental; it passes to finite extensions (`IsGaussFinite.of_finite`) and implies
  inertially generated (G2);
* `inertiaDeg_eq_finrank_of_isGalois`: a finite Galois `N / B` with `B` Gauss-finite is
  unramified-defectless, by strong induction on `[N : B]`: if the fixed field `N^T` of the inertia
  group is nontrivial, it is unramified over `B` (D3) and we pass to `N / N^T`; otherwise the
  Galois group is a `p`-group (D2) with a normal subgroup of index `p` (D4), whose fixed field is
  defectless over `B` (F5, `B` being inertially generated by G2), and we pass to it.
-/

open Polynomial IsLocalRing Valuation
open scoped IntermediateField

namespace SemistableReduction

open FundamentalInequality DenseCompletion KummerNormalForm DiscreteCoefficients
  InertiallyGenerated NormedTower NoImmediate ChangeOfGenerator

namespace LocalStability

local notation "κ" X => ResidueField (HenselComplete.integers X)

section GaussFinite

variable {C : Type*} [NontriviallyNormedField C] [IsUltrametricDist C]

variable (C) in
/-- `B` is finite over the closure of `C(z)` for some `z` with `‖z‖ ≤ 1` and residue
transcendental over the residue field of `C`. -/
def IsGaussFinite (B : Type*) [NontriviallyNormedField B] [IsUltrametricDist B]
    [NormedAlgebra C B] : Prop :=
  ∃ z : B, ‖z‖ ≤ 1 ∧ Transcendental (κ C) (rd z) ∧ FiniteDimensional (genClosure C z) B

variable {B B' : Type*} [NontriviallyNormedField B] [IsUltrametricDist B] [NormedAlgebra C B]
  [NontriviallyNormedField B'] [IsUltrametricDist B'] [NormedAlgebra C B'] [NormedAlgebra B B']
  [IsScalarTower C B B'] [FiniteDimensional B B']

/-- Finite extensions of Gauss-finite fields are Gauss-finite. -/
theorem IsGaussFinite.of_finite (hB : IsGaussFinite C B) : IsGaussFinite C B' := by
  obtain ⟨z, hz1, htr, hfin⟩ := hB
  set z' := algebraMap B B' z
  have hz'1 : ‖z'‖ ≤ 1 := by rw [norm_algebraMap']; exact hz1
  refine ⟨z', hz'1, ?_, ?_⟩
  · rw [rd_algebraMap' hz1, transcendental_algebraMap_iff (algebraMap (κ B) (κ B')).injective]
    exact htr
  · set G := genField C z
    set G' := genField C z'
    haveI : FiniteDimensional G B := (finite_genField_iff z).2 hfin
    haveI : Module.Finite G B' := Module.Finite.trans B B'
    have hGG' : ∀ g : G, algebraMap G B' g ∈ G' := by
      intro g
      have hcont : Continuous (algebraMap B B') :=
        (AddMonoidHomClass.isometry_of_norm (algebraMap B B') (norm_algebraMap' B')).continuous
      have h1 := mem_closure_image hcont.continuousAt g.2
      refine closure_mono ?_ h1
      rintro _ ⟨y, hy, rfl⟩
      have hmap : (C⟮z⟯).map (IsScalarTower.toAlgHom C B B') = C⟮z'⟯ := by
        rw [IntermediateField.adjoin_map, Set.image_singleton]
        rfl
      have : algebraMap B B' y ∈ (C⟮z⟯).map (IsScalarTower.toAlgHom C B B') := ⟨y, hy, rfl⟩
      rw [hmap] at this
      exact this
    letI : Algebra G G' := (RingHom.codRestrict (algebraMap G B') G' hGG').toAlgebra
    haveI : IsScalarTower G G' B' := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
    haveI : Module.Finite G' B' := Module.Finite.of_restrictScalars_finite G G' B'
    exact (finite_genField_iff z').1 this

end GaussFinite

section Galois

universe u

variable {C : Type*} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
include hp hp1

/-- **Reduction step.** Let `B` be Gauss-finite and `N / B` finite Galois of degree `> 1`. There
is an intermediate field `B' ≠ B` with `f(B' | B) = [B' : B]`: the fixed field of the inertia group
if it is nontrivial (D3), otherwise the fixed field of a normal subgroup of index `p` of the
Galois group, a `p`-group (D2, D4, F5). -/
theorem exists_intermediateField_inertiaDeg_eq {B N : Type u} [NontriviallyNormedField B]
    [IsUltrametricDist B] [CompleteSpace B] [NormedAlgebra C B] [NormedField N]
    [IsUltrametricDist N] [NormedAlgebra B N] [FiniteDimensional B N] [IsGalois B N]
    (hB : IsGaussFinite C B) (hN : 1 < Module.finrank B N) :
    ∃ B' : IntermediateField B N, B' ≠ ⊥ ∧
      inertiaDeg (NormedField.valuation (K := B)) (NormedField.valuation (K := B')) =
        Module.finrank B B' := by
  haveI := Fact.mk hp
  obtain ⟨z, hz1, hztr, hzfin⟩ := hB
  obtain ⟨z', hIG⟩ := exists_isInertiallyGenerated hp hp1 hz1 hztr
  have hσ : ∀ (σ : N ≃ₐ[B] N) (y : N),
      NormedField.valuation (σ y) = NormedField.valuation (K := N) y :=
    fun σ y ↦ UniqueExtension.valuation_algEquiv_apply (K := B) _ σ y
  set T := inertia (NormedField.valuation (K := B)) hσ
  by_cases hKT : IntermediateField.fixedField T = ⊥
  · -- the inertia group is everything: a `p`-group
    have hT : T = ⊤ := by
      rw [← IntermediateField.fixingSubgroup_fixedField T, hKT,
        IntermediateField.fixingSubgroup_bot]
    have hpB1 : ‖(p : B)‖ < 1 := by
      rw [← map_natCast (algebraMap C B), norm_algebraMap']
      exact hp1
    haveI : CharP (κ B) p := charP_residueField hp hpB1
    have hG : IsPGroup p (N ≃ₐ[B] N) := by
      have h := isPGroup_inertia (u := NormedField.valuation (K := B)) hσ
        (fun c n hn ↦ exists_valuation_pow_eq hp hp1 hIG c hn) (fun ℓ hℓ _ ↦ by
          haveI : NeZero (ℓ : C) := ⟨Nat.cast_ne_zero.2 hℓ.ne_zero⟩
          obtain ⟨ζ, hζ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot C ℓ
          exact ⟨algebraMap C B ζ, hζ.map_of_injective (algebraMap C B).injective⟩)
      rw [ringChar.eq (κ B) p] at h
      change IsPGroup p T at h
      rw [hT] at h
      exact h.of_equiv Subgroup.topEquiv
    obtain ⟨m, c, hc0, hcm, hc⟩ := PGroupChain.exists_chain hG ⊥
    have hbt : (⊥ : Subgroup (N ≃ₐ[B] N)) ≠ ⊤ := by
      intro h
      have hcard := IsGalois.card_aut_eq_finrank B N
      rw [← Subgroup.card_top (G := N ≃ₐ[B] N), ← h, Subgroup.card_bot] at hcard
      omega
    have hm : m ≠ 0 := by
      rintro rfl
      exact hbt (hc0.symm.trans hcm)
    obtain ⟨k, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hm
    obtain ⟨hle, hnormal, hidx⟩ := hc k (Nat.lt_succ_self k)
    rw [hcm] at hle hnormal hidx
    haveI : (c k).Normal := by
      have := (Subgroup.normal_subgroupOf_iff_le_normalizer hle).1 hnormal
      exact ⟨fun n hn g ↦ (this (Subgroup.mem_top g) n).1 hn⟩
    set Y := IntermediateField.fixedField (c k)
    have hYdeg : Module.finrank B Y = p := by
      have h1 := IntermediateField.finrank_fixedField_eq_card (c k)
      have h2 := Module.finrank_mul_finrank B Y N
      have h3 := IsGalois.card_aut_eq_finrank B N
      rw [h1, ← h3, ← Subgroup.index_mul_card (c k)] at h2
      rw [Subgroup.relIndex_top_right] at hidx
      rw [hidx] at h2
      exact Nat.eq_of_mul_eq_mul_right Nat.card_pos h2
    refine ⟨Y, fun h ↦ ?_, ?_⟩
    · rw [h, IntermediateField.finrank_bot] at hYdeg
      exact hp.one_lt.ne hYdeg
    · rw [hYdeg]
      exact (KummerDefectless.ramificationIdx_eq_one_and_inertiaDeg_eq
        (NormedField.valuation (K := Y)) hp hp1 hIG hYdeg).2.trans hYdeg
  · -- the fixed field of the inertia group is unramified (D3)
    obtain ⟨-, hfT, -⟩ := unramified_fixedField_inertia (u := NormedField.valuation (K := B))
      (w := NormedField.valuation (K := N)) hσ
    refine ⟨IntermediateField.fixedField T, hKT, ?_⟩
    exact (inertiaDeg_congr comap_valuation_algebraMap).symm.trans hfT

set_option maxHeartbeats 1000000 in
-- the instance arguments of the induction hypothesis at an intermediate field are slow to unify
/-- **Galois extensions of Gauss-finite fields are unramified-defectless**: `f(N | B) = [N : B]`
for `N / B` finite Galois and `B` Gauss-finite (strong induction on `[N : B]`). -/
theorem inertiaDeg_eq_finrank_of_isGalois (n : ℕ) :
    ∀ (B N : Type u) [NontriviallyNormedField B] [IsUltrametricDist B] [CompleteSpace B]
      [NormedAlgebra C B] [NormedField N] [IsUltrametricDist N] [NormedAlgebra B N]
      [NormedAlgebra C N] [IsScalarTower C B N] [FiniteDimensional B N] [IsGalois B N],
      IsGaussFinite C B → Module.finrank B N = n →
        inertiaDeg (NormedField.valuation (K := B)) (NormedField.valuation (K := N)) = n := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro B N _ _ _ _ _ _ _ _ _ _ _ hB hn
  rcases Nat.lt_or_ge 1 n with h1 | h1
  · obtain ⟨B', hB'ne, hfB'⟩ := exists_intermediateField_inertiaDeg_eq hp hp1 hB (hn ▸ h1)
    have hB'1 : 1 < Module.finrank B B' := by
      rcases Nat.lt_or_ge 1 (Module.finrank B B') with h | h
      · exact h
      · exact absurd (IntermediateField.finrank_eq_one_iff.1
          (le_antisymm h Module.finrank_pos)) hB'ne
    have hmul := Module.finrank_mul_finrank B B' N
    have hlt : Module.finrank B' N < n := by
      rw [← hn, ← hmul]
      exact lt_mul_left Module.finrank_pos hB'1
    have hB' : IsGaussFinite C B' := IsGaussFinite.of_finite hB
    haveI : IsScalarTower C B' N := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
    haveI : IsGalois B' N := IsGalois.tower_top_intermediateField B'
    have hIH := ih (Module.finrank B' N) hlt B' N hB' rfl
    rw [inertiaDeg_tower (NormedField.valuation (K := B)) (NormedField.valuation (K := B'))
      (NormedField.valuation (K := N)), hIH, hfB', ← hn, ← hmul, mul_comm]
  · have h1' : n = 1 := le_antisymm h1 (hn ▸ Module.finrank_pos)
    subst h1'
    exact le_antisymm (hn ▸ inertiaDeg_le_finrank) inertiaDeg_pos

end Galois

section Main

universe u

variable {C : Type*} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
  {K : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [CompleteSpace K]
  [NormedAlgebra C K]

omit [IsAlgClosed C] [CharZero C] [CompleteSpace K] in
/-- A Gauss-complete field is Gauss-finite. -/
lemma isGaussFinite_of_isGaussComplete {x : K} (hx : IsGaussComplete C x) :
    IsGaussFinite C K := by
  refine ⟨x, hx.norm_le_one, hx.transcendental, ?_⟩
  have h : (algebraMap K K).fieldRange = genClosure C x := by
    rw [hx.genClosure_eq_top]
    exact eq_top_iff.2 fun y _ ↦ ⟨y, rfl⟩
  rw [← h]
  exact finite_fieldRange_iff.2 inferInstance

include hp hp1

/-- **G3 (local stability).** Every finite extension `L` of a Gauss-complete `K` (the completion
of `C(x)` for a Gauss valuation) is defectless: `e(L | K) = 1` and `f(L | K) = [L : K]`. -/
theorem ramificationIdx_eq_one_and_inertiaDeg_eq {x : K} (hx : IsGaussComplete C x)
    (L : Type u) [NormedField L] [IsUltrametricDist L] [NormedAlgebra K L] [FiniteDimensional K L] :
    ramificationIdx K (NormedField.valuation (K := L)) = 1 ∧
      inertiaDeg (NormedField.valuation (K := K)) (NormedField.valuation (K := L)) =
        Module.finrank K L := by
  haveI : CharZero K := charZero_of_injective_algebraMap (algebraMap C K).injective
  obtain ⟨N, _, _, _, _, _, _, _, _, _⟩ := exists_normed_galois_closure C K L
  haveI : FiniteDimensional L N := Module.Finite.of_restrictScalars_finite K L N
  have hf := inertiaDeg_eq_finrank_of_isGalois hp hp1 _ K N
    (isGaussFinite_of_isGaussComplete hx) rfl
  have hfL := (inertiaDeg_eq_finrank_of_tower (A := L) hf).1
  refine ⟨?_, hfL⟩
  have hle := ramificationIdx_mul_inertiaDeg_le (K := K) (v := NormedField.valuation (K := K))
    (w := NormedField.valuation (K := L))
  rw [hfL] at hle
  have he0 := ramificationIdx_ne_zero (K := K) (NormedField.valuation (K := L))
  have hpos : 0 < Module.finrank K L := Module.finrank_pos
  exact le_antisymm (by
    by_contra h
    have := Nat.mul_le_mul_right (Module.finrank K L) (not_le.1 h)
    omega) (Nat.pos_of_ne_zero he0)

/-- **G3 (local stability)**, for any valuation `w` of a finite extension `E / K` extending the
norm valuation of `K`: `e(w | K) f(w | K) = [E : K]`. -/
theorem ramificationIdx_mul_inertiaDeg_eq {x : K} (hx : IsGaussComplete C x)
    (E : Type u) [Field E] [Algebra K E] [FiniteDimensional K E]
    {Γ : Type*} [LinearOrderedCommGroupWithZero Γ] (w : Valuation E Γ)
    [(NormedField.valuation (K := K)).HasExtension w] :
    ramificationIdx K w * inertiaDeg (NormedField.valuation (K := K)) w = Module.finrank K E := by
  letI : NontriviallyNormedField E := spectralNorm.nontriviallyNormedField K E
  letI : NormedAlgebra K E := spectralNorm.normedAlgebra K E
  haveI : IsUltrametricDist E := IsUltrametricDist.of_normedAlgebra K
  have hf : inertiaDeg (NormedField.valuation (K := K)) w = Module.finrank K E :=
    (inertiaDeg_eq_of_valuationSubring_eq (UniqueExtension.valuationSubring_eq (K := K) w
      (NormedField.valuation (K := E)))).trans
      (ramificationIdx_eq_one_and_inertiaDeg_eq hp hp1 hx E).2
  have hle := ramificationIdx_mul_inertiaDeg_le (K := K) (v := NormedField.valuation (K := K))
    (w := w)
  rw [hf] at hle ⊢
  have he0 := ramificationIdx_ne_zero (K := K) w
  have hpos : 0 < Module.finrank K E := Module.finrank_pos
  have he1 : ramificationIdx K w = 1 := le_antisymm (by
    by_contra h
    have := Nat.mul_le_mul_right (Module.finrank K E) (not_le.1 h)
    omega) (Nat.pos_of_ne_zero he0)
  rw [he1, one_mul]

end Main

end LocalStability

end SemistableReduction
