/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.MonomialPoint

/-!
# Uniqueness of interior monomial points (Blueprint §9.7, XL2)

Let `O ⊆ K` be a discrete valuation subring with uniformizer `ϖ` and `P ⊆ L` the germs of a node
(`NodeGerm`): `O ⊆ P`, node coordinates `u, v ∈ P` with `u v = ϖ ^ n`, every element of `P` is
`o + ϖ a + u b + v c` with `o ∈ O`, `a, b, c ∈ P` (residue field `κ(O)`, maximal ideal
`(ϖ, u, v)`), `L = Frac P`, and every element of `P` satisfies a polynomial relation over `K[u]`
(`L / K(u)` algebraic). Then for `0 < s < n` there is **at most one** monomial point at `s`
(`NodeGerm.eq_of_isMonomialPt`).

Proof (no completions): by `gen`, `P = A + J_N` for every `N`, with `A` the Laurent
polynomials `Q(u) / u ^ k` and `J_N` the elements of the form `Σ μ p` (`μ` monomials of degree
`N` in `ϖ, u, v`, `p ∈ P`), and every interior monomial point has `U(J_N) ^ d ≤ U(ϖ) ^ N`. The
polynomial relation bounds `U(f) ^ d ≥ U(ϖ) ^ B` from below with `B` independent of `U`; so for
`N > B` the approximation `a ∈ A` of `f` has `U(f) = U(a)`, and `U(a) ^ d = U(ϖ) ^ e` with an
exponent `e` independent of `U` (`valuation_aeval_pow_den`). Hence all interior monomial points
at `s` have the same normalised values on `P`, so on `L`, so they are equal.
-/

open Polynomial

namespace SemistableReduction

variable {K L : Type*} [Field K] [Field L] [Algebra K L]
  {O : ValuationSubring K} [IsDiscreteValuationRing O] {ϖ : O}

/-- **The germs of a node** (the input from XL1): `P ⊆ L` contains `O`, node coordinates `u, v`
with `u v = ϖ ^ n`, is generated by `O` modulo `(ϖ, u, v)`, has fraction field `L`, and its
elements are algebraic over `K(u)` (in the form of a relation with nonzero constant term). -/
structure NodeGerm (O : ValuationSubring K) (ϖ : O) (P : Subring L) (u v : L) (n : ℕ) :
    Prop where
  algebraMap_mem : ∀ o : O, algebraMap K L (o : K) ∈ P
  u_mem : u ∈ P
  v_mem : v ∈ P
  mul_eq : u * v = algebraMap K L (ϖ : K) ^ n
  gen : ∀ z ∈ P, ∃ o : O, ∃ a ∈ P, ∃ b ∈ P, ∃ c ∈ P,
    z = algebraMap K L (o : K) + algebraMap K L (ϖ : K) * a + u * b + v * c
  frac : ∀ f : L, ∃ g ∈ P, ∃ h ∈ P, h ≠ 0 ∧ f = g / h
  alg : ∀ f ∈ P, f ≠ 0 → ∃ (c₀ : K[X]) (S : Finset ℕ) (c : ℕ → K[X]),
    c₀ ≠ 0 ∧ aeval u c₀ = ∑ k ∈ S, aeval u (c k) * f ^ (k + 1)

variable (K) in
/-- Elements `Q(u) / u ^ k` (Laurent polynomials in `u`). -/
def IsLaurent (u a : L) : Prop :=
  ∃ (Q : K[X]) (k : ℕ), a = aeval u Q / u ^ k

/-- The sets `J_N`: `J_0 = P`, `J_{N+1} = ϖ J_N + u J_N + v J_N`. -/
def nodeJ (P : Set L) (p u v : L) : ℕ → Set L
  | 0 => P
  | N + 1 => {z | ∃ a ∈ nodeJ P p u v N, ∃ b ∈ nodeJ P p u v N, ∃ c ∈ nodeJ P p u v N,
      z = p * a + u * b + v * c}

section Laurent

variable {u : L}

lemma IsLaurent.zero : IsLaurent K u 0 := ⟨0, 0, by simp⟩

lemma IsLaurent.const (q : K) : IsLaurent K u (algebraMap K L q) := ⟨C q, 0, by simp⟩

lemma IsLaurent.add (hu : u ≠ 0) {a b : L} (ha : IsLaurent K u a) (hb : IsLaurent K u b) :
    IsLaurent K u (a + b) := by
  obtain ⟨Q, k, rfl⟩ := ha
  obtain ⟨R, l, rfl⟩ := hb
  refine ⟨Q * X ^ l + R * X ^ k, k + l, ?_⟩
  simp only [map_add, map_mul, map_pow, aeval_X]
  field_simp
  ring

lemma IsLaurent.mul_const {a : L} (ha : IsLaurent K u a) (q : K) :
    IsLaurent K u (algebraMap K L q * a) := by
  obtain ⟨Q, k, rfl⟩ := ha
  exact ⟨C q * Q, k, by simp [mul_div_assoc]⟩

lemma IsLaurent.mul_u {a : L} (ha : IsLaurent K u a) : IsLaurent K u (u * a) := by
  obtain ⟨Q, k, rfl⟩ := ha
  exact ⟨X * Q, k, by simp [mul_div_assoc]⟩

lemma IsLaurent.mul_v (hu : u ≠ 0) {v : L} {q' : K} {n : ℕ}
    (huv : u * v = algebraMap K L q' ^ n) {a : L} (ha : IsLaurent K u a) :
    IsLaurent K u (v * a) := by
  obtain ⟨Q, k, rfl⟩ := ha
  refine ⟨C (q' ^ n) * Q, k + 1, ?_⟩
  have hv : v = algebraMap K L q' ^ n / u := by
    rw [eq_div_iff hu, mul_comm, huv]
  rw [hv]
  simp only [map_mul, aeval_C, map_pow]
  field_simp
  ring

end Laurent

namespace NodeGerm

variable {P : Subring L} {u v : L} {n : ℕ}

omit [IsDiscreteValuationRing O] in
/-- **Approximation step**: every `r ∈ J_N` is a Laurent polynomial modulo `J_{N+1}`. -/
lemma exists_laurent_sub_mem (h : NodeGerm O ϖ P u v n) (hu : u ≠ 0) (N : ℕ) :
    ∀ r ∈ nodeJ (P : Set L) (algebraMap K L (ϖ : K)) u v N,
      ∃ a, IsLaurent K u a ∧ r - a ∈ nodeJ (P : Set L) (algebraMap K L (ϖ : K)) u v (N + 1) := by
  induction N with
  | zero =>
    intro r hr
    obtain ⟨o, a, ha, b, hb, c, hc, rfl⟩ := h.gen r hr
    exact ⟨_, IsLaurent.const (o : K), a, ha, b, hb, c, hc, by ring⟩
  | succ N ih =>
    intro r hr
    obtain ⟨a, ha, b, hb, c, hc, rfl⟩ := hr
    obtain ⟨α, hα, ha'⟩ := ih a ha
    obtain ⟨β, hβ, hb'⟩ := ih b hb
    obtain ⟨γ, hγ, hc'⟩ := ih c hc
    refine ⟨algebraMap K L (ϖ : K) * α + u * β + v * γ, ?_, a - α, ha', b - β, hb', c - γ, hc',
      by ring⟩
    exact ((hα.mul_const _).add hu (hβ.mul_u)).add hu (hγ.mul_v hu h.mul_eq)

omit [IsDiscreteValuationRing O] in
/-- **Approximation**: every element of `P` is a Laurent polynomial modulo `J_N`. -/
lemma exists_laurent_sub_mem' (h : NodeGerm O ϖ P u v n) (hu : u ≠ 0) (N : ℕ) :
    ∀ f ∈ P, ∃ a, IsLaurent K u a ∧ f - a ∈ nodeJ (P : Set L) (algebraMap K L (ϖ : K)) u v N := by
  induction N with
  | zero => exact fun f hf ↦ ⟨0, IsLaurent.zero, by simpa [nodeJ] using hf⟩
  | succ N ih =>
    intro f hf
    obtain ⟨a, ha, hfa⟩ := ih f hf
    obtain ⟨a', ha', h'⟩ := h.exists_laurent_sub_mem hu N _ hfa
    exact ⟨a + a', ha.add hu ha', by rwa [sub_add_eq_sub_sub]⟩

end NodeGerm

/-- **Valuations of `J_N`**: if `U ⊇ P` and `U(x) ^ d ≤ U(ϖ)` for the generators `x = ϖ, u, v`,
then `U(z) ^ d ≤ U(ϖ) ^ N` on `J_N`. -/
lemma valuation_pow_le_of_mem_nodeJ {P : Set L} {p u v : L} {U : ValuationSubring L}
    (hP : P ⊆ U) {d : ℕ} (hp : U.valuation p ^ d ≤ U.valuation p)
    (hu : U.valuation u ^ d ≤ U.valuation p) (hv : U.valuation v ^ d ≤ U.valuation p) :
    ∀ N, ∀ z ∈ nodeJ P p u v N, U.valuation z ^ d ≤ U.valuation p ^ N := by
  intro N
  induction N with
  | zero =>
    intro z hz
    rw [pow_zero]
    exact pow_le_one₀ zero_le ((U.valuation_le_one_iff z).mpr (hP hz))
  | succ N ih =>
    intro z hz
    obtain ⟨a, ha, b, hb, c, hc, rfl⟩ := hz
    have key : ∀ x y : L, U.valuation x ^ d ≤ U.valuation p → y ∈ nodeJ P p u v N →
        U.valuation (x * y) ^ d ≤ U.valuation p ^ (N + 1) := fun x y hx hy ↦ by
      rw [map_mul, mul_pow, pow_succ, mul_comm (U.valuation p ^ N)]
      exact mul_le_mul' hx (ih y hy)
    have h1 := key _ _ hp ha
    have h2 := key _ _ hu hb
    have h3 := key _ _ hv hc
    calc U.valuation (p * a + u * b + v * c) ^ d
        ≤ (max (max (U.valuation (p * a)) (U.valuation (u * b))) (U.valuation (v * c))) ^ d := by
          gcongr
          exact (U.valuation.map_add _ _).trans (max_le_max_right _ (U.valuation.map_add _ _))
      _ ≤ U.valuation p ^ (N + 1) := by
          rcases le_total (max (U.valuation (p * a)) (U.valuation (u * b)))
              (U.valuation (v * c)) with hm | hm
          · rw [max_eq_right hm]; exact h3
          · rw [max_eq_left hm]
            rcases le_total (U.valuation (p * a)) (U.valuation (u * b)) with hm' | hm'
            · rw [max_eq_right hm']; exact h2
            · rw [max_eq_left hm']; exact h1

/-- A valuation subring of `L` containing `O` on which `ϖ` is not a unit lies over `O`. -/
lemma comap_eq_of_lt_one {U : ValuationSubring L} (hϖ : Irreducible ϖ)
    (hO : ∀ o : O, algebraMap K L (o : K) ∈ U)
    (hlt : U.valuation (algebraMap K L (ϖ : K)) < 1) : U.comap (algebraMap K L) = O := by
  ext q
  refine ⟨fun hq ↦ ?_, fun hq ↦ hO ⟨q, hq⟩⟩
  by_contra hqO
  have hq0 : q ≠ 0 := fun h ↦ hqO (h ▸ O.zero_mem)
  have hinv : q⁻¹ ∈ O := (O.mem_or_inv_mem q).resolve_left hqO
  set o : O := ⟨q⁻¹, hinv⟩
  have hno : ¬ IsUnit o := fun hu ↦ by
    obtain ⟨o', ho'⟩ := hu.exists_right_inv
    apply hqO
    have : q = (o' : K) := by
      have := congrArg (fun x : O ↦ (x : K)) ho'
      simp only [MulMemClass.coe_mul, OneMemClass.coe_one, o] at this
      field_simp at this
      exact this.symm
    rw [this]; exact o'.2
  have hmax : o ∈ IsLocalRing.maximalIdeal O := hno
  rw [hϖ.maximalIdeal_eq, Ideal.mem_span_singleton'] at hmax
  obtain ⟨o', ho'⟩ := hmax
  have hval : U.valuation (algebraMap K L q⁻¹) < 1 := by
    have : q⁻¹ = (o' : K) * ϖ := by
      have := congrArg (fun x : O ↦ (x : K)) ho'
      simpa [o] using this.symm
    rw [this, map_mul, map_mul]
    calc U.valuation (algebraMap K L o') * U.valuation (algebraMap K L ϖ)
        ≤ 1 * U.valuation (algebraMap K L ϖ) := by
          gcongr
          exact (U.valuation_le_one_iff _).mpr (hO o')
      _ < 1 := by rw [one_mul]; exact hlt
  have hq1 : U.valuation (algebraMap K L q) ≤ 1 := (U.valuation_le_one_iff _).mpr hq
  have : U.valuation (algebraMap K L q) * U.valuation (algebraMap K L q⁻¹) = 1 := by
    rw [← map_mul, ← map_mul, mul_inv_cancel₀ hq0, map_one, map_one]
  have hlt' : U.valuation (algebraMap K L q) * U.valuation (algebraMap K L q⁻¹) < 1 :=
    calc U.valuation (algebraMap K L q) * U.valuation (algebraMap K L q⁻¹)
        ≤ 1 * U.valuation (algebraMap K L q⁻¹) := mul_le_mul_left hq1 _
      _ < 1 := by rw [one_mul]; exact hval
  rw [this] at hlt'
  exact lt_irrefl _ hlt'

section Interior

variable {P : Subring L} {u v : L} {n : ℕ} {U : ValuationSubring L}

/-- The value of a Laurent polynomial at a monomial point, in exponent form. -/
lemma valuation_laurent_pow_den (hU : U.comap (algebraMap K L) = O) (hϖ : Irreducible ϖ)
    {s : ℚ} (hs : IsLogValue U (algebraMap K L (ϖ : K)) u s)
    (htr : IsResidueTranscendental O U (u ^ s.den / algebraMap K L (ϖ : K) ^ s.num))
    {Q : K[X]} (hQ : Q ≠ 0) (k : ℕ) :
    U.valuation (aeval u Q / u ^ k) ^ s.den =
      U.valuation (algebraMap K L (ϖ : K)) ^ (gaussExp O ϖ s Q - s.num * k) := by
  obtain ⟨hwp0, -⟩ := valuation_uniformizer hU hϖ
  rw [map_div₀, div_pow, valuation_aeval_pow_den hU hϖ hs htr hQ, map_pow, ← pow_mul,
    mul_comm, pow_mul, hs, ← zpow_natCast, ← zpow_mul, ← zpow_sub₀ hwp0]

omit [IsDiscreteValuationRing O] in
/-- At an interior monomial point the generators `ϖ, u, v` have `U(x) ^ d ≤ U(ϖ)`. -/
lemma generator_bounds (huv : u * v = algebraMap K L (ϖ : K) ^ n)
    (hU : U.comap (algebraMap K L) = O) (hϖ : Irreducible ϖ)
    {s : ℚ} (hs0 : 0 < s) (hsn : s < n) (hs : IsLogValue U (algebraMap K L (ϖ : K)) u s) :
    U.valuation (algebraMap K L (ϖ : K)) ^ s.den ≤ U.valuation (algebraMap K L (ϖ : K)) ∧
    U.valuation u ^ s.den ≤ U.valuation (algebraMap K L (ϖ : K)) ∧
    U.valuation v ^ s.den ≤ U.valuation (algebraMap K L (ϖ : K)) := by
  obtain ⟨hwp0, hwp1⟩ := valuation_uniformizer hU hϖ
  set w := U.valuation (algebraMap K L (ϖ : K))
  have h0 : (0 : U.ValueGroup) < w := zero_lt_iff.mpr hwp0
  have hnum : 1 ≤ s.num := Rat.num_pos.mpr hs0
  have hnum' : s.num + 1 ≤ n * s.den := by
    have h1 : (s.num : ℚ) = s * s.den := s.mul_den_eq_num.symm
    have h2 : (s.num : ℚ) < n * s.den := by
      rw [h1]; exact mul_lt_mul_of_pos_right hsn (by exact_mod_cast s.den_pos)
    exact_mod_cast h2
  have hle : ∀ m : ℤ, 1 ≤ m → w ^ m ≤ w := fun m hm ↦ by
    simpa using (zpow_le_zpow_iff_right_of_lt_one₀ h0 hwp1).mpr hm
  refine ⟨pow_le_of_le_one zero_le hwp1.le s.den_nz, ?_, ?_⟩
  · unfold IsLogValue at hs
    rw [hs]; exact hle _ hnum
  · have hu0 : U.valuation u ^ s.den ≠ 0 := by
      unfold IsLogValue at hs; rw [hs]; exact zpow_ne_zero _ hwp0
    have hprod : U.valuation u ^ s.den * U.valuation v ^ s.den = w ^ ((n : ℤ) * s.den) := by
      rw [← mul_pow, ← map_mul, huv, map_pow, ← pow_mul, ← zpow_natCast]
      norm_cast
    have hv : U.valuation v ^ s.den = w ^ ((n : ℤ) * s.den - s.num) := by
      unfold IsLogValue at hs
      rw [zpow_sub₀ hwp0, ← hprod, ← hs]
      field_simp
    rw [hv]; exact hle _ (by linarith)

/-- Unpacking a monomial point of a node germ: it lies over `O`. -/
lemma NodeGerm.comap_eq (h : NodeGerm O ϖ P u v n) (hϖ : Irreducible ϖ) {s : ℚ}
    (hU : IsMonomialPt O (P : Set L) (algebraMap K L (ϖ : K)) u s U) :
    U.comap (algebraMap K L) = O :=
  comap_eq_of_lt_one hϖ (fun o ↦ hU.1 (h.algebraMap_mem o)) hU.2.1

/-- **Lower bound** from the polynomial relation: `U(f) ^ d ≥ U(ϖ) ^ B` at every monomial point
at `s`, with `B` independent of the point. -/
lemma NodeGerm.exists_lower_bound (h : NodeGerm O ϖ P u v n) (hϖ : Irreducible ϖ) (s : ℚ)
    {f : L} (hf : f ∈ P) (hf0 : f ≠ 0) :
    ∃ B : ℤ, ∀ U : ValuationSubring L,
      IsMonomialPt O (P : Set L) (algebraMap K L (ϖ : K)) u s U →
      U.valuation (algebraMap K L (ϖ : K)) ^ B ≤ U.valuation f ^ s.den := by
  classical
  obtain ⟨c₀, S, c, hc₀, hrel⟩ := h.alg f hf hf0
  set Emin : ℤ := -∑ k ∈ S, |gaussExp O ϖ s (c k)|
  refine ⟨gaussExp O ϖ s c₀ - Emin, fun U hU ↦ ?_⟩
  have hUO := h.comap_eq hϖ hU
  obtain ⟨hP, -, hs, htr⟩ := hU
  obtain ⟨hwp0, hwp1⟩ := valuation_uniformizer hUO hϖ
  set w := U.valuation (algebraMap K L (ϖ : K))
  have h0 : (0 : U.ValueGroup) < w := zero_lt_iff.mpr hwp0
  have hfle : U.valuation f ≤ 1 := (U.valuation_le_one_iff f).mpr (hP hf)
  have hterm : ∀ k ∈ S, U.valuation (aeval u (c k) * f ^ (k + 1)) ^ s.den ≤
      w ^ Emin * U.valuation f ^ s.den := by
    intro k hk
    by_cases hck : c k = 0
    · rw [hck, map_zero, zero_mul, map_zero, zero_pow s.den_nz]; exact zero_le
    rw [map_mul, mul_pow, valuation_aeval_pow_den hUO hϖ hs htr hck]
    have h1 : w ^ gaussExp O ϖ s (c k) ≤ w ^ Emin := by
      rw [zpow_le_zpow_iff_right_of_lt_one₀ h0 hwp1]
      have := Finset.single_le_sum (f := fun k ↦ |gaussExp O ϖ s (c k)|)
        (fun _ _ ↦ abs_nonneg _) hk
      have := neg_abs_le (gaussExp O ϖ s (c k))
      simp only [Emin]
      linarith
    have h2 : U.valuation (f ^ (k + 1)) ^ s.den ≤ U.valuation f ^ s.den := by
      refine pow_le_pow_left₀ zero_le ?_ _
      rw [map_pow]
      exact pow_le_of_le_one zero_le hfle (Nat.succ_ne_zero k)
    exact mul_le_mul' h1 h2
  have hc₀v := valuation_aeval_pow_den hUO hϖ hs htr hc₀
  have hS : S.Nonempty := by
    by_contra hS
    rw [Finset.not_nonempty_iff_eq_empty] at hS
    rw [hS, Finset.sum_empty] at hrel
    rw [hrel, map_zero, zero_pow s.den_nz] at hc₀v
    exact zpow_ne_zero _ hwp0 hc₀v.symm
  obtain ⟨k₁, hk₁, hmax⟩ := Finset.exists_max_image S
    (fun k ↦ U.valuation (aeval u (c k) * f ^ (k + 1))) hS
  have hle : U.valuation (aeval u c₀) ≤ U.valuation (aeval u (c k₁) * f ^ (k₁ + 1)) := by
    rw [hrel]; exact Valuation.map_sum_le _ hmax
  have key : w ^ gaussExp O ϖ s c₀ ≤ w ^ Emin * U.valuation f ^ s.den := by
    rw [← hc₀v]
    exact (pow_le_pow_left₀ zero_le hle _).trans (hterm k₁ hk₁)
  rw [zpow_sub₀ hwp0, div_le_iff₀ (zpow_pos h0 _), mul_comm]
  exact key

/-- **Normalised values on `P`**: for `0 < s < n` and `f ∈ P ∖ 0` there is an exponent `e`
with `U(f) ^ d = U(ϖ) ^ e` at **every** monomial point `U` at `s`. -/
lemma NodeGerm.exists_exponent (h : NodeGerm O ϖ P u v n) (hϖ : Irreducible ϖ) (hu : u ≠ 0)
    {s : ℚ} (hs0 : 0 < s) (hsn : s < n) {f : L} (hf : f ∈ P) (hf0 : f ≠ 0) :
    ∃ e : ℤ, ∀ U : ValuationSubring L,
      IsMonomialPt O (P : Set L) (algebraMap K L (ϖ : K)) u s U →
      U.valuation f ^ s.den = U.valuation (algebraMap K L (ϖ : K)) ^ e := by
  obtain ⟨B, hB⟩ := h.exists_lower_bound hϖ s hf hf0
  obtain ⟨a, ⟨Q, k, rfl⟩, hfa⟩ := h.exists_laurent_sub_mem' hu (B + 1).toNat f hf
  refine ⟨gaussExp O ϖ s Q - s.num * k, fun U hU ↦ ?_⟩
  have hUO := h.comap_eq hϖ hU
  have hBU := hB U hU
  obtain ⟨hP, -, hs, htr⟩ := hU
  obtain ⟨hwp0, hwp1⟩ := valuation_uniformizer hUO hϖ
  set w := U.valuation (algebraMap K L (ϖ : K))
  have h0 : (0 : U.ValueGroup) < w := zero_lt_iff.mpr hwp0
  obtain ⟨g1, g2, g3⟩ := generator_bounds h.mul_eq hUO hϖ hs0 hsn hs
  have hJ := valuation_pow_le_of_mem_nodeJ hP g1 g2 g3 _ _ hfa
  have hlt : U.valuation (f - aeval u Q / u ^ k) < U.valuation f := by
    rw [← pow_lt_pow_iff_left₀ zero_le zero_le s.den_nz]
    refine lt_of_le_of_lt hJ (lt_of_lt_of_le ?_ hBU)
    rw [← zpow_natCast, zpow_lt_zpow_iff_right_of_lt_one₀ h0 hwp1]
    omega
  have heq : U.valuation (aeval u Q / u ^ k) = U.valuation f := by
    have : aeval u Q / u ^ k = f + -(f - aeval u Q / u ^ k) := by ring
    rw [this, Valuation.map_add_eq_of_lt_left _ (by rwa [Valuation.map_neg])]
  by_cases hQ : Q = 0
  · rw [hQ, map_zero, zero_div, map_zero, eq_comm] at heq
    exact absurd ((map_eq_zero _).mp heq) hf0
  rw [← heq]
  exact valuation_laurent_pow_den hUO hϖ hs htr hQ k

/-- **Uniqueness of interior monomial points** (XL2): for `0 < s < n` there is at most one
monomial point of the node at `s`. -/
theorem NodeGerm.eq_of_isMonomialPt (h : NodeGerm O ϖ P u v n) (hϖ : Irreducible ϖ)
    (hu : u ≠ 0) {s : ℚ} (hs0 : 0 < s) (hsn : s < n) {U U' : ValuationSubring L}
    (hU : IsMonomialPt O (P : Set L) (algebraMap K L (ϖ : K)) u s U)
    (hU' : IsMonomialPt O (P : Set L) (algebraMap K L (ϖ : K)) u s U') : U = U' := by
  have key : ∀ V : ValuationSubring L,
      IsMonomialPt O (P : Set L) (algebraMap K L (ϖ : K)) u s V →
      ∀ g ∈ P, g ≠ 0 → ∀ hh ∈ P, hh ≠ 0 → ∀ eg eh : ℤ,
      V.valuation g ^ s.den = V.valuation (algebraMap K L (ϖ : K)) ^ eg →
      V.valuation hh ^ s.den = V.valuation (algebraMap K L (ϖ : K)) ^ eh →
      (g / hh ∈ V ↔ eh ≤ eg) := by
    intro V hV g hg hg0 r hr hr0 eg eh hge hhe
    obtain ⟨hwp0, hwp1⟩ := valuation_uniformizer (h.comap_eq hϖ hV) hϖ
    have h0 : (0 : V.ValueGroup) < V.valuation (algebraMap K L (ϖ : K)) := zero_lt_iff.mpr hwp0
    have hhv : V.valuation r ≠ 0 := by simpa using hr0
    rw [← V.valuation_le_one_iff, map_div₀, div_le_one₀ (zero_lt_iff.mpr hhv),
      ← pow_le_pow_iff_left₀ zero_le zero_le s.den_nz, hge, hhe,
      zpow_le_zpow_iff_right_of_lt_one₀ h0 hwp1]
  ext f
  obtain ⟨g, hg, hh', hh, hh0, rfl⟩ := h.frac f
  by_cases hg0 : g = 0
  · simp [hg0]
  obtain ⟨eg, heg⟩ := h.exists_exponent hϖ hu hs0 hsn hg hg0
  obtain ⟨eh, heh⟩ := h.exists_exponent hϖ hu hs0 hsn hh hh0
  rw [key U hU g hg hg0 hh' hh hh0 eg eh (heg U hU) (heh U hU),
    key U' hU' g hg hg0 hh' hh hh0 eg eh (heg U' hU') (heh U' hU')]

end Interior

end SemistableReduction
