/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.MonomialUnique

/-!
# Existence of interior monomial points (Blueprint §9.7, XL2)

Let `P ⊆ L` be the germs of a node over a discrete valuation subring `O ⊆ K` (`NodeGerm`), local
with maximal ideal `(ϖ, u, v)`, and **flat** over a ring `A` mapping to the node coordinates
(the node `O[u, v] ⧸ (u v - ϖ ^ n)`; the germs are étale over it, XL1). Then for every
`0 < s < n` there is a monomial point of the node at `s` (`exists_isMonomialPt`).

Proof (no completions, no Hensel):
1. `exists_valuationSubring_of_isPrime`: a prime `𝔐` of a subring `R ⊆ L` is the trace of the
   maximal ideal of a valuation subring of `L` dominating `R_𝔐` (Chevalley, Mathlib's
   `LocalSubring.exists_le_valuationSubring`).
2. `exists_gauss`: for `g` transcendental over `K` there is a valuation subring `U₀ ⊆ L` over `O`
   in which `g` has transcendental residue (apply 1 to `O[g]` and the prime `𝔪_O[g]`). For
   `g = u ^ d / ϖ ^ m` this is a monomial point of the *u-line*, but in general not centred at
   `P`.
3. `one_notMem`: let `O_w` be the elements of `U₀` that are fractions of elements of `A`. By the
   equational criterion for flatness, `1` is not a sum `Σ pᵢ oᵢ` with `pᵢ ∈ P`, `oᵢ ∈ O_w` and in
   each term `pᵢ ∈ 𝔪_P` or `oᵢ ∈ 𝔪_{U₀}`: clearing denominators gives a relation in `P` with
   coefficients in `A`, it is trivial, and evaluating with the residue maps
   `P → κ(O) → κ(U₀)` and `O_w → κ(U₀)` gives `1 = 0`.
4. Hence the ideal generated by `𝔪_P` and `𝔪_{U₀} ∩ O_w` in `P[O_w]` is proper; a valuation
   subring `U` dominating it (step 1) contains `P`, has `U(ϖ) < 1`, makes `g` and `Q(g)`
   (`Q̄ ≠ 0`) units: `U` is a monomial point at `s`.
-/

open Polynomial

namespace SemistableReduction

variable {L : Type*} [Field L]

/-- **Valuation subrings dominating a localization** (Chevalley): for a subring `R ⊆ L` and a
prime `𝔐` of `R` there is a valuation subring `U ⊇ R` of `L` with `𝔐 = R ∩ 𝔪_U`. -/
theorem exists_valuationSubring_of_isPrime (R : Subring L) (𝔐 : Ideal R) [𝔐.IsPrime] :
    ∃ U : ValuationSubring L, R ≤ U.toSubring ∧
      (∀ x : R, x ∈ 𝔐 → U.valuation (x : L) < 1) ∧
      (∀ x : R, x ∉ 𝔐 → U.valuation (x : L) = 1) := by
  obtain ⟨U, hU⟩ := (LocalSubring.ofPrime R 𝔐).exists_le_valuationSubring
  obtain ⟨hle, hloc⟩ := hU
  have hR : R ≤ U.toSubring := (LocalSubring.le_ofPrime R 𝔐).trans hle
  refine ⟨U, hR, fun x hx ↦ ?_, fun x hx ↦ ?_⟩
  · -- `x` is a nonunit of the localization, hence of `U`
    set y : (LocalSubring.ofPrime R 𝔐).toSubring := algebraMap R _ x
    have hy : y ∈ IsLocalRing.maximalIdeal _ := by
      rw [IsLocalization.AtPrime.to_map_mem_maximal_iff _ 𝔐]; exact hx
    have hy' : Subring.inclusion hle y ∈ IsLocalRing.maximalIdeal U :=
      fun hu ↦ hy (hloc.map_nonunit _ hu)
    exact (ValuationSubring.valuation_lt_one_iff U _).mp hy'
  · set y : (LocalSubring.ofPrime R 𝔐).toSubring := algebraMap R _ x
    have hy : IsUnit y := by
      by_contra h
      exact hx ((IsLocalization.AtPrime.to_map_mem_maximal_iff _ 𝔐 x).mp h)
    exact (ValuationSubring.valuation_eq_one_iff U _).mp (hy.map (Subring.inclusion hle))

variable {K : Type*} [Field K] [Algebra K L]

/-- **A Gauss point of radius one in a transcendental `g`**: a valuation subring `U₀ ⊆ L`
containing `O` with `U₀(𝔪_O) < 1` in which `g` has transcendental residue over `κ(O)`. -/
theorem exists_gauss (O : ValuationSubring K) {g : L} (hg : Transcendental K g) :
    ∃ U₀ : ValuationSubring L, (∀ o : O, algebraMap K L (o : K) ∈ U₀) ∧
      (∀ o : O, o ∈ IsLocalRing.maximalIdeal O → U₀.valuation (algebraMap K L (o : K)) < 1) ∧
      IsResidueTranscendental O U₀ g := by
  classical
  set φ : O[X] →+* L := (aeval g).toRingHom.comp (mapRingHom (algebraMap O K)) with hφ
  have hφinj : Function.Injective φ := by
    refine (transcendental_iff_injective.mp hg).comp ?_
    exact map_injective _ (FaithfulSMul.algebraMap_injective O K)
  set R : Subring L := φ.range
  let e : O[X] ≃+* R := RingEquiv.ofBijective φ.rangeRestrict
    ⟨fun a b h ↦ hφinj (congrArg Subtype.val h), φ.rangeRestrict_surjective⟩
  set I : Ideal O[X] := Ideal.map C (IsLocalRing.maximalIdeal O)
  set 𝔐 : Ideal R := I.comap e.symm.toRingHom
  obtain ⟨U₀, hR, hlt, hone⟩ := exists_valuationSubring_of_isPrime R 𝔐
  have he : ∀ Q : O[X], ((e Q : R) : L) = aeval g (Q.map (algebraMap O K)) := fun Q ↦ rfl
  have hmem : ∀ Q : O[X], e Q ∈ 𝔐 ↔ Q ∈ I := fun Q ↦ by
    simp [𝔐, Ideal.mem_comap]
  refine ⟨U₀, fun o ↦ ?_, fun o ho ↦ ?_, ⟨?_, fun Q hQ ↦ ?_⟩⟩
  · have := hR (e (C o)).2
    simpa [he] using this
  · have := hlt (e (C o)) ((hmem _).mpr (Ideal.mem_map_of_mem _ ho))
    simpa [he] using this
  · have := hR (e X).2
    simpa [he] using this
  · have := hone (e Q) fun h ↦ hQ ?_
    · simpa [he] using this
    rw [hmem, Ideal.mem_map_C_iff] at h
    ext n
    simp only [coeff_map, coeff_zero]
    exact (IsLocalRing.residue_eq_zero_iff _).mpr (h n)

/-- **Properness from flatness** (step 3): let `P ⊆ L` be a local subring, flat over `A`, and
`χ : P → κ(U₀)` a ring map killing `𝔪_P` which on `A` is the residue map of `U₀ ⊇ A`. Then `1` is
not a sum `Σ pᵢ oᵢ` with `pᵢ ∈ P`, `oᵢ ∈ U₀` fractions of elements of `A`, and in every term
`pᵢ ∈ 𝔪_P` or `oᵢ ∈ 𝔪_{U₀}`. -/
theorem sum_ne_one_of_flat (P : Subring L) [IsLocalRing P] {A : Type*} [CommRing A]
    [Algebra A P] [Module.Flat A P] (U₀ : ValuationSubring L)
    (χ : P →+* IsLocalRing.ResidueField U₀) (hχ : ∀ p ∈ IsLocalRing.maximalIdeal P, χ p = 0)
    (hAU : ∀ b : A, ((algebraMap A P b : P) : L) ∈ U₀)
    (hχA : ∀ b : A, χ (algebraMap A P b) = IsLocalRing.residue U₀ ⟨_, hAU b⟩)
    {ι' : Type*} [Fintype ι'] (p : ι' → P) (o : ι' → L) (ho : ∀ i, o i ∈ U₀)
    (hfrac : ∀ i, ∃ a' a : A, ((algebraMap A P a : P) : L) ≠ 0 ∧
      o i = (algebraMap A P a' : L) / (algebraMap A P a : L))
    (hbad : ∀ i, p i ∈ IsLocalRing.maximalIdeal P ∨ U₀.valuation (o i) < 1) :
    ∑ i, (p i : L) * o i ≠ 1 := by
  classical
  intro hsum
  set ι : A →+* L := P.subtype.comp (algebraMap A P) with hι
  have hιP : ∀ b : A, ((algebraMap A P b : P) : L) = ι b := fun _ ↦ rfl
  choose a' a ha0 hoa using hfrac
  simp only [hιP] at ha0 hoa hAU
  set c : A := ∏ i, a i
  have hc0 : ι c ≠ 0 := by
    rw [map_prod]; exact Finset.prod_ne_zero_iff.mpr fun i _ ↦ ha0 i
  set a'' : ι' → A := fun i ↦ a' i * ∏ j ∈ Finset.univ.erase i, a j
  have hoi : ∀ i, o i * ι c = ι (a'' i) := fun i ↦ by
    have hprod : ι c = ι (a i) * ∏ j ∈ Finset.univ.erase i, ι (a j) := by
      simp only [c, map_prod]
      exact (Finset.mul_prod_erase _ _ (Finset.mem_univ i)).symm
    rw [hprod, hoa i]
    simp only [a'', map_mul, map_prod]
    have : ι (a i) ≠ 0 := ha0 i
    field_simp
  -- the relation in `P`
  let f : Option (ι') → A := fun i ↦ i.elim c a''
  let x : Option (ι') → P := fun i ↦ i.elim 1 (fun i ↦ -p i)
  have hrel : ∑ i, f i • x i = 0 := by
    apply Subtype.ext
    have hcoe : ((∑ i, f i • x i : P) : L) = ∑ i, ι (f i) * (x i : L) := by
      simp only [AddSubmonoidClass.coe_finsetSum, Algebra.smul_def, MulMemClass.coe_mul, hιP]
    rw [hcoe, Fintype.sum_option]
    simp only [Option.elim, f, x, OneMemClass.coe_one, mul_one, NegMemClass.coe_neg, mul_neg,
      Finset.sum_neg_distrib, ZeroMemClass.coe_zero]
    have : ∑ i, (p i : L) * o i * ι c = ι c := by rw [← Finset.sum_mul, hsum, one_mul]
    rw [← this, add_neg_eq_zero]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [mul_assoc, hoi i, mul_comm]
  have htriv : Module.IsTrivialRelation f x :=
    Module.Flat.isTrivialRelation_of_sum_smul_eq_zero (R := A) (M := P) (f := f) (x := x) hrel
  obtain ⟨m, b, y, hx, hb⟩ := htriv
  -- the residues of the fractions
  have hfo : ∀ i : ι', ι (f (some i)) / ι c = o i := fun i ↦ by
    simp only [f, Option.elim]; rw [← hoi i]; field_simp
  have hF : ∀ i, (ι (f i) / ι c) ∈ U₀ := fun i ↦ by
    cases i with
    | none => simp only [f, Option.elim, div_self hc0]; exact U₀.one_mem
    | some i => rw [hfo i]; exact ho i
  let F : Option (ι') → U₀ := fun i ↦ ⟨_, hF i⟩
  let B : A → U₀ := fun b ↦ ⟨_, hAU b⟩
  have hBF : ∀ j, ∑ i, B (b i j) * F i = 0 := fun j ↦ by
    apply Subtype.ext
    have h0 : ∑ i, ι (f i * b i j) = 0 := by rw [← map_sum, hb j, map_zero]
    simp only [AddSubmonoidClass.coe_finsetSum, MulMemClass.coe_mul, ZeroMemClass.coe_zero, B, F]
    calc ∑ i, ι (b i j) * (ι (f i) / ι c) = (∑ i, ι (f i * b i j)) / ι c := by
          rw [Finset.sum_div]
          refine Finset.sum_congr rfl fun i _ ↦ ?_
          rw [map_mul]; ring
      _ = 0 := by rw [h0, zero_div]
  have hres : ∀ b' : A, χ (algebraMap A P b') = IsLocalRing.residue U₀ (B b') := fun b' ↦ by
    rw [hχA]; rfl
  set Λ := ∑ i, χ (x i) * IsLocalRing.residue U₀ (F i)
  have h1 : Λ = 1 := by
    simp only [Λ, Fintype.sum_option]
    have hF1 : F none = 1 := Subtype.ext (by simp [F, f, div_self hc0])
    rw [hF1, map_one, mul_one]
    simp only [x, Option.elim, map_one, add_eq_left]
    refine Finset.sum_eq_zero fun i _ ↦ ?_
    rw [map_neg, neg_mul, neg_eq_zero]
    rcases hbad i with h | h
    · rw [hχ _ h, zero_mul]
    · have hm : F (some i) ∈ IsLocalRing.maximalIdeal U₀ := by
        rw [ValuationSubring.valuation_lt_one_iff]
        change U₀.valuation (ι (f (some i)) / ι c) < 1
        rw [hfo i]; exact h
      rw [(IsLocalRing.residue_eq_zero_iff _).mpr hm, mul_zero]
  have h2 : Λ = 0 := by
    have hχx : ∀ i, χ (x i) =
        ∑ j, IsLocalRing.residue U₀ (B (b i j)) * χ (y j) := fun i ↦ by
      rw [hx i, map_sum]
      refine Finset.sum_congr rfl fun j _ ↦ ?_
      rw [Algebra.smul_def, map_mul, hres]
    simp only [Λ, hχx, Finset.sum_mul]
    rw [Finset.sum_comm]
    refine Finset.sum_eq_zero fun j _ ↦ ?_
    calc ∑ i, IsLocalRing.residue U₀ (B (b i j)) * χ (y j) * IsLocalRing.residue U₀ (F i)
        = χ (y j) * IsLocalRing.residue U₀ (∑ i, B (b i j) * F i) := by
          rw [map_sum, Finset.mul_sum]
          refine Finset.sum_congr rfl fun i _ ↦ ?_
          rw [map_mul]; ring
      _ = 0 := by rw [hBF j, map_zero, mul_zero]
  exact one_ne_zero (h1.symm.trans h2)

section Span

variable (P Ow : Subring L) (𝔪P 𝔪w : Set L)

/-- Finite sums `Σ pᵢ oᵢ` with `pᵢ ∈ P`, `oᵢ ∈ Ow`. -/
def IsPOSum (x : L) : Prop :=
  ∃ (ι : Type) (_ : Fintype ι) (p o : ι → L), (∀ i, p i ∈ P) ∧ (∀ i, o i ∈ Ow) ∧
    x = ∑ i, p i * o i

/-- Finite sums `Σ pᵢ oᵢ` in which every term is *bad*: `pᵢ ∈ 𝔪P` or `oᵢ ∈ 𝔪w`. -/
def IsBadSum (x : L) : Prop :=
  ∃ (ι : Type) (_ : Fintype ι) (p o : ι → L), (∀ i, p i ∈ P) ∧ (∀ i, o i ∈ Ow) ∧
    (∀ i, p i ∈ 𝔪P ∨ o i ∈ 𝔪w) ∧ x = ∑ i, p i * o i

variable {P Ow}

lemma isPOSum_of_mem_closure {x : L} (hx : x ∈ Subring.closure ((P : Set L) ∪ Ow)) :
    IsPOSum P Ow x := by
  induction hx using Subring.closure_induction with
  | mem x hx =>
    rcases hx with hx | hx
    · exact ⟨Unit, inferInstance, fun _ ↦ x, fun _ ↦ 1, fun _ ↦ hx, fun _ ↦ Ow.one_mem, by simp⟩
    · exact ⟨Unit, inferInstance, fun _ ↦ 1, fun _ ↦ x, fun _ ↦ P.one_mem, fun _ ↦ hx, by simp⟩
  | zero => exact ⟨Empty, inferInstance, Empty.elim, Empty.elim, (·.elim), (·.elim), by simp⟩
  | one => exact ⟨Unit, inferInstance, fun _ ↦ 1, fun _ ↦ 1, fun _ ↦ P.one_mem,
      fun _ ↦ Ow.one_mem, by simp⟩
  | add x y _ _ hx hy =>
    obtain ⟨ι, _, p, o, hp, ho, rfl⟩ := hx
    obtain ⟨ι', _, p', o', hp', ho', rfl⟩ := hy
    refine ⟨ι ⊕ ι', inferInstance, Sum.elim p p', Sum.elim o o', ?_, ?_, ?_⟩
    · rintro (i | i) <;> simp [hp, hp']
    · rintro (i | i) <;> simp [ho, ho']
    · simp [Fintype.sum_sum_type]
  | neg x _ hx =>
    obtain ⟨ι, _, p, o, hp, ho, rfl⟩ := hx
    exact ⟨ι, inferInstance, fun i ↦ -p i, o, fun i ↦ P.neg_mem (hp i), ho, by
      simp [Finset.sum_neg_distrib]⟩
  | mul x y _ _ hx hy =>
    obtain ⟨ι, _, p, o, hp, ho, rfl⟩ := hx
    obtain ⟨ι', _, p', o', hp', ho', rfl⟩ := hy
    refine ⟨ι × ι', inferInstance, fun ij ↦ p ij.1 * p' ij.2, fun ij ↦ o ij.1 * o' ij.2,
      fun ij ↦ P.mul_mem (hp _) (hp' _), fun ij ↦ Ow.mul_mem (ho _) (ho' _), ?_⟩
    rw [Finset.sum_mul_sum, ← Finset.univ_product_univ, Finset.sum_product]
    refine Finset.sum_congr rfl fun i _ ↦ Finset.sum_congr rfl fun j _ ↦ ?_
    ring

/-- **The ideal generated by the bad elements is proper** if `1` is not a bad sum. -/
theorem span_ne_top_of_forall_isBadSum (h𝔪P : 𝔪P ⊆ P) (h𝔪w : 𝔪w ⊆ Ow)
    (hPm : ∀ p ∈ P, ∀ m ∈ 𝔪P, p * m ∈ 𝔪P) (hOm : ∀ o ∈ Ow, ∀ m ∈ 𝔪w, o * m ∈ 𝔪w)
    (H : ¬ IsBadSum P Ow 𝔪P 𝔪w 1) :
    Ideal.span {x : Subring.closure ((P : Set L) ∪ Ow) | (x : L) ∈ 𝔪P ∪ 𝔪w} ≠ ⊤ := by
  intro htop
  apply H
  have h1 := (Ideal.eq_top_iff_one _).mp htop
  have key : ∀ x ∈ Ideal.span {x : Subring.closure ((P : Set L) ∪ Ow) | (x : L) ∈ 𝔪P ∪ 𝔪w},
      IsBadSum P Ow 𝔪P 𝔪w (x : L) := by
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
      rcases hx with hx | hx
      · exact ⟨Unit, inferInstance, fun _ ↦ x, fun _ ↦ 1, fun _ ↦ h𝔪P hx,
          fun _ ↦ Ow.one_mem, fun _ ↦ Or.inl hx, by simp⟩
      · exact ⟨Unit, inferInstance, fun _ ↦ 1, fun _ ↦ x, fun _ ↦ P.one_mem,
          fun _ ↦ h𝔪w hx, fun _ ↦ Or.inr hx, by simp⟩
    | zero => exact ⟨Empty, inferInstance, Empty.elim, Empty.elim, (·.elim), (·.elim),
        (·.elim), by simp⟩
    | add x y _ _ hx hy =>
      obtain ⟨ι, _, p, o, hp, ho, hb, hxe⟩ := hx
      obtain ⟨ι', _, p', o', hp', ho', hb', hye⟩ := hy
      refine ⟨ι ⊕ ι', inferInstance, Sum.elim p p', Sum.elim o o', ?_, ?_, ?_, ?_⟩
      · rintro (i | i) <;> simp [hp, hp']
      · rintro (i | i) <;> simp [ho, ho']
      · rintro (i | i) <;> simp [hb, hb']
      · simp [Fintype.sum_sum_type, hxe, hye]
    | smul r x _ hx =>
      obtain ⟨ι, _, p, o, hp, ho, hb, hxe⟩ := hx
      obtain ⟨ι', _, p', o', hp', ho', hre⟩ := isPOSum_of_mem_closure r.2
      refine ⟨ι' × ι, inferInstance, fun ij ↦ p' ij.1 * p ij.2, fun ij ↦ o' ij.1 * o ij.2,
        fun ij ↦ P.mul_mem (hp' _) (hp _), fun ij ↦ Ow.mul_mem (ho' _) (ho _), ?_, ?_⟩
      · rintro ⟨i, j⟩
        rcases hb j with h | h
        · exact Or.inl (hPm _ (hp' i) _ h)
        · exact Or.inr (hOm _ (ho' i) _ h)
      · rw [smul_eq_mul, Subring.coe_mul, hre, hxe, Finset.sum_mul_sum,
          ← Finset.univ_product_univ, Finset.sum_product]
        refine Finset.sum_congr rfl fun i _ ↦ Finset.sum_congr rfl fun j _ ↦ ?_
        ring
  simpa using key 1 h1

end Span

section Exists

variable {O : ValuationSubring K} [IsDiscreteValuationRing O] {ϖ : O}

omit [IsDiscreteValuationRing O] in
/-- Polynomials in `u, v` over `O` are `o + ϖ a + u b + v c`. -/
lemma exists_decomp_of_mem_closure {u v z : L}
    (hz : z ∈ Subring.closure (Set.range (fun o : O ↦ algebraMap K L (o : K)) ∪ {u, v})) :
    ∃ o : O, ∃ a ∈ Subring.closure (Set.range (fun o : O ↦ algebraMap K L (o : K)) ∪ {u, v}),
      ∃ b ∈ Subring.closure (Set.range (fun o : O ↦ algebraMap K L (o : K)) ∪ {u, v}),
      ∃ c ∈ Subring.closure (Set.range (fun o : O ↦ algebraMap K L (o : K)) ∪ {u, v}),
      z = algebraMap K L (o : K) + algebraMap K L (ϖ : K) * a + u * b + v * c := by
  set S := Subring.closure (Set.range (fun o : O ↦ algebraMap K L (o : K)) ∪ {u, v})
  have hO : ∀ o : O, algebraMap K L (o : K) ∈ S := fun o ↦ Subring.subset_closure (Or.inl ⟨o, rfl⟩)
  have hu : u ∈ S := Subring.subset_closure (Or.inr (Or.inl rfl))
  have hv : v ∈ S := Subring.subset_closure (Or.inr (Or.inr rfl))
  induction hz using Subring.closure_induction with
  | mem x hx =>
    rcases hx with ⟨o, rfl⟩ | rfl | rfl
    · exact ⟨o, 0, S.zero_mem, 0, S.zero_mem, 0, S.zero_mem, by ring⟩
    · exact ⟨0, 0, S.zero_mem, 1, S.one_mem, 0, S.zero_mem, by simp⟩
    · exact ⟨0, 0, S.zero_mem, 0, S.zero_mem, 1, S.one_mem, by simp⟩
  | zero => exact ⟨0, 0, S.zero_mem, 0, S.zero_mem, 0, S.zero_mem, by simp⟩
  | one => exact ⟨1, 0, S.zero_mem, 0, S.zero_mem, 0, S.zero_mem, by simp⟩
  | add x y _ _ hx hy =>
    obtain ⟨o, a, ha, b, hb, c, hc, rfl⟩ := hx
    obtain ⟨o', a', ha', b', hb', c', hc', rfl⟩ := hy
    exact ⟨o + o', a + a', S.add_mem ha ha', b + b', S.add_mem hb hb', c + c', S.add_mem hc hc',
      by push_cast; ring⟩
  | neg x _ hx =>
    obtain ⟨o, a, ha, b, hb, c, hc, rfl⟩ := hx
    exact ⟨-o, -a, S.neg_mem ha, -b, S.neg_mem hb, -c, S.neg_mem hc, by push_cast; ring⟩
  | mul x y hxS hyS hx hy =>
    obtain ⟨o, a, ha, b, hb, c, hc, rfl⟩ := hx
    obtain ⟨o', a', ha', b', hb', c', hc', rfl⟩ := hy
    refine ⟨o * o', algebraMap K L (o : K) * a' + a * (algebraMap K L (o' : K) +
        algebraMap K L (ϖ : K) * a' + u * b' + v * c'), ?_,
      algebraMap K L (o : K) * b' + b * (algebraMap K L (o' : K) +
        algebraMap K L (ϖ : K) * a' + u * b' + v * c'), ?_,
      algebraMap K L (o : K) * c' + c * (algebraMap K L (o' : K) +
        algebraMap K L (ϖ : K) * a' + u * b' + v * c'), ?_, by push_cast; ring⟩ <;>
    exact S.add_mem (S.mul_mem (hO _) ‹_›) (S.mul_mem ‹_› hyS)

/-- **Existence of interior monomial points** (XL2): let `P` be the germs of a node
(`NodeGerm`), a local ring in whose maximal ideal `ϖ, u, v` lie, with `u` transcendental over
`K`, and flat over a ring `A` whose image consists of polynomials in `u, v` over `O` and
contains `O` and `u`. Then for every `0 < s < n` there is a monomial point of the node at `s`. -/
theorem NodeGerm.exists_isMonomialPt {P : Subring L} {u v : L} {n : ℕ}
    (h : NodeGerm O ϖ P u v n) (hϖ : Irreducible ϖ) (hu : Transcendental K u) [IsLocalRing P]
    (hϖm : (⟨_, h.algebraMap_mem ϖ⟩ : P) ∈ IsLocalRing.maximalIdeal P)
    (hum : (⟨u, h.u_mem⟩ : P) ∈ IsLocalRing.maximalIdeal P)
    (hvm : (⟨v, h.v_mem⟩ : P) ∈ IsLocalRing.maximalIdeal P)
    {A : Type*} [CommRing A] [Algebra A P] [Module.Flat A P]
    (hAimg : ∀ b : A, ((algebraMap A P b : P) : L) ∈
      Subring.closure (Set.range (fun o : O ↦ algebraMap K L (o : K)) ∪ {u, v}))
    (hAO : ∀ o : O, ∃ b : A, ((algebraMap A P b : P) : L) = algebraMap K L (o : K))
    (hAu : ∃ b : A, ((algebraMap A P b : P) : L) = u)
    {s : ℚ} (hs0 : 0 < s) (hsn : s < n) :
    ∃ U : ValuationSubring L, IsMonomialPt O (P : Set L) (algebraMap K L (ϖ : K)) u s U := by
  classical
  set p := algebraMap K L (ϖ : K) with hp
  have hϖ0 : (ϖ : K) ≠ 0 := by exact_mod_cast hϖ.ne_zero
  have hp0 : p ≠ 0 := by simpa [p] using hϖ0
  set g := u ^ s.den / p ^ s.num with hg
  have hgu : u ^ s.den = g * p ^ s.num := by
    rw [hg, div_mul_cancel₀ _ (zpow_ne_zero _ hp0)]
  -- step 2: a Gauss point of radius one in `g`
  have hgtr : Transcendental K g := by
    intro halg
    apply hu
    have h' : IsAlgebraic K ((ϖ : K) ^ s.num • g) := halg.smul _
    have : (ϖ : K) ^ s.num • g = u ^ s.den := by
      rw [Algebra.smul_def, map_zpow₀, hgu, mul_comm]
    rw [this] at h'
    exact h'.of_pow s.den_pos
  obtain ⟨U₀, hO₀, hlt₀, htr₀⟩ := exists_gauss O hgtr
  have hϖmax : ϖ ∈ IsLocalRing.maximalIdeal O :=
    (IsLocalRing.mem_maximalIdeal _).mpr hϖ.not_isUnit
  have hU₀O : U₀.comap (algebraMap K L) = O := comap_eq_of_lt_one hϖ hO₀ (hlt₀ ϖ hϖmax)
  have hg1 : U₀.valuation g = 1 := by
    have := htr₀.2 X (by simp)
    simpa using this
  have hlog₀ : IsLogValue U₀ p u s := by
    unfold IsLogValue
    rw [← map_pow, hgu, map_mul, hg1, one_mul, map_zpow₀]
  obtain ⟨g1, g2, g3⟩ := generator_bounds h.mul_eq hU₀O hϖ hs0 hsn hlog₀
  have hwp1 : U₀.valuation p < 1 := (valuation_uniformizer hU₀O hϖ).2
  have hlt1 : ∀ x, U₀.valuation x ^ s.den ≤ U₀.valuation p → U₀.valuation x < 1 := by
    intro x hx
    by_contra hge
    push Not at hge
    exact absurd ((one_le_pow₀ hge).trans hx) (not_le.mpr hwp1)
  have hu1 := hlt1 u g2
  have hv1 := hlt1 v g3
  -- the polynomials in `u, v` lie in `U₀` and in `P`
  set S := Subring.closure (Set.range (fun o : O ↦ algebraMap K L (o : K)) ∪ {u, v})
  have hSU₀ : ∀ x ∈ S, x ∈ U₀ := by
    intro x hx
    refine (Subring.closure_le (t := U₀.toSubring)).mpr ?_ hx
    rintro x (⟨o, rfl⟩ | rfl | rfl)
    · exact hO₀ o
    · exact (U₀.valuation_le_one_iff _).mp hu1.le
    · exact (U₀.valuation_le_one_iff _).mp hv1.le
  have hSP : ∀ x ∈ S, x ∈ P := by
    intro x hx
    refine (Subring.closure_le (t := P)).mpr ?_ hx
    rintro x (⟨o, rfl⟩ | rfl | rfl)
    · exact h.algebraMap_mem o
    · exact h.u_mem
    · exact h.v_mem
  -- step 3: the residue map `χ : P → κ(O) → κ(U₀)`
  have hcomb : ∀ a b c : P, (⟨p, h.algebraMap_mem ϖ⟩ : P) * a + ⟨u, h.u_mem⟩ * b +
      ⟨v, h.v_mem⟩ * c ∈ IsLocalRing.maximalIdeal P := fun a b c ↦
    Ideal.add_mem _ (Ideal.add_mem _ (Ideal.mul_mem_right _ _ hϖm)
      (Ideal.mul_mem_right _ _ hum)) (Ideal.mul_mem_right _ _ hvm)
  let rP : O →+* P := ((algebraMap K L).comp O.subtype).codRestrict P
    (fun o ↦ h.algebraMap_mem o)
  haveI : IsLocalHom rP := ⟨fun o ho ↦ by
    by_contra hno
    have hmem : o ∈ IsLocalRing.maximalIdeal O := hno
    rw [hϖ.maximalIdeal_eq, Ideal.mem_span_singleton'] at hmem
    obtain ⟨o', rfl⟩ := hmem
    have : rP (o' * ϖ) ∈ IsLocalRing.maximalIdeal P := by
      rw [map_mul]; exact Ideal.mul_mem_left _ _ hϖm
    exact this ho⟩
  let eP := IsLocalRing.ResidueField.map rP
  have heP : Function.Bijective eP := by
    refine ⟨eP.injective, fun z ↦ ?_⟩
    obtain ⟨x, rfl⟩ := IsLocalRing.residue_surjective z
    obtain ⟨o, a, ha, b, hb, c, hc, hx⟩ := h.gen x x.2
    refine ⟨IsLocalRing.residue O o, ?_⟩
    rw [IsLocalRing.ResidueField.map_residue]
    refine (Ideal.Quotient.eq).mpr ?_
    have : rP o - x = -((⟨p, h.algebraMap_mem ϖ⟩ : P) * ⟨a, ha⟩ + ⟨u, h.u_mem⟩ * ⟨b, hb⟩ +
        ⟨v, h.v_mem⟩ * ⟨c, hc⟩) := by
      apply Subtype.ext
      simp only [AddSubgroupClass.coe_sub, NegMemClass.coe_neg, AddMemClass.coe_add,
        MulMemClass.coe_mul, hx]
      simp [rP, p]
      ring
    rw [this]
    exact neg_mem (hcomb _ _ _)
  let e := RingEquiv.ofBijective eP heP
  let rU : O →+* U₀ := ((algebraMap K L).comp O.subtype).codRestrict U₀.toSubring
    (fun o ↦ hO₀ o)
  haveI : IsLocalHom rU := ⟨fun o ho ↦ by
    have h1 : (U₀.valuation (rU o : L)) = 1 := (ValuationSubring.valuation_eq_one_iff U₀ _).mp ho
    obtain ⟨-, -, hinv⟩ := (valuation_eq_one_iff_mem_and_inv_mem U₀).mp h1
    change (algebraMap K L (o : K))⁻¹ ∈ U₀ at hinv
    rw [← map_inv₀, ← ValuationSubring.mem_comap, hU₀O] at hinv
    have ho0 : (o : K) ≠ 0 := by
      intro h0
      have : (rU o : L) = 0 := by simp [rU, h0]
      rw [this, map_zero] at h1
      exact zero_ne_one h1
    exact IsUnit.of_mul_eq_one (⟨_, hinv⟩ : O) (Subtype.ext (by simp [ho0]))⟩
  let χ : P →+* IsLocalRing.ResidueField U₀ :=
    (IsLocalRing.ResidueField.map rU).comp (e.symm.toRingHom.comp (IsLocalRing.residue P))
  have hχ : ∀ x ∈ IsLocalRing.maximalIdeal P, χ x = 0 := fun x hx ↦ by
    simp [χ, (IsLocalRing.residue_eq_zero_iff x).mpr hx]
  have hχO : ∀ o : O, χ (rP o) = IsLocalRing.residue U₀ (rU o) := fun o ↦ by
    have : e.symm (IsLocalRing.residue P (rP o)) = IsLocalRing.residue O o := by
      rw [RingEquiv.symm_apply_eq]
      change IsLocalRing.residue P (rP o) = eP (IsLocalRing.residue O o)
      rw [IsLocalRing.ResidueField.map_residue]
    simp only [χ, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom, this,
      IsLocalRing.ResidueField.map_residue]
  have hAU : ∀ b : A, ((algebraMap A P b : P) : L) ∈ U₀ := fun b ↦ hSU₀ _ (hAimg b)
  have hχA : ∀ b : A, χ (algebraMap A P b) = IsLocalRing.residue U₀ ⟨_, hAU b⟩ := by
    intro b
    obtain ⟨o, a, ha, b', hb', c, hc, hdec⟩ := exists_decomp_of_mem_closure (ϖ := ϖ) (hAimg b)
    have hP : algebraMap A P b = rP o + ((⟨p, h.algebraMap_mem ϖ⟩ : P) * ⟨a, hSP a ha⟩ +
        ⟨u, h.u_mem⟩ * ⟨b', hSP b' hb'⟩ + ⟨v, h.v_mem⟩ * ⟨c, hSP c hc⟩) := by
      apply Subtype.ext
      simp only [AddMemClass.coe_add, MulMemClass.coe_mul, hdec]
      simp [rP, p]
      ring
    have hU : (⟨_, hAU b⟩ : U₀) = rU o + ((⟨p, hO₀ ϖ⟩ : U₀) * ⟨a, hSU₀ a ha⟩ +
        ⟨u, (U₀.valuation_le_one_iff _).mp hu1.le⟩ * ⟨b', hSU₀ b' hb'⟩ +
        ⟨v, (U₀.valuation_le_one_iff _).mp hv1.le⟩ * ⟨c, hSU₀ c hc⟩) := by
      apply Subtype.ext
      simp only [AddMemClass.coe_add, MulMemClass.coe_mul]
      rw [hdec]
      simp [rU, p]
      ring
    have hm : ((⟨p, hO₀ ϖ⟩ : U₀) * ⟨a, hSU₀ a ha⟩ +
        ⟨u, (U₀.valuation_le_one_iff _).mp hu1.le⟩ * ⟨b', hSU₀ b' hb'⟩ +
        ⟨v, (U₀.valuation_le_one_iff _).mp hv1.le⟩ * ⟨c, hSU₀ c hc⟩) ∈
        IsLocalRing.maximalIdeal U₀ := by
      have hmax : ∀ x : U₀, U₀.valuation (x : L) < 1 → x ∈ IsLocalRing.maximalIdeal U₀ :=
        fun x hx ↦ (ValuationSubring.valuation_lt_one_iff U₀ x).mpr hx
      refine Ideal.add_mem _ (Ideal.add_mem _ (Ideal.mul_mem_right _ _ (hmax _ hwp1))
        (Ideal.mul_mem_right _ _ (hmax _ hu1))) (Ideal.mul_mem_right _ _ (hmax _ hv1))
    have e1 : χ (algebraMap A P b) = IsLocalRing.residue U₀ (rU o) := by
      rw [hP, map_add, hχO, hχ _ (hcomb _ _ _), add_zero]
    have e2 : IsLocalRing.residue U₀ ⟨_, hAU b⟩ = IsLocalRing.residue U₀ (rU o) := by
      rw [hU, map_add, (IsLocalRing.residue_eq_zero_iff _).mpr hm, add_zero]
    exact e1.trans e2.symm
  -- step 4: the fractions in `U₀` and the dominating valuation
  let img : A →+* L := P.subtype.comp (algebraMap A P)
  have himg : ∀ b : A, img b = ((algebraMap A P b : P) : L) := fun _ ↦ rfl
  let Ow : Subring L :=
    { carrier := {f | f ∈ U₀ ∧ ∃ a' a : A, img a ≠ 0 ∧ f = img a' / img a}
      mul_mem' := by
        rintro x y ⟨hx, a, b, hb, rfl⟩ ⟨hy, c, d, hd, rfl⟩
        exact ⟨U₀.mul_mem _ _ hx hy, a * c, b * d, by simp [hb, hd], by simp [div_mul_div_comm]⟩
      one_mem' := ⟨U₀.one_mem, 1, 1, by simp, by simp⟩
      add_mem' := by
        rintro x y ⟨hx, a, b, hb, rfl⟩ ⟨hy, c, d, hd, rfl⟩
        refine ⟨U₀.add_mem _ _ hx hy, a * d + c * b, b * d, by simp [hb, hd], ?_⟩
        simp only [map_add, map_mul]
        field_simp
      zero_mem' := ⟨U₀.zero_mem, 0, 1, by simp, by simp⟩
      neg_mem' := by
        rintro x ⟨hx, a, b, hb, rfl⟩
        exact ⟨U₀.neg_mem _ hx, -a, b, hb, by simp [neg_div]⟩ }
  have hOw_inv : ∀ f ∈ Ow, f ≠ 0 → U₀.valuation f = 1 → f⁻¹ ∈ Ow := by
    rintro f ⟨-, a, b, hb, rfl⟩ hf0 hf1
    refine ⟨?_, b, a, fun h0 ↦ hf0 (by simp [h0]), by rw [inv_div]⟩
    exact ((valuation_eq_one_iff_mem_and_inv_mem U₀).mp hf1).2.2
  obtain ⟨bϖ, hbϖ⟩ := hAO ϖ
  obtain ⟨bu, hbu⟩ := hAu
  have hu0 : u ≠ 0 := fun h0 ↦ hu (h0 ▸ isAlgebraic_zero)
  have hconst : ∀ o : O, algebraMap K L (o : K) ∈ Ow := fun o ↦ by
    obtain ⟨b, hb⟩ := hAO o
    exact ⟨hO₀ o, b, 1, by simp, by rw [map_one, div_one, himg, hb]⟩
  have hgOw : g ∈ Ow := by
    refine ⟨(U₀.valuation_le_one_iff _).mp hg1.le, bu ^ s.den, bϖ ^ s.num.toNat, ?_, ?_⟩
    · rw [map_pow, himg, hbϖ]; exact pow_ne_zero _ hp0
    · rw [map_pow, map_pow, himg, himg, hbu, hbϖ, hg]
      congr 1
      rw [← zpow_natCast, Int.toNat_of_nonneg (Rat.num_pos.mpr hs0).le]
  have hpolyOw : ∀ Q : O[X], aeval g (Q.map (algebraMap O K)) ∈ Ow := by
    intro Q
    induction Q using Polynomial.induction_on' with
    | add Q R hQ hR => rw [Polynomial.map_add, map_add]; exact Ow.add_mem hQ hR
    | monomial k o =>
      rw [Polynomial.map_monomial, aeval_monomial]
      exact Ow.mul_mem (hconst o) (Ow.pow_mem hgOw k)
  set R : Subring L := Subring.closure ((P : Set L) ∪ Ow)
  set 𝔪P : Set L := {x | ∃ hx : x ∈ P, (⟨x, hx⟩ : P) ∈ IsLocalRing.maximalIdeal P}
  set 𝔪w : Set L := {x | x ∈ Ow ∧ U₀.valuation x < 1}
  have H : ¬ IsBadSum P Ow 𝔪P 𝔪w 1 := by
    rintro ⟨ι, _, pp, oo, hpp, hoo, hbad, hsum⟩
    refine sum_ne_one_of_flat P U₀ χ hχ hAU hχA (fun i ↦ ⟨pp i, hpp i⟩) oo (fun i ↦ (hoo i).1)
      (fun i ↦ (hoo i).2) (fun i ↦ ?_) hsum.symm
    rcases hbad i with ⟨_, hm⟩ | ⟨_, hm⟩
    · exact Or.inl hm
    · exact Or.inr hm
  have hJ := span_ne_top_of_forall_isBadSum 𝔪P 𝔪w (fun x ⟨hx, _⟩ ↦ hx) (fun x hx ↦ hx.1)
    (fun a ha m ⟨hm, hm'⟩ ↦ ⟨P.mul_mem ha hm, by
      have : (⟨a * m, P.mul_mem ha hm⟩ : P) = ⟨a, ha⟩ * ⟨m, hm⟩ := rfl
      rw [this]; exact Ideal.mul_mem_left _ _ hm'⟩)
    (fun o ho m hm ↦ ⟨Ow.mul_mem ho hm.1, by
      rw [map_mul]
      calc U₀.valuation o * U₀.valuation m ≤ 1 * U₀.valuation m :=
            mul_le_mul_left ((U₀.valuation_le_one_iff _).mpr ho.1) _
        _ < 1 := by rw [one_mul]; exact hm.2⟩) H
  obtain ⟨𝔐, h𝔐, hJ𝔐⟩ := Ideal.exists_le_maximal _ hJ
  haveI := h𝔐.isPrime
  obtain ⟨U, hRU, hlt, -⟩ := exists_valuationSubring_of_isPrime R 𝔐
  have hRmem : ∀ x ∈ (P : Set L) ∪ Ow, x ∈ U := fun x hx ↦ hRU (Subring.subset_closure hx)
  have hunit : ∀ f ∈ Ow, f ≠ 0 → U₀.valuation f = 1 → U.valuation f = 1 := by
    intro f hf hf0 hf1
    rw [valuation_eq_one_iff_mem_and_inv_mem]
    exact ⟨hf0, hRmem f (Or.inr hf), hRmem _ (Or.inr (hOw_inv f hf hf0 hf1))⟩
  refine ⟨U, fun x hx ↦ hRmem x (Or.inl hx), ?_, ?_, ?_⟩
  · have hpR : p ∈ R := Subring.subset_closure (Or.inl (h.algebraMap_mem ϖ))
    refine hlt ⟨p, hpR⟩ (hJ𝔐 (Ideal.subset_span ?_))
    exact Or.inl ⟨h.algebraMap_mem ϖ, hϖm⟩
  · have hg0 : g ≠ 0 := div_ne_zero (pow_ne_zero _ hu0) (zpow_ne_zero _ hp0)
    have hUg := hunit g hgOw hg0 hg1
    unfold IsLogValue
    rw [← map_pow, hgu, map_mul, hUg, one_mul, map_zpow₀]
  · refine ⟨hRmem g (Or.inr hgOw), fun Q hQ ↦ ?_⟩
    have h1 := htr₀.2 Q hQ
    refine hunit _ (hpolyOw Q) (fun h0 ↦ ?_) h1
    rw [h0, map_zero] at h1
    exact zero_ne_one h1

end Exists

end SemistableReduction
