/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.AnnulusThickness
import TemperedFundamentalGroups.SemistableReduction.NodeNormal
import TemperedFundamentalGroups.SemistableReduction.KummerNode

/-!
# The thickness of a node is well defined (W8′, H3)

Blueprint §9.7. If an `O`-algebra is étale-locally at a prime both the singular point of
`O[u, v] ⧸ (u v - ϖ ^ n)` and that of `O[u, v] ⧸ (u v - ϖ ^ m)`, then `n = m`
(`eq_of_isEtaleLocallyAt_node`). The invariant: in a local ring `R` formally étale over a node
`O[u, v] ⧸ (u v - c)` (at its singular point), `Ω_{R/O}` is generated by `du, dv` with relation
module `R · (v, u)` (`relations_eq`), so the ideal `(u, v) R` is the ideal of coordinates of the
relations among any two minimal generators of `Ω_{R/O}` (`relIdeal_eq_of_minimal`), hence
independent of the chart; and `ϖ ^ k ∈ (u, v)` iff `k ≥ n` (faithful flatness of the local map
from the localized node).
-/

universe u

namespace SemistableReduction

section RelIdeal

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- The relations among a pair of elements. -/
def relations (e : Fin 2 → M) : Set (Fin 2 → R) := {a | ∑ i, a i • e i = 0}

/-- The ideal of the coordinates of the relations among a pair of elements. -/
def relIdeal (e : Fin 2 → M) : Ideal R :=
  Ideal.span {r | ∃ a ∈ relations (R := R) e, ∃ i, r = a i}

lemma mem_relIdeal {e : Fin 2 → M} {a : Fin 2 → R} (ha : a ∈ relations e) (i : Fin 2) :
    a i ∈ relIdeal (R := R) e :=
  Ideal.subset_span ⟨a, ha, i, rfl⟩

variable [IsLocalRing R]

lemma relIdeal_le_of_minimal {e e' : Fin 2 → M} (he : Submodule.span R (Set.range e) = ⊤)
    (he' : Submodule.span R (Set.range e') = ⊤)
    (hm' : ∀ a ∈ relations (R := R) e', ∀ i, a i ∈ IsLocalRing.maximalIdeal R) :
    relIdeal (R := R) e' ≤ relIdeal e := by
  classical
  -- `e' = P e`, `e = Q e'`
  have hP : ∀ j, ∃ c : Fin 2 → R, ∑ i, c i • e i = e' j := fun j ↦ by
    have : e' j ∈ Submodule.span R (Set.range e) := he ▸ Submodule.mem_top
    exact (Submodule.mem_span_range_iff_exists_fun R).mp this
  have hQ : ∀ i, ∃ c : Fin 2 → R, ∑ j, c j • e' j = e i := fun i ↦ by
    have : e i ∈ Submodule.span R (Set.range e') := he' ▸ Submodule.mem_top
    exact (Submodule.mem_span_range_iff_exists_fun R).mp this
  choose P hP using hP
  choose Q hQ using hQ
  set PM : Matrix (Fin 2) (Fin 2) R := Matrix.of P
  set QM : Matrix (Fin 2) (Fin 2) R := Matrix.of Q
  -- the rows of `P Q - 1` are relations of `e'`
  have hrow : ∀ j, (fun k ↦ (PM * QM) j k - (1 : Matrix (Fin 2) (Fin 2) R) j k) ∈
      relations (R := R) e' := by
    intro j
    simp only [relations, Set.mem_setOf_eq, sub_smul, Finset.sum_sub_distrib, Matrix.mul_apply]
    rw [sub_eq_zero]
    calc ∑ k, (∑ i, PM j i * QM i k) • e' k = ∑ i, PM j i • ∑ k, QM i k • e' k := by
          simp_rw [Finset.smul_sum, smul_smul, Finset.sum_smul]
          exact Finset.sum_comm
      _ = e' j := by simp_rw [PM, QM, Matrix.of_apply, hQ, hP]
      _ = ∑ k, (1 : Matrix (Fin 2) (Fin 2) R) j k • e' k := by
          simp [Matrix.one_apply]
  have hdet : IsUnit (PM * QM).det := by
    have h00 := hm' _ (hrow 0) 0
    have h01 := hm' _ (hrow 0) 1
    have h10 := hm' _ (hrow 1) 0
    have h11 := hm' _ (hrow 1) 1
    simp only [Matrix.one_apply_eq, Matrix.one_apply_ne (by decide : (0 : Fin 2) ≠ 1),
      Matrix.one_apply_ne (by decide : (1 : Fin 2) ≠ 0), sub_zero] at h00 h01 h10 h11
    rw [Matrix.det_fin_two]
    by_contra hnu
    have hmem := (IsLocalRing.mem_maximalIdeal _).mpr hnu
    have : (1 : R) ∈ IsLocalRing.maximalIdeal R := by
      have e : (1 : R) = ((PM * QM) 0 0 * (PM * QM) 1 1 - (PM * QM) 0 1 * (PM * QM) 1 0) +
          (PM * QM) 0 1 * (PM * QM) 1 0 - ((PM * QM) 0 0 - 1) * ((PM * QM) 1 1 - 1) -
          ((PM * QM) 0 0 - 1) - ((PM * QM) 1 1 - 1) := by ring
      rw [e]
      exact Ideal.sub_mem _ (Ideal.sub_mem _ (Ideal.sub_mem _ (Ideal.add_mem _ hmem
        (Ideal.mul_mem_right _ _ h01)) (Ideal.mul_mem_right _ _ h00)) h00) h11
    exact (IsLocalRing.maximalIdeal.isMaximal R).ne_top ((Ideal.eq_top_iff_one _).mpr this)
  have hPu : IsUnit PM := by
    rw [Matrix.isUnit_iff_isUnit_det]
    rw [Matrix.det_mul] at hdet
    exact isUnit_of_mul_isUnit_left hdet
  -- a relation `a'` of `e'` gives the relation `a' P` of `e`
  rw [relIdeal, Ideal.span_le]
  rintro _ ⟨a', ha', j, rfl⟩
  set b : Fin 2 → R := fun i ↦ ∑ k, a' k * PM k i
  have hb : b ∈ relations (R := R) e := by
    simp only [relations, Set.mem_setOf_eq, b, Finset.sum_smul, ← smul_smul]
    rw [Finset.sum_comm]
    simp_rw [← Finset.smul_sum, PM, Matrix.of_apply, hP]
    exact ha'
  have ha'b : a' = Matrix.vecMul b PM⁻¹ := by
    have : Matrix.vecMul a' PM = b := rfl
    rw [← this, Matrix.vecMul_vecMul, Matrix.mul_nonsing_inv _ ((Matrix.isUnit_iff_isUnit_det _).mp
      hPu), Matrix.vecMul_one]
  rw [ha'b, Matrix.vecMul, dotProduct]
  exact Ideal.sum_mem _ fun i _ ↦ Ideal.mul_mem_right _ _ (mem_relIdeal hb i)

/-- **The relation ideal of a minimal generating pair is intrinsic.** -/
theorem relIdeal_eq_of_minimal {e e' : Fin 2 → M} (he : Submodule.span R (Set.range e) = ⊤)
    (he' : Submodule.span R (Set.range e') = ⊤)
    (hm : ∀ a ∈ relations (R := R) e, ∀ i, a i ∈ IsLocalRing.maximalIdeal R)
    (hm' : ∀ a ∈ relations (R := R) e', ∀ i, a i ∈ IsLocalRing.maximalIdeal R) :
    relIdeal (R := R) e = relIdeal e' :=
  le_antisymm (relIdeal_le_of_minimal he' he hm) (relIdeal_le_of_minimal he he' hm')

end RelIdeal

section Omega

open TrivSqZeroExt

variable {O : Type u} [CommRing O] (c : O) (T : Type u) [CommRing T] [Algebra O T]
  [Algebra (Node O c) T] [IsScalarTower O (Node O c) T]

/-- The images of the node coordinates. -/
noncomputable abbrev uT : T := algebraMap (Node O c) T (Node.u c)

/-- The images of the node coordinates. -/
noncomputable abbrev vT : T := algebraMap (Node O c) T (Node.v c)

lemma uT_mul_vT : uT c T * vT c T = algebraMap O T c := by
  rw [← map_mul, Node.u_mul_v, ← IsScalarTower.algebraMap_apply]

/-- The module `T² ⧸ T (v, u)`: the expected `Ω_{T/O}`. -/
abbrev RelQ : Type u := (Fin 2 → T) ⧸ Submodule.span T {![vT c T, uT c T]}

/-- The basis vectors of `RelQ`. -/
noncomputable def relE (i : Fin 2) : RelQ c T := Submodule.Quotient.mk (Pi.single i 1)

omit [Algebra O T] [IsScalarTower O (Node O c) T] in
lemma relE_rel : vT c T • relE c T 0 + uT c T • relE c T 1 = 0 := by
  rw [relE, relE, ← Submodule.Quotient.mk_smul, ← Submodule.Quotient.mk_smul,
    ← Submodule.Quotient.mk_add, Submodule.Quotient.mk_eq_zero]
  have : vT c T • (Pi.single 0 1 : Fin 2 → T) + uT c T • Pi.single 1 1 = ![vT c T, uT c T] := by
    funext i
    fin_cases i <;> simp [Algebra.algebraMap_eq_smul_one]
  rw [this]
  exact Submodule.mem_span_singleton_self _

/-- The map `O[u, v] ⧸ (u v - c) → T ⊕ RelQ`, `u ↦ (u, e₀)`, `v ↦ (v, e₁)`. -/
noncomputable def toTriv : Node O c →ₐ[O] TrivSqZeroExt T (RelQ c T) :=
  Node.lift (inl (uT c T) + inr (relE c T 0)) (inl (vT c T) + inr (relE c T 1)) (by
    rw [TrivSqZeroExt.algebraMap_eq_inl', ← uT_mul_vT]
    ext
    · simp
    · simp only [snd_mul, fst_add, fst_inl, fst_inr, add_zero, snd_add, snd_inl, snd_inr,
        zero_add, op_smul_eq_smul]
      rw [add_comm]
      exact relE_rel c T)

lemma fst_toTriv (x : Node O c) : (toTriv c T x).fst = algebraMap (Node O c) T x := by
  have : (TrivSqZeroExt.fstHom O T (RelQ c T)).comp (toTriv c T) =
      IsScalarTower.toAlgHom O (Node O c) T :=
    Node.algHom_ext (by simp [toTriv]) (by simp [toTriv])
  exact AlgHom.congr_fun this x

omit [Algebra O T] [Algebra (Node O c) T] [IsScalarTower O (Node O c) T] in
lemma tsze_mul_eq_zero {M : Type*} [AddCommGroup M] [Module T M] [Module Tᵐᵒᵖ M]
    {x y : TrivSqZeroExt T M} (hx : x.fst = 0) (hy : y.fst = 0) : x * y = 0 := by
  ext
  · rw [fst_mul, hx, zero_mul, fst_zero]
  · rw [snd_mul, hx, hy, zero_smul, MulOpposite.op_zero, zero_smul, add_zero, snd_zero]

/-- `T ⊕ RelQ` with the `O[u, v] ⧸ (u v - c)`-algebra structure given by `toTriv`. -/
def TrivQ : Type u := TrivSqZeroExt T (RelQ c T)

noncomputable instance : CommRing (TrivQ c T) :=
  inferInstanceAs (CommRing (TrivSqZeroExt T (RelQ c T)))

noncomputable instance : Algebra (Node O c) (TrivQ c T) := (toTriv c T).toRingHom.toAlgebra

/-- The first projection `TrivQ → T`, as an algebra map over the node. -/
noncomputable def trivFst : TrivQ c T →ₐ[Node O c] T :=
  { (TrivSqZeroExt.fstHom O T (RelQ c T)).toRingHom with
    commutes' := fun x ↦ fst_toTriv c T x }

lemma trivFst_apply (x : TrivQ c T) :
    trivFst c T x = TrivSqZeroExt.fst (R := T) (M := RelQ c T) x :=
  rfl

lemma isNilpotent_ker_trivFst : IsNilpotent (RingHom.ker (trivFst c T : TrivQ c T →+* T)) := by
  refine ⟨2, ?_⟩
  rw [pow_two, Ideal.zero_eq_bot, ← le_bot_iff, Ideal.mul_le]
  intro x hx y hy
  rw [RingHom.mem_ker] at hx hy
  change TrivSqZeroExt.fst (R := T) (M := RelQ c T) x = 0 at hx
  change TrivSqZeroExt.fst (R := T) (M := RelQ c T) y = 0 at hy
  rw [Ideal.mem_bot]
  exact tsze_mul_eq_zero T (M := RelQ c T) hx hy

variable [Algebra.FormallyEtale (Node O c) T]

/-- The lift `T → T ⊕ RelQ` of `toTriv` (formal smoothness), a section of the first projection. -/
noncomputable def liftTriv : T →ₐ[Node O c] TrivQ c T :=
  Algebra.FormallySmooth.liftOfSurjective (AlgHom.id (Node O c) T) (trivFst c T)
    (fun t ↦ ⟨(inl t : TrivSqZeroExt T (RelQ c T)), fst_inl (RelQ c T) t⟩)
    (isNilpotent_ker_trivFst c T)

lemma fst_liftTriv (t : T) :
    TrivSqZeroExt.fst (R := T) (M := RelQ c T) (liftTriv c T t) = t :=
  Algebra.FormallySmooth.liftOfSurjective_apply (AlgHom.id _ T) (trivFst c T) _ _ t

/-- The snd component of `liftTriv`, as a function. -/
noncomputable def relDerFun (t : T) : RelQ c T :=
  TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T t)

lemma liftTriv_algebraMap (o : O) :
    (liftTriv c T (algebraMap O T o) : TrivSqZeroExt T (RelQ c T)) = inl (algebraMap O T o) := by
  rw [IsScalarTower.algebraMap_apply O (Node O c) T, AlgHom.commutes]
  change toTriv c T (algebraMap O (Node O c) o) = _
  rw [AlgHom.commutes, TrivSqZeroExt.algebraMap_eq_inl', ← IsScalarTower.algebraMap_apply]

omit [Algebra O T] [IsScalarTower O (Node O c) T] [Algebra.FormallyEtale (Node O c) T] in
lemma snd_mul' (x y : TrivQ c T) :
    TrivSqZeroExt.snd (R := T) (M := RelQ c T) (x * y) =
      TrivSqZeroExt.fst (R := T) (M := RelQ c T) x • TrivSqZeroExt.snd (R := T) (M := RelQ c T) y +
      MulOpposite.op (TrivSqZeroExt.fst (R := T) (M := RelQ c T) y) •
        TrivSqZeroExt.snd (R := T) (M := RelQ c T) x :=
  snd_mul (R := T) (M := RelQ c T) x y

lemma snd_liftTriv_algebraMap (o : O) :
    TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T (algebraMap O T o)) = 0 := by
  rw [liftTriv_algebraMap, snd_inl]

/-- The derivation `T → T² ⧸ T (v, u)` with `u ↦ e₀`, `v ↦ e₁`. -/
noncomputable def relDer : Derivation O T (RelQ c T) where
  toFun := relDerFun c T
  map_add' s t := by
    change TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T (s + t)) = _
    rw [map_add]
    exact snd_add (R := T) (M := RelQ c T) _ _
  map_smul' o t := by
    change TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T (o • t)) = _
    rw [Algebra.smul_def, map_mul, snd_mul', snd_liftTriv_algebraMap, fst_liftTriv, smul_zero,
      add_zero, algebraMap_smul]
    rfl
  map_one_eq_zero' := by
    change TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T 1) = 0
    rw [map_one]
    exact snd_one (R := T) (M := RelQ c T)
  leibniz' s t := by
    change TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T (s * t)) = _
    rw [map_mul, snd_mul', fst_liftTriv, fst_liftTriv, op_smul_eq_smul]
    rfl

lemma relDer_uT : relDer c T (uT c T) = relE c T 0 := by
  change TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T (algebraMap _ T _)) = _
  rw [AlgHom.commutes]
  change TrivSqZeroExt.snd (toTriv c T (Node.u c)) = _
  simp [toTriv]

lemma relDer_vT : relDer c T (vT c T) = relE c T 1 := by
  change TrivSqZeroExt.snd (R := T) (M := RelQ c T) (liftTriv c T (algebraMap _ T _)) = _
  rw [AlgHom.commutes]
  change TrivSqZeroExt.snd (toTriv c T (Node.v c)) = _
  simp [toTriv]

/-- The pair `(du, dv)` in `Ω_{T/O}`. -/
noncomputable def dPair : Fin 2 → Ω[T⁄O] :=
  ![KaehlerDifferential.D O T (uT c T), KaehlerDifferential.D O T (vT c T)]

/-- **The relations among `du, dv`** in `Ω_{T/O}` are the multiples of `(v, u)`. -/
theorem mem_relations_dPair_iff (a : Fin 2 → T) :
    a ∈ relations (R := T) (dPair c T) ↔ ∃ t : T, a = t • ![vT c T, uT c T] := by
  constructor
  · intro ha
    have h := congrArg (relDer c T).liftKaehlerDifferential ha
    simp only [Fin.sum_univ_two, dPair, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_fin_one, map_add, map_smul, Derivation.liftKaehlerDifferential_comp_D,
      relDer_uT, relDer_vT, map_zero] at h
    rw [relE, relE, ← Submodule.Quotient.mk_smul, ← Submodule.Quotient.mk_smul,
      ← Submodule.Quotient.mk_add, Submodule.Quotient.mk_eq_zero,
      Submodule.mem_span_singleton] at h
    obtain ⟨t, ht⟩ := h
    refine ⟨t, ?_⟩
    rw [ht]
    funext i
    fin_cases i <;> simp
  · rintro ⟨t, rfl⟩
    simp only [relations, Set.mem_setOf_eq, Fin.sum_univ_two, dPair, Pi.smul_apply,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_fin_one, smul_eq_mul, mul_smul,
      ← smul_add]
    rw [add_comm, ← Derivation.leibniz, uT_mul_vT,
      Derivation.map_algebraMap, smul_zero]

omit [Algebra.FormallyEtale (Node O c) T] in
lemma span_dNode : Submodule.span (Node O c)
    (Set.range ![KaehlerDifferential.D O (Node O c) (Node.u c),
      KaehlerDifferential.D O (Node O c) (Node.v c)]) = ⊤ := by
  rw [eq_top_iff, ← KaehlerDifferential.span_range_derivation, Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  have hx : x ∈ Algebra.adjoin O {Node.u c, Node.v c} := (Node.adjoin_u_v c).symm ▸ trivial
  induction hx using Algebra.adjoin_induction with
  | mem y hy =>
    rcases hy with rfl | rfl
    · exact Submodule.subset_span ⟨0, rfl⟩
    · exact Submodule.subset_span ⟨1, rfl⟩
  | algebraMap o => simp
  | add y z _ _ hy hz => rw [map_add]; exact add_mem hy hz
  | mul y z _ _ hy hz =>
    rw [Derivation.leibniz]
    exact add_mem (Submodule.smul_mem _ _ hz) (Submodule.smul_mem _ _ hy)

/-- **`du, dv` generate `Ω_{T/O}`.** -/
theorem span_dPair : Submodule.span T (Set.range (dPair c T)) = ⊤ := by
  have hsurj : Function.Surjective (KaehlerDifferential.mapBaseChange O (Node O c) T) := by
    intro ω
    exact (KaehlerDifferential.exact_mapBaseChange_map O (Node O c) T ω).mp
      (Subsingleton.elim _ _)
  rw [eq_top_iff]
  rintro ω -
  obtain ⟨x, rfl⟩ := hsurj ω
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add x y hx hy => rw [map_add]; exact add_mem hx hy
  | tmul t ω =>
    rw [KaehlerDifferential.mapBaseChange_tmul]
    refine Submodule.smul_mem _ _ ?_
    have hω : ω ∈ Submodule.span (Node O c)
        (Set.range ![KaehlerDifferential.D O (Node O c) (Node.u c),
          KaehlerDifferential.D O (Node O c) (Node.v c)]) := (span_dNode c).symm ▸ trivial
    induction hω using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨i, rfl⟩ := hy
      fin_cases i
      · exact Submodule.subset_span ⟨0, by simp [dPair, KaehlerDifferential.map_D]⟩
      · exact Submodule.subset_span ⟨1, by simp [dPair, KaehlerDifferential.map_D]⟩
    | zero => simp
    | add y z _ _ hy hz => rw [map_add]; exact add_mem hy hz
    | smul r y _ hy =>
      rw [map_smul, algebra_compatible_smul T r]
      exact Submodule.smul_mem _ _ hy

theorem relIdeal_dPair : relIdeal (R := T) (dPair c T) = Ideal.span {uT c T, vT c T} := by
  apply le_antisymm
  · rw [relIdeal, Ideal.span_le]
    rintro _ ⟨a, ha, i, rfl⟩
    obtain ⟨t, rfl⟩ := (mem_relations_dPair_iff c T a).mp ha
    fin_cases i
    · simpa using Ideal.mul_mem_left _ t (Ideal.subset_span (by simp))
    · simpa using Ideal.mul_mem_left _ t (Ideal.subset_span (by simp))
  · have h1 : ![vT c T, uT c T] ∈ relations (R := T) (dPair c T) :=
      (mem_relations_dPair_iff c T _).mpr ⟨1, by simp⟩
    rw [Ideal.span_le]
    rintro _ (rfl | rfl)
    · simpa using mem_relIdeal h1 1
    · simpa using mem_relIdeal h1 0

theorem relations_dPair_le_maximalIdeal [IsLocalRing T] (hu : uT c T ∈ IsLocalRing.maximalIdeal T)
    (hv : vT c T ∈ IsLocalRing.maximalIdeal T) :
    ∀ a ∈ relations (R := T) (dPair c T), ∀ i, a i ∈ IsLocalRing.maximalIdeal T := by
  intro a ha i
  obtain ⟨t, rfl⟩ := (mem_relations_dPair_iff c T a).mp ha
  fin_cases i
  · simpa using Ideal.mul_mem_left _ t hv
  · simpa using Ideal.mul_mem_left _ t hu

end Omega

/-- **Two étale node charts at a singular point define the same ideal `(u, v)`.** -/
theorem span_uv_eq {O : Type u} [CommRing O] {c₁ c₂ : O} {T : Type u} [CommRing T]
    [IsLocalRing T] [Algebra O T] (i₁ : Algebra (Node O c₁) T) (i₂ : Algebra (Node O c₂) T)
    (t₁ : @IsScalarTower O (Node O c₁) T _ i₁.toSMul _)
    (t₂ : @IsScalarTower O (Node O c₂) T _ i₂.toSMul _)
    (e₁ : @Algebra.FormallyEtale (Node O c₁) T _ _ i₁)
    (e₂ : @Algebra.FormallyEtale (Node O c₂) T _ _ i₂)
    (hu₁ : @uT O _ c₁ T _ i₁ ∈ IsLocalRing.maximalIdeal T)
    (hv₁ : @vT O _ c₁ T _ i₁ ∈ IsLocalRing.maximalIdeal T)
    (hu₂ : @uT O _ c₂ T _ i₂ ∈ IsLocalRing.maximalIdeal T)
    (hv₂ : @vT O _ c₂ T _ i₂ ∈ IsLocalRing.maximalIdeal T) :
    Ideal.span {@uT O _ c₁ T _ i₁, @vT O _ c₁ T _ i₁} =
      Ideal.span {@uT O _ c₂ T _ i₂, @vT O _ c₂ T _ i₂} := by
  rw [← @relIdeal_dPair O _ c₁ T _ _ i₁ t₁ e₁, ← @relIdeal_dPair O _ c₂ T _ _ i₂ t₂ e₂]
  exact relIdeal_eq_of_minimal (@span_dPair O _ c₁ T _ _ i₁ t₁ e₁)
    (@span_dPair O _ c₂ T _ _ i₂ t₂ e₂)
    (@relations_dPair_le_maximalIdeal O _ c₁ T _ _ i₁ t₁ e₁ _ hu₁ hv₁)
    (@relations_dPair_le_maximalIdeal O _ c₂ T _ _ i₂ t₂ e₂ _ hu₂ hv₂)

section Thickness

variable {O : Type u} [CommRing O]

/-- Every element of the node is a constant modulo `(u, v)`. -/
theorem Node.exists_sub_mem_span (a : O) (x : Node O a) :
    ∃ o : O, x - algebraMap O _ o ∈ Ideal.span {Node.u a, Node.v a} := by
  have hx : x ∈ Algebra.adjoin O {Node.u a, Node.v a} := (Node.adjoin_u_v a).symm ▸ trivial
  induction hx using Algebra.adjoin_induction with
  | mem y hy =>
    refine ⟨0, ?_⟩
    rw [map_zero, sub_zero]
    exact Ideal.subset_span hy
  | algebraMap o => exact ⟨o, by simp⟩
  | add y z _ _ hy hz =>
    obtain ⟨o, ho⟩ := hy
    obtain ⟨p, hp⟩ := hz
    exact ⟨o + p, by rw [map_add]; convert Ideal.add_mem _ ho hp using 1; ring⟩
  | mul y z _ _ hy hz =>
    obtain ⟨o, ho⟩ := hy
    obtain ⟨p, hp⟩ := hz
    refine ⟨o * p, ?_⟩
    have : y * z - algebraMap O _ (o * p) =
        (y - algebraMap O _ o) * z + algebraMap O _ o * (z - algebraMap O _ p) := by
      rw [map_mul]; ring
    rw [this]
    exact Ideal.add_mem _ (Ideal.mul_mem_right _ _ ho) (Ideal.mul_mem_left _ _ hp)

variable [IsDomain O] [IsDiscreteValuationRing O] {ϖ : O}

/-- In the node localized at a prime containing `u, v`: `ϖ ^ k ∈ (u, v)` iff `n ≤ k`. -/
theorem Node.pow_mem_span_iff (hϖ : Irreducible ϖ) {n : ℕ} (𝔯 : Ideal (Node O (ϖ ^ n)))
    [𝔯.IsPrime] (hu : Node.u (ϖ ^ n) ∈ 𝔯) (hv : Node.v (ϖ ^ n) ∈ 𝔯) (k : ℕ) :
    algebraMap O (Localization.AtPrime 𝔯) (ϖ ^ k) ∈
      (Ideal.span {Node.u (ϖ ^ n), Node.v (ϖ ^ n)}).map
        (algebraMap (Node O (ϖ ^ n)) (Localization.AtPrime 𝔯)) ↔ n ≤ k := by
  set I : Ideal (Node O (ϖ ^ n)) := Ideal.span {Node.u (ϖ ^ n), Node.v (ϖ ^ n)}
  have huv : algebraMap O (Node O (ϖ ^ n)) (ϖ ^ n) ∈ I := by
    rw [← Node.u_mul_v]
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp))
  have hI𝔯 : I ≤ 𝔯 := by
    rw [Ideal.span_le]
    rintro _ (rfl | rfl)
    · exact hu
    · exact hv
  have hϖ𝔯 : algebraMap O (Node O (ϖ ^ n)) ϖ ∈ 𝔯 := by
    refine (inferInstance : 𝔯.IsPrime).mem_of_pow_mem n ?_
    rw [← map_pow]
    exact hI𝔯 huv
  constructor
  · intro h
    rw [IsLocalization.mem_map_algebraMap_iff 𝔯.primeCompl] at h
    obtain ⟨⟨⟨x, hx⟩, ⟨s, hs⟩⟩, hxs⟩ := h
    simp only at hxs
    rw [IsScalarTower.algebraMap_apply O (Node O (ϖ ^ n)), ← map_mul,
      IsLocalization.eq_iff_exists 𝔯.primeCompl] at hxs
    obtain ⟨⟨t, ht⟩, hts⟩ := hxs
    simp only at hts
    -- `t s ϖ ^ k ∈ I` with `t s ∉ 𝔯`
    have hmem : (t * s) * algebraMap O _ (ϖ ^ k) ∈ I := by
      have : (t * s) * algebraMap O _ (ϖ ^ k) = t * x := by rw [← hts]; ring
      rw [this]
      exact Ideal.mul_mem_left _ _ hx
    have hts𝔯 : t * s ∉ 𝔯 := fun h ↦ ((inferInstance : 𝔯.IsPrime).mem_or_mem h).elim ht hs
    obtain ⟨o, ho⟩ := Node.exists_sub_mem_span (ϖ ^ n) (t * s)
    have hou : IsUnit o := by
      by_contra hno
      apply hts𝔯
      have : o ∈ IsLocalRing.maximalIdeal O := (IsLocalRing.mem_maximalIdeal o).mpr hno
      rw [(IsDiscreteValuationRing.irreducible_iff_uniformizer ϖ).mp hϖ,
        Ideal.mem_span_singleton] at this
      obtain ⟨r, rfl⟩ := this
      have h1 : algebraMap O (Node O (ϖ ^ n)) (ϖ * r) ∈ 𝔯 := by
        rw [map_mul]; exact Ideal.mul_mem_right _ _ hϖ𝔯
      have : t * s = (t * s - algebraMap O _ (ϖ * r)) + algebraMap O _ (ϖ * r) := by ring
      rw [this]
      exact Ideal.add_mem _ (hI𝔯 ho) h1
    -- reduce modulo `(u, v)`: `o ϖ ^ k ∈ (ϖ ^ n)`
    let ρ : Node O (ϖ ^ n) →ₐ[O] O ⧸ Ideal.span {ϖ ^ n} :=
      Node.lift 0 0 (by
        rw [zero_mul, eq_comm, Ideal.Quotient.algebraMap_eq, Ideal.Quotient.eq_zero_iff_mem]
        exact Ideal.subset_span rfl)
    have hρI : ∀ y ∈ I, ρ y = 0 := by
      intro y hy
      rw [← RingHom.mem_ker]
      refine (Ideal.span_le.mpr ?_) hy
      rintro _ (rfl | rfl)
      · simp [ρ]
      · simp [ρ]
    have h1 := hρI _ hmem
    have h2 := hρI _ ho
    rw [map_sub, sub_eq_zero] at h2
    rw [map_mul, h2, AlgHom.commutes, AlgHom.commutes, ← map_mul, Ideal.Quotient.algebraMap_eq,
      Ideal.Quotient.eq_zero_iff_mem, Ideal.mem_span_singleton] at h1
    have h3 : ϖ ^ n ∣ ϖ ^ k := by
      obtain ⟨r, hr⟩ := h1
      refine ⟨↑hou.unit⁻¹ * r, ?_⟩
      calc ϖ ^ k = ↑hou.unit⁻¹ * (o * ϖ ^ k) := by
            rw [← mul_assoc, IsUnit.val_inv_mul, one_mul]
        _ = ϖ ^ n * (↑hou.unit⁻¹ * r) := by rw [hr]; ring
    exact (pow_dvd_pow_iff hϖ.ne_zero hϖ.not_isUnit).mp h3
  · intro hk
    obtain ⟨j, rfl⟩ := Nat.exists_eq_add_of_le hk
    rw [pow_add, map_mul, IsScalarTower.algebraMap_apply O (Node O (ϖ ^ n))]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ huv)

/-- **The thickness is read off from the ideal `(u, v)` in an étale neighbourhood**: for an étale
node chart `f : O[u, v] ⧸ (u v - ϖ ^ n) → E` at a prime `𝔢` over its singular point,
`ϖ ^ k ∈ (f u, f v) E_𝔢` iff `n ≤ k`. -/
theorem chart_pow_mem_iff (hϖ : Irreducible ϖ) {n : ℕ} {E : Type u} [CommRing E] (𝔢 : Ideal E)
    [𝔢.IsPrime] (f : Node O (ϖ ^ n) →+* E) (hf : f.Etale) (hu : f (Node.u _) ∈ 𝔢)
    (hv : f (Node.v _) ∈ 𝔢) (k : ℕ) :
    algebraMap E (Localization.AtPrime 𝔢) (f (algebraMap O _ (ϖ ^ k))) ∈
      Ideal.span {algebraMap E (Localization.AtPrime 𝔢) (f (Node.u _)),
        algebraMap E (Localization.AtPrime 𝔢) (f (Node.v _))} ↔ n ≤ k := by
  set 𝔯 := 𝔢.comap f
  have hu𝔯 : Node.u (ϖ ^ n) ∈ 𝔯 := hu
  have hv𝔯 : Node.v (ϖ ^ n) ∈ 𝔯 := hv
  set φ := Localization.localRingHom 𝔯 𝔢 f rfl
  letI : Algebra (Localization.AtPrime 𝔯) (Localization.AtPrime 𝔢) := φ.toAlgebra
  haveI : Module.Flat (Localization.AtPrime 𝔯) (Localization.AtPrime 𝔢) :=
    RingHom.Flat.localRingHom (RingHom.Etale.iff_flat_and_formallyUnramified.mp hf).1 𝔢 𝔯 rfl
  haveI : IsLocalHom (algebraMap (Localization.AtPrime 𝔯) (Localization.AtPrime 𝔢)) :=
    Localization.isLocalHom_localRingHom 𝔯 𝔢 f rfl
  haveI : Module.FaithfullyFlat (Localization.AtPrime 𝔯) (Localization.AtPrime 𝔢) :=
    Module.FaithfullyFlat.of_flat_of_isLocalHom
  rw [← Node.pow_mem_span_iff hϖ 𝔯 hu𝔯 hv𝔯 k,
    ← Ideal.comap_map_eq_self_of_faithfullyFlat (B := Localization.AtPrime 𝔢)
      ((Ideal.span {Node.u (ϖ ^ n), Node.v (ϖ ^ n)}).map
        (algebraMap (Node O (ϖ ^ n)) (Localization.AtPrime 𝔯))),
    Ideal.mem_comap, Ideal.map_map, Ideal.map_span, Set.image_pair]
  have e : ∀ x : Node O (ϖ ^ n), algebraMap (Localization.AtPrime 𝔯) (Localization.AtPrime 𝔢)
      (algebraMap (Node O (ϖ ^ n)) (Localization.AtPrime 𝔯) x) =
      algebraMap E (Localization.AtPrime 𝔢) (f x) :=
    fun x ↦ Localization.localRingHom_to_map 𝔯 𝔢 f rfl x
  simp only [RingHom.coe_comp, Function.comp_apply, e]
  rw [IsScalarTower.algebraMap_apply O (Node O (ϖ ^ n)) (Localization.AtPrime 𝔯), e]

/-- **The thickness of a node is well defined** (two étale node charts at the singular point of
a common étale neighbourhood have the same thickness). -/
theorem eq_of_two_node_charts (hϖ : Irreducible ϖ) {n m : ℕ} {E : Type u} [CommRing E]
    (𝔢 : Ideal E) [𝔢.IsPrime] (f₁ : Node O (ϖ ^ n) →+* E) (f₂ : Node O (ϖ ^ m) →+* E)
    (hf₁ : f₁.Etale) (hf₂ : f₂.Etale)
    (hO : f₁.comp (algebraMap O _) = f₂.comp (algebraMap O _))
    (hu₁ : f₁ (Node.u _) ∈ 𝔢) (hv₁ : f₁ (Node.v _) ∈ 𝔢)
    (hu₂ : f₂ (Node.u _) ∈ 𝔢) (hv₂ : f₂ (Node.v _) ∈ 𝔢) : n = m := by
  set T := Localization.AtPrime 𝔢
  letI i₁ : Algebra (Node O (ϖ ^ n)) E := f₁.toAlgebra
  letI i₂ : Algebra (Node O (ϖ ^ m)) E := f₂.toAlgebra
  letI : Algebra O E := (f₁.comp (algebraMap O _)).toAlgebra
  haveI : Algebra.Etale (Node O (ϖ ^ n)) E := RingHom.etale_algebraMap.mp hf₁
  haveI : Algebra.Etale (Node O (ϖ ^ m)) E := RingHom.etale_algebraMap.mp hf₂
  have t₁ : IsScalarTower O (Node O (ϖ ^ n)) T :=
    IsScalarTower.of_algebraMap_eq (R := O) (S := Node O (ϖ ^ n)) (A := T) fun o ↦ rfl
  have t₂ : IsScalarTower O (Node O (ϖ ^ m)) T :=
    IsScalarTower.of_algebraMap_eq (R := O) (S := Node O (ϖ ^ m)) (A := T) fun o ↦ by
    change algebraMap E T (f₁ (algebraMap O _ o)) = algebraMap E T (f₂ (algebraMap O _ o))
    rw [← RingHom.comp_apply f₁, hO, RingHom.comp_apply]
  have hspan := span_uv_eq (T := T) inferInstance inferInstance t₁ t₂ inferInstance inferInstance
    ((IsLocalization.AtPrime.to_map_mem_maximal_iff T 𝔢 _).mpr hu₁)
    ((IsLocalization.AtPrime.to_map_mem_maximal_iff T 𝔢 _).mpr hv₁)
    ((IsLocalization.AtPrime.to_map_mem_maximal_iff T 𝔢 _).mpr hu₂)
    ((IsLocalization.AtPrime.to_map_mem_maximal_iff T 𝔢 _).mpr hv₂)
  have h₁ := chart_pow_mem_iff hϖ 𝔢 f₁ hf₁ hu₁ hv₁
  have h₂ := chart_pow_mem_iff hϖ 𝔢 f₂ hf₂ hu₂ hv₂
  have hc : ∀ k, f₁ (algebraMap O _ (ϖ ^ k)) = f₂ (algebraMap O _ (ϖ ^ k)) := fun k ↦ by
    rw [← RingHom.comp_apply f₁, hO, RingHom.comp_apply]
  apply le_antisymm
  · rw [← h₁, hc]
    change _ ∈ Ideal.span {@uT O _ _ T _ (inferInstance : Algebra (Node O (ϖ ^ n)) T),
      @vT O _ _ T _ (inferInstance : Algebra (Node O (ϖ ^ n)) T)}
    rw [hspan]
    exact (h₂ m).mpr le_rfl
  · rw [← h₂, ← hc]
    change _ ∈ Ideal.span {@uT O _ _ T _ (inferInstance : Algebra (Node O (ϖ ^ m)) T),
      @vT O _ _ T _ (inferInstance : Algebra (Node O (ϖ ^ m)) T)}
    rw [← hspan]
    exact (h₁ n).mpr le_rfl

open TensorProduct in
/-- `A` is **étale-locally at `𝔭` the singular point of the node** `O[u, v] ⧸ (u v - ϖ ^ n)`. -/
def IsNodeAt (ϖ : O) (n : ℕ) {A : Type u} [CommRing A] [Algebra O A] (𝔭 : Ideal A) : Prop :=
  ∃ (C : Type u) (_ : CommRing C) (g : A →+* C) (f : Node O (ϖ ^ n) →+* C) (𝔮 : Ideal C),
    g.Etale ∧ f.Etale ∧ 𝔮.IsPrime ∧ 𝔮.comap g = 𝔭 ∧
    f.comp (algebraMap O _) = g.comp (algebraMap O A) ∧
    f (Node.u _) ∈ 𝔮 ∧ f (Node.v _) ∈ 𝔮

open TensorProduct in
/-- **The thickness of a node is well defined.** -/
theorem IsNodeAt.unique (hϖ : Irreducible ϖ) {n m : ℕ} {A : Type u} [CommRing A] [Algebra O A]
    {𝔭 : Ideal A} [𝔭.IsPrime] (h₁ : IsNodeAt ϖ n 𝔭) (h₂ : IsNodeAt ϖ m 𝔭) : n = m := by
  obtain ⟨C₁, _, g₁, f₁, 𝔮₁, hg₁, hf₁, h𝔮₁, hc₁, hO₁, hu₁, hv₁⟩ := h₁
  obtain ⟨C₂, _, g₂, f₂, 𝔮₂, hg₂, hf₂, h𝔮₂, hc₂, hO₂, hu₂, hv₂⟩ := h₂
  letI : Algebra A C₁ := g₁.toAlgebra
  letI : Algebra A C₂ := g₂.toAlgebra
  obtain ⟨R, hR, hR₁, hR₂⟩ := exists_isPrime_tensorProduct (A := A) 𝔮₁ 𝔮₂ (hc₁.trans hc₂.symm)
  have hl : (Algebra.TensorProduct.includeLeftRingHom : C₁ →+* C₁ ⊗[A] C₂).Etale :=
    RingHom.Etale.isStableUnderBaseChange.tensorProduct C₁ hg₂
  have hr : (Algebra.TensorProduct.includeRight : C₂ →ₐ[A] C₁ ⊗[A] C₂).toRingHom.Etale :=
    etale_includeRight hg₁
  refine eq_of_two_node_charts hϖ R
    ((Algebra.TensorProduct.includeLeftRingHom : C₁ →+* C₁ ⊗[A] C₂).comp f₁)
    ((Algebra.TensorProduct.includeRight : C₂ →ₐ[A] C₁ ⊗[A] C₂).toRingHom.comp f₂)
    (RingHom.Etale.stableUnderComposition _ _ hf₁ hl)
    (RingHom.Etale.stableUnderComposition _ _ hf₂ hr) ?_ ?_ ?_ ?_ ?_
  · rw [RingHom.comp_assoc, RingHom.comp_assoc, hO₁, hO₂, ← RingHom.comp_assoc,
      ← RingHom.comp_assoc]
    congr 1
    ext a
    simp only [RingHom.coe_comp, Function.comp_apply,
      Algebra.TensorProduct.includeLeftRingHom_apply,
      AlgHom.toRingHom_eq_coe, RingHom.coe_coe, Algebra.TensorProduct.includeRight_apply]
    change algebraMap A C₁ a ⊗ₜ[A] 1 = 1 ⊗ₜ algebraMap A C₂ a
    exact Algebra.TensorProduct.tmul_one_eq_one_tmul a
  · rw [← hR₁] at hu₁; exact hu₁
  · rw [← hR₁] at hv₁; exact hv₁
  · rw [← hR₂] at hu₂; exact hu₂
  · rw [← hR₂] at hv₂; exact hv₂

end Thickness

end SemistableReduction
