/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.NodeGermL

/-!
# Divisors and branches of an ordinary double point (W8′, XL6)

Blueprint §9.7 (XL6). Let `D` be a noetherian normal local domain which is an ordinary double
point `u v = ϖ ^ n` over a DVR `O` (`IsOrdinaryDoublePoint`), with branches `𝔔₁ ∌ u`, `𝔔₂ ∌ v`.

* `isIntegrallyClosed_of_faithfullyFlat` (`FaithfullyFlatNormal`): normality descends along
  faithfully flat maps of domains.
* `IsOrdinaryDoublePoint.swap`: the roles of the coordinates are symmetric.
* `IsOrdinaryDoublePoint.eq_unit_mul_of_dvd`: every divisor `t` of a power of `ϖ` is
  `t = ε ϖ ^ α u ^ e` or `t = ε ϖ ^ α v ^ e` with `ε` a unit (the class group of the node is
  `ℤ / n`, generated by a branch; a Krull argument on the two branch DVRs,
  `IsOrdinaryDoublePoint.dvd_of_branches`).
-/

open IsLocalRing Polynomial

namespace SemistableReduction


section Branches

variable {O D : Type*} [CommRing O] [IsDomain O] [IsDiscreteValuationRing O] [CommRing D]
  [IsDomain D] [IsLocalRing D] [Algebra O D] {ϖ : O} {u v : D} {𝔔₁ 𝔔₂ : Ideal D}

namespace IsOrdinaryDoublePoint

omit [IsDomain O] [IsDiscreteValuationRing O] [IsDomain D] in
/-- The roles of the two coordinates of an ordinary double point are symmetric. -/
theorem swap (H : IsOrdinaryDoublePoint ϖ u v 𝔔₁ 𝔔₂) : IsOrdinaryDoublePoint ϖ v u 𝔔₂ 𝔔₁ where
  maximalIdeal_eq := by rw [H.maximalIdeal_eq, Set.pair_comm u v]
  residue := H.residue
  mul_mem := by rw [mul_comm]; exact H.mul_mem
  isPrime₁ := H.isPrime₂
  isPrime₂ := H.isPrime₁
  mem₁ := H.mem₂
  mem₂ := H.mem₁
  notMem₁ := H.notMem₂
  notMem₂ := H.notMem₁
  reduced₁ := H.reduced₂
  reduced₂ := H.reduced₁
  branches := fun 𝔔 h𝔔 hϖ ↦ (H.branches 𝔔 h𝔔 hϖ).symm

omit [IsDomain O] [IsDiscreteValuationRing O] [IsDomain D] in
/-- A non-unit of `D` stays a non-unit modulo a prime. -/
lemma not_isUnit_mk {𝔔 : Ideal D} [𝔔.IsPrime] {z : D} (hz : z ∈ maximalIdeal D) :
    ¬ IsUnit (Ideal.Quotient.mk 𝔔 z) := by
  rintro ⟨w, hw⟩
  obtain ⟨w', hw'⟩ := Ideal.Quotient.mk_surjective (w⁻¹ : (D ⧸ 𝔔)ˣ).1
  have h1 : z * w' - 1 ∈ 𝔔 := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, map_mul, map_one, hw', ← hw,
      Units.mul_inv, sub_self]
  have h2 : z * w' - 1 ∈ maximalIdeal D :=
    le_maximalIdeal (Ideal.IsPrime.ne_top ‹_›) h1
  have h3 : z * w' ∈ maximalIdeal D := Ideal.mul_mem_right _ _ hz
  exact (maximalIdeal.isMaximal D).ne_top ((Ideal.eq_top_iff_one _).mpr (by
    have := sub_mem h3 h2; simp at this))

/-- Divisibility of unit multiples of powers. -/
lemma unit_mul_pow_dvd {R : Type*} [CommRing R] {π : R} (w w' : Rˣ) {i j : ℕ} (h : i ≤ j) :
    ↑w * π ^ i ∣ ↑w' * π ^ j := by
  rw [Units.mul_left_dvd, Units.dvd_mul_left]; exact pow_dvd_pow π h

variable [IsNoetherianRing D] [IsIntegrallyClosed D] [𝔔₁.IsPrime] [𝔔₂.IsPrime]

omit [IsDomain O] [IsDiscreteValuationRing O] in
/-- **Krull divisibility on the node**: a divisor `Q` of a power of `ϖ` divides `P` as soon as it
does on the two branch DVRs (or is a unit there). -/
theorem dvd_of_branches (H : IsOrdinaryDoublePoint ϖ u v 𝔔₁ 𝔔₂) (hϖ0 : algebraMap O D ϖ ≠ 0)
    {Q P : D} (hQ : Q ≠ 0) (hQN : ∃ N, Q ∣ algebraMap O D ϖ ^ N)
    (h₁ : Q ∉ 𝔔₁ ∨
      algebraMap D (Localization.AtPrime 𝔔₁) Q ∣ algebraMap D (Localization.AtPrime 𝔔₁) P)
    (h₂ : Q ∉ 𝔔₂ ∨
      algebraMap D (Localization.AtPrime 𝔔₂) Q ∣ algebraMap D (Localization.AtPrime 𝔔₂) P) :
    Q ∣ P := by
  obtain ⟨g, hg⟩ := exists_mul_eq_of_forall_dvr hQ fun 𝔮 h𝔮 hdvr ↦ by
    by_cases hp : algebraMap O D ϖ ∈ 𝔮
    · rcases H.eq_or_eq_of_isDiscreteValuationRing hϖ0 hdvr hp with h𝔮' | h𝔮'
      · subst 𝔮
        rcases h₁ with h | h
        · exact .inl ⟨1, by rwa [mul_one]⟩
        · exact .inr h
      · subst 𝔮
        rcases h₂ with h | h
        · exact .inl ⟨1, by rwa [mul_one]⟩
        · exact .inr h
    · obtain ⟨N, R, hR⟩ := hQN
      exact .inl ⟨R, fun hm ↦ hp (h𝔮.mem_of_pow_mem N (hR ▸ hm))⟩
  exact ⟨g, hg.symm⟩

omit [IsDomain O] [IsDiscreteValuationRing O] in
/-- **Divisors of powers of `ϖ`, the case `ord₁ ≤ ord₂`**: if `t ∣ ϖ ^ m` has order `a₁` on the
branch `𝔔₁` and `a₂ ≥ a₁` on `𝔔₂`, then `t = ε ϖ ^ a₁ u ^ e` with `a₂ = a₁ + n e`. -/
theorem eq_unit_mul_of_le (H : IsOrdinaryDoublePoint ϖ u v 𝔔₁ 𝔔₂) {n : ℕ} (hn : 1 ≤ n)
    (huv : u * v = algebraMap O D ϖ ^ n) (hϖ0 : algebraMap O D ϖ ≠ 0) {t : D} {m : ℕ}
    (ht : t ∣ algebraMap O D ϖ ^ m) {a₁ a₂ : ℕ} (w₁ : (Localization.AtPrime 𝔔₁)ˣ)
    (w₂ : (Localization.AtPrime 𝔔₂)ˣ)
    (h₁ : algebraMap D _ t = w₁ * algebraMap O (Localization.AtPrime 𝔔₁) ϖ ^ a₁)
    (h₂ : algebraMap D _ t = w₂ * algebraMap O (Localization.AtPrime 𝔔₂) ϖ ^ a₂)
    (hle : a₁ ≤ a₂) :
    ∃ (ε : Dˣ) (e : ℕ), t = ε * algebraMap O D ϖ ^ a₁ * u ^ e ∧ a₂ = a₁ + n * e := by
  classical
  set p := algebraMap O D ϖ with hp
  set ℓ₁ := algebraMap D (Localization.AtPrime 𝔔₁)
  set ℓ₂ := algebraMap D (Localization.AtPrime 𝔔₂)
  have hp₁ : algebraMap O (Localization.AtPrime 𝔔₁) ϖ = ℓ₁ p :=
    IsScalarTower.algebraMap_apply _ _ _ _
  have hp₂ : algebraMap O (Localization.AtPrime 𝔔₂) ϖ = ℓ₂ p :=
    IsScalarTower.algebraMap_apply _ _ _ _
  rw [hp₁] at h₁
  rw [hp₂] at h₂
  obtain ⟨-, hm₂⟩ := isDiscreteValuationRing_of_reduced hϖ0 H.mem₂ H.reduced₂
  have hinj₁ : Function.Injective ℓ₁ :=
    IsLocalization.injective _ 𝔔₁.primeCompl_le_nonZeroDivisors
  have hinj₂ : Function.Injective ℓ₂ :=
    IsLocalization.injective _ 𝔔₂.primeCompl_le_nonZeroDivisors
  have hpne₁ : ℓ₁ p ≠ 0 := (map_ne_zero_iff _ hinj₁).mpr hϖ0
  have hpne₂ : ℓ₂ p ≠ 0 := (map_ne_zero_iff _ hinj₂).mpr hϖ0
  have hu₁ : IsUnit (ℓ₁ u) := (IsLocalization.AtPrime.isUnit_to_map_iff _ 𝔔₁ u).mpr H.notMem₁
  have hv₂ : IsUnit (ℓ₂ v) := (IsLocalization.AtPrime.isUnit_to_map_iff _ 𝔔₂ v).mpr H.notMem₂
  have hu₂ : ℓ₂ u = ↑(hv₂.unit⁻¹) * ℓ₂ p ^ n := by
    have : ℓ₂ u * ℓ₂ v = ℓ₂ p ^ n := by rw [← map_mul, huv, map_pow]
    rw [← this, mul_comm (ℓ₂ u), ← mul_assoc, IsUnit.val_inv_mul, one_mul]
  have hu0 : u ≠ 0 := left_ne_zero_of_mul (b := v) (by rw [huv]; exact pow_ne_zero _ hϖ0)
  obtain ⟨k, r, hb, hr⟩ : ∃ k r, a₂ = a₁ + n * k + r ∧ r < n :=
    ⟨(a₂ - a₁) / n, (a₂ - a₁) % n, by have := Nat.div_add_mod (a₂ - a₁) n; omega,
      Nat.mod_lt _ (by omega)⟩
  -- `p ^ a₁ u ^ k ∣ t`
  set Q := p ^ a₁ * u ^ k with hQdef
  have hQ0 : Q ≠ 0 := mul_ne_zero (pow_ne_zero _ hϖ0) (pow_ne_zero _ hu0)
  have hQ₁ : ℓ₁ Q = ↑(hu₁.unit ^ k) * ℓ₁ p ^ a₁ := by
    simp only [Q, map_mul, map_pow, Units.val_pow_eq_pow_val, IsUnit.unit_spec]; ring
  have hQ₂ : ℓ₂ Q = ↑(hv₂.unit⁻¹ ^ k) * ℓ₂ p ^ (a₁ + n * k) := by
    simp only [Q, map_mul, map_pow, Units.val_pow_eq_pow_val, hu₂]; ring
  obtain ⟨g, hg⟩ : Q ∣ t := H.dvd_of_branches hϖ0 hQ0
    ⟨a₁ + n * k, v ^ k, by simp only [Q]; rw [pow_add, pow_mul, ← huv]; ring⟩
    (.inr (by rw [hQ₁, h₁]; exact unit_mul_pow_dvd _ _ le_rfl))
    (.inr (by rw [hQ₂, h₂]; exact unit_mul_pow_dvd _ _ (by omega)))
  have ht0 : t ≠ 0 := ne_zero_of_dvd_ne_zero (pow_ne_zero _ hϖ0) ht
  have hg0 : g ≠ 0 := right_ne_zero_of_mul (a := Q) (hg ▸ ht0)
  have hgN : g ∣ p ^ m := (Dvd.intro_left _ hg.symm).trans ht
  have e₁ : (↑w₁ : Localization.AtPrime 𝔔₁) * ℓ₁ p ^ a₁ =
      (↑(hu₁.unit ^ k) * ℓ₁ g) * ℓ₁ p ^ a₁ := by
    rw [← h₁, hg, map_mul, hQ₁]; ring
  have hg₁ : IsUnit (ℓ₁ g) :=
    isUnit_of_mul_isUnit_right ((mul_right_cancel₀ (pow_ne_zero a₁ hpne₁) e₁) ▸ w₁.isUnit)
  have hg₁' : g ∉ 𝔔₁ := (IsLocalization.AtPrime.isUnit_to_map_iff _ 𝔔₁ g).mp hg₁
  have e₂ : (↑w₂ * ℓ₂ p ^ r : Localization.AtPrime 𝔔₂) * ℓ₂ p ^ (a₁ + n * k) =
      (↑(hv₂.unit⁻¹ ^ k) * ℓ₂ g) * ℓ₂ p ^ (a₁ + n * k) := by
    rw [mul_assoc, ← pow_add, show r + (a₁ + n * k) = a₂ by omega, ← h₂, hg, map_mul, hQ₂]
    ring
  have hg₂ := mul_right_cancel₀ (pow_ne_zero _ hpne₂) e₂
  by_cases hr0 : r = 0
  · rw [hr0, pow_zero, mul_one] at hg₂
    have hg₂u : IsUnit (ℓ₂ g) := isUnit_of_mul_isUnit_right (hg₂ ▸ w₂.isUnit)
    have hgu : IsUnit g := isUnit_of_dvd_one (H.dvd_of_branches hϖ0 hg0 ⟨m, hgN⟩
      (.inr (by rw [map_one]; exact hg₁.dvd)) (.inr (by rw [map_one]; exact hg₂u.dvd)))
    refine ⟨hgu.unit, k, ?_, by omega⟩
    rw [hg, IsUnit.unit_spec]
    ring
  exfalso
  -- `g ^ n` and `u ^ r` are associated
  set V : (Localization.AtPrime 𝔔₂)ˣ := (hv₂.unit⁻¹ ^ k)⁻¹ * w₂
  have hg₂' : ℓ₂ g = ↑V * ℓ₂ p ^ r := by
    rw [Units.val_mul, mul_assoc, hg₂, ← mul_assoc, Units.inv_mul, one_mul]
  have hgn : g ^ n ∣ u ^ r := H.dvd_of_branches hϖ0 (pow_ne_zero _ hg0)
    ⟨m * n, by rw [pow_mul]; exact pow_dvd_pow_of_dvd hgN n⟩
    (.inl fun h ↦ hg₁' (Ideal.IsPrime.mem_of_pow_mem ‹_› n h))
    (.inr (by
      rw [map_pow, map_pow, hg₂', hu₂, mul_pow, mul_pow, ← pow_mul, ← pow_mul,
        ← Units.val_pow_eq_pow_val, ← Units.val_pow_eq_pow_val, mul_comm r n]
      exact unit_mul_pow_dvd _ _ le_rfl))
  have hun : u ^ r ∣ g ^ n := H.dvd_of_branches hϖ0 (pow_ne_zero _ hu0)
    ⟨n * r, v ^ r, by rw [pow_mul, ← huv, mul_pow]⟩
    (.inl fun h ↦ H.notMem₁ (Ideal.IsPrime.mem_of_pow_mem ‹_› r h))
    (.inr (by
      rw [map_pow, map_pow, hg₂', hu₂, mul_pow, mul_pow, ← pow_mul, ← pow_mul,
        ← Units.val_pow_eq_pow_val, ← Units.val_pow_eq_pow_val, mul_comm r n]
      exact unit_mul_pow_dvd _ _ le_rfl))
  obtain ⟨x, hx⟩ := hun
  obtain ⟨y, hy⟩ := hgn
  have hxy : x * y = 1 := by
    apply mul_left_cancel₀ (pow_ne_zero r hu0)
    rw [mul_one, ← mul_assoc, ← hx, ← hy]
  have hxu : IsUnit x := IsUnit.of_mul_eq_one y hxy
  -- modulo the first branch
  obtain ⟨-, hirr⟩ := H.isDiscreteValuationRing_quotient
  haveI := (H.isDiscreteValuationRing_quotient).1
  set π := Ideal.Quotient.mk 𝔔₁ u
  have hpm₂ : ℓ₂ p ∈ maximalIdeal (Localization.AtPrime 𝔔₂) := by
    rw [hm₂, hp₂]; exact Ideal.subset_span rfl
  have hg𝔔₂ : g ∈ 𝔔₂ := by
    rw [← IsLocalization.AtPrime.to_map_mem_maximal_iff (Localization.AtPrime 𝔔₂) 𝔔₂ g, hg₂']
    exact Ideal.mul_mem_left _ _ (Ideal.pow_mem_of_mem _ hpm₂ r (by omega))
  have hgm : g ∈ maximalIdeal D := le_maximalIdeal (Ideal.IsPrime.ne_top ‹_›) hg𝔔₂
  have hg0' : Ideal.Quotient.mk 𝔔₁ g ≠ 0 := fun h ↦ hg₁' (Ideal.Quotient.eq_zero_iff_mem.mp h)
  have hgnu := not_isUnit_mk (𝔔 := 𝔔₁) hgm
  obtain ⟨j, hj⟩ := IsDiscreteValuationRing.associated_pow_irreducible hg0' hirr
  have hj0 : j ≠ 0 := by
    rintro rfl
    rw [pow_zero, associated_one_iff_isUnit] at hj
    exact hgnu hj
  obtain ⟨c, hc⟩ := (dvd_pow_self π hj0).trans hj.symm.dvd
  have key : π ^ r * (π ^ (n - r) * c ^ n) = π ^ r * Ideal.Quotient.mk 𝔔₁ x := by
    rw [← mul_assoc, ← pow_add, Nat.add_sub_cancel' hr.le, ← mul_pow, ← hc, ← map_pow, hx,
      map_mul, map_pow]
  have := mul_left_cancel₀ (pow_ne_zero r hirr.ne_zero) key
  have hunit : IsUnit (π ^ (n - r)) := isUnit_of_mul_isUnit_left (this ▸ hxu.map _)
  exact hirr.not_isUnit ((isUnit_pow_iff (by omega)).mp hunit)

omit [IsDomain O] [IsDiscreteValuationRing O] in
/-- **Divisors of powers of `ϖ` on the node** (the class group is `ℤ / n`): every `t ∣ ϖ ^ m` is
`ε ϖ ^ α u ^ e` or `ε ϖ ^ α v ^ e` with `ε` a unit. -/
theorem eq_unit_mul_of_dvd (H : IsOrdinaryDoublePoint ϖ u v 𝔔₁ 𝔔₂) {n : ℕ} (hn : 1 ≤ n)
    (huv : u * v = algebraMap O D ϖ ^ n) (hϖ0 : algebraMap O D ϖ ≠ 0) {t : D} {m : ℕ}
    (ht : t ∣ algebraMap O D ϖ ^ m) :
    ∃ (ε : Dˣ) (α e : ℕ), t = ε * algebraMap O D ϖ ^ α * u ^ e ∨
      t = ε * algebraMap O D ϖ ^ α * v ^ e := by
  have ht0 : t ≠ 0 := ne_zero_of_dvd_ne_zero (pow_ne_zero _ hϖ0) ht
  obtain ⟨hD₁, hm₁⟩ := isDiscreteValuationRing_of_reduced hϖ0 H.mem₁ H.reduced₁
  obtain ⟨hD₂, hm₂⟩ := isDiscreteValuationRing_of_reduced hϖ0 H.mem₂ H.reduced₂
  have hirr₁ := (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr hm₁
  have hirr₂ := (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr hm₂
  have hne : ∀ (𝔔 : Ideal D) [𝔔.IsPrime], algebraMap D (Localization.AtPrime 𝔔) t ≠ 0 :=
    fun 𝔔 _ ↦ (map_ne_zero_iff _
      (IsLocalization.injective _ 𝔔.primeCompl_le_nonZeroDivisors)).mpr ht0
  obtain ⟨a₁, w₁, h₁⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible (hne 𝔔₁) hirr₁
  obtain ⟨a₂, w₂, h₂⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible (hne 𝔔₂) hirr₂
  rcases le_total a₁ a₂ with h | h
  · obtain ⟨ε, e, hε, -⟩ := H.eq_unit_mul_of_le hn huv hϖ0 ht w₁ w₂ h₁ h₂ h
    exact ⟨ε, a₁, e, .inl hε⟩
  · obtain ⟨ε, e, hε, -⟩ :=
      H.swap.eq_unit_mul_of_le hn (by rw [mul_comm]; exact huv) hϖ0 ht w₂ w₁ h₂ h₁ h
    exact ⟨ε, a₂, e, .inr hε⟩

end IsOrdinaryDoublePoint

end Branches

end SemistableReduction
