/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.NodeDeformation
import TemperedFundamentalGroups.SemistableReduction.UnramifiedNode
import TemperedFundamentalGroups.SemistableReduction.AnnulusAt
import TemperedFundamentalGroups.SemistableReduction.NodeNormal

/-!
# The node lemma (W7, S9)

Blueprint §9.9, S9. Let `O` be a discrete valuation ring with uniformizer `ϖ`, `B` a normal
domain of finite type over `O` (a chart of the normalization of a base node chart in a function
field) and `𝔭` a point of `B` over the base node `x y = c₀`. If the special fibre has an ordinary
double point at `𝔭` (`IsOrdinaryDoublePoint` on `B_𝔭`, with coordinates `u', v'`, the outer
branch `𝔔₁` and the inner branch `𝔔₂`), the base coordinate `x` has order `d` on the outer branch
(`s x ≡ η u' ^ d` modulo `(ϖ, v')`) and `y` is a unit on the inner branch, then `B` is an
annulus over the base node at `𝔭` of multiplicity `d` (`IsAnnulusAt ϖ x y d 𝔭`,
`isAnnulusAt_of_isOrdinaryDoublePoint`):

1. the node coordinates are corrected to an honest node `u v = ϖ ^ n` with `x = ε u ^ d`,
   `y = ε' v ^ d` (`IsOrdinaryDoublePoint.exists_node`, `NodeDeformation`);
2. after inverting a common denominator `t`, `B_t` is a domain of finite type over the node
   `O[U, V] ⧸ (U V - ϖ ^ n)` (`U ↦ u`, `V ↦ v`), into which the node embeds
   (`Node.lift_injective`, the node coordinates being transcendental);
3. it is unramified at `𝔭` (the maximal ideal of `B_𝔭` is `(ϖ, u, v)` and the residue field is
   that of `O`, `formallyUnramified_of_map_maximalIdeal`), hence étale at `𝔭`
   (`isEtaleAt_of_isUnramifiedAt`), hence étale over the node on a basic open neighbourhood,
   which is the common étale neighbourhood of `IsAnnulusAt`.
-/

universe u

open IsLocalRing

namespace SemistableReduction

/-- **Local unramifiedness criterion**: a local ring `D`, essentially of finite type over `R`,
whose maximal ideal is generated by the image of its contraction to `R` and whose residue field
is that of `R`, is formally unramified over `R`. -/
theorem formallyUnramified_of_map_maximalIdeal {R D : Type*} [CommRing R] [CommRing D]
    [IsLocalRing D] [Algebra R D] [Algebra.EssFiniteType R D]
    (hmax : maximalIdeal D = Ideal.map (algebraMap R D) ((maximalIdeal D).comap (algebraMap R D)))
    (hres : ∀ z : D, ∃ r : R, z - algebraMap R D r ∈ maximalIdeal D) :
    Algebra.FormallyUnramified R D := by
  let p := (maximalIdeal D).comap (algebraMap R D)
  let Rp := Localization.AtPrime p
  have hunits : ∀ y : p.primeCompl, IsUnit (algebraMap R D y) := fun y ↦ by
    by_contra h
    exact y.2 ((mem_maximalIdeal _).mpr h)
  let φ : Rp →+* D := IsLocalization.lift hunits
  letI : Algebra Rp D := φ.toAlgebra
  have hφ : ∀ r, algebraMap Rp D (algebraMap R Rp r) = algebraMap R D r :=
    fun r ↦ IsLocalization.lift_eq hunits r
  haveI : IsScalarTower R Rp D := IsScalarTower.of_algebraMap_eq fun r ↦ (hφ r).symm
  have hmapmax : (maximalIdeal Rp).map (algebraMap Rp D) = maximalIdeal D := by
    rw [← Localization.AtPrime.map_eq_maximalIdeal, Ideal.map_map,
      ← IsScalarTower.algebraMap_eq, ← hmax]
  haveI : IsLocalHom (algebraMap Rp D) := by
    refine ((local_hom_TFAE (algebraMap Rp D)).out 0 2).mpr ?_
    rw [hmapmax]
  haveI : Algebra.EssFiniteType Rp D := Algebra.EssFiniteType.of_comp R Rp D
  haveI : Algebra.IsSeparable (ResidueField Rp) (ResidueField D) := by
    refine ⟨fun z ↦ ?_⟩
    obtain ⟨z, rfl⟩ := IsLocalRing.residue_surjective z
    obtain ⟨r, hr⟩ := hres z
    have : residue D z = algebraMap (ResidueField Rp) (ResidueField D)
        (residue Rp (algebraMap R Rp r)) := by
      rw [ResidueField.algebraMap_residue, hφ, ← sub_eq_zero, ← map_sub,
        residue_eq_zero_iff]
      exact hr
    rw [this]
    exact isSeparable_algebraMap _
  haveI : Algebra.FormallyUnramified Rp D := Algebra.FormallyUnramified.of_map_maximalIdeal hmapmax
  haveI : Algebra.FormallyUnramified R Rp := .of_isLocalization p.primeCompl
  exact Algebra.FormallyUnramified.comp R Rp D

section Assembly

variable {O : Type u} [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]
  {B : Type u} [CommRing B] [IsDomain B] [IsIntegrallyClosed B] [Algebra O B]
  [Algebra.FiniteType O B] [FaithfulSMul O B]

/-- **The node lemma** (S9): at a point `𝔭` of a normal chart `B` over the base node `x y = c₀`
at which the special fibre is an ordinary double point with branch orders `d`, `B` is
étale-locally the node `O[u, v] ⧸ (u v - ϖ ^ n)` with `x = ε u ^ d`, `y = ε' v ^ d`. -/
theorem isAnnulusAt_of_isOrdinaryDoublePoint {ϖ : O} (hϖ : Irreducible ϖ) (𝔭 : Ideal B)
    [𝔭.IsPrime] {u' v' : B} {𝔔₁ 𝔔₂ : Ideal (Localization.AtPrime 𝔭)}
    (H : IsOrdinaryDoublePoint ϖ (algebraMap B (Localization.AtPrime 𝔭) u')
      (algebraMap B (Localization.AtPrime 𝔭) v') 𝔔₁ 𝔔₂)
    {x y : B} {c₀ : O} (hc₀ : c₀ ≠ 0) (hxy : x * y = algebraMap O B c₀) {d : ℕ} (hd : 1 ≤ d)
    {s η : B} (hs : s ∉ 𝔭) (hη : η ∉ 𝔭)
    (hx : s * x - η * u' ^ d ∈ Ideal.span {algebraMap O B ϖ, v'})
    (hy : algebraMap B (Localization.AtPrime 𝔭) y ∉ 𝔔₂) :
    IsAnnulusAt ϖ x y d 𝔭 := by
  classical
  let D := Localization.AtPrime 𝔭
  let ιD := algebraMap B D
  haveI : IsNoetherianRing B := Algebra.FiniteType.isNoetherianRing O B
  haveI : IsNoetherianRing D := IsLocalization.isNoetherianRing 𝔭.primeCompl D inferInstance
  haveI : IsIntegrallyClosed D :=
    isIntegrallyClosed_of_isLocalization D 𝔭.primeCompl 𝔭.primeCompl_le_nonZeroDivisors
  have hιD : Function.Injective ιD :=
    IsLocalization.injective D 𝔭.primeCompl_le_nonZeroDivisors
  have hOB : Function.Injective (algebraMap O B) := FaithfulSMul.algebraMap_injective O B
  have hϖ0 : algebraMap O D ϖ ≠ 0 := by
    rw [IsScalarTower.algebraMap_apply O B D]
    exact fun h ↦ hϖ.ne_zero (hOB (hιD (by rw [h, map_zero, map_zero])))
  have hmaxD : ∀ z : B, z ∉ 𝔭 → ιD z ∉ maximalIdeal D := fun z hz h ↦
    h (IsLocalization.map_units D (⟨z, hz⟩ : 𝔭.primeCompl))
  -- step 1: an honest node in `D`
  have hxD : ιD s * ιD x - ιD η * ιD u' ^ d ∈
      Ideal.span {algebraMap O D ϖ, ιD v'} := by
    have := Ideal.mem_map_of_mem ιD hx
    rw [Ideal.map_span, Set.image_pair, ← IsScalarTower.algebraMap_apply] at this
    simpa only [map_sub, map_mul, map_pow] using this
  obtain ⟨n, u, v, hn, huv, hmax, hu₁, hv₂, hu, ⟨ε, hε⟩, ⟨ε', hε'⟩⟩ :=
    H.exists_node hϖ hϖ0 hc₀ (by rw [← map_mul, hxy, ← IsScalarTower.algebraMap_apply])
      hd (hmaxD s hs) (hmaxD η hη) hxD hy
  -- step 2: a common denominator `t`
  obtain ⟨⟨t, ht⟩, htint⟩ := IsLocalization.exist_integer_multiples_of_finset 𝔭.primeCompl
    ({u, v, ↑ε, ↑ε⁻¹, ↑ε', ↑ε'⁻¹} : Finset D)
  have hpre : ∀ z ∈ ({u, v, ↑ε, ↑ε⁻¹, ↑ε', ↑ε'⁻¹} : Finset D),
      ∃ b : B, ιD b = ιD t * z := fun z hz ↦ by
    obtain ⟨b, hb⟩ := htint z hz
    exact ⟨b, by rw [hb, Algebra.smul_def]⟩
  let C₀ := Localization.Away t
  have htD : IsUnit (ιD t) := IsLocalization.map_units D (⟨t, ht⟩ : 𝔭.primeCompl)
  let φ₀ : C₀ →+* D := IsLocalization.Away.lift t htD
  have hφ₀ : ∀ b, φ₀ (algebraMap B C₀ b) = ιD b := fun b ↦ IsLocalization.lift_eq _ b
  have hmk : ∀ (b : B) (m : Submonoid.powers t),
      φ₀ (IsLocalization.mk' C₀ b m) * ιD m = ιD b := fun b m ↦ by
    rw [← hφ₀, ← hφ₀, ← map_mul, IsLocalization.mk'_spec]
  have hφ₀inj : Function.Injective φ₀ := by
    rw [injective_iff_map_eq_zero]
    intro z hz
    obtain ⟨⟨b, m⟩, rfl⟩ := IsLocalization.mk'_surjective (Submonoid.powers t) z
    have h1 := hmk b m
    simp only at hz h1
    rw [hz, zero_mul] at h1
    have hb : b = 0 := hιD (by rw [← h1, map_zero])
    simp [hb]
  have hlift : ∀ z ∈ ({u, v, ↑ε, ↑ε⁻¹, ↑ε', ↑ε'⁻¹} : Finset D), ∃ z₀ : C₀, φ₀ z₀ = z := by
    intro z hz
    obtain ⟨b, hb⟩ := hpre z hz
    refine ⟨IsLocalization.mk' C₀ b (⟨t, Submonoid.mem_powers t⟩ : Submonoid.powers t), ?_⟩
    have h1 := hmk b ⟨t, Submonoid.mem_powers t⟩
    simp only at h1
    rw [hb, mul_comm] at h1
    exact (htD.mul_left_cancel h1)
  obtain ⟨u₀, hu₀⟩ := hlift u (by simp)
  obtain ⟨v₀, hv₀⟩ := hlift v (by simp)
  obtain ⟨e₀, he₀⟩ := hlift ↑ε (by simp)
  obtain ⟨e₀i, he₀i⟩ := hlift ↑ε⁻¹ (by simp)
  obtain ⟨f₀, hf₀⟩ := hlift ↑ε' (by simp)
  obtain ⟨f₀i, hf₀i⟩ := hlift ↑ε'⁻¹ (by simp)
  have hφO : ∀ o, φ₀ (algebraMap O C₀ o) = algebraMap O D o := fun o ↦ by
    rw [IsScalarTower.algebraMap_apply O B C₀, hφ₀, ← IsScalarTower.algebraMap_apply]
  have huvD : u * v = algebraMap O D (ϖ ^ n) := by rw [huv, map_pow]
  have huv₀ : u₀ * v₀ = algebraMap O C₀ (ϖ ^ n) := hφ₀inj (by rw [map_mul, hu₀, hv₀, hφO, huvD])
  have he₀u : e₀ * e₀i = 1 := hφ₀inj (by rw [map_mul, he₀, he₀i, Units.mul_inv, map_one])
  have hf₀u : f₀ * f₀i = 1 := hφ₀inj (by rw [map_mul, hf₀, hf₀i, Units.mul_inv, map_one])
  have hx₀ : algebraMap B C₀ x = e₀ * u₀ ^ d :=
    hφ₀inj (by rw [hφ₀, map_mul, map_pow, he₀, hu₀, hε])
  have hy₀ : algebraMap B C₀ y = f₀ * v₀ ^ d :=
    hφ₀inj (by rw [hφ₀, map_mul, map_pow, hf₀, hv₀, hε'])
  -- step 3: `C₀` over the node
  have hϖn : ϖ ^ n ≠ 0 := pow_ne_zero _ hϖ.ne_zero
  haveI : IsDomain (Node O (ϖ ^ n)) := Node.isDomain hϖn
  haveI : IsIntegrallyClosed (Node O (ϖ ^ n)) := Node.isIntegrallyClosed hϖn
  have ht0 : t ≠ 0 := fun h ↦ ht (h ▸ zero_mem 𝔭)
  haveI : IsDomain C₀ := IsLocalization.isDomain_localization
    (powers_le_nonZeroDivisors_of_noZeroDivisors ht0)
  let χ : Node O (ϖ ^ n) →ₐ[O] C₀ := Node.lift u₀ v₀ huv₀
  letI : Algebra (Node O (ϖ ^ n)) C₀ := χ.toRingHom.toAlgebra
  haveI : IsScalarTower O (Node O (ϖ ^ n)) C₀ :=
    IsScalarTower.of_algebraMap_eq fun o ↦ (χ.commutes o).symm
  have hχ : ∀ z, algebraMap (Node O (ϖ ^ n)) C₀ z = χ z := fun _ ↦ rfl
  -- the node embeds
  have hχinj : Function.Injective (algebraMap (Node O (ϖ ^ n)) C₀) := by
    haveI := H.isPrime₁
    have hπ : Ideal.Quotient.mk 𝔔₁ u = Ideal.Quotient.mk 𝔔₁ (ιD u') := by
      rw [← sub_eq_zero, ← map_sub]
      exact Ideal.Quotient.eq_zero_iff_mem.mpr
        ((Ideal.span_singleton_le_iff_mem _).mpr H.mem₁ hu)
    have hirr : Irreducible (Ideal.Quotient.mk 𝔔₁ u) := hπ ▸ H.isDiscreteValuationRing_quotient.2
    have hinjD := Node.lift_injective hϖn huvD
      (fun P hP ↦ H.transcendental_of_irreducible hϖ hϖ0 hirr hP)
    let φ₀A : C₀ →ₐ[O] D := { φ₀ with commutes' := hφO }
    have hcomp : φ₀A.comp χ = Node.lift u v huvD :=
      Node.algHom_ext (by simp [χ, φ₀A, hu₀]) (by simp [χ, φ₀A, hv₀])
    intro a b hab
    apply hinjD
    rw [← hcomp]
    simp only [AlgHom.comp_apply]
    exact congrArg φ₀A hab
  -- finiteness
  haveI : Algebra.FiniteType B C₀ :=
    IsLocalization.finiteType_of_monoid_fg (Submonoid.powers t) C₀
  haveI : Algebra.FiniteType O C₀ := Algebra.FiniteType.trans (S := B) inferInstance inferInstance
  haveI : Algebra.FiniteType (Node O (ϖ ^ n)) C₀ :=
    .of_restrictScalars_finiteType O (Node O (ϖ ^ n)) C₀
  -- the point `P` of `C₀` and `D = (C₀)_P`
  letI : Algebra C₀ D := φ₀.toAlgebra
  have hC₀D : ∀ z, algebraMap C₀ D z = φ₀ z := fun _ ↦ rfl
  haveI : IsScalarTower B C₀ D := IsScalarTower.of_algebraMap_eq fun b ↦ (hφ₀ b).symm
  let P : Ideal C₀ := (maximalIdeal D).comap (algebraMap C₀ D)
  haveI : P.IsPrime := Ideal.comap_isPrime _ _
  haveI : IsLocalization P.primeCompl D := by
    rw [isLocalization_iff]
    refine ⟨fun y ↦ ?_, fun z ↦ ?_, fun {a b} hab ↦ ⟨1, by rw [hφ₀inj hab]⟩⟩
    · by_contra h
      exact y.2 ((mem_maximalIdeal _).mpr h)
    · obtain ⟨⟨b, m⟩, hbm⟩ := IsLocalization.surj 𝔭.primeCompl z
      refine ⟨⟨algebraMap B C₀ b, algebraMap B C₀ m, ?_⟩, ?_⟩
      · change algebraMap C₀ D (algebraMap B C₀ m) ∉ maximalIdeal D
        rw [← IsScalarTower.algebraMap_apply]
        exact hmaxD m m.2
      · simp only
        rw [← IsScalarTower.algebraMap_apply, ← IsScalarTower.algebraMap_apply]
        exact hbm
  -- unramified at `P` over the node
  let N := Node O (ϖ ^ n)
  letI : Algebra N D := ((algebraMap C₀ D).comp (algebraMap N C₀)).toAlgebra
  haveI : IsScalarTower N C₀ D := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
  have hND : ∀ z, algebraMap N D z = φ₀ (χ z) := fun _ ↦ rfl
  haveI : Algebra.EssFiniteType C₀ D := .of_isLocalization D P.primeCompl
  haveI : Algebra.EssFiniteType N D := .comp N C₀ D
  have hunrD : Algebra.FormallyUnramified N D := by
    refine formallyUnramified_of_map_maximalIdeal ?_ fun z ↦ ?_
    · refine le_antisymm ?_ Ideal.map_comap_le
      have hmem : ∀ w : N, algebraMap N D w ∈ maximalIdeal D →
          algebraMap N D w ∈ Ideal.map (algebraMap N D)
            ((maximalIdeal D).comap (algebraMap N D)) :=
        fun w hw ↦ Ideal.mem_map_of_mem _ hw
      have hu' : algebraMap N D (Node.u (ϖ ^ n)) = u := by
        rw [hND]; simp [χ, hu₀]
      have hv' : algebraMap N D (Node.v (ϖ ^ n)) = v := by
        rw [hND]; simp [χ, hv₀]
      have hp' : algebraMap N D (algebraMap O N ϖ) = algebraMap O D ϖ := by
        rw [hND, AlgHom.commutes, hφO]
      have hmaxu : u ∈ maximalIdeal D := by
        rw [hmax]; exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert _ _))
      have hmaxv : v ∈ maximalIdeal D := by
        rw [hmax]; exact Ideal.subset_span (by simp)
      have hmaxp : algebraMap O D ϖ ∈ maximalIdeal D := by
        rw [hmax]; exact Ideal.subset_span (Set.mem_insert _ _)
      calc maximalIdeal D = Ideal.span {algebraMap O D ϖ, u, v} := hmax
        _ ≤ _ := by
          rw [Ideal.span_le]
          intro z hz
          simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
          rcases hz with hz | hz | hz <;> rw [hz]
          · rw [← hp'] at hmaxp ⊢; exact hmem _ hmaxp
          · rw [← hu'] at hmaxu ⊢; exact hmem _ hmaxu
          · rw [← hv'] at hmaxv ⊢; exact hmem _ hmaxv
    · obtain ⟨o, ho⟩ := H.residue z
      refine ⟨algebraMap O N o, ?_⟩
      rwa [hND, AlgHom.commutes, hφO]
  let e : Localization.AtPrime P ≃ₐ[C₀] D := IsLocalization.algEquiv P.primeCompl _ _
  haveI : Algebra.IsUnramifiedAt N P :=
    Algebra.FormallyUnramified.of_equiv (e.symm.restrictScalars N)
  have hEt : Algebra.IsEtaleAt N P := isEtaleAt_of_isUnramifiedAt hχinj P
  -- an étale neighbourhood
  haveI : IsNoetherianRing N := Algebra.FiniteType.isNoetherianRing O N
  haveI : Algebra.FinitePresentation N C₀ :=
    Algebra.FinitePresentation.of_finiteType.mp inferInstance
  obtain ⟨f, hfP, hfet⟩ := Algebra.exists_etale_of_isEtaleAt (R := N) P
  let C := Localization.Away f
  let g : B →+* C := (algebraMap C₀ C).comp (algebraMap B C₀)
  have hg : g.Etale :=
    RingHom.Etale.stableUnderComposition _ _
      (RingHom.etale_algebraMap.mpr (Algebra.Etale.of_isLocalizationAway t))
      (RingHom.etale_algebraMap.mpr (Algebra.Etale.of_isLocalizationAway f))
  have hfN : (algebraMap N C).Etale := RingHom.etale_algebraMap.mpr hfet
  have hdisj : Disjoint (Submonoid.powers f : Set C₀) P := by
    rw [Set.disjoint_left]
    rintro _ ⟨k, rfl⟩ hk
    exact hfP (‹P.IsPrime›.mem_of_pow_mem k hk)
  let 𝔮 : Ideal C := P.map (algebraMap C₀ C)
  have h𝔮 : 𝔮.IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint (Submonoid.powers f) C P inferInstance hdisj
  have hP𝔮 : 𝔮.comap (algebraMap C₀ C) = P :=
    IsLocalization.under_map_of_isPrime_disjoint (Submonoid.powers f) C inferInstance hdisj
  have hNC : ∀ z : N, algebraMap N C z = algebraMap C₀ C (χ z) := fun z ↦
    IsScalarTower.algebraMap_apply N C₀ C z
  have huP : u₀ ∈ P := by
    change algebraMap C₀ D u₀ ∈ maximalIdeal D
    rw [hC₀D, hu₀, hmax]
    exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert _ _))
  have hvP : v₀ ∈ P := by
    change algebraMap C₀ D v₀ ∈ maximalIdeal D
    rw [hC₀D, hv₀, hmax]
    exact Ideal.subset_span (by simp)
  have hunit : ∀ a b : C₀, a * b = 1 → IsUnit (algebraMap C₀ C a) := fun a b hab ↦
    IsUnit.of_mul_eq_one (b := algebraMap C₀ C b) (by rw [← map_mul, hab, map_one])
  refine ⟨n, C, inferInstance, g, algebraMap N C, 𝔮, hg, hfN, h𝔮, ?_, ?_, ?_, ?_,
    (hunit e₀ e₀i he₀u).unit, (hunit f₀ f₀i hf₀u).unit, ?_, ?_⟩
  · change Ideal.comap (algebraMap B C₀) (Ideal.comap (algebraMap C₀ C) 𝔮) = 𝔭
    rw [hP𝔮]
    change Ideal.comap (algebraMap B C₀) (Ideal.comap (algebraMap C₀ D) (maximalIdeal D)) = 𝔭
    rw [Ideal.comap_comap, ← IsScalarTower.algebraMap_eq]
    exact Localization.AtPrime.under_maximalIdeal
  · ext o
    simp only [RingHom.comp_apply, g]
    rw [hNC, AlgHom.commutes, ← IsScalarTower.algebraMap_apply O B C₀]
  · rw [hNC]
    simpa [χ] using Ideal.mem_map_of_mem _ huP
  · rw [hNC]
    simpa [χ] using Ideal.mem_map_of_mem _ hvP
  · simp only [IsUnit.unit_spec, g, RingHom.comp_apply, hx₀, hNC, map_mul, map_pow]
    simp [χ]
  · simp only [IsUnit.unit_spec, g, RingHom.comp_apply, hy₀, hNC, map_mul, map_pow]
    simp [χ]

end Assembly

end SemistableReduction
