/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.NormedTower
import TemperedFundamentalGroups.SemistableReduction.PGroupChain
import TemperedFundamentalGroups.SemistableReduction.Gauss

/-!
# Inertially generated fields have no immediate extensions

Blueprint §9.4, G1 (Kuhlmann, *Elimination of ramification I*, Lemma 5.2, mixed characteristic).
Let `C` be algebraically closed of characteristic `0` with `‖p‖ < 1`.

* `IsGaussComplete C x`: a complete field `K ⊇ C` is the closure of `C(x)`, with `‖x‖ ≤ 1` and
  `x̄` transcendental over the residue field `k` of `C` (e.g. the completion of a Gauss-valued
  rational function field);
* `isInertiallyGenerated_of_unramified`: a finite unramified extension `B` of such a `K`
  (`f = [B : K]`, separable residue field extension) is inertially generated (by `x`);
* `exists_norm_eq`: an inertially generated field has the values of `C`;
* `eq_bot_of_isPurelyInseparable` (wild step): if `M₀` is inertially generated, `N / M₀` finite
  Galois with purely inseparable residue field extension, then `N / M₀` has no proper
  intermediate field `X` with `f(X | M₀) = 1` (the inertia group is a `p`-group; a maximal proper
  subgroup containing `Gal(N / X)` is normal of index `p`, and its fixed field has `f = p` by F5);
* **G1'** `inertiaDeg_eq_finrank_of_isSeparable`: a finite extension `B / K` of a Gauss-complete
  `K` with separable residue field extension is unramified: `f(B | K) = [B : K]`;
* **G1** `finrank_eq_one_of_immediate`: an inertially generated field has no proper immediate
  finite extension.
-/

open Polynomial IsLocalRing Valuation
open scoped IntermediateField

namespace SemistableReduction

open FundamentalInequality DenseCompletion KummerNormalForm DiscreteCoefficients
  InertiallyGenerated NormedTower

namespace NoImmediate

local notation "κ" X => ResidueField (HenselComplete.integers X)

section Gauss

variable {C K : Type*} [NontriviallyNormedField C] [IsUltrametricDist C]
  [NontriviallyNormedField K] [IsUltrametricDist K] [NormedAlgebra C K]

variable (C) in
/-- `K` is the closure of `C(x)`, where `‖x‖ ≤ 1` and the residue `x̄` is transcendental over the
residue field of `C` (for complete `K`: `K = \widehat{C(x)}`, Gauss-valued). -/
structure IsGaussComplete (x : K) : Prop where
  norm_le_one : ‖x‖ ≤ 1
  transcendental : Transcendental (κ C) (rd x)
  genClosure_eq_top : genClosure C x = ⊤

variable {B : Type*} [NormedField B] [IsUltrametricDist B] [NormedAlgebra K B]
  [NormedAlgebra C B] [IsScalarTower C K B]

omit [IsUltrametricDist C] [IsUltrametricDist K] [IsUltrametricDist B] in
/-- The image of `\widehat{C(x)}` lies in the closure of `C(x)`. -/
lemma fieldRange_le_genClosure {x : K} (hx : genClosure C x = ⊤) :
    (algebraMap K B).fieldRange ≤ genClosure C (algebraMap K B x) := by
  rintro _ ⟨k, rfl⟩
  have hk : k ∈ closure ((IntermediateField.adjoin C {x}).toSubfield : Set K) := by
    have : k ∈ genClosure C x := by rw [hx]; trivial
    exact this
  have hcont : Continuous (algebraMap K B) :=
    (AddMonoidHomClass.isometry_of_norm (algebraMap K B) (norm_algebraMap' B)).continuous
  have h1 := mem_closure_image hcont.continuousAt hk
  refine closure_mono ?_ h1
  rintro _ ⟨y, hy, rfl⟩
  have hmap : (IntermediateField.adjoin C {x}).map (IsScalarTower.toAlgHom C K B) =
      IntermediateField.adjoin C {algebraMap K B x} := by
    rw [IntermediateField.adjoin_map, Set.image_singleton]
    rfl
  have : algebraMap K B y ∈ (IntermediateField.adjoin C {x}).map (IsScalarTower.toAlgHom C K B) :=
    ⟨y, hy, rfl⟩
  rw [hmap] at this
  exact this

variable [FiniteDimensional K B]

omit [IsUltrametricDist C] [IsUltrametricDist K] [IsUltrametricDist B] in
/-- `B` is finite over the closure of `C(x)` in `B`. -/
lemma finiteDimensional_genClosure {x : K} (hx : genClosure C x = ⊤) :
    FiniteDimensional (genClosure C (algebraMap K B x)) B ∧
      Module.finrank (genClosure C (algebraMap K B x)) B ≤ Module.finrank K B := by
  set S := genClosure C (algebraMap K B x)
  have hS := fieldRange_le_genClosure (B := B) hx
  letI : Algebra K S := (RingHom.codRestrict (algebraMap K B) S fun k ↦ hS ⟨k, rfl⟩).toAlgebra
  haveI : IsScalarTower K S B := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
  haveI : FiniteDimensional S B := Module.Finite.of_restrictScalars_finite K S B
  haveI : FiniteDimensional K S := Module.Finite.of_injective
    (IsScalarTower.toAlgHom K S B).toLinearMap (algebraMap S B).injective
  refine ⟨inferInstance, ?_⟩
  rw [← Module.finrank_mul_finrank K S B]
  exact Nat.le_mul_of_pos_left _ Module.finrank_pos

/-- **Unramified extensions of `\widehat{C(x)}` are inertially generated.** If `K` is
Gauss-complete (generated by `x`) and `B / K` is finite with `f(B | K) = [B : K]` and separable
residue field extension, then `B` is inertially generated by `x`. -/
theorem isInertiallyGenerated_of_unramified {x : K} (hx : IsGaussComplete C x)
    (hf : inertiaDeg (NormedField.valuation (K := K)) (NormedField.valuation (K := B)) =
      Module.finrank K B)
    [Algebra.IsSeparable (κ K) (κ B)] : IsInertiallyGenerated C (algebraMap K B x) := by
  set y := algebraMap K B x
  have hy1 : ‖y‖ ≤ 1 := by rw [norm_algebraMap']; exact hx.norm_le_one
  have hrd : rd y = algebraMap (κ K) (κ B) (rd x) := rd_algebraMap' hx.norm_le_one
  have htr : Transcendental (κ C) (rd y) := by
    rw [hrd, transcendental_algebraMap_iff (algebraMap (κ K) (κ B)).injective]
    exact hx.transcendental
  obtain ⟨hfin, hle⟩ := finiteDimensional_genClosure (B := B) hx.genClosure_eq_top
  set S := genClosure C y
  set R := residueSubfield S
  set ρ := algebraMap (κ K) (κ B)
  -- the residue field of `S` is the image of `κ_K`
  have hR : R = ρ.fieldRange := by
    refine le_antisymm ?_ ?_
    · change residueSubfield (genClosure C y) ≤ _
      rw [residueSubfield_genClosure hy1 htr]
      have hle' : IntermediateField.adjoin (κ C) {rd y} ≤
          (IsScalarTower.toAlgHom (κ C) (κ K) (κ B)).fieldRange := by
        rw [IntermediateField.adjoin_simple_le_iff, hrd]
        exact ⟨rd x, rfl⟩
      exact hle'
    · rw [fieldRange_algebraMap_residueField]
      exact residueSubfield_mono (fieldRange_le_genClosure hx.genClosure_eq_top)
  haveI : FiniteDimensional (κ K) (κ B) := finite_residueField
  letI : Algebra (κ K) R := (RingHom.codRestrict ρ R fun a ↦ hR ▸ ⟨a, rfl⟩).toAlgebra
  haveI : IsScalarTower (κ K) R (κ B) := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
  have hsurj : Function.Surjective (algebraMap (κ K) R) := by
    rintro ⟨r, hr⟩
    rw [hR] at hr
    obtain ⟨a, rfl⟩ := hr
    exact ⟨a, rfl⟩
  have hKR : Module.finrank (κ K) R = 1 :=
    Subalgebra.bot_eq_top_iff_finrank_eq_one.1
      (eq_top_iff.2 fun r _ ↦ Algebra.mem_bot.2 (hsurj r))
  haveI : FiniteDimensional R (κ B) := Module.Finite.of_restrictScalars_finite (κ K) R (κ B)
  haveI : FiniteDimensional (κ K) R := Module.Finite.of_injective
    (IsScalarTower.toAlgHom (κ K) R (κ B)).toLinearMap (algebraMap R (κ B)).injective
  refine ⟨hy1, htr, hfin, inferInstance,
    Algebra.isSeparable_tower_top_of_isSeparable (κ K) R (κ B), ?_⟩
  calc Module.finrank S B ≤ Module.finrank K B := hle
    _ = inertiaDeg (NormedField.valuation (K := K)) (NormedField.valuation (K := B)) := hf.symm
    _ = Module.finrank R (κ B) := by
      rw [inertiaDeg, ← Module.finrank_mul_finrank (κ K) R (κ B), hKR, one_mul]

end Gauss

section Residue

variable {M N : Type*} [NontriviallyNormedField M] [IsUltrametricDist M] [NormedField N]
  [IsUltrametricDist N] [NormedAlgebra M N]

/-- If the residues of the elements of an intermediate field `X` lie in the residue field of
`M`, then `f(X | M) ≤ 1`. -/
theorem inertiaDeg_le_one_of_rd_mem (X : IntermediateField M N)
    (h : ∀ a : N, a ∈ X → ‖a‖ ≤ 1 → rd a ∈ (algebraMap (κ M) (κ N)).range) :
    inertiaDeg (NormedField.valuation (K := M)) (NormedField.valuation (K := X)) ≤ 1 := by
  have hsurj : Function.Surjective (algebraMap (κ M) (κ X)) := by
    intro r
    obtain ⟨a, rfl⟩ := residue_surjective r
    obtain ⟨s, hs⟩ := h ((a : X) : N) (a : X).2 (HenselComplete.norm_le_one a)
    refine ⟨s, (algebraMap (κ X) (κ N)).injective ?_⟩
    rw [← IsScalarTower.algebraMap_apply (κ M) (κ X) (κ N), hs, ← rd_coe]
    exact rd_algebraMap' (HenselComplete.norm_le_one a)
  rw [inertiaDeg, (Subalgebra.bot_eq_top_iff_finrank_eq_one).1
    (eq_top_iff.2 fun r _ ↦ Algebra.mem_bot.2 (hsurj r))]

end Residue

section GenField

variable {C M : Type*} [NontriviallyNormedField C] [IsUltrametricDist C]
  [NontriviallyNormedField M] [IsUltrametricDist M] [NormedAlgebra C M]

variable (C) in
/-- The closure `\widehat{C(z)}` of `C(z)` in `M` as an intermediate field. -/
noncomputable abbrev genField (z : M) : IntermediateField C M :=
  (genClosure C z).toIntermediateField (algebraMap_mem_genClosure z)

omit [IsUltrametricDist C] [IsUltrametricDist M] in
lemma fieldRange_genField (z : M) : (algebraMap (genField C z) M).fieldRange = genClosure C z := by
  ext x
  exact ⟨fun ⟨k, hk⟩ ↦ hk ▸ k.2, fun hx ↦ ⟨⟨x, hx⟩, rfl⟩⟩

omit [IsUltrametricDist C] [IsUltrametricDist M] in
lemma finrank_genField (z : M) :
    Module.finrank (genField C z) M = Module.finrank (genClosure C z) M := by
  rw [← finrank_fieldRange_eq, fieldRange_genField]

omit [IsUltrametricDist C] [IsUltrametricDist M] in
lemma finite_genField_iff (z : M) :
    Module.Finite (genField C z) M ↔ Module.Finite (genClosure C z) M := by
  rw [← finite_fieldRange_iff, fieldRange_genField]

omit [IsUltrametricDist C] in
lemma fieldRange_residue_genField (z : M) :
    (algebraMap (κ (genField C z)) (κ M)).fieldRange = residueSubfield (genClosure C z) := by
  rw [fieldRange_algebraMap_residueField, fieldRange_genField]

omit [IsUltrametricDist C] in
lemma inertiaDeg_genField (z : M) :
    inertiaDeg (NormedField.valuation (K := genField C z)) (NormedField.valuation (K := M)) =
      Module.finrank (residueSubfield (genClosure C z)) (κ M) := by
  rw [inertiaDeg, ← finrank_fieldRange_eq, fieldRange_residue_genField]

omit [IsUltrametricDist C] in
lemma finite_residue_genField_iff (z : M) :
    Module.Finite (κ (genField C z)) (κ M) ↔
      Module.Finite (residueSubfield (genClosure C z)) (κ M) := by
  rw [← finite_fieldRange_iff, fieldRange_residue_genField]

omit [IsUltrametricDist C] in
lemma isSeparable_residue_genField_iff (z : M) :
    Algebra.IsSeparable (κ (genField C z)) (κ M) ↔
      Algebra.IsSeparable (residueSubfield (genClosure C z)) (κ M) := by
  rw [← isSeparable_fieldRange_iff, fieldRange_residue_genField]

omit [IsUltrametricDist C] [IsUltrametricDist M] in
instance completeSpace_genField [CompleteSpace M] (z : M) : CompleteSpace (genField C z) :=
  (Subfield.isClosed_topologicalClosure _).completeSpace_coe

omit [IsUltrametricDist C] [IsUltrametricDist M] in
/-- `C(z)` is dense in `\widehat{C(z)}`. -/
theorem genClosure_genField_eq_top (z : M) :
    genClosure C (⟨z, mem_genClosure_self z⟩ : genField C z) = ⊤ := by
  set z' : genField C z := ⟨z, mem_genClosure_self z⟩
  refine eq_top_iff.2 fun y _ ↦ ?_
  change y ∈ closure ((IntermediateField.adjoin C {z'}).toSubfield : Set (genField C z))
  rw [Topology.IsInducing.subtypeVal.closure_eq_preimage_closure_image]
  have hmap : (IntermediateField.adjoin C {z'}).map (genField C z).val =
      IntermediateField.adjoin C {z} := by
    rw [IntermediateField.adjoin_map, Set.image_singleton]
    rfl
  have : Subtype.val '' ((IntermediateField.adjoin C {z'}).toSubfield : Set (genField C z)) =
      (IntermediateField.adjoin C {z} : Set M) := by
    rw [← hmap]
    rfl
  have h2 : (y : M) ∈ closure (IntermediateField.adjoin C {z} : Set M) := y.2
  rw [← this] at h2
  exact h2

/-- `\widehat{C(z)}` is Gauss-complete. -/
theorem isGaussComplete_genField {z : M} (hz : ‖z‖ ≤ 1) (htr : Transcendental (κ C) (rd z)) :
    IsGaussComplete C (⟨z, mem_genClosure_self z⟩ : genField C z) := by
  set z' : genField C z := ⟨z, mem_genClosure_self z⟩
  refine ⟨hz, ?_, genClosure_genField_eq_top z⟩
  have h := rd_algebraMap' (B := M) (a := z') hz
  change rd z = _ at h
  rwa [h, transcendental_algebraMap_iff
    (algebraMap (κ (genField C z)) (κ M)).injective] at htr

end GenField

section Wild

variable {C : Type*} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
  {M : Type*} [NontriviallyNormedField M] [IsUltrametricDist M] [CompleteSpace M]
  [NormedAlgebra C M]
include hp hp1

/-- **Values of inertially generated fields** are the values of `C` (density of the span of a
lifted Frobenius-closed basis, F2). -/
theorem exists_norm_eq {z : M} (hM : IsInertiallyGenerated C z) (c : M) :
    ∃ γ : C, ‖c‖ = ‖γ‖ := by
  by_cases hc : c = 0
  · exact ⟨0, by rw [hc, norm_zero, norm_zero]⟩
  obtain ⟨L⟩ := nonempty_liftedFrobeniusBasis hp hp1 hM
  obtain ⟨f, hf, -⟩ := L.exists_approx c (norm_pos_iff.2 hc)
  have hfc : ‖L.val f‖ = ‖c‖ :=
    DenseCompletion.norm_eq_of_norm_sub_lt (by rwa [norm_sub_rev] at hf)
  have hf0 : f ≠ 0 := by
    rintro rfl
    rw [LiftedFrobeniusFamily.val_zero, norm_zero, eq_comm, _root_.norm_eq_zero] at hfc
    exact hc hfc
  obtain ⟨i, -, hi⟩ := L.exists_coeff_eq f hf0
  exact ⟨f i, by rw [← hfc, hi]⟩

/-- The value group of an inertially generated field is divisible. -/
theorem exists_valuation_pow_eq {z : M} (hM : IsInertiallyGenerated C z) (c : M) {n : ℕ}
    (hn : 0 < n) :
    ∃ d : M, NormedField.valuation d ^ n = NormedField.valuation c := by
  obtain ⟨γ, hγ⟩ := exists_norm_eq hp hp1 hM c
  obtain ⟨δ, hδ⟩ := IsAlgClosed.exists_pow_nat_eq γ hn
  refine ⟨algebraMap C M δ, ?_⟩
  rw [NormedField.valuation_apply, NormedField.valuation_apply, ← nnnorm_pow, ← map_pow, hδ]
  exact NNReal.eq (by rw [coe_nnnorm, coe_nnnorm, norm_algebraMap', hγ])

variable {N : Type*} [NormedField N] [IsUltrametricDist N] [NormedAlgebra M N]
  [FiniteDimensional M N] [IsGalois M N]

/-- **The wild step.** Let `M` be inertially generated and `N / M` finite Galois with purely
inseparable residue field extension. An intermediate field `X` with `f(X | M) = 1` is trivial:
otherwise the fixed field of a maximal subgroup containing `Gal(N / X)` (normal of index `p`, the
Galois group being a `p`-group, D2 + D4) is a Galois extension of degree `p` inside `X` with
`f = p` (F5). -/
theorem eq_bot_of_isPurelyInseparable {z : M} (hM : IsInertiallyGenerated C z)
    [IsPurelyInseparable (κ M) (κ N)] (X : IntermediateField M N)
    (hX : inertiaDeg (NormedField.valuation (K := M)) (NormedField.valuation (K := X)) ≤ 1) :
    X = ⊥ := by
  haveI := Fact.mk hp
  have hσ : ∀ (σ : N ≃ₐ[M] N) (x : N),
      NormedField.valuation (σ x) = NormedField.valuation (K := N) x :=
    fun σ x ↦ UniqueExtension.valuation_algEquiv_apply (K := M) _ σ x
  -- the inertia group is everything
  have hT : inertia (NormedField.valuation (K := M)) hσ = ⊤ := by
    refine eq_top_iff.2 fun σ _ ↦ ?_
    refine (MonoidHom.mem_ker).2 (AlgEquiv.ext fun r ↦ ?_)
    have := congrArg (fun f : (κ N) →ₐ[κ M] (κ N) ↦ f r)
      (Subsingleton.elim (residueHom (NormedField.valuation (K := M)) hσ σ).toAlgHom
        (1 : (κ N) ≃ₐ[κ M] (κ N)).toAlgHom)
    exact this
  -- it is a `p`-group
  have hpM1 : ‖(p : M)‖ < 1 := by
    rw [← map_natCast (algebraMap C M), norm_algebraMap']
    exact hp1
  haveI : CharP (κ M) p := charP_residueField hp hpM1
  have hG : IsPGroup p (N ≃ₐ[M] N) := by
    have h := isPGroup_inertia (u := NormedField.valuation (K := M)) hσ
      (fun c n hn ↦ exists_valuation_pow_eq hp hp1 hM c hn) (fun ℓ hℓ _ ↦ by
        haveI : NeZero (ℓ : C) := ⟨Nat.cast_ne_zero.2 hℓ.ne_zero⟩
        obtain ⟨ζ, hζ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot C ℓ
        exact ⟨algebraMap C M ζ, hζ.map_of_injective (algebraMap C M).injective⟩)
    rw [ringChar.eq (κ M) p, hT] at h
    exact h.of_equiv Subgroup.topEquiv
  -- a maximal subgroup containing `Gal(N / X)`
  by_contra hne
  set H := X.fixingSubgroup with hH
  have hHtop : H ≠ ⊤ := by
    intro h
    apply hne
    rw [← IsGalois.fixedField_fixingSubgroup X, ← hH, h, IsGalois.fixedField_top]
  obtain ⟨m, c, hc0, hcm, hc⟩ := PGroupChain.exists_chain hG H
  have hm : m ≠ 0 := by
    rintro rfl
    exact hHtop (hc0.symm.trans hcm)
  obtain ⟨k, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hm
  obtain ⟨hle, hnormal, hidx⟩ := hc k (Nat.lt_succ_self k)
  rw [hcm] at hle hnormal hidx
  haveI : (c k).Normal := by
    have := (Subgroup.normal_subgroupOf_iff_le_normalizer hle).1 hnormal
    exact ⟨fun n hn g ↦ (this (Subgroup.mem_top g) n).1 hn⟩
  have hHc : H ≤ c k := by
    have : ∀ i ≤ k, c 0 ≤ c i := by
      intro i hi
      induction i with
      | zero => exact le_rfl
      | succ i ih => exact (ih (by omega)).trans (hc i (by omega)).1
    exact hc0 ▸ this k le_rfl
  set Y := IntermediateField.fixedField (c k)
  have hYX : Y ≤ X := by
    rw [← IsGalois.fixedField_fixingSubgroup X]
    exact IntermediateField.fixedField_le hHc
  have hYdeg : Module.finrank M Y = p := by
    have h1 := IntermediateField.finrank_fixedField_eq_card (c k)
    have h2 := Module.finrank_mul_finrank M Y N
    have h3 := IsGalois.card_aut_eq_finrank M N
    rw [h1, ← h3, ← Subgroup.index_mul_card (c k)] at h2
    rw [Subgroup.relIndex_top_right] at hidx
    rw [hidx] at h2
    exact Nat.eq_of_mul_eq_mul_right Nat.card_pos h2
  have hF5 := (KummerDefectless.ramificationIdx_eq_one_and_inertiaDeg_eq
    (NormedField.valuation (K := Y)) hp hp1 hM hYdeg).2
  have hmono := inertiaDeg_le_of_le hYX
  rw [hF5, hYdeg] at hmono
  exact absurd (hmono.trans hX) (not_le.2 hp.one_lt)

end Wild

section Core

variable {C : Type*} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
  {K : Type*} [NontriviallyNormedField K] [IsUltrametricDist K] [CompleteSpace K]
  [NormedAlgebra C K]
  {N : Type*} [NormedField N] [IsUltrametricDist N] [NormedAlgebra K N] [NormedAlgebra C N]
  [IsScalarTower C K N] [FiniteDimensional K N] [IsGalois K N]
  {B : Type*} [NontriviallyNormedField B] [IsUltrametricDist B] [NormedAlgebra K B]
  [NormedAlgebra B N] [IsScalarTower K B N]
include hp hp1

variable (N) in
include N in
/-- **G1'** (inside a Galois extension): let `K` be Gauss-complete, `N / K` finite Galois and
`K ⊆ B ⊆ N` with `κ_B / κ_K` separable. Then `B / K` is unramified: `f(B | K) = [B : K]`.

Proof: `B` lies in the fixed field `K_T` of the inertia group. Let `y` be a Hensel generator of
the unramified extension `K_T / K` (D3, C2). `B(y) / B` is unramified with separable residue
field extension (C4), so the residues of `X' = K_T(B) ⊆ B(y)` are separable over `κ_K`, hence lie
in `κ_{K_T}` (`κ_N / κ_{K_T}` is purely inseparable): `f(X' | K_T) = 1`. `K_T` is inertially
generated, so the wild step gives `X' = K_T`. -/
theorem inertiaDeg_eq_finrank_of_isSeparable_of_isGalois {x : K} (hx : IsGaussComplete C x)
    [Algebra.IsSeparable (κ K) (κ B)] :
    inertiaDeg (NormedField.valuation (K := K)) (NormedField.valuation (K := B)) =
      Module.finrank K B := by
  haveI : FiniteDimensional K B := Module.Finite.of_injective
    (IsScalarTower.toAlgHom K B N).toLinearMap (algebraMap B N).injective
  have hσ : ∀ (σ : N ≃ₐ[K] N) (y : N),
      NormedField.valuation (σ y) = NormedField.valuation (K := N) y :=
    fun σ y ↦ UniqueExtension.valuation_algEquiv_apply (K := K) _ σ y
  set KT := IntermediateField.fixedField (inertia (NormedField.valuation (K := K)) hσ)
  have hcomap : (NormedField.valuation (K := N)).comap (algebraMap KT N) =
      NormedField.valuation (K := KT) := comap_valuation_algebraMap
  -- D3: `K_T / K` is unramified, `κ_N / κ_{K_T}` is purely inseparable
  obtain ⟨-, hfT, hsepT⟩ := unramified_fixedField_inertia (u := NormedField.valuation (K := K))
    (w := NormedField.valuation (K := N)) hσ
  have hfT' : inertiaDeg (NormedField.valuation (K := K)) (NormedField.valuation (K := KT)) =
      Module.finrank K KT := (inertiaDeg_congr hcomap).symm.trans hfT
  haveI : Algebra.IsSeparable (κ K) (κ KT) := isSeparable_congr hcomap
  haveI : IsPurelyInseparable (κ KT) (κ N) := by
    have := isPurelyInseparable_residueField_fixedField (u := NormedField.valuation (K := K))
      (w := NormedField.valuation (K := N)) hσ
    exact isPurelyInseparable_congr_left hcomap
  -- `K_T` is inertially generated
  have hIG := isInertiallyGenerated_of_unramified (B := KT) hx hfT'
  clear hfT hsepT hcomap
  clear_value KT
  -- a Hensel generator `y` of `K_T / K`
  haveI : HenselianLocalRing (NormedField.valuation (K := KT)).valuationSubring :=
    HenselComplete.henselianLocalRing (K := KT)
  obtain ⟨y, q, hq, hyq, hqmin, -, hytop, -⟩ :=
    exists_unramified_generator (u := NormedField.valuation (K := K))
      (w := NormedField.valuation (K := KT)) hfT'
  set yN : N := ((y : KT) : N) with hyN
  have hy1 : ‖yN‖ ≤ 1 := HenselComplete.norm_le_one y
  -- the unramified extension `X'' = B(y)` of `B`
  set X'' := IntermediateField.adjoin B {yN}
  haveI : IsScalarTower K X'' N := IsScalarTower.of_algebraMap_eq fun k ↦ rfl
  haveI : IsScalarTower K B X'' := IsScalarTower.of_algebraMap_eq fun k ↦
    Subtype.ext (IsScalarTower.algebraMap_apply K B N k)
  haveI : FiniteDimensional K X'' := Module.Finite.of_injective
    (IsScalarTower.toAlgHom K X'' N).toLinearMap (algebraMap X'' N).injective
  haveI : FiniteDimensional B X'' := Module.Finite.of_restrictScalars_finite K B X''
  set g : X'' := IntermediateField.AdjoinSimple.gen B yN
  set yP : HenselComplete.integers X'' := ⟨g, (HenselComplete.mem_integers_iff _).2 hy1⟩
  set qB : (HenselComplete.integers B)[X] :=
    q.map (algebraMap (HenselComplete.integers K) (HenselComplete.integers B))
  have hqB : qB.Monic := hq.map _
  have hmapB : qB.map (algebraMap (HenselComplete.integers B) B) =
      (q.map (algebraMap (HenselComplete.integers K) K)).map (algebraMap K B) := by
    rw [Polynomial.map_map, Polynomial.map_map]
    congr 1
  have hyP : aeval yP qB = 0 := by
    apply Subtype.val_injective
    apply (algebraMap X'' N).injective
    have h1 := ValuationResidue.coe_aeval (v := NormedField.valuation (K := K))
      (w := NormedField.valuation (K := KT)) q y
    rw [hyq] at h1
    rw [ValuationResidue.coe_aeval, hmapB, aeval_map_algebraMap, ZeroMemClass.coe_zero,
      map_zero, ← aeval_algebraMap_apply]
    change aeval (algebraMap KT N (y : KT)) _ = 0
    rw [aeval_algebraMap_apply, ← h1]
    simp
  set ybar := residue (NormedField.valuation (K := KT)).valuationSubring y
  have hsep : (minpoly (κ K) ybar).Separable := Algebra.IsSeparable.isSeparable _ _
  have hres : algebraMap (κ X'') (κ N) (residue (HenselComplete.integers X'') yP) =
      algebraMap (κ KT) (κ N) ybar := by
    have e1 : residue (HenselComplete.integers X'') yP = rd (g : X'') := (rd_coe yP).symm
    have e2 : ybar = rd (y : KT) := (rd_coe y).symm
    rw [e1, e2, ← rd_algebraMap' (HenselComplete.norm_le_one yP),
      ← rd_algebraMap' (HenselComplete.norm_le_one y)]
    rfl
  have hsimple : aeval (residue (HenselComplete.integers X'') yP)
      (derivative (qB.map (residue (HenselComplete.integers B)))) ≠ 0 := by
    have hmap : qB.map (residue (HenselComplete.integers B)) =
        (q.map (residue (HenselComplete.integers K))).map (algebraMap (κ K) (κ B)) := by
      rw [Polynomial.map_map, Polynomial.map_map]
      rfl
    rw [hmap, hqmin, derivative_map, aeval_map_algebraMap]
    intro h0
    have h2 := congrArg (algebraMap (κ X'') (κ N)) h0
    rw [map_zero, ← aeval_algebraMap_apply, hres, aeval_algebraMap_apply] at h2
    exact hsep.aeval_derivative_ne_zero (minpoly.aeval _ _)
      ((map_eq_zero_iff _ (algebraMap (κ KT) (κ N)).injective).1 h2)
  have hgen : B⟮((yP : HenselComplete.integers X'') : X'')⟯ = ⊤ := by
    haveI : FiniteDimensional B N := Module.Finite.of_restrictScalars_finite K B N
    have hint : IsIntegral B yN := IsIntegral.of_finite B _
    refine IntermediateField.eq_of_le_of_finrank_le le_top ?_
    rw [IntermediateField.finrank_top', IntermediateField.adjoin.finrank hint,
      IntermediateField.adjoin.finrank (IsIntegral.of_finite B _)]
    change _ ≤ (minpoly B g).natDegree
    rw [IntermediateField.minpoly_gen]
  haveI := UniqueExtension.henselianLocalRing_valuationSubring K
    (NormedField.valuation (K := X''))
  obtain ⟨-, -, hsepX⟩ := unramified_of_adjoin_simple_root (u := NormedField.valuation (K := B))
    (w := NormedField.valuation (K := X''))
    (fun K' ↦ UniqueExtension.henselianLocalRing_comap K (NormedField.valuation (K := X'')) K')
    hqB hyP hsimple hgen
  haveI : Algebra.IsSeparable (κ K) (κ X'') := Algebra.IsSeparable.trans (κ K) (κ B) (κ X'')
  clear hgen hsimple hres hyP hmapB hqB qB yP g
  -- `X' = K_T(B)` lies in `X''`
  set X' := IntermediateField.adjoin KT (Set.range (algebraMap B N)) with hX'def
  have hKT : KT ≤ X''.restrictScalars K := by
    intro a ha
    have ha' : (⟨a, ha⟩ : KT) ∈ K⟮(y : KT)⟯ := by rw [hytop]; trivial
    have hmap : (K⟮(y : KT)⟯).map KT.val = K⟮yN⟯ := by
      rw [IntermediateField.adjoin_map, Set.image_singleton]
      rfl
    have : a ∈ K⟮yN⟯ := hmap ▸ ⟨_, ha', rfl⟩
    have hle : K⟮yN⟯ ≤ X''.restrictScalars K :=
      IntermediateField.adjoin_simple_le_iff.2 (IntermediateField.mem_adjoin_simple_self B yN)
    exact hle this
  have hX'X'' : X'.restrictScalars K ≤ X''.restrictScalars K := by
    rw [IntermediateField.restrictScalars_adjoin, IntermediateField.adjoin_le_iff]
    rintro a (ha | ⟨b, rfl⟩)
    · exact hKT ha
    · exact X''.algebraMap_mem b
  clear hKT
  clear_value X' X''
  -- the residues of `X'` lie in `κ_{K_T}`
  have hA : ∀ a : N, a ∈ X' → ‖a‖ ≤ 1 → rd a ∈ (algebraMap (κ KT) (κ N)).range := by
    intro a ha ha1
    have ha'' : a ∈ X'' := hX'X'' ha
    have e : rd a = algebraMap (κ X'') (κ N) (rd (⟨a, ha''⟩ : X'')) :=
      rd_algebraMap' (A := X'') (a := ⟨a, ha''⟩) ha1
    have hsepa : IsSeparable (κ K) (rd a) := by
      rw [e]
      exact isSeparable_algHom_apply (IsScalarTower.toAlgHom (κ K) (κ X'') (κ N))
        (Algebra.IsSeparable.isSeparable _ _)
    exact IsPurelyInseparable.inseparable (κ KT) _ (hsepa.tower_top (κ KT))
  have hf1 := inertiaDeg_le_one_of_rd_mem X' hA
  -- the wild step: `X' = K_T`
  have hX' : X' = ⊥ := eq_bot_of_isPurelyInseparable hp hp1 (M := KT) (N := N) hIG X' hf1
  have hBKT : ∀ b : B, algebraMap B N b ∈ KT := by
    intro b
    have : algebraMap B N b ∈ X' := by
      rw [hX'def]
      exact IntermediateField.subset_adjoin _ _ ⟨b, rfl⟩
    rw [hX', IntermediateField.mem_bot] at this
    obtain ⟨t, ht⟩ := this
    rw [← ht]
    exact t.2
  -- `B ⊆ K_T` is unramified
  letI : Algebra B KT := (RingHom.codRestrict (algebraMap B N) KT hBKT).toAlgebra
  letI : NormedAlgebra B KT :=
    { norm_smul_le := fun b t ↦ le_of_eq (by
        rw [Algebra.smul_def, norm_mul]
        congr 1
        exact norm_algebraMap' N b) }
  haveI : IsScalarTower K B KT := IsScalarTower.of_algebraMap_eq fun k ↦
    Subtype.ext (IsScalarTower.algebraMap_apply K B N k)
  haveI : FiniteDimensional B KT := Module.Finite.of_restrictScalars_finite K B KT
  exact (inertiaDeg_eq_finrank_of_tower hfT').1

end Core

section Main

universe u

variable {C : Type*} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
  {K : Type u} [NontriviallyNormedField K] [IsUltrametricDist K] [CompleteSpace K]
  [NormedAlgebra C K]
include hp hp1

/-- **G1'.** Let `K` be Gauss-complete (the completion of `C(x)` for a Gauss valuation). A finite
extension `B / K` with separable residue field extension is unramified: `f(B | K) = [B : K]`. -/
theorem inertiaDeg_eq_finrank_of_isSeparable {x : K} (hx : IsGaussComplete C x)
    {B : Type u} [NontriviallyNormedField B] [IsUltrametricDist B] [NormedAlgebra K B]
    [FiniteDimensional K B] [Algebra.IsSeparable (κ K) (κ B)] :
    inertiaDeg (NormedField.valuation (K := K)) (NormedField.valuation (K := B)) =
      Module.finrank K B := by
  haveI : CharZero K := charZero_of_injective_algebraMap (algebraMap C K).injective
  obtain ⟨N, _, _, _, _, _, _, _, _, _⟩ := exists_normed_galois_closure C K B
  exact inertiaDeg_eq_finrank_of_isSeparable_of_isGalois hp hp1 N hx


/-- **G1.** An inertially generated field `M` has no proper immediate finite extension: if
`E / M` is finite and `f(w | M) = 1` for a valuation `w` of `E` extending that of `M` (the value
group is divisible, so `e = 1` automatically), then `E = M`.

Proof: `M` is finite over the Gauss-complete `\widehat{C(z)}` with separable residue field
extension, hence so is `E` (`κ_E = κ_M`); by G1' `E / \widehat{C(z)}` is unramified, so
`[E : \widehat{C(z)}] = f(E) = f(M) ≤ [M : \widehat{C(z)}]`. -/
theorem finrank_eq_one_of_immediate {M : Type u} [NontriviallyNormedField M] [IsUltrametricDist M]
    [CompleteSpace M] [NormedAlgebra C M] {z : M} (hM : IsInertiallyGenerated C z)
    {E : Type u} [Field E] [Algebra M E] [FiniteDimensional M E]
    {Γ : Type*} [LinearOrderedCommGroupWithZero Γ] (w : Valuation E Γ)
    [(NormedField.valuation (K := M)).HasExtension w]
    (hf : inertiaDeg (NormedField.valuation (K := M)) w = 1) : Module.finrank M E = 1 := by
  set G := genField C z
  have hx := isGaussComplete_genField hM.norm_le_one hM.transcendental
  haveI : FiniteDimensional G M := (finite_genField_iff z).2 hM.finiteDimensional
  haveI : Algebra.IsSeparable (κ G) (κ M) :=
    (isSeparable_residue_genField_iff z).2 hM.isSeparable
  -- the spectral norm on `E`
  letI : NontriviallyNormedField E := spectralNorm.nontriviallyNormedField M E
  letI : NormedAlgebra M E := spectralNorm.normedAlgebra M E
  haveI : IsUltrametricDist E := IsUltrametricDist.of_normedAlgebra M
  have hf' : inertiaDeg (NormedField.valuation (K := M)) (NormedField.valuation (K := E)) = 1 :=
    (inertiaDeg_eq_of_valuationSubring_eq (UniqueExtension.valuationSubring_eq (K := M) w
      (NormedField.valuation (K := E)))).symm.trans hf
  letI : NormedAlgebra G E :=
    { norm_smul_le := fun g e ↦ le_of_eq (by
        rw [Algebra.smul_def, norm_mul, IsScalarTower.algebraMap_apply G M E, norm_algebraMap',
          norm_algebraMap']) }
  haveI : FiniteDimensional G E := Module.Finite.trans M E
  haveI : Algebra.IsSeparable (κ M) (κ E) := by
    have hbot : (⊥ : Subalgebra (κ M) (κ E)) = ⊤ :=
      Subalgebra.bot_eq_top_iff_finrank_eq_one.2 hf'
    refine ⟨fun r ↦ ?_⟩
    have hr : r ∈ (⊥ : Subalgebra (κ M) (κ E)) := hbot ▸ Algebra.mem_top
    obtain ⟨a, rfl⟩ := Algebra.mem_bot.1 hr
    exact isSeparable_algebraMap a
  haveI : Algebra.IsSeparable (κ G) (κ E) := Algebra.IsSeparable.trans (κ G) (κ M) (κ E)
  have hG := inertiaDeg_eq_finrank_of_isSeparable hp hp1 hx (B := E)
  have ht := inertiaDeg_tower (NormedField.valuation (K := G)) (NormedField.valuation (K := M))
    (NormedField.valuation (K := E))
  rw [hf', one_mul] at ht
  have hle : inertiaDeg (NormedField.valuation (K := G)) (NormedField.valuation (K := M)) ≤
      Module.finrank G M := inertiaDeg_le_finrank
  have hmul := Module.finrank_mul_finrank G M E
  have h : Module.finrank G M * Module.finrank M E ≤ Module.finrank G M * 1 := by
    rw [hmul, mul_one, ← hG, ht]
    exact hle
  exact le_antisymm (Nat.le_of_mul_le_mul_left h Module.finrank_pos) Module.finrank_pos

end Main

end NoImmediate

end SemistableReduction
