/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.VertexDescent
import TemperedFundamentalGroups.SemistableReduction.FundamentalInequality

/-!
# Descent of residue fields of vertices

Blueprint §9.8 (W9), layer D3d (residue fields). Let `v` be a valuation on a field `Ω`, `L` a
finite extension of `Ω(X)` and `W` a valuation subring of `L` over a Gauss valuation `w_{a, r}`.

* `exists_finset_adjoin_residue`: the residue field `κ(W)` is generated over `κ(v)` by the
  residues of finitely many elements of `W` (it is finite over `κ(w_{a,r}) = κ(v)(x̄)`,
  `FundamentalInequality.finite_residueField`, and `x̄` is the residue of an element).
* `exists_adjoin_residue_eq_top`: if `L` is the directed union of subfields `E j` (e.g.
  `E j = L'·K_j`), then for some `j` and all vertices `W` in a finite set, `κ(W)` is generated
  over `κ(v)` by the residues of elements of `W ∩ E j`: the residue field of a vertex over `Ω` is
  generated by `k` and the residue field of the restricted vertex over `K_j`.
-/

open Polynomial IsLocalRing

namespace SemistableReduction

open ZariskiModel

variable {Ω L : Type*} [Field Ω] [Field L] [Algebra Ω L] [Algebra (RatFunc Ω) L]
  [IsScalarTower Ω (RatFunc Ω) L] {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
  {v : Valuation Ω Γ₀}

/-- A valuation subring over a Gauss valuation lies over `O_v`. -/
lemma comap_algebraMap_eq_of_comap_eq_gaussRat {a : Ω} {r : Γ₀ˣ} {W : ValuationSubring L}
    (hW : W.comap (algebraMap (RatFunc Ω) L) = (gaussRat v a r).valuationSubring) :
    W.comap (algebraMap Ω L) = v.valuationSubring := by
  rw [IsScalarTower.algebraMap_eq Ω (RatFunc Ω) L, ← ValuationSubring.comap_comap, hW,
    comap_algebraMap_gaussRat]

/-- **(W9, D3d) The residue field of a vertex is finitely generated by residues.** For `L` finite
over `Ω(X)` and `W` over the Gauss valuation `w_{a, r}` (`v(c) = r`), `κ(W)` is generated over
`κ(v)` by the residues of finitely many elements of `W` (it is finite over
`κ(w_{a,r}) = κ(v)(x̄)`, `FundamentalInequality.finite_residueField`). -/
theorem exists_finset_adjoin_residue [FiniteDimensional (RatFunc Ω) L] {a c : Ω} {r : Γ₀ˣ}
    (hc : v c = r) {W : ValuationSubring L}
    (hW : W.comap (algebraMap (RatFunc Ω) L) = (gaussRat v a r).valuationSubring) :
    ∃ s : Finset W, ∀ z : W,
      letI := residueAlgebra (comap_algebraMap_eq_of_comap_eq_gaussRat hW)
      residue W z ∈
        IntermediateField.adjoin (ResidueField v.valuationSubring) (residue W '' (s : Set W)) := by
  set u := gaussRat v a r
  have key (w : Valuation L W.ValueGroup) (V : ValuationSubring L) (h : w.valuationSubring = V)
      (hV : V.comap (algebraMap (RatFunc Ω) L) = u.valuationSubring) :
      ∃ s : Finset V, ∀ z : V,
        letI := residueAlgebra (comap_algebraMap_eq_of_comap_eq_gaussRat hV)
        residue V z ∈ IntermediateField.adjoin (ResidueField v.valuationSubring)
          (residue V '' (s : Set V)) := by
    subst h
    haveI : u.HasExtension w := by
      refine ⟨(Valuation.isEquiv_iff_valuationSubring _ _).2 ?_⟩
      rw [← hV]
      ext x
      simp
    haveI := FundamentalInequality.finite_residueField (v := u) (w := w)
    letI := residueAlgebra (comap_algebraMap_eq_of_comap_eq_gaussRat hV)
    have hsmul (e : ResidueField u.valuationSubring) (y : ResidueField w.valuationSubring) :
        e • y = algebraMap (ResidueField u.valuationSubring) (ResidueField w.valuationSubring) e *
          y :=
      Algebra.smul_def e y
    haveI : IsScalarTower (ResidueField v.valuationSubring) (ResidueField u.valuationSubring)
        (ResidueField w.valuationSubring) := by
      refine IsScalarTower.of_algebraMap_eq fun o ↦ ?_
      obtain ⟨o, rfl⟩ := residue_surjective o
      change ResidueField.map _ (residue _ o) = _
      rw [ResidueField.map_residue, ResidueField.algebraMap_residue,
        ResidueField.algebraMap_residue]
      congr 1
      refine Subtype.ext ?_
      simp [IsScalarTower.algebraMap_apply Ω (RatFunc Ω) L]
    obtain ⟨s₀, hs₀⟩ := Module.Finite.fg_top (R := ResidueField u.valuationSubring)
      (M := ResidueField w.valuationSubring)
    classical
    set lift := Function.surjInv (residue_surjective (R := w.valuationSubring))
    set x : w.valuationSubring :=
      algebraMap u.valuationSubring w.valuationSubring (gaussGen v a r hc)
    refine ⟨insert x (s₀.image lift), fun z ↦ ?_⟩
    set A := IntermediateField.adjoin (ResidueField v.valuationSubring)
      (residue w.valuationSubring '' ((insert x (s₀.image lift) : Finset _) : Set _))
    have hx : residue _ x ∈ A :=
      IntermediateField.subset_adjoin _ _ ⟨x, by simp, rfl⟩
    have hκ (e : ResidueField u.valuationSubring) :
        algebraMap (ResidueField u.valuationSubring) (ResidueField w.valuationSubring) e ∈ A := by
      set φ := IsScalarTower.toAlgHom (ResidueField v.valuationSubring)
        (ResidueField u.valuationSubring) (ResidueField w.valuationSubring)
      have he : e ∈ (IntermediateField.adjoin (ResidueField v.valuationSubring)
          {residue u.valuationSubring (gaussGen v a r hc)}) := by
        rw [adjoin_residue_gaussGen_eq_top hc]
        exact IntermediateField.mem_top
      have : φ e ∈ (IntermediateField.adjoin (ResidueField v.valuationSubring)
          {residue u.valuationSubring (gaussGen v a r hc)}).map φ :=
        (IntermediateField.mem_map _).2 ⟨e, he, rfl⟩
      rw [IntermediateField.adjoin_map, Set.image_singleton] at this
      refine IntermediateField.adjoin_le_iff.2 ?_ this
      rintro _ rfl
      exact hx
    have hz : residue _ z ∈ Submodule.span (ResidueField u.valuationSubring) (s₀ : Set _) := by
      rw [hs₀]
      exact Submodule.mem_top
    refine Submodule.span_induction (p := fun y _ ↦ y ∈ A) ?_ ?_ ?_ ?_ hz
    · intro b hb
      have : residue _ (lift b) = b := Function.surjInv_eq _ b
      rw [← this]
      exact IntermediateField.subset_adjoin _ _ ⟨lift b,
        Finset.mem_coe.2 (Finset.mem_insert_of_mem (Finset.mem_image_of_mem _ hb)), rfl⟩
    · exact zero_mem _
    · intro _ _ _ _ h₁ h₂
      exact add_mem h₁ h₂
    · intro e y _ hy
      rw [hsmul]
      exact mul_mem (hκ e) hy
  exact key W.valuation W W.valuationSubring_valuation hW

/-- Finitely many elements of a directed union of subfields lie in one of them. -/
lemma exists_subset_subfield {J : Type*} [Nonempty J] {E : J → Subfield L}
    (hdir : Directed (· ≤ ·) E) (hcov : ∀ x, ∃ j, x ∈ E j) {T : Set L} (hT : T.Finite) :
    ∃ j, ∀ x ∈ T, x ∈ E j := by
  classical
  choose f hf using hcov
  obtain ⟨j, hj⟩ := hdir.finset_le (hT.toFinset.image f)
  exact ⟨j, fun x hx ↦ hj _ (Finset.mem_image.2 ⟨x, hT.mem_toFinset.2 hx, rfl⟩) (hf x)⟩

/-- **(W9, D3d) Residue fields of vertices descend.** Let `L` be finite over `Ω(X)` and the
directed union of subfields `E j` (e.g. `E j = L' · K_j`). For a finite set `S` of valuation
subrings of `L`, each over one of finitely many Gauss valuations `w_{a i, r i}` (e.g. the vertex
set of the normalization of the tree model), there is a `j` such that for every `W ∈ S` the residue
field `κ(W)` is generated over `κ(v)` by the residues of the elements of `W ∩ E j`, i.e. by `k`
and the image of the residue field of the restricted vertex `W ∩ E j`. -/
theorem exists_adjoin_residue_eq_top [FiniteDimensional (RatFunc Ω) L] {ι : Type*}
    {a c : ι → Ω} {r : ι → Γ₀ˣ} (hc : ∀ i, v (c i) = r i) {J : Type*} [Nonempty J]
    {E : J → Subfield L} (hdir : Directed (· ≤ ·) E) (hcov : ∀ x, ∃ j, x ∈ E j)
    {S : Set (ValuationSubring L)} (hS : S.Finite)
    (hSv : ∀ W ∈ S, ∃ i, W.comap (algebraMap (RatFunc Ω) L) =
      (gaussRat v (a i) (r i)).valuationSubring) :
    ∃ j, ∀ W ∈ S, ∀ h : W.comap (algebraMap Ω L) = v.valuationSubring,
      letI := residueAlgebra h
      IntermediateField.adjoin (ResidueField v.valuationSubring)
        (residue W '' {y : W | (y : L) ∈ E j}) = ⊤ := by
  classical
  have hfs (W : ValuationSubring L) : ∃ s : Finset L, W ∈ S → ∃ hs : ∀ y ∈ s, y ∈ W,
      ∀ h : W.comap (algebraMap Ω L) = v.valuationSubring, ∀ z : W,
        letI := residueAlgebra h
        residue W z ∈ IntermediateField.adjoin (ResidueField v.valuationSubring)
          (residue W '' {y : W | (y : L) ∈ s}) := by
    by_cases hW : W ∈ S
    · obtain ⟨i, hi⟩ := hSv W hW
      obtain ⟨s, hs⟩ := exists_finset_adjoin_residue (hc i) hi
      refine ⟨s.image Subtype.val, fun _ ↦ ⟨?_, fun h z ↦ ?_⟩⟩
      · intro y hy
        obtain ⟨y, -, rfl⟩ := Finset.mem_image.1 hy
        exact y.2
      · letI := residueAlgebra h
        refine IntermediateField.adjoin.mono _ _ _ ?_ (hs z)
        rintro _ ⟨y, hy, rfl⟩
        exact ⟨y, Finset.mem_image_of_mem _ hy, rfl⟩
    · exact ⟨∅, fun h ↦ (hW h).elim⟩
  choose s hs using hfs
  obtain ⟨j, hj⟩ := exists_subset_subfield hdir hcov
    (hS.biUnion fun W _ ↦ (s W).finite_toSet)
  refine ⟨j, fun W hW h ↦ ?_⟩
  letI := residueAlgebra h
  obtain ⟨-, hgen⟩ := hs W hW
  refine eq_top_iff.2 fun z _ ↦ ?_
  obtain ⟨z, rfl⟩ := residue_surjective z
  refine IntermediateField.adjoin.mono _ _ _ ?_ (hgen h z)
  rintro _ ⟨y, hy, rfl⟩
  exact ⟨y, hj _ (Set.mem_biUnion hW hy), rfl⟩

/-! ### D3e: generator descent -/

/-- **(W9, D3e) Integrality descends along directed unions.** If the subring `B` of `L` is
contained in the directed union of subrings `A j` (e.g. the tree chart over `O_C`, the union of
the tree charts over the `O_j`), then finitely many elements integral over `B` are integral over
a single `A j`: the coefficients of their monic equations lie in some `A j`. -/
theorem exists_isIntegral_of_le_iSup {L : Type*} [Field L] {J : Type*} [Nonempty J]
    {A : J → Subring L} (hdir : Directed (· ≤ ·) A) {B : Subring L} (hB : B ≤ ⨆ j, A j)
    {s : Finset L} (hs : ∀ x ∈ s, IsIntegral B x) :
    ∃ j, ∀ k, A j ≤ A k → ∀ x ∈ s, IsIntegral (A k) x := by
  classical
  choose p hpm hpx using fun x : s ↦ hs x x.2
  set P : s → L[X] := fun x ↦ (p x).map B.subtype
  have hcoeff (y : L) : ∃ j, y ∈ ⨆ i, A i → y ∈ A j := by
    by_cases hy : y ∈ ⨆ i, A i
    · obtain ⟨j, hj⟩ := (Subring.mem_iSup_of_directed hdir).1 hy
      exact ⟨j, fun _ ↦ hj⟩
    · exact ⟨Classical.arbitrary J, fun h ↦ (hy h).elim⟩
  choose g hg using hcoeff
  have hmem (x : s) (y : L) (hy : y ∈ (P x).coeffs) : y ∈ ⨆ i, A i := by
    obtain ⟨n, -, rfl⟩ := Polynomial.mem_coeffs_iff.1 hy
    rw [Polynomial.coeff_map]
    exact hB (p x |>.coeff n).2
  obtain ⟨j, hj⟩ := hdir.finset_le (Finset.univ.biUnion fun x : s ↦ (P x).coeffs.image g)
  refine ⟨j, fun k hk x hx ↦ ?_⟩
  have hsub : ((P ⟨x, hx⟩).coeffs : Set L) ⊆ A k := by
    intro y hy
    refine hk (hj _ ?_ (hg y (hmem _ y hy)))
    exact Finset.mem_biUnion.2 ⟨⟨x, hx⟩, Finset.mem_univ _, Finset.mem_image_of_mem _ hy⟩
  refine ⟨(P ⟨x, hx⟩).toSubring (A k) hsub,
    (Polynomial.monic_toSubring _ _ _).2 ((hpm ⟨x, hx⟩).map _), ?_⟩
  change Polynomial.eval₂ (A k).subtype x _ = 0
  rw [← Polynomial.eval_map, Polynomial.map_toSubring]
  simp only [P, Polynomial.eval_map]
  exact hpx ⟨x, hx⟩

/-- **(W9, D3e) Generator descent.** Let `L` be the union of subfields `E j` and `B ⊆ L` a
subring contained in the union of subrings `A j ⊆ E j`, both families monotone along a directed
index (e.g. `E j = F'·K_j`, `A j` the tree chart over `O_j`, `B` the tree chart over `O_C`).
Finitely many elements of `L` integral over `B` (generators of the normalization over `O_C`, node
coordinates, units, étale-chart data) all lie in a single `E j` and are integral over `A j`. -/
theorem exists_mem_and_isIntegral {L : Type*} [Field L] {J : Type*} [Preorder J]
    [IsDirectedOrder J] [Nonempty J] {E : J → Subfield L} (hE : Monotone E)
    (hcov : ∀ x, ∃ j, x ∈ E j) {A : J → Subring L} (hA : Monotone A)
    {B : Subring L} (hB : B ≤ ⨆ j, A j) {s : Finset L} (hs : ∀ x ∈ s, IsIntegral B x) :
    ∃ j, ∀ x ∈ s, x ∈ E j ∧ IsIntegral (A j) x := by
  obtain ⟨j₁, hj₁⟩ := exists_subset_subfield hE.directed_le hcov s.finite_toSet
  obtain ⟨j₂, hj₂⟩ := exists_isIntegral_of_le_iSup hA.directed_le hB hs
  obtain ⟨j, h₁, h₂⟩ := directed_of (· ≤ ·) j₁ j₂
  exact ⟨j, fun x hx ↦ ⟨hE h₁ (hj₁ x hx), hj₂ j (hA h₂) x hx⟩⟩

end SemistableReduction
