/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.NodeLemma

/-!
# The smooth-point lemma (W10, smooth part of the descent)

Blueprint §9.9 (S9), §9.12 (O7). The one-branch analogue of the node lemma
(`NodeLemma.isAnnulusAt_of_isOrdinaryDoublePoint`): a point of a chart over a DVR at which the
chart is unramified over a polynomial ring `O[u]` is étale-locally the affine line.

* `isEtaleLocallyAt_of_isUnramifiedAt`: if `B ⊇ R` is a domain of finite type over a noetherian
  normal domain `R` (an `O`-algebra), unramified at `𝔭`, then `B` is étale-locally `R` at `𝔭`
  (Zariski's main theorem, via `isEtaleAt_of_isUnramifiedAt`; the neighbourhood is a basic open
  `B_f`, `f ∉ 𝔭`).
* `IsEtaleLocallyAt.of_le`, `IsSemistableAt.of_le`: étale-local models are stable under
  **generization** (étale maps are flat, flat maps have going down). In particular semistability
  at a closed point of the special fibre gives semistability at the generic points of the
  components through it and at the generic-fibre points specializing to it.
* (S) `isSemistableAt_of_maximalIdeal_eq_span`: at a prime `𝔭` of a domain `B` of finite type over
  a noetherian normal domain `O` such that the maximal ideal of `B_𝔭` is `(ϖ, u)` for an element
  `u` transcendental over `O` and the residue field of `B_𝔭` is that of `O`, `B` is étale-locally
  `O[u]` at `𝔭`: `IsSemistableAt ϖ 𝔭`.
* (G) `isSemistableAt_of_maximalIdeal_eq_span_of_charZero`: the generic-fibre version: the
  maximal ideal of `B_𝔭` is generated by one element `u` transcendental over `O` (or is zero) and
  the residue field of `B_𝔭` is algebraic over the fraction field of `O`, of characteristic `0`.
-/

universe u

open IsLocalRing Polynomial

namespace SemistableReduction

section Core

variable {O R B : Type u} [CommRing O] [CommRing R] [CommRing B] [Algebra O R] [Algebra R B]
  [Algebra O B] [IsScalarTower O R B]

/-- **Unramified ⇒ étale-locally the base** (Zariski's main theorem): a domain `B ⊇ R` of finite
type over a noetherian normal domain `R`, unramified over `R` at `𝔭`, is étale-locally `R` at
`𝔭` (the common étale neighbourhood is a basic open `B_f`, `f ∉ 𝔭`, étale over `R`). -/
theorem isEtaleLocallyAt_of_isUnramifiedAt [IsDomain R] [IsIntegrallyClosed R] [IsNoetherianRing R]
    [IsDomain B] [Algebra.FiniteType R B] (hinj : Function.Injective (algebraMap R B))
    (𝔭 : Ideal B) [𝔭.IsPrime] [Algebra.IsUnramifiedAt R 𝔭] : IsEtaleLocallyAt O R 𝔭 := by
  have hEt : Algebra.IsEtaleAt R 𝔭 := isEtaleAt_of_isUnramifiedAt hinj 𝔭
  haveI : Algebra.FinitePresentation R B :=
    Algebra.FinitePresentation.of_finiteType.mp inferInstance
  obtain ⟨f, hf𝔭, hfet⟩ := Algebra.exists_etale_of_isEtaleAt (R := R) 𝔭
  let C := Localization.Away f
  have hdisj : Disjoint (Submonoid.powers f : Set B) 𝔭 := by
    rw [Set.disjoint_left]
    rintro _ ⟨k, rfl⟩ hk
    exact hf𝔭 (‹𝔭.IsPrime›.mem_of_pow_mem k hk)
  refine ⟨C, inferInstance, algebraMap B C, algebraMap R C, 𝔭.map (algebraMap B C),
    RingHom.etale_algebraMap.mpr (Algebra.Etale.of_isLocalizationAway f),
    RingHom.etale_algebraMap.mpr hfet,
    IsLocalization.isPrime_of_isPrime_disjoint (Submonoid.powers f) C 𝔭 inferInstance hdisj,
    IsLocalization.under_map_of_isPrime_disjoint (Submonoid.powers f) C inferInstance hdisj, ?_⟩
  rw [← IsScalarTower.algebraMap_eq, ← IsScalarTower.algebraMap_eq]

end Core

section Generization

variable {O : Type u} [CommRing O] {M : Type u} [CommRing M] [Algebra O M]
  {A : Type u} [CommRing A] [Algebra O A]

/-- **Generization.** If `A` is étale-locally `M` at `𝔭` and `𝔭' ⊆ 𝔭`, then `A` is étale-locally
`M` at `𝔭'` (the étale neighbourhood is flat, hence has going down). -/
theorem IsEtaleLocallyAt.of_le {𝔭 𝔭' : Ideal A} [𝔭'.IsPrime] (h : IsEtaleLocallyAt O M 𝔭)
    (hle : 𝔭' ≤ 𝔭) : IsEtaleLocallyAt O M 𝔭' := by
  obtain ⟨C, _, g, f, 𝔮, hg, hf, h𝔮, hcomap, hcomp⟩ := h
  letI : Algebra A C := g.toAlgebra
  have hC : Algebra.Etale A C := hg
  haveI : 𝔭.IsPrime := hcomap ▸ Ideal.comap_isPrime g 𝔮
  haveI : 𝔮.LiesOver 𝔭 := ⟨hcomap.symm⟩
  obtain ⟨𝔮', hle', h𝔮', hlies⟩ := Ideal.exists_ideal_le_liesOver_of_le (p := 𝔭') (q := 𝔭) 𝔮 hle
  exact ⟨C, inferInstance, g, f, 𝔮', hg, hf, h𝔮', hlies.over.symm, hcomp⟩

/-- **Generization** of semistability. -/
theorem IsSemistableAt.of_le {ϖ : O} {𝔭 𝔭' : Ideal A} [𝔭'.IsPrime] (h : IsSemistableAt ϖ 𝔭)
    (hle : 𝔭' ≤ 𝔭) : IsSemistableAt ϖ 𝔭' := by
  rcases h with ⟨n, h⟩ | h
  · exact .inl ⟨n, h.of_le hle⟩
  · exact .inr (h.of_le hle)

end Generization

section CharZero

/-- **Local unramifiedness criterion in characteristic zero**: a local ring `D`, essentially of
finite type over `R`, whose maximal ideal is generated by the image of its contraction to `R`, is
formally unramified over `R` if its residue field is algebraic over a ring `O` of characteristic
`0` mapping injectively to it (e.g. a generic-fibre point over a DVR `O`). -/
theorem formallyUnramified_of_map_maximalIdeal_of_charZero {O R D : Type*} [CommRing O]
    [CharZero O] [CommRing R] [CommRing D] [IsLocalRing D] [Algebra O R] [Algebra R D]
    [Algebra O D] [IsScalarTower O R D] [Algebra.EssFiniteType R D]
    (hmax : maximalIdeal D = Ideal.map (algebraMap R D) ((maximalIdeal D).comap (algebraMap R D)))
    (hinj : ∀ o : O, algebraMap O D o ∈ maximalIdeal D → o = 0)
    (halg : ∀ z : D, IsAlgebraic O (residue D z)) :
    Algebra.FormallyUnramified R D := by
  let p := (maximalIdeal D).comap (algebraMap R D)
  let Rp := Localization.AtPrime p
  have hunits : ∀ y : p.primeCompl, IsUnit (algebraMap R D y) := fun y ↦ by
    by_contra h
    exact y.2 ((mem_maximalIdeal _).mpr h)
  let φ : Rp →+* D := IsLocalization.lift hunits
  letI : Algebra Rp D := φ.toAlgebra
  have hφ : ∀ r, algebraMap Rp D (algebraMap R Rp r) = algebraMap R D r :=
    fun r ↦ IsLocalization.lift_eq hunits r
  haveI : IsScalarTower R Rp D := IsScalarTower.of_algebraMap_eq fun r ↦ (hφ r).symm
  haveI : IsScalarTower O Rp D := IsScalarTower.of_algebraMap_eq fun o ↦ by
    rw [IsScalarTower.algebraMap_apply O R Rp, hφ, ← IsScalarTower.algebraMap_apply]
  have hmapmax : (maximalIdeal Rp).map (algebraMap Rp D) = maximalIdeal D := by
    rw [← Localization.AtPrime.map_eq_maximalIdeal, Ideal.map_map,
      ← IsScalarTower.algebraMap_eq, ← hmax]
  haveI : IsLocalHom (algebraMap Rp D) := by
    refine ((local_hom_TFAE (algebraMap Rp D)).out 0 2).mpr ?_
    rw [hmapmax]
  haveI : Algebra.EssFiniteType Rp D := Algebra.EssFiniteType.of_comp R Rp D
  -- `O` embeds into the residue field of `R_p`
  have hOk : Function.Injective (algebraMap O (ResidueField Rp)) := by
    rw [injective_iff_map_eq_zero]
    intro o ho
    apply hinj o
    have : algebraMap (ResidueField Rp) (ResidueField D)
        (algebraMap O (ResidueField Rp) o) = 0 := by
      rw [ho, map_zero]
    rw [← IsScalarTower.algebraMap_apply, IsScalarTower.algebraMap_apply O D (ResidueField D),
      ResidueField.algebraMap_eq, residue_eq_zero_iff] at this
    exact this
  haveI : CharZero (ResidueField Rp) := charZero_of_injective_algebraMap hOk
  haveI : Algebra.IsAlgebraic (ResidueField Rp) (ResidueField D) := by
    refine ⟨fun z ↦ ?_⟩
    obtain ⟨z, rfl⟩ := IsLocalRing.residue_surjective z
    exact (halg z).extendScalars hOk
  haveI : Algebra.FormallyUnramified Rp D := Algebra.FormallyUnramified.of_map_maximalIdeal hmapmax
  haveI : Algebra.FormallyUnramified R Rp := .of_isLocalization p.primeCompl
  exact Algebra.FormallyUnramified.comp R Rp D

end CharZero

section Polynomial

variable {O B : Type u} [CommRing O] [IsDomain O] [IsIntegrallyClosed O] [IsNoetherianRing O]
  [CommRing B] [IsDomain B] [Algebra O B] [Algebra.FiniteType O B]

/-- **The smooth-point lemma (S)**: at a prime `𝔭` of a domain `B` of finite type over a
noetherian normal domain `O`, if the maximal ideal of `B_𝔭` is `(ϖ, u)` for an element `u`
transcendental over `O` and the residue field of `B_𝔭` is that of `O`, then `B` is étale-locally
the affine line `O[u]` at `𝔭` (`u` is a coordinate of the étale chart). -/
theorem isSemistableAt_of_maximalIdeal_eq_span {ϖ : O} {u : B} (hu : Transcendental O u)
    (𝔭 : Ideal B) [𝔭.IsPrime]
    (hmax : maximalIdeal (Localization.AtPrime 𝔭) =
      Ideal.span {algebraMap O (Localization.AtPrime 𝔭) ϖ,
        algebraMap B (Localization.AtPrime 𝔭) u})
    (hres : ∀ z : Localization.AtPrime 𝔭, ∃ o : O,
      z - algebraMap O (Localization.AtPrime 𝔭) o ∈ maximalIdeal (Localization.AtPrime 𝔭)) :
    IsSemistableAt ϖ 𝔭 := by
  let D := Localization.AtPrime 𝔭
  letI : Algebra O[X] B := (aeval u).toRingHom.toAlgebra
  have hXB : ∀ q : O[X], algebraMap O[X] B q = aeval u q := fun _ ↦ rfl
  haveI : IsScalarTower O O[X] B :=
    IsScalarTower.of_algebraMap_eq fun o ↦ ((aeval u).commutes o).symm
  haveI : Algebra.FiniteType O[X] B := .of_restrictScalars_finiteType O O[X] B
  have hinj : Function.Injective (algebraMap O[X] B) := (transcendental_iff_injective).mp hu
  haveI : Algebra.EssFiniteType B D := .of_isLocalization D 𝔭.primeCompl
  haveI : Algebra.EssFiniteType O[X] D := .comp O[X] B D
  have hXD : ∀ q : O[X], algebraMap O[X] D q = algebraMap B D (aeval u q) := fun q ↦ by
    rw [IsScalarTower.algebraMap_apply O[X] B D, hXB]
  have hunr : Algebra.FormallyUnramified O[X] D := by
    refine formallyUnramified_of_map_maximalIdeal ?_ fun z ↦ ?_
    · refine le_antisymm ?_ Ideal.map_comap_le
      have hmem : ∀ w : O[X], algebraMap O[X] D w ∈ maximalIdeal D →
          algebraMap O[X] D w ∈ Ideal.map (algebraMap O[X] D)
            ((maximalIdeal D).comap (algebraMap O[X] D)) :=
        fun w hw ↦ Ideal.mem_map_of_mem _ hw
      have hϖ : algebraMap O D ϖ = algebraMap O[X] D (C ϖ) := by
        rw [hXD, aeval_C, ← IsScalarTower.algebraMap_apply]
      have hu' : algebraMap B D u = algebraMap O[X] D X := by rw [hXD, aeval_X]
      have hmaxϖ : algebraMap O D ϖ ∈ maximalIdeal D := by
        rw [hmax]; exact Ideal.subset_span (Set.mem_insert _ _)
      have hmaxu : algebraMap B D u ∈ maximalIdeal D := by
        rw [hmax]; exact Ideal.subset_span (Set.mem_insert_of_mem _ rfl)
      refine hmax.le.trans ?_
      rw [Ideal.span_le]
      intro z hz
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
      rcases hz with rfl | rfl
      · rw [hϖ] at hmaxϖ ⊢; exact hmem _ hmaxϖ
      · rw [hu'] at hmaxu ⊢; exact hmem _ hmaxu
    · obtain ⟨o, ho⟩ := hres z
      exact ⟨C o, by rwa [hXD, aeval_C, ← IsScalarTower.algebraMap_apply]⟩
  haveI : Algebra.IsUnramifiedAt O[X] 𝔭 := hunr
  exact .inr (isEtaleLocallyAt_of_isUnramifiedAt hinj 𝔭)

/-- **The smooth-point lemma on the generic fibre (G)**: at a prime `𝔭` of a domain `B` of
finite type over a noetherian normal domain `O` of characteristic `0`, lying over `0 ⊆ O`, if the
maximal ideal of `B_𝔭` is `(u)` for an element `u` transcendental over `O` (or `0`, at the
generic point) and the residue field of `B_𝔭` is algebraic over `O`, then `B` is étale-locally
the affine line `O[u]` at `𝔭`. -/
theorem isSemistableAt_of_maximalIdeal_eq_span_of_charZero [CharZero O] (ϖ : O) {u : B}
    (hu : Transcendental O u) (𝔭 : Ideal B) [𝔭.IsPrime]
    (hmax : maximalIdeal (Localization.AtPrime 𝔭) =
        Ideal.span {algebraMap B (Localization.AtPrime 𝔭) u} ∨
      maximalIdeal (Localization.AtPrime 𝔭) = ⊥)
    (hinj𝔭 : ∀ o : O, algebraMap O B o ∈ 𝔭 → o = 0)
    (halg : ∀ z : Localization.AtPrime 𝔭, IsAlgebraic O (residue _ z)) :
    IsSemistableAt ϖ 𝔭 := by
  let D := Localization.AtPrime 𝔭
  letI : Algebra O[X] B := (aeval u).toRingHom.toAlgebra
  have hXB : ∀ q : O[X], algebraMap O[X] B q = aeval u q := fun _ ↦ rfl
  haveI : IsScalarTower O O[X] B :=
    IsScalarTower.of_algebraMap_eq fun o ↦ ((aeval u).commutes o).symm
  haveI : Algebra.FiniteType O[X] B := .of_restrictScalars_finiteType O O[X] B
  have hinj : Function.Injective (algebraMap O[X] B) := (transcendental_iff_injective).mp hu
  haveI : Algebra.EssFiniteType B D := .of_isLocalization D 𝔭.primeCompl
  haveI : Algebra.EssFiniteType O[X] D := .comp O[X] B D
  have hXD : ∀ q : O[X], algebraMap O[X] D q = algebraMap B D (aeval u q) := fun q ↦ by
    rw [IsScalarTower.algebraMap_apply O[X] B D, hXB]
  have hunr : Algebra.FormallyUnramified O[X] D := by
    refine formallyUnramified_of_map_maximalIdeal_of_charZero (O := O) ?_ (fun o ho ↦ ?_) halg
    · refine le_antisymm ?_ Ideal.map_comap_le
      rcases hmax with hmax | hmax
      · have hu' : algebraMap B D u = algebraMap O[X] D X := by rw [hXD, aeval_X]
        have hmaxu : algebraMap B D u ∈ maximalIdeal D := by
          rw [hmax]; exact Ideal.subset_span rfl
        refine hmax.le.trans ?_
        rw [Ideal.span_le, Set.singleton_subset_iff, hu']
        rw [hu'] at hmaxu
        exact Ideal.mem_map_of_mem _ hmaxu
      · rw [hmax]; exact bot_le
    · apply hinj𝔭 o
      rw [IsScalarTower.algebraMap_apply O B D] at ho
      exact (IsLocalization.AtPrime.to_map_mem_maximal_iff D 𝔭 _).mp ho
  haveI : Algebra.IsUnramifiedAt O[X] 𝔭 := hunr
  exact .inr (isEtaleLocallyAt_of_isUnramifiedAt hinj 𝔭)

end Polynomial

section Residue

/-- **Rational residue fields**: if every element of `B` is congruent modulo `𝔭` to an element of
the local ring `O`, and `𝔪_O` maps into `𝔭`, then the residue field of `B_𝔭` is that of `O`. -/
theorem exists_sub_mem_maximalIdeal_of_forall {O B : Type*} [CommRing O] [IsLocalRing O]
    [CommRing B] [Algebra O B] (𝔭 : Ideal B) [𝔭.IsPrime]
    (hm : ∀ o ∈ maximalIdeal O, algebraMap O B o ∈ 𝔭)
    (hrat : ∀ z : B, ∃ o : O, z - algebraMap O B o ∈ 𝔭) (d : Localization.AtPrime 𝔭) :
    ∃ o : O, d - algebraMap O (Localization.AtPrime 𝔭) o ∈ maximalIdeal _ := by
  obtain ⟨a, s, rfl⟩ : ∃ (a : B) (s : 𝔭.primeCompl), d = IsLocalization.mk' _ a s := by
    obtain ⟨⟨a, s⟩, h⟩ := IsLocalization.mk'_surjective 𝔭.primeCompl d
    exact ⟨a, s, h.symm⟩
  obtain ⟨e₁, he₁⟩ := hrat a
  obtain ⟨e₂, he₂⟩ := hrat s
  have he₂u : IsUnit e₂ := by
    by_contra h
    apply s.2
    have : (s : B) = (s - algebraMap O B e₂) + algebraMap O B e₂ := by ring
    rw [this]
    exact 𝔭.add_mem he₂ (hm _ ((mem_maximalIdeal _).2 h))
  obtain ⟨o, ho⟩ : ∃ o : O, o * e₂ = e₁ :=
    ⟨e₁ * ↑he₂u.unit⁻¹, by rw [mul_assoc, IsUnit.val_inv_mul, mul_one]⟩
  have key : a - algebraMap O B o * s ∈ 𝔭 := by
    have : a - algebraMap O B o * s =
        (a - algebraMap O B e₁) - algebraMap O B o * (s - algebraMap O B e₂) := by
      rw [← ho, map_mul]; ring
    rw [this]
    exact 𝔭.sub_mem he₁ (𝔭.mul_mem_left _ he₂)
  refine ⟨o, ?_⟩
  have hs_unit : IsUnit (algebraMap B (Localization.AtPrime 𝔭) s) :=
    IsLocalization.map_units _ s
  have hx : (IsLocalization.mk' (Localization.AtPrime 𝔭) a s -
      algebraMap O (Localization.AtPrime 𝔭) o) * algebraMap B (Localization.AtPrime 𝔭) s =
      algebraMap B (Localization.AtPrime 𝔭) (a - algebraMap O B o * s) := by
    rw [map_sub, map_mul, IsScalarTower.algebraMap_apply O B (Localization.AtPrime 𝔭)]
    linear_combination IsLocalization.mk'_spec (Localization.AtPrime 𝔭) a s
  rw [← Ideal.mul_unit_mem_iff_mem _ hs_unit, hx]
  exact (IsLocalization.AtPrime.to_map_mem_maximal_iff _ 𝔭 _).2 key

/-- **The maximal ideal of `B_𝔭` is `(ϖ, u)`** if `ϖ, u ∈ 𝔭` and every `z ∈ 𝔭` satisfies
`s z ∈ ϖ B + u B` for some `s ∉ 𝔭`. -/
theorem maximalIdeal_eq_span_of_forall {O B : Type*} [CommRing O] [CommRing B] [Algebra O B]
    (𝔭 : Ideal B) [𝔭.IsPrime] {ϖ : O} {u : B} (hϖ : algebraMap O B ϖ ∈ 𝔭) (hu : u ∈ 𝔭)
    (h : ∀ z ∈ 𝔭, ∃ s ∉ 𝔭, ∃ y₁ y₂ : B, s * z = algebraMap O B ϖ * y₁ + y₂ * u) :
    maximalIdeal (Localization.AtPrime 𝔭) =
      Ideal.span {algebraMap O (Localization.AtPrime 𝔭) ϖ,
        algebraMap B (Localization.AtPrime 𝔭) u} := by
  apply le_antisymm
  · rw [← Localization.AtPrime.map_eq_maximalIdeal, Ideal.map_le_iff_le_comap]
    intro z hz
    obtain ⟨s, hs, y₁, y₂, heq⟩ := h z hz
    rw [Ideal.mem_comap]
    have hunit : IsUnit (algebraMap B (Localization.AtPrime 𝔭) s) :=
      IsLocalization.map_units (Localization.AtPrime 𝔭) (⟨s, hs⟩ : 𝔭.primeCompl)
    have hzD : algebraMap B (Localization.AtPrime 𝔭) z = ↑hunit.unit⁻¹ *
        (algebraMap O (Localization.AtPrime 𝔭) ϖ * algebraMap B (Localization.AtPrime 𝔭) y₁ +
          algebraMap B (Localization.AtPrime 𝔭) y₂ * algebraMap B (Localization.AtPrime 𝔭) u) := by
      rw [IsScalarTower.algebraMap_apply O B (Localization.AtPrime 𝔭), ← map_mul, ← map_mul,
        ← map_add, ← heq, map_mul, ← mul_assoc, IsUnit.val_inv_mul, one_mul]
    rw [hzD]
    exact Ideal.mul_mem_left _ _ (Ideal.add_mem _
      (Ideal.mul_mem_right _ _ (Ideal.subset_span (Set.mem_insert _ _)))
      (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert_of_mem _ rfl))))
  · rw [Ideal.span_le]
    rintro _ (rfl | rfl)
    · rw [IsScalarTower.algebraMap_apply O B (Localization.AtPrime 𝔭)]
      exact (IsLocalization.AtPrime.to_map_mem_maximal_iff _ 𝔭 _).2 hϖ
    · exact (IsLocalization.AtPrime.to_map_mem_maximal_iff _ 𝔭 _).2 hu

end Residue

end SemistableReduction
