/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.DVRDescentDisc
import TemperedFundamentalGroups.SemistableReduction.DVRDescentCount
import TemperedFundamentalGroups.SemistableReduction.VertexDescent
import TemperedFundamentalGroups.SemistableReduction.ResidueDescent

/-!
# The hypotheses of the smooth descent for large `E` (W10, smooth part)

Blueprint §9.12 (O7). The descent of smooth points `isSemistableAt_of_isDiscSmooth` (and its
twisted form `isSemistableAt_of_isDiscSmooth_aff`) takes, besides the rationality of the point,
four hypotheses on `E` and `F₀` which only concern the untwisted `G / C(x)`:
* `hθ`: a primitive element `θ₀` of `F₀ / E(x)` maps to a generator of `G / C(x)`;
* `hinj` (D3c): restriction along `χ` is injective on the vertices of `G` over `w_{0,1}`;
* `hgen` (D3d): the residue fields of the vertices are generated over `k` by residues of `χ(F₀)`;
* `hspan` (D3e): the reductions of `R' = DRint 0 1 G` at any two vertices are `k`-spanned by the
  reductions of `ιD(BD)`.

**`exists_finset_smoothHyps`**: for `G = C(x)[T]` with `T` finite, there is a finite set `S ⊆ C`
of constants such that all four hold for **every** `E` with `S ⊆ φ(E)` and every `E`-form `F₀`
of `G` with `T ⊆ χ(F₀)` (same degree). The proof follows the uniform node descent (O1): the
subfields `famT T S = k₀(S, x, T)` of `G` form a directed family covering `G`, D3c/D3d hold from
some member on (`exists_injOn_adjoin`), and the finitely many spanning elements of
`exists_spanningD` (for the finitely many pairs of vertices) and `x` lie in some member, hence in
`χ(F₀)`, hence in `ιD(BD)` (`mem_BD_of_χ`).

The family lemmas below are local copies (in the namespace `SmoothHyps`) of those of the O1 files
`DVRDescentChoice`/`DVRDescentUniform` (branch `wp-tempered-o1c`), which are not available on
this branch; they can be deduplicated after the merge.
-/

open NNReal Polynomial IsLocalRing Valuation

namespace SemistableReduction

namespace DVRDescent

namespace SmoothHyps

open GaussTube DiscCount FundamentalInequality GaussStability GaussFibre SmoothVertex
  ConstantDescent

universe u v w

/-! ### The family of subfields generated by constants, `x` and `T` -/

section Family

variable {C : Type u} [NontriviallyNormedField C] {G : Type*} [Field G]
  [Algebra (RatFunc C) G] [Algebra C G] [IsScalarTower C (RatFunc C) G]

/-- The subfield of `G` generated by the constants in `S`, `x` and `T`. -/
noncomputable def famT (T : Finset G) (S : Set C) : Subfield G :=
  Subfield.closure (algebraMap C G '' S ∪ ({xF C G} ∪ (T : Set G)))

omit [IsScalarTower C (RatFunc C) G] in
lemma famT_mono (T : Finset G) {S S' : Set C} (h : S ⊆ S') : famT T S ≤ famT T S' :=
  Subfield.closure_mono (Set.union_subset_union_left _ (Set.image_mono h))

omit [IsScalarTower C (RatFunc C) G] in
lemma xF_mem_famT (T : Finset G) (S : Set C) : xF C G ∈ famT T S :=
  Subfield.subset_closure (Set.mem_union_right _ (Set.mem_union_left _ rfl))

omit [IsScalarTower C (RatFunc C) G] in
lemma mem_famT_of_mem (T : Finset G) (S : Set C) {t : G} (ht : t ∈ T) : t ∈ famT T S :=
  Subfield.subset_closure (Set.mem_union_right _ (Set.mem_union_right _ ht))

omit [IsScalarTower C (RatFunc C) G] in
lemma algebraMap_mem_famT (T : Finset G) {S : Set C} {e : C} (he : e ∈ S) :
    algebraMap C G e ∈ famT T S :=
  Subfield.subset_closure (Set.mem_union_left _ ⟨e, he, rfl⟩)

/-- Polynomials in `x` with coefficients in a subfield `M`. -/
lemma algebraMap_poly_mem (M : Subfield G) (P : C[X])
    (hP : ∀ i, algebraMap C G (P.coeff i) ∈ M) (hx : xF C G ∈ M) :
    algebraMap (RatFunc C) G (algebraMap C[X] (RatFunc C) P) ∈ M := by
  rw [← aeval_xF, aeval_eq_sum_range]
  refine M.sum_mem fun i _ ↦ ?_
  rw [Algebra.smul_def]
  exact M.mul_mem (hP i) (M.pow_mem hx _)

/-- Rational functions with coefficients in a subfield `M`. -/
lemma algebraMap_ratFunc_mem (M : Subfield G) (f : RatFunc C)
    (hf : ∀ i, algebraMap C G (f.num.coeff i) ∈ M ∧ algebraMap C G (f.denom.coeff i) ∈ M)
    (hx : xF C G ∈ M) : algebraMap (RatFunc C) G f ∈ M := by
  rw [← RatFunc.num_div_denom f, map_div₀]
  exact M.div_mem (algebraMap_poly_mem M _ (fun i ↦ (hf i).1) hx)
    (algebraMap_poly_mem M _ (fun i ↦ (hf i).2) hx)

/-- **The family covers `G`**: every element of `G = C(x)[T]` lies in `famT T S` for a finite
set `S` of constants. -/
lemma exists_finset_mem_famT {T : Finset G} (hT : Algebra.adjoin (RatFunc C) (T : Set G) = ⊤)
    (y : G) : ∃ S : Finset C, y ∈ famT T (S : Set C) := by
  classical
  have hy : y ∈ Algebra.adjoin (RatFunc C) (T : Set G) := by rw [hT]; exact Algebra.mem_top
  induction hy using Algebra.adjoin_induction with
  | mem t ht => exact ⟨∅, mem_famT_of_mem T _ ht⟩
  | algebraMap f =>
    refine ⟨f.num.coeffs ∪ f.denom.coeffs, algebraMap_ratFunc_mem _ f (fun j ↦ ?_)
      (xF_mem_famT T _)⟩
    have hmem : ∀ q : C[X], q.coeffs ⊆ f.num.coeffs ∪ f.denom.coeffs →
        algebraMap C G (q.coeff j) ∈
          famT T ((f.num.coeffs ∪ f.denom.coeffs : Finset C) : Set C) := by
      intro q hq
      by_cases h0 : q.coeff j = 0
      · rw [h0, map_zero]; exact zero_mem _
      · exact algebraMap_mem_famT T (Finset.mem_coe.mpr (hq (Polynomial.coeff_mem_coeffs h0)))
    exact ⟨hmem _ Finset.subset_union_left, hmem _ Finset.subset_union_right⟩
  | add a b _ _ ha hb =>
    obtain ⟨S, hS⟩ := ha
    obtain ⟨S', hS'⟩ := hb
    exact ⟨S ∪ S', add_mem (famT_mono T (by simp) hS) (famT_mono T (by simp) hS')⟩
  | mul a b _ _ ha hb =>
    obtain ⟨S, hS⟩ := ha
    obtain ⟨S', hS'⟩ := hb
    exact ⟨S ∪ S', mul_mem (famT_mono T (by simp) hS) (famT_mono T (by simp) hS')⟩

/-- `famT T S ⊆ χ(F₀)` when the constants `S` come from `E` and `T ⊆ χ(F₀)`. -/
lemma famT_le_fieldRange {E : Type*} [NontriviallyNormedField E] {φ : E →+* C}
    {F₀ : Type*} [Field F₀] [Algebra (RatFunc E) F₀] {χ : F₀ →+* G} (hχ : IsCompat φ χ)
    {T : Finset G} (hTχ : (T : Set G) ⊆ Set.range χ) {S : Set C} (hS : S ⊆ Set.range φ) :
    famT T S ≤ χ.fieldRange := by
  refine Subfield.closure_le.mpr ?_
  rintro _ (⟨e, he, rfl⟩ | h | h)
  · obtain ⟨e', rfl⟩ := hS he
    refine ⟨algebraMap (RatFunc E) F₀ (algebraMap E (RatFunc E) e'), ?_⟩
    rw [hχ, ratFuncMap_algebraMap_C, ← IsScalarTower.algebraMap_apply]
  · rw [Set.mem_singleton_iff] at h
    subst h
    refine ⟨algebraMap (RatFunc E) F₀ RatFunc.X, ?_⟩
    rw [hχ, ratFuncMap_X]
  · obtain ⟨f, hf⟩ := hTχ h
    exact ⟨f, hf⟩

end Family

/-! ### A primitive element mapping to a generator (`hθ`) -/

section Primitive

variable {C : Type u} [NontriviallyNormedField C] {G : Type*} [Field G] [Algebra (RatFunc C) G]
  {E : Type*} [NontriviallyNormedField E] {φ : E →+* C}
  {F₀ : Type*} [Field F₀] [Algebra (RatFunc E) F₀] [FiniteDimensional (RatFunc E) F₀]
  [Algebra.IsSeparable (RatFunc E) F₀] {χ : F₀ →+* G}

/-- A primitive element of `F₀ / E(x)` maps to a generator of `G / C(x)` if `T ⊆ χ(F₀)`. -/
lemma exists_primitive_χ (hχ : IsCompat φ χ) {T : Finset G}
    (hT : Algebra.adjoin (RatFunc C) (T : Set G) = ⊤) (hTχ : (T : Set G) ⊆ Set.range χ) :
    ∃ θ₀ : F₀, Algebra.adjoin (RatFunc C) {χ θ₀} = ⊤ := by
  obtain ⟨α, hα⟩ := Field.exists_primitive_element (RatFunc E) F₀
  refine ⟨α, eq_top_iff.mpr ?_⟩
  rw [← hT, Algebra.adjoin_le_iff]
  intro t ht
  obtain ⟨f, rfl⟩ := hTχ ht
  have hint : IsIntegral (RatFunc E) α := Algebra.IsIntegral.isIntegral α
  have hf : f ∈ Algebra.adjoin (RatFunc E) {α} := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hint.isAlgebraic, hα]
    trivial
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hf
  obtain ⟨P, rfl⟩ := hf
  change χ (aeval α P) ∈ _
  rw [← aeval_map_χ hχ]
  exact Polynomial.aeval_mem_adjoin_singleton _ _

end Primitive

/-! ### D3c and D3d along a covering family (`hinj`, `hgen`) -/

section Vertices

variable {C : Type u} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
  {F' : Type*} [Field F'] [Algebra (RatFunc C) F'] [Algebra C F']
  [IsScalarTower C (RatFunc C) F'] [FiniteDimensional (RatFunc C) F']

local notation "𝓀" => ResidueField (HenselComplete.integers C)

omit [IsAlgClosed C] [CharZero C] [FiniteDimensional (RatFunc C) F'] in
/-- The residue algebra of a vertex is the one of its extension structure. -/
lemma residueAlgebra_eq (W : Ext C F')
    (h : W.1.valuationSubring.comap (algebraMap C F') =
      (NormedField.valuation (K := C)).valuationSubring) :
    residueAlgebra h = (inferInstance : Algebra 𝓀 (ResidueField W.1.valuationSubring)) := by
  refine Algebra.algebra_ext _ _ fun r ↦ ?_
  obtain ⟨o, rfl⟩ := residue_surjective r
  rw [Valuation.HasExtension.algebraMap_residue_eq_residue_algebraMap]
  rfl

omit [IsAlgClosed C] [CharZero C] [FiniteDimensional (RatFunc C) F'] in
lemma comap_algebraMap_C (W : Ext C F') :
    W.1.valuationSubring.comap (algebraMap C F') =
      (NormedField.valuation (K := C)).valuationSubring := by
  ext a
  simp only [ValuationSubring.mem_comap, Valuation.mem_valuationSubring_iff]
  rw [IsScalarTower.algebraMap_apply C (RatFunc C) F', valuation_algebraMap, gauss1_algebraMap_C,
    NormedField.valuation_apply]

omit [CharZero C] [Algebra C F'] [IsScalarTower C (RatFunc C) F'] in
/-- Vertices are determined by their valuation rings. -/
lemma ext_eq_of_valuationSubring_eq {W W' : Ext C F'}
    (h : W.1.valuationSubring = W'.1.valuationSubring) : W = W' := by
  refine eq_of_le (ramificationIdx_eq_one W) fun a ha ↦ ?_
  have : a ∈ W'.1.valuationSubring := h ▸ ((Valuation.mem_valuationSubring_iff _ _).mpr ha)
  exact (Valuation.mem_valuationSubring_iff _ _).mp this

include hp hp1 in
/-- **D3c + D3d for the vertices**: for a monotone directed family of subfields covering `F'`,
from some index on, restriction is injective on the vertices and the residue fields of the
vertices are generated over `𝓀` by residues of the subfield. -/
theorem exists_injOn_adjoin {J : Type*} [Nonempty J] [Preorder J] [IsDirectedOrder J]
    (Lf : J → Subfield F') (hmono : Monotone Lf) (hcov : ∀ y, ∃ j, y ∈ Lf j) :
    ∃ j, ∀ M : Subfield F', Lf j ≤ M →
      (∀ W W' : Ext C F', W.1.valuationSubring.comap M.subtype =
        W'.1.valuationSubring.comap M.subtype → W = W') ∧
      (∀ W : Ext C F', IntermediateField.adjoin 𝓀
        {z | ∃ y ∈ M, ∃ _ : W.1 y ≤ 1, red C y W = z} = ⊤) := by
  classical
  haveI := finite_ext (F := F') hp hp1
  set S : Set (ValuationSubring F') := Set.range fun W : Ext C F' ↦ W.1.valuationSubring
  have hS : S.Finite := Set.finite_range _
  obtain ⟨j₁, hj₁⟩ := exists_injOn_comap Lf hmono.directed_le hcov hS
  obtain ⟨j₂, hj₂⟩ := exists_adjoin_residue_eq_top (Ω := C) (L := F')
    (v := NormedField.valuation (K := C)) (ι := Unit) (a := fun _ ↦ 0) (c := fun _ ↦ 1)
    (r := fun _ ↦ 1) (fun _ ↦ by simp) hmono.directed_le hcov hS (by
      rintro _ ⟨W, rfl⟩
      refine ⟨(), ?_⟩
      ext a
      simp only [ValuationSubring.mem_comap, Valuation.mem_valuationSubring_iff]
      rw [valuation_algebraMap])
  obtain ⟨j, h₁, h₂⟩ := directed_of (· ≤ ·) j₁ j₂
  refine ⟨j, fun M hM ↦ ⟨fun W W' hWW' ↦ ?_, fun W ↦ ?_⟩⟩
  · apply ext_eq_of_valuationSubring_eq
    refine hj₁ ⟨W, rfl⟩ ⟨W', rfl⟩ ?_
    ext ⟨y, hy⟩
    have hyM : y ∈ M := hM (hmono h₁ hy)
    have := congrArg (fun V : ValuationSubring M ↦ (⟨y, hyM⟩ : M) ∈ V) hWW'
    exact Iff.of_eq this
  · have hgen := hj₂ _ ⟨W, rfl⟩ (comap_algebraMap_C W)
    rw [residueAlgebra_eq W (comap_algebraMap_C W)] at hgen
    rw [eq_top_iff, ← hgen]
    refine IntermediateField.adjoin.mono _ _ _ ?_
    rintro _ ⟨⟨y, hyW⟩, hy, rfl⟩
    exact ⟨y, hM (hmono h₂ hy), hyW, red_of_le hyW⟩

end Vertices

section Translate

variable {C : Type u} [NontriviallyNormedField C] [IsUltrametricDist C]
  {F' : Type*} [Field F'] [Algebra (RatFunc C) F'] [Algebra C F']
  [IsScalarTower C (RatFunc C) F']
  {E : Type*} [NontriviallyNormedField E] {φ : E →+* C}
  {F₀ : Type*} [Field F₀] [Algebra (RatFunc E) F₀] (χ : F₀ →+* F')

local notation "𝓀" => ResidueField (HenselComplete.integers C)

omit [Algebra C F'] [IsScalarTower C (RatFunc C) F'] in
/-- `hinj` from injectivity of the restriction to the subfield `χ(F₀)`. -/
lemma hinj_of_injOn
    (h : ∀ W W' : Ext C F', W.1.valuationSubring.comap χ.fieldRange.subtype =
      W'.1.valuationSubring.comap χ.fieldRange.subtype → W = W')
    (W W' : Ext C F') (hWW : W.1.comap χ = W'.1.comap χ) : W = W' := by
  refine h W W' ?_
  ext ⟨y, f, rfl⟩
  have := congrArg (fun v : Valuation F₀ ℝ≥0 ↦ v f ≤ 1) hWW
  simp only [Valuation.comap_apply] at this
  change W.1 (χ f) ≤ 1 ↔ W'.1 (χ f) ≤ 1
  rw [this]

/-- `hgen` from generation by the residues of the subfield `χ(F₀)`. -/
lemma hgen_of_adjoin (W : Ext C F')
    (h : IntermediateField.adjoin 𝓀
      {z | ∃ y ∈ χ.fieldRange, ∃ _ : W.1 y ≤ 1, red C y W = z} = ⊤) :
    IntermediateField.adjoin 𝓀 (resE χ W : Set (ResidueField W.1.valuationSubring)) = ⊤ := by
  rw [← h]
  congr 1
  ext z
  constructor
  · rintro ⟨f, hf, rfl⟩
    exact ⟨χ f, ⟨f, rfl⟩, hf, rfl⟩
  · rintro ⟨_, ⟨f, rfl⟩, hf, rfl⟩
    exact ⟨f, hf, rfl⟩

end Translate

/-! ### The four hypotheses for every `E ⊇ S` -/

section Main

variable {C : Type u} [NontriviallyNormedField C] [IsUltrametricDist C] [IsAlgClosed C]
  [CharZero C] {p : ℕ} (hp : p.Prime) (hp1 : ‖(p : C)‖ < 1)
  {G : Type v} [Field G] [Algebra (RatFunc C) G] [Algebra C G]
  [IsScalarTower C (RatFunc C) G] [FiniteDimensional (RatFunc C) G]

attribute [local instance] isCurveFunctionField DiscreteCoefficients.isAlgClosed_residueField

local notation "𝓀" => ResidueField (HenselComplete.integers C)

include hp hp1 in
/-- **The hypotheses of the smooth descent hold for large `E`** (`hθ`, `hinj`, `hgen`, `hspan` of
`isSemistableAt_of_isDiscSmooth`): for `G = C(x)[T]` there is a finite set `S` of constants such
that for every `E` with `S ⊆ φ(E)` and every `E`-form `F₀` of `G` of the same degree with
`T ⊆ χ(F₀)`, a primitive element of `F₀` maps to a generator of `G`, restriction to `F₀` is
injective on the vertices, the residues over `E` generate the residue fields of the vertices, and
the reductions of `ιD(BD)` span the reductions of `R'` at any two vertices. -/
theorem exists_finset_smoothHyps {T : Finset G}
    (hT : Algebra.adjoin (RatFunc C) (T : Set G) = ⊤) :
    ∃ S : Finset C, ∀ {E F₀ : Type w} [NontriviallyNormedField E] [IsUltrametricDist E]
      (φ : E →+* C) (hφ : ∀ e, ‖φ e‖ = ‖e‖) (_hS : (S : Set C) ⊆ Set.range φ)
      [Field F₀] [Algebra (RatFunc E) F₀] [FiniteDimensional (RatFunc E) F₀]
      [Algebra.IsSeparable (RatFunc E) F₀] (χ : F₀ →+* G) (hχ : IsCompat φ χ)
      (_hdeg : Module.finrank (RatFunc E) F₀ = Module.finrank (RatFunc C) G)
      (_hTχ : (T : Set G) ⊆ Set.range χ),
      (∃ θ₀ : F₀, Algebra.adjoin (RatFunc C) {χ θ₀} = ⊤) ∧
      (∀ W W' : Ext C G, W.1.comap χ = W'.1.comap χ → W = W') ∧
      (∀ W : Ext C G, IntermediateField.adjoin 𝓀
        (resE χ W : Set (ResidueField W.1.valuationSubring)) = ⊤) ∧
      (∀ v₁ v₂ : Ext C G, ∀ y,
        IsSpanned 𝓀 (ιD χ hφ hχ (F₀ := F₀)).range (redD v₁) (redD v₂) y) := by
  classical
  haveI := finite_ext (F := G) hp hp1
  letI : Fintype (Ext C G) := Fintype.ofFinite _
  -- D3c/D3d along the family `famT T S`
  have hLmono : Monotone fun S : Finset C ↦ famT T (S : Set C) :=
    fun S S' h ↦ famT_mono T (Finset.coe_subset.mpr h)
  have hLcov : ∀ y : G, ∃ S : Finset C, y ∈ famT T (S : Set C) := exists_finset_mem_famT hT
  obtain ⟨T₁, hT₁⟩ := exists_injOn_adjoin hp hp1 _ hLmono hLcov
  -- the spanning elements for every pair of vertices, and `x`
  choose N r hr using fun vv : Ext C G × Ext C G ↦ exists_spanningD (F' := G) vv.1 vv.2
  obtain ⟨ys, hys⟩ : ∃ ys : Finset (DRint (0 : C) 1 G),
      ys = insert xD (Finset.univ.biUnion fun vv ↦ Finset.univ.image (r vv)) := ⟨_, rfl⟩
  choose Ty hTy using fun y : DRint (0 : C) 1 G ↦ hLcov (y : G)
  refine ⟨T₁ ∪ ys.biUnion Ty, ?_⟩
  intro E F₀ _ _ φ hφ hS _ _ _ _ χ hχ hdeg hTχ
  have hleS : ∀ S' : Finset C, S' ⊆ T₁ ∪ ys.biUnion Ty → famT T (S' : Set C) ≤ χ.fieldRange :=
    fun S' hS' ↦ famT_le_fieldRange hχ hTχ fun t ht ↦ hS (Finset.mem_coe.mpr (hS' ht))
  obtain ⟨θ₀, hθ₀⟩ := exists_primitive_χ hχ hT hTχ
  obtain ⟨hinj₁, hgen₁⟩ := hT₁ _ (hleS T₁ Finset.subset_union_left)
  -- the elements of `ys` descend to `BD`
  have hdesc : ∀ y ∈ ys, y ∈ (ιD χ hφ hχ (F₀ := F₀)).range := by
    intro y hy
    obtain ⟨f, hf⟩ := hleS (Ty y) (fun t ht ↦ Finset.mem_union_right _
      (Finset.mem_biUnion.mpr ⟨y, hy, ht⟩)) (hTy y)
    have hfB : f ∈ BD E F₀ := mem_BD_of_χ hφ hχ hdeg hθ₀ (by rw [hf]; exact y.2)
    exact ⟨⟨f, hfB⟩, Subtype.ext (by rw [coe_ιD]; exact hf)⟩
  refine ⟨⟨θ₀, hθ₀⟩, hinj_of_injOn χ hinj₁, fun W ↦ hgen_of_adjoin χ W (hgen₁ W),
    fun v₁ v₂ y ↦ hr (v₁, v₂) _ (fun j ↦ hdesc _ ?_) (hdesc _ ?_) y⟩
  · rw [hys]
    exact Finset.mem_insert_of_mem (Finset.mem_biUnion.mpr
      ⟨(v₁, v₂), Finset.mem_univ _, Finset.mem_image_of_mem _ (Finset.mem_univ j)⟩)
  · rw [hys]
    exact Finset.mem_insert_self _ _

end Main

end SmoothHyps

end DVRDescent

end SemistableReduction
