/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.SmoothLemma

/-!
# Semistability descends along étale base change of the base DVR (W10, smooth part (3))

Blueprint §9.12 (O7). Let `O → O'` be étale (an unramified extension of DVRs `O_E → O_{E'}`).

* `etale_adjoinRoot`: `R[X] ⧸ (f)` is étale over `R` for `f` monic and coprime to `f'`
  (a standard étale algebra);
* `etale_of_aeval_eq_zero`: an `R`-algebra generated by a root `x` of such an `f` whose powers
  `1, x, …, x^{d-1}` are independent is étale (it is `R[X] ⧸ (f)`);
* `IsEtaleLocallyAt.of_base`: étale-local models over `O'` are étale-local models over `O`
  when the model over `O'` is étale over the model over `O`;
* `Node.baseMap`, `etale_nodeBaseMap`: `O[u, v] ⧸ (u v - c) → O'[u, v] ⧸ (u v - c)` is étale
  (base change); likewise `O[X] → O'[X]`;
* **`IsSemistableAt.of_base`**: semistability over `O'` (for the image of `ϖ`) of an
  `O'`-algebra implies semistability over `O`;
* **`IsSemistableAt.comap_of_baseChange`**: if `ψ : B → B'` is étale (`B'` an `O'`-algebra, e.g.
  `B' = O' ⊗_O B`) and `B'` is semistable over `O'` at `𝔭'`, then `B` is semistable over `O` at
  `ψ⁻¹ 𝔭'`.
-/

universe u

open Polynomial TensorProduct

namespace SemistableReduction

section StandardEtale

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]

/-- `R[X] ⧸ (f)` is étale for `f` monic if `f' p₁ + f p₂` is a unit modulo `f`. -/
theorem etale_adjoinRoot {f : R[X]} (hf : f.Monic) (p₁ p₂ : R[X])
    (hunit : IsUnit (AdjoinRoot.mk f (derivative f * p₁ + f * p₂))) :
    Algebra.Etale R (AdjoinRoot f) := by
  let P : StandardEtalePair R :=
    ⟨f, hf, derivative f * p₁ + f * p₂, ⟨p₁, p₂, 1, by rw [pow_one]⟩⟩
  let e₁ : AdjoinRoot f ≃ₐ[R] Localization.Away (AdjoinRoot.mk P.f P.g) :=
    ((IsLocalization.atUnit (AdjoinRoot f) (Localization.Away (AdjoinRoot.mk P.f P.g))
      (AdjoinRoot.mk P.f P.g) hunit).restrictScalars R)
  let e : P.Ring ≃ₐ[R] AdjoinRoot f := P.equivAwayAdjoinRoot.trans e₁.symm
  haveI : Algebra.IsStandardEtale R (AdjoinRoot f) := Algebra.IsStandardEtale.of_equiv e
  infer_instance

/-- An `R`-algebra generated by a root `x` of a monic `f`, without relations of degree `< deg f`,
is étale over `R` if `f'(x) p₁(x)` is a unit (for some `p₁`; more generally `f' p₁ + f p₂`). -/
theorem etale_of_aeval_eq_zero [Nontrivial R] {f : R[X]} (hf : f.Monic) (p₁ p₂ : R[X])
    {x : S} (hx : aeval x f = 0) (hunit : IsUnit (aeval x (derivative f * p₁ + f * p₂)))
    (hgen : Algebra.adjoin R {x} = ⊤)
    (hinj : ∀ q : R[X], q.degree < f.degree → aeval x q = 0 → q = 0) :
    Algebra.Etale R S := by
  have hx' : f.eval₂ (Algebra.ofId R S).toRingHom x = 0 := by
    rw [← hx, aeval_def]; rfl
  let φ : AdjoinRoot f →ₐ[R] S := AdjoinRoot.liftAlgHom f (Algebra.ofId R S) x hx'
  have hφ : ∀ q : R[X], φ (AdjoinRoot.mk f q) = aeval x q := fun q ↦ by
    rw [AdjoinRoot.liftAlgHom_mk, aeval_def]; rfl
  have hbij : Function.Bijective φ := by
    refine ⟨fun a b hab ↦ ?_, fun s ↦ ?_⟩
    · obtain ⟨a, rfl⟩ := AdjoinRoot.mk_surjective a
      obtain ⟨b, rfl⟩ := AdjoinRoot.mk_surjective b
      rw [hφ, hφ, ← sub_eq_zero, ← map_sub] at hab
      rw [← sub_eq_zero, ← map_sub, AdjoinRoot.mk_eq_zero]
      have hmod : aeval x ((a - b) %ₘ f) = 0 := by
        rw [← modByMonic_add_div (a - b) f, map_add, map_mul, hx, zero_mul, add_zero] at hab
        exact hab
      have := hinj _ (degree_modByMonic_lt _ hf) hmod
      exact (modByMonic_eq_zero_iff_dvd hf).1 this
    · have hs : s ∈ Algebra.adjoin R {x} := hgen ▸ Algebra.mem_top
      rw [Algebra.adjoin_singleton_eq_range_aeval] at hs
      obtain ⟨q, rfl⟩ := hs
      exact ⟨AdjoinRoot.mk f q, hφ q⟩
  let e := AlgEquiv.ofBijective φ hbij
  haveI := etale_adjoinRoot hf p₁ p₂ (by
    have : φ (AdjoinRoot.mk f (derivative f * p₁ + f * p₂)) =
        aeval x (derivative f * p₁ + f * p₂) := hφ _
    rw [← this] at hunit
    exact (isUnit_map_iff e _).1 hunit)
  exact Algebra.Etale.of_equiv e

end StandardEtale

section Base

variable {O O' : Type u} [CommRing O] [CommRing O'] [Algebra O O']

/-- **Change of base for étale-local models**: if `A` (an `O'`-algebra, hence an `O`-algebra) is
étale-locally `M'` over `O'` and `κ : M → M'` is étale over `O → O'`, then `A` is étale-locally
`M` over `O`. -/
theorem IsEtaleLocallyAt.of_base {M M' A : Type u} [CommRing M] [CommRing M'] [CommRing A]
    [Algebra O M] [Algebra O' M'] [Algebra O' A] [Algebra O A] [IsScalarTower O O' A]
    (κ : M →+* M') (hκ : κ.Etale)
    (hκc : κ.comp (algebraMap O M) = (algebraMap O' M').comp (algebraMap O O')) {𝔭 : Ideal A}
    (h : IsEtaleLocallyAt O' M' 𝔭) : IsEtaleLocallyAt O M 𝔭 := by
  obtain ⟨C, _, g, f, 𝔮, hg, hf, h𝔮, hcomap, hcomp⟩ := h
  refine ⟨C, inferInstance, g, f.comp κ, 𝔮, hg,
    RingHom.Etale.stableUnderComposition κ f hκ hf, h𝔮, hcomap, ?_⟩
  rw [RingHom.comp_assoc, hκc, ← RingHom.comp_assoc, hcomp, RingHom.comp_assoc,
    ← IsScalarTower.algebraMap_eq]

/-- `Node O c → Node O' c` as an `O`-algebra map. -/
noncomputable def Node.baseAlg (c : O) : Node O c →ₐ[O] Node O' (algebraMap O O' c) :=
  Node.lift (Node.u _) (Node.v _) (by
    rw [Node.u_mul_v, IsScalarTower.algebraMap_apply O O' (Node O' (algebraMap O O' c))])

/-- The node over `O'` is the base change of the node over `O`. -/
noncomputable def Node.tensorEquiv (c : O) :
    O' ⊗[O] Node O c ≃ₐ[O'] Node O' (algebraMap O O' c) := by
  refine AlgEquiv.ofAlgHom
    (Algebra.TensorProduct.lift (Algebra.ofId O' _) (Node.baseAlg c) fun _ _ ↦ Commute.all _ _)
    (Node.lift (O := O') (S := O' ⊗[O] Node O c) ((1 : O') ⊗ₜ[O] Node.u c)
      ((1 : O') ⊗ₜ[O] Node.v c) ?_) ?_ ?_
  · rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, Node.u_mul_v,
      ← IsScalarTower.algebraMap_apply, Algebra.TensorProduct.algebraMap_apply']
  · apply Node.algHom_ext
    · simp [Node.baseAlg]
    · simp [Node.baseAlg]
  · apply Algebra.TensorProduct.ext
    · exact Subsingleton.elim _ _
    · exact Node.algHom_ext (O := O) (a := c) (S := O' ⊗[O] Node O c) (by simp [Node.baseAlg])
        (by simp [Node.baseAlg])

lemma Node.tensorEquiv_tmul (c : O) (z : Node O c) :
    Node.tensorEquiv (O' := O') c (1 ⊗ₜ z) = Node.baseAlg c z := by
  simp [Node.tensorEquiv]

/-- `T → O' ⊗_O T` is étale if `O → O'` is. -/
theorem etale_includeRight_base (hO : (algebraMap O O').Etale) (T : Type u) [CommRing T]
    [Algebra O T] :
    (Algebra.TensorProduct.includeRight : T →ₐ[O] O' ⊗[O] T).toRingHom.Etale := by
  have h₁ : (Algebra.TensorProduct.includeLeftRingHom : T →+* T ⊗[O] O').Etale :=
    RingHom.Etale.isStableUnderBaseChange.tensorProduct T hO
  have e : (Algebra.TensorProduct.includeRight : T →ₐ[O] O' ⊗[O] T).toRingHom =
      (Algebra.TensorProduct.comm O T O').toRingHom.comp
        Algebra.TensorProduct.includeLeftRingHom := by
    ext z
    simp
  rw [e]
  exact RingHom.Etale.stableUnderComposition _ _ h₁
    (RingHom.Etale.of_bijective (Algebra.TensorProduct.comm O T O').bijective)

/-- A map `T → T'` identified with `T → O' ⊗_O T` is étale if `O → O'` is. -/
theorem etale_of_tensorEquiv (hO : (algebraMap O O').Etale) {T T' : Type u} [CommRing T]
    [CommRing T'] [Algebra O T] [Algebra O T'] (g : T →ₐ[O] T') (e : O' ⊗[O] T ≃+* T')
    (he : ∀ z, e (1 ⊗ₜ z) = g z) : g.toRingHom.Etale := by
  have h : g.toRingHom = e.toRingHom.comp
      (Algebra.TensorProduct.includeRight : T →ₐ[O] O' ⊗[O] T).toRingHom := by
    ext z
    exact (he z).symm
  rw [h]
  exact RingHom.Etale.stableUnderComposition _ _ (etale_includeRight_base hO T)
    (RingHom.Etale.of_bijective e.bijective)

/-- `Node O c → Node O' c` is étale if `O → O'` is. -/
theorem Node.etale_baseAlg (hO : (algebraMap O O').Etale) (c : O) :
    (Node.baseAlg (O' := O') c).toRingHom.Etale := by
  exact etale_of_tensorEquiv (T := Node O c) (T' := Node O' (algebraMap O O' c)) hO
    (Node.baseAlg c) (Node.tensorEquiv c).toRingEquiv (Node.tensorEquiv_tmul c)

/-- **Semistability descends along an étale extension of the base**: an `O'`-algebra semistable
over `O'` at `𝔭` (for the image of `ϖ`) is semistable over `O` at `𝔭`. -/
theorem IsSemistableAt.of_base (hO : (algebraMap O O').Etale) {ϖ : O} {A : Type u} [CommRing A]
    [Algebra O' A] [Algebra O A] [IsScalarTower O O' A] {𝔭 : Ideal A}
    (h : IsSemistableAt (algebraMap O O' ϖ) 𝔭) : IsSemistableAt ϖ 𝔭 := by
  rcases h with ⟨n, h⟩ | h
  · rw [← map_pow] at h
    refine .inl ⟨n, h.of_base (Node.baseAlg (ϖ ^ n)).toRingHom (Node.etale_baseAlg hO _) ?_⟩
    ext o
    exact ((Node.baseAlg (O' := O') (ϖ ^ n)).commutes o).trans
      (IsScalarTower.algebraMap_apply O O' _ o)
  · letI := Polynomial.algebra (R := O) (A := O')
    refine .inr (h.of_base (algebraMap O[X] O'[X]) ?_ ?_)
    · exact RingHom.Etale.isStableUnderBaseChange O O' O[X] O'[X] hO
    · rw [← IsScalarTower.algebraMap_eq, ← IsScalarTower.algebraMap_eq]

/-- **Descent along an étale base change**: if `ψ : B → B'` is an étale `O`-algebra map to an
`O'`-algebra `B'` (e.g. `B' = O' ⊗_O B`, or the normalization over `O'`) and `B'` is semistable over
`O'` at `𝔭'`, then `B` is semistable over `O` at `ψ⁻¹ 𝔭'`. -/
theorem IsSemistableAt.comap_of_baseChange (hO : (algebraMap O O').Etale) {ϖ : O}
    {B B' : Type u} [CommRing B] [CommRing B'] [Algebra O B] [Algebra O' B'] [Algebra O B']
    [IsScalarTower O O' B'] (ψ : B →ₐ[O] B') (hψ : ψ.toRingHom.Etale) {𝔭' : Ideal B'}
    (h : IsSemistableAt (algebraMap O O' ϖ) 𝔭') : IsSemistableAt ϖ (𝔭'.comap ψ.toRingHom) :=
  (h.of_base hO).of_etale_of_comap ψ hψ

/-- Smoothness descends along an étale extension of the base. -/
theorem IsEtaleLocallyAt.poly_of_base (hO : (algebraMap O O').Etale) {A : Type u} [CommRing A]
    [Algebra O' A] [Algebra O A] [IsScalarTower O O' A] {𝔭 : Ideal A}
    (h : IsEtaleLocallyAt O' O'[X] 𝔭) : IsEtaleLocallyAt O O[X] 𝔭 := by
  letI := Polynomial.algebra (R := O) (A := O')
  refine h.of_base (algebraMap O[X] O'[X]) ?_ ?_
  · exact RingHom.Etale.isStableUnderBaseChange O O' O[X] O'[X] hO
  · rw [← IsScalarTower.algebraMap_eq, ← IsScalarTower.algebraMap_eq]

/-- **Smoothness descends along an étale base change** (smooth form of
`IsSemistableAt.comap_of_baseChange`). -/
theorem IsEtaleLocallyAt.poly_comap_of_baseChange (hO : (algebraMap O O').Etale)
    {B B' : Type u} [CommRing B] [CommRing B'] [Algebra O B] [Algebra O' B'] [Algebra O B']
    [IsScalarTower O O' B'] (ψ : B →ₐ[O] B') (hψ : ψ.toRingHom.Etale) {𝔭' : Ideal B'}
    (h : IsEtaleLocallyAt O' O'[X] 𝔭') : IsEtaleLocallyAt O O[X] (𝔭'.comap ψ.toRingHom) :=
  (h.poly_of_base hO).of_etale_of_comap ψ hψ

end Base

end SemistableReduction
