/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.EtaleLocalDomain

/-!
# Unramified birational-type maps out of normal domains are étale (W7, S9)

Blueprint §9.9, S9. Let `R` be an integrally closed domain and `S ⊇ R` a domain of finite type
over `R`, unramified at a prime `Q`. Then `S` is étale over `R` at `Q`
(`isEtaleAt_of_isUnramifiedAt`).

Proof. By Mathlib's local structure of unramified algebras (via Zariski's main theorem) a standard
étale `R`-algebra `B` surjects onto `S[1/f]` for some `f ∉ Q`. Let `Q'` be the prime of `B` under
`Q`. The induced surjection `B_{Q'} → S_Q` is injective: `B_{Q'}` is a domain whose nonzero
elements divide nonzero constants of `R` (`EtaleLocalDomain`), and `R → S_Q` is injective. So
`S_Q` is a localization of the étale algebra `B`, hence formally étale over `R`.

Applied to `R` the node `O[u, v] ⧸ (u v - ϖ ^ n)` this is the core of the node lemma: a point of
a normal model at which the maximal ideal is generated by `ϖ` and two node coordinates is
étale-locally the node.
-/

open Algebra IsLocalRing

namespace SemistableReduction


/-- **Unramified + injective ⇒ étale (and flat)**, for a domain of finite type over a normal
domain. -/
theorem isEtaleAt_and_flat_of_isUnramifiedAt {R S : Type*} [CommRing R] [IsDomain R]
    [IsIntegrallyClosed R] [CommRing S] [IsDomain S] [Algebra R S] [Algebra.FiniteType R S]
    (hinj : Function.Injective (algebraMap R S)) (Q : Ideal S)
    [Q.IsPrime] [Algebra.IsUnramifiedAt R Q] :
    Algebra.IsEtaleAt R Q ∧ Module.Flat R (Localization.AtPrime Q) := by
  obtain ⟨f, hfQ, P, φ, hφ⟩ := Algebra.IsUnramifiedAt.exists_hasStandardEtaleSurjectionOn (R := R) Q
  let SQ := Localization.AtPrime Q
  have hfu : IsUnit (algebraMap S SQ f) := IsLocalization.map_units SQ (⟨f, hfQ⟩ : Q.primeCompl)
  let lf : Localization.Away f →+* SQ := IsLocalization.Away.lift f hfu
  have hlf : ∀ s, lf (algebraMap S _ s) = algebraMap S SQ s := fun s ↦ IsLocalization.lift_eq _ s
  let ψ : P.Ring →+* SQ := lf.comp φ.toRingHom
  letI : Algebra P.Ring SQ := ψ.toAlgebra
  have hψ : ∀ b, algebraMap P.Ring SQ b = lf (φ b) := fun _ ↦ rfl
  haveI : IsScalarTower R P.Ring SQ := IsScalarTower.of_algebraMap_eq fun r ↦ by
    rw [hψ, φ.commutes, IsScalarTower.algebraMap_apply R S (Localization.Away f), hlf,
      ← IsScalarTower.algebraMap_apply]
  let Q' : Ideal P.Ring := (maximalIdeal SQ).comap (algebraMap P.Ring SQ)
  -- `R → SQ` is injective
  have hRSQ : Function.Injective (algebraMap R SQ) := by
    rw [IsScalarTower.algebraMap_eq R S SQ]
    exact (IsLocalization.injective SQ Q.primeCompl_le_nonZeroDivisors).comp hinj
  haveI : IsLocalization Q'.primeCompl SQ := by
    rw [isLocalization_iff]
    refine ⟨fun y ↦ ?_, fun z ↦ ?_, fun {x y} hxy ↦ ?_⟩
    · by_contra h
      exact y.2 ((IsLocalRing.mem_maximalIdeal _).mpr h)
    · obtain ⟨⟨s, t⟩, hst⟩ := IsLocalization.surj Q.primeCompl z
      obtain ⟨b₁, hb₁⟩ := hφ (algebraMap S _ s)
      obtain ⟨b₂, hb₂⟩ := hφ (algebraMap S _ (t : S))
      have h₂ : algebraMap P.Ring SQ b₂ = algebraMap S SQ t := by rw [hψ, hb₂, hlf]
      refine ⟨⟨b₁, ⟨b₂, ?_⟩⟩, ?_⟩
      · change b₂ ∉ Q'
        change algebraMap P.Ring SQ b₂ ∉ maximalIdeal SQ
        rw [h₂, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, not_not]
        exact IsLocalization.map_units SQ t
      · simp only
        rw [h₂, hψ, hb₁, hlf]
        exact hst
    · -- injectivity of `B_{Q'} → SQ`
      suffices H : ∀ b, algebraMap P.Ring SQ b = 0 → ∃ c : Q'.primeCompl, (c : P.Ring) * b = 0 by
        obtain ⟨c, hc⟩ := H (x - y) (by rw [map_sub, hxy, sub_self])
        exact ⟨c, by rw [mul_sub, sub_eq_zero] at hc; exact hc⟩
      intro b hb
      let D := Localization.AtPrime Q'
      by_cases hb0 : algebraMap P.Ring D b = 0
      · exact (IsLocalization.map_eq_zero_iff Q'.primeCompl D b).mp hb0
      · exfalso
        obtain ⟨r, hr0, e, he⟩ := exists_dvd_algebraMap R Q' hb0
        -- map `D → SQ`
        have hunits : ∀ y : Q'.primeCompl, IsUnit (algebraMap P.Ring SQ y) := fun y ↦ by
          by_contra h
          exact y.2 ((IsLocalRing.mem_maximalIdeal _).mpr h)
        let θ : D →+* SQ := IsLocalization.lift hunits
        have hθ : ∀ b, θ (algebraMap P.Ring D b) = algebraMap P.Ring SQ b :=
          fun b ↦ IsLocalization.lift_eq hunits b
        have := congrArg θ he
        rw [map_mul, hθ, hb, zero_mul, IsScalarTower.algebraMap_apply R P.Ring D, hθ,
          ← IsScalarTower.algebraMap_apply] at this
        exact hr0 (hRSQ (by rw [this, map_zero]))
  haveI : FormallyEtale P.Ring SQ := .of_isLocalization Q'.primeCompl
  haveI : Module.Flat P.Ring SQ := IsLocalization.flat SQ Q'.primeCompl
  exact ⟨FormallyEtale.comp R P.Ring SQ, Module.Flat.trans R P.Ring SQ⟩

/-- **Unramified + injective ⇒ étale**, for a domain of finite type over a normal domain. -/
theorem isEtaleAt_of_isUnramifiedAt {R S : Type*} [CommRing R] [IsDomain R]
    [IsIntegrallyClosed R] [CommRing S] [IsDomain S] [Algebra R S] [Algebra.FiniteType R S]
    (hinj : Function.Injective (algebraMap R S)) (Q : Ideal S)
    [Q.IsPrime] [Algebra.IsUnramifiedAt R Q] : Algebra.IsEtaleAt R Q :=
  (isEtaleAt_and_flat_of_isUnramifiedAt hinj Q).1

end SemistableReduction
