/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.UnramifiedExt
import TemperedFundamentalGroups.SemistableReduction.SmoothDescent
import TemperedFundamentalGroups.Setup.SmoothNormal

/-!
# The vertex chart over an unramified extension (W10, smooth part (2)/(3))

Blueprint §9.12 (O7). Setting of `DVRDescentDisc` (`φ : E → C` isometric, `χ : F₀ → F'`
compatible) and an unramified extension `E' = E[X] ⧸ (g)` inside `C` (`Unramified.UnrData`).

* `F₀' = F₀[X] ⧸ (g₁)`, `g₁` the minimal polynomial over `F₀` of `β ∈ F'` (`UnrChart.F₀'`), with
  `χ' : F₀' → F'` (`UnrChart.χ'`), its `E'(x)`-algebra structure and `IsCompat φ' χ'`
  (`UnrChart.isCompat`), `[F₀' : E'(x)] = [F' : C(x)]` (`UnrChart.finrank_eq`);
* the map of vertex charts `BD E F₀ → BD E' F₀'` is étale (`UnrChart.etale_j`).
-/

open Polynomial IsLocalRing

set_option linter.unusedSectionVars false

namespace SemistableReduction

/-- Ring homomorphisms out of `K(X)` agreeing on constants and on `X` are equal. -/
theorem ratFunc_ringHom_ext {K L : Type*} [Field K] [CommRing L] {f g : RatFunc K →+* L}
    (hC : ∀ a, f (algebraMap K (RatFunc K) a) = g (algebraMap K (RatFunc K) a))
    (hX : f RatFunc.X = g RatFunc.X) : f = g := by
  refine IsLocalization.ringHom_ext (nonZeroDivisors K[X]) ?_
  refine Polynomial.ringHom_ext (fun a ↦ ?_) ?_
  · simp only [RingHom.coe_comp, Function.comp_apply]
    rw [← Polynomial.algebraMap_eq, ← IsScalarTower.algebraMap_apply]
    exact hC a
  · simp only [RingHom.coe_comp, Function.comp_apply, RatFunc.algebraMap_X]
    exact hX

/-- A field generated by an integral element is finite, of degree that of its minimal
polynomial. -/
theorem finiteDimensional_and_finrank_of_adjoin {K L : Type*} [Field K] [Field L] [Algebra K L]
    {x : L} (hx : IsIntegral K x) (htop : Algebra.adjoin K {x} = ⊤) :
    FiniteDimensional K L ∧ Module.finrank K L = (minpoly K x).natDegree := by
  have h := IntermediateField.adjoin_eq_top_of_algebra K {x} htop
  haveI := IntermediateField.adjoin.finiteDimensional hx
  have hf := IntermediateField.adjoin.finrank hx
  rw [h, IntermediateField.finrank_top'] at hf
  refine ⟨?_, hf⟩
  have : FiniteDimensional K (⊤ : IntermediateField K L) := h ▸ inferInstance
  exact (IntermediateField.topEquiv (F := K) (E := L)).toLinearEquiv.finiteDimensional

/-- **Étale algebras over normal domains are integrally closed** (in the form used here): if
`T` is étale over an integrally closed domain `R`, `T ⊆ L` a field, and `z ∈ L` is integral over
`T` with `m z ∈ T` for some nonzero `m ∈ R`, then `z ∈ T`. -/
theorem mem_of_etale_of_isIntegral {R T L : Type*} [CommRing R] [IsDomain R]
    [IsIntegrallyClosed R] [CommRing T] [IsDomain T] [Algebra R T] [Algebra.Etale R T] [Field L]
    [Algebra T L] (hinj : Function.Injective (algebraMap T L)) {z : L} {m : R}
    (hm : algebraMap R T m ≠ 0) {a : T}
    (ha : algebraMap T L a = algebraMap T L (algebraMap R T m) * z) (hz : IsIntegral T z) :
    ∃ t : T, algebraMap T L t = z := by
  obtain ⟨p, hpm, hpz⟩ := hz
  set n := p.natDegree
  set M := algebraMap R T m
  have hM : M ∈ nonZeroDivisors T := mem_nonZeroDivisors_of_ne_zero hm
  have heq : a ^ n + ∑ i : Fin n, p.coeff i * a ^ (i : ℕ) * M ^ (n - i) = 0 := by
    apply hinj
    rw [map_zero, map_add, map_pow, map_sum, ha]
    have hp := hpm.as_sum
    have h0 : (X ^ n + ∑ i ∈ Finset.range n, C (p.coeff i) * X ^ i).eval₂ (algebraMap T L) z
        = 0 := by rw [← hp]; exact hpz
    simp only [eval₂_add, eval₂_X_pow, eval₂_finsetSum, eval₂_mul, eval₂_C] at h0
    have : (algebraMap T L M * z) ^ n + ∑ i : Fin n, algebraMap T L (p.coeff i * a ^ (i : ℕ) *
        M ^ (n - i)) = algebraMap T L M ^ n * (z ^ n + ∑ i ∈ Finset.range n,
          algebraMap T L (p.coeff i) * z ^ i) := by
      rw [mul_add, mul_pow, Finset.mul_sum, ← Fin.sum_univ_eq_sum_range]
      congr 1
      refine Finset.sum_congr rfl fun i _ ↦ ?_
      rw [map_mul, map_mul, map_pow, map_pow, ha, mul_pow]
      have hi : (i : ℕ) ≤ n := i.2.le
      have hpow : algebraMap T L M ^ n = algebraMap T L M ^ (n - i) * algebraMap T L M ^ (i : ℕ) :=
        by rw [← pow_add, Nat.sub_add_cancel hi]
      rw [hpow]
      ring
    rw [this, h0, mul_zero]
  obtain ⟨t, ht⟩ := TemperedFundamentalGroups.SmoothNormal.dvd_of_etale (P := R) hM _ heq
  refine ⟨t, ?_⟩
  have hM' : algebraMap T L M ≠ 0 := by
    rw [ne_eq, map_eq_zero_iff _ hinj]; exact hm
  apply mul_left_cancel₀ hM'
  rw [← ha, ht, map_mul]

namespace Unramified

namespace UnrChart

open DVRDescent GaussTube DiscCount SmoothVertex

universe u w

variable {C : Type u} [NontriviallyNormedField C] [IsUltrametricDist C]
  {E : Type w} [NontriviallyNormedField E] [IsUltrametricDist E] {φ : E →+* C} (D : UnrData φ)
  {F' : Type*} [Field F'] [Algebra (RatFunc C) F'] [Algebra C F']
  [IsScalarTower C (RatFunc C) F']
  {F₀ : Type w} [Field F₀] [Algebra (RatFunc E) F₀] (χ : F₀ →+* F')

local notation "O_E" => HenselComplete.integers E

/-- `E → F₀`. -/
noncomputable abbrev cE : E →+* F₀ := (algebraMap (RatFunc E) F₀).comp (algebraMap E (RatFunc E))

/-- `β ∈ F'`. -/
noncomputable abbrev βF : F' := algebraMap C F' D.β

/-- The minimal polynomial of `β` over `F₀` (via `χ`). -/
noncomputable def g₁ : F₀[X] := letI := χ.toAlgebra; minpoly F₀ (βF (F' := F') D)

variable {χ}

lemma eval₂_βF (hχ : IsCompat φ χ) :
    (D.g.map (cE.comp (O_E).subtype)).eval₂ χ (βF (F' := F') D) = 0 := by
  rw [eval₂_map]
  have : χ.comp (cE.comp (O_E).subtype) = (algebraMap C F').comp (φ.comp (O_E).subtype) := by
    ext e
    simp only [RingHom.coe_comp, Function.comp_apply]
    exact χ_cst hχ e
  rw [this, ← hom_eval₂, D.root, map_zero]

lemma isIntegral_βF (hχ : IsCompat φ χ) :
    letI := χ.toAlgebra; IsIntegral F₀ (βF (F' := F') D) := by
  letI := χ.toAlgebra
  refine ⟨D.g.map (cE.comp (O_E).subtype), D.monic.map _, ?_⟩
  exact eval₂_βF D hχ

lemma irreducible_g₁ (hχ : IsCompat φ χ) : Irreducible (g₁ D χ) := by
  letI := χ.toAlgebra
  exact minpoly.irreducible (isIntegral_βF D hχ)

lemma monic_g₁ (hχ : IsCompat φ χ) : (g₁ D χ).Monic := by
  letI := χ.toAlgebra
  exact minpoly.monic (isIntegral_βF D hχ)

lemma eval₂_g₁ : (g₁ D χ).eval₂ χ (βF (F' := F') D) = 0 := by
  letI := χ.toAlgebra
  exact minpoly.aeval F₀ _

lemma g₁_dvd (hχ : IsCompat φ χ) : g₁ D χ ∣ D.g.map (cE.comp (O_E).subtype) := by
  letI := χ.toAlgebra
  exact minpoly.dvd F₀ _ (eval₂_βF D hχ)

variable (χ)

/-- The function field `F₀' = F₀[X] ⧸ (g₁)` over `E'`. -/
abbrev F₀' : Type w := AdjoinRoot (g₁ D χ)

variable [Fact (Irreducible (g₁ D χ))]

/-- `F₀ → F₀'`. -/
noncomputable abbrev of₀ : F₀ →+* F₀' D χ := AdjoinRoot.of _

/-- `χ' : F₀' → F'`, `root ↦ β`. -/
noncomputable def χ' : F₀' D χ →+* F' := AdjoinRoot.lift χ (βF D) (eval₂_g₁ D)

lemma χ'_of₀ (f : F₀) : χ' D χ (of₀ D χ f) = χ f := AdjoinRoot.lift_of _

lemma χ'_root : χ' D χ (AdjoinRoot.root _) = βF D := AdjoinRoot.lift_root _

variable {χ}

lemma eval₂_root_gF (hχ : IsCompat φ χ) :
    (D.g.map (cE.comp (O_E).subtype)).eval₂ (of₀ D χ) (AdjoinRoot.root (g₁ D χ)) = 0 := by
  obtain ⟨q, hq⟩ := g₁_dvd D hχ
  rw [hq, eval₂_mul]
  have h0 : (g₁ D χ).eval₂ (of₀ D χ) (AdjoinRoot.root (g₁ D χ)) = 0 :=
    AdjoinRoot.eval₂_root _
  rw [h0, zero_mul]

/-- `E' → F₀'`, `root ↦ root`. -/
noncomputable def ιE (hχ : IsCompat φ χ) : D.F →+* F₀' D χ :=
  AdjoinRoot.lift ((of₀ D χ).comp cE) (AdjoinRoot.root _) (by
    obtain ⟨q, hq⟩ := g₁_dvd D hχ
    have : (D.g.map (cE.comp (O_E).subtype)).eval₂ (of₀ D χ) (AdjoinRoot.root (g₁ D χ)) = 0 := by
      rw [hq, eval₂_mul]
      have h0 : (g₁ D χ).eval₂ (of₀ D χ) (AdjoinRoot.root (g₁ D χ)) = 0 :=
        AdjoinRoot.eval₂_root _
      rw [h0, zero_mul]
    rw [eval₂_map] at this ⊢
    exact this)

lemma ιE_algebraMap (hχ : IsCompat φ χ) (e : E) :
    ιE D hχ (algebraMap E D.F e) = of₀ D χ (cE e) := AdjoinRoot.lift_of _

lemma χ'_ιE (hχ : IsCompat φ χ) (a : D.F) : χ' D χ (ιE D hχ a) = algebraMap C F' (D.φ' a) := by
  have : (χ' D χ).comp (ιE D hχ) = (algebraMap C F').comp D.φ' := by
    refine AdjoinRoot.ringHom_ext (RingHom.ext fun e ↦ ?_) ?_
    · simp only [RingHom.coe_comp, Function.comp_apply]
      change χ' D χ (ιE D hχ (algebraMap E D.F e)) = algebraMap C F' (D.φ' (algebraMap E D.F e))
      rw [ιE_algebraMap, χ'_of₀, UnrData.φ'_algebraMap]
      exact χ_cst hχ e
    · simp only [RingHom.coe_comp, Function.comp_apply]
      change χ' D χ (ιE D hχ D.r) = algebraMap C F' (D.φ' D.r)
      rw [UnrData.φ'_r]
      change χ' D χ (AdjoinRoot.lift _ _ _ (AdjoinRoot.root _)) = _
      rw [AdjoinRoot.lift_root, χ'_root]
  exact congrArg (fun f ↦ f a) this

/-- The image of `x` in `F₀'`. -/
noncomputable abbrev xF₀' : F₀' D χ := of₀ D χ (algebraMap (RatFunc E) F₀ RatFunc.X)

/-- `E'[X] → F₀'`. -/
noncomputable def polyMap (hχ : IsCompat φ χ) : D.F[X] →+* F₀' D χ :=
  eval₂RingHom (ιE D hχ) (xF₀' D (χ := χ))

lemma χ'_polyMap (hχ : IsCompat φ χ) (p : D.F[X]) :
    χ' D χ (polyMap D hχ p) =
      algebraMap (RatFunc C) F' (algebraMap C[X] (RatFunc C) (p.map D.φ')) := by
  have : (χ' D χ).comp (polyMap D hχ) = ((algebraMap (RatFunc C) F').comp
      (algebraMap C[X] (RatFunc C))).comp (mapRingHom D.φ') := by
    refine Polynomial.ringHom_ext (fun a ↦ ?_) ?_
    · simp only [polyMap, RingHom.coe_comp, Function.comp_apply, coe_eval₂RingHom, eval₂_C,
        coe_mapRingHom, Polynomial.map_C, χ'_ιE, RatFunc.algebraMap_C]
      rw [← RatFunc.algebraMap_eq_C, ← IsScalarTower.algebraMap_apply]
    · simp only [polyMap, RingHom.coe_comp, Function.comp_apply, coe_eval₂RingHom, eval₂_X,
        coe_mapRingHom, Polynomial.map_X]
      rw [RatFunc.algebraMap_X, χ'_of₀, hχ, ← RatFunc.algebraMap_X, ratFuncMap_algebraMap,
        Polynomial.map_X, RatFunc.algebraMap_X]
  exact congrArg (fun f ↦ f p) this

lemma polyMap_nonZeroDivisors (hχ : IsCompat φ χ) :
    nonZeroDivisors D.F[X] ≤ (nonZeroDivisors (F₀' D χ)).comap (polyMap D hχ) := by
  intro p hp
  rw [Submonoid.mem_comap, mem_nonZeroDivisors_iff_ne_zero]
  intro h0
  have h1 := χ'_polyMap D hχ p
  rw [h0, map_zero] at h1
  have h2 : algebraMap C[X] (RatFunc C) (p.map D.φ') = 0 :=
    (map_eq_zero_iff _ (algebraMap (RatFunc C) F').injective).1 h1.symm
  rw [map_eq_zero_iff _ (IsFractionRing.injective C[X] (RatFunc C)),
    Polynomial.map_eq_zero_iff D.φ'.injective] at h2
  exact (mem_nonZeroDivisors_iff_ne_zero.1 hp) h2

/-- The `E'(x)`-algebra structure of `F₀'`. -/
@[reducible] noncomputable def algRat (hχ : IsCompat φ χ) : Algebra (RatFunc D.F) (F₀' D χ) :=
  (RatFunc.liftRingHom (polyMap D hχ) (polyMap_nonZeroDivisors D hχ)).toAlgebra

lemma algRat_algebraMap_poly (hχ : IsCompat φ χ) (p : D.F[X]) :
    letI := algRat D hχ
    algebraMap (RatFunc D.F) (F₀' D χ) (algebraMap D.F[X] (RatFunc D.F) p) = polyMap D hχ p :=
  RatFunc.liftRingHom_algebraMap _ _ p

lemma algRat_algebraMap_C (hχ : IsCompat φ χ) (a : D.F) :
    letI := algRat D hχ
    algebraMap (RatFunc D.F) (F₀' D χ) (algebraMap D.F (RatFunc D.F) a) = ιE D hχ a := by
  rw [IsScalarTower.algebraMap_apply D.F D.F[X] (RatFunc D.F), algRat_algebraMap_poly,
    Polynomial.algebraMap_apply, polyMap, coe_eval₂RingHom, eval₂_C]
  rfl

lemma algRat_X (hχ : IsCompat φ χ) :
    letI := algRat D hχ
    algebraMap (RatFunc D.F) (F₀' D χ) RatFunc.X = xF₀' D (χ := χ) := by
  rw [← RatFunc.algebraMap_X, algRat_algebraMap_poly, polyMap, coe_eval₂RingHom, eval₂_X]

/-- `χ'` is compatible with `ratFuncMap φ'`. -/
theorem isCompat (hχ : IsCompat φ χ) :
    letI := algRat D hχ
    IsCompat D.φ' (χ' D χ) := by
  letI := algRat D hχ
  intro f
  have := ratFunc_ringHom_ext (f := (χ' D χ).comp (algebraMap (RatFunc D.F) (F₀' D χ)))
    (g := (algebraMap (RatFunc C) F').comp (ratFuncMap D.φ')) (fun a ↦ by
      simp only [RingHom.coe_comp, Function.comp_apply]
      rw [algRat_algebraMap_C, χ'_ιE, ratFuncMap_algebraMap_C, ← IsScalarTower.algebraMap_apply])
    (by
      simp only [RingHom.coe_comp, Function.comp_apply]
      rw [algRat_X, χ'_of₀, hχ, DVRDescent.ratFuncMap_X, DVRDescent.ratFuncMap_X])
  exact congrArg (fun h ↦ h f) this

/-- `of₀ : F₀ → F₀'` is compatible with `ratFuncMap (E → E')`. -/
theorem isCompat_of₀ (hχ : IsCompat φ χ) :
    letI := algRat D hχ
    IsCompat (algebraMap E D.F) (of₀ D χ) := by
  letI := algRat D hχ
  intro f
  have := ratFunc_ringHom_ext (f := (of₀ D χ).comp (algebraMap (RatFunc E) F₀))
    (g := (algebraMap (RatFunc D.F) (F₀' D χ)).comp (ratFuncMap (algebraMap E D.F))) (fun a ↦ by
      simp only [RingHom.coe_comp, Function.comp_apply]
      rw [ratFuncMap_algebraMap_C, algRat_algebraMap_C, ιE_algebraMap]
      rfl)
    (by
      simp only [RingHom.coe_comp, Function.comp_apply]
      rw [DVRDescent.ratFuncMap_X, algRat_X])
  exact congrArg (fun h ↦ h f) this

section Degree

variable [FiniteDimensional (RatFunc E) F₀] [FiniteDimensional (RatFunc C) F']

/-- The image of the primitive element. -/
noncomputable abbrev θ' (θ₀ : F₀) : F₀' D χ := of₀ D χ θ₀

omit [Fact (Irreducible (g₁ D χ))] in
lemma natDegree_minpoly_θ₀ (hχ : IsCompat φ χ)
    (hdeg : Module.finrank (RatFunc E) F₀ = Module.finrank (RatFunc C) F')
    {θ₀ : F₀} (hθ : Algebra.adjoin (RatFunc C) {χ θ₀} = ⊤) :
    (minpoly (RatFunc E) θ₀).natDegree = Module.finrank (RatFunc C) F' := by
  have hint : IsIntegral (RatFunc C) (χ θ₀) := Algebra.IsIntegral.isIntegral _
  have h := (finiteDimensional_and_finrank_of_adjoin hint hθ).2
  rw [h, minpoly_χ_eq hχ hdeg hθ θ₀, natDegree_map]

omit [Fact (Irreducible (g₁ D χ))] in
lemma adjoin_θ₀ (hχ : IsCompat φ χ)
    (hdeg : Module.finrank (RatFunc E) F₀ = Module.finrank (RatFunc C) F')
    {θ₀ : F₀} (hθ : Algebra.adjoin (RatFunc C) {χ θ₀} = ⊤) :
    Algebra.adjoin (RatFunc E) {θ₀} = ⊤ := by
  have hint : IsIntegral (RatFunc E) θ₀ := Algebra.IsIntegral.isIntegral _
  have hfr := IntermediateField.adjoin.finrank hint
  rw [natDegree_minpoly_θ₀ hχ hdeg hθ, ← hdeg] at hfr
  have htop : IntermediateField.adjoin (RatFunc E) {θ₀} = ⊤ :=
    IntermediateField.eq_of_le_of_finrank_eq le_top (by rw [hfr, IntermediateField.finrank_top'])
  rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hint.isAlgebraic, htop,
    IntermediateField.top_toSubalgebra]

lemma aeval_θ' (hχ : IsCompat φ χ) (θ₀ : F₀) :
    letI := algRat D hχ
    aeval (θ' D (χ := χ) θ₀)
      ((minpoly (RatFunc E) θ₀).map (ratFuncMap (algebraMap E D.F))) = 0 := by
  letI := algRat D hχ
  rw [aeval_map_χ (isCompat_of₀ D hχ), minpoly.aeval, map_zero]

lemma isIntegral_θ' (hχ : IsCompat φ χ) (θ₀ : F₀) :
    letI := algRat D hχ
    IsIntegral (RatFunc D.F) (θ' D (χ := χ) θ₀) := by
  letI := algRat D hχ
  refine ⟨_, (minpoly.monic (Algebra.IsIntegral.isIntegral (R := RatFunc E) θ₀)).map
    (ratFuncMap (algebraMap E D.F)), ?_⟩
  rw [← aeval_def]
  exact aeval_θ' D hχ θ₀

lemma adjoin_θ' (hχ : IsCompat φ χ)
    (hdeg : Module.finrank (RatFunc E) F₀ = Module.finrank (RatFunc C) F')
    {θ₀ : F₀} (hθ : Algebra.adjoin (RatFunc C) {χ θ₀} = ⊤) :
    letI := algRat D hχ
    Algebra.adjoin (RatFunc D.F) {θ' D (χ := χ) θ₀} = ⊤ := by
  letI := algRat D hχ
  set A := Algebra.adjoin (RatFunc D.F) {θ' D (χ := χ) θ₀}
  have hof : ∀ f : F₀, of₀ D χ f ∈ A := by
    intro f
    have hf : f ∈ Algebra.adjoin (RatFunc E) {θ₀} := (adjoin_θ₀ hχ hdeg hθ) ▸ Algebra.mem_top
    rw [Algebra.adjoin_singleton_eq_range_aeval] at hf
    obtain ⟨q, rfl⟩ := hf
    change of₀ D χ (aeval θ₀ q) ∈ A
    rw [← aeval_map_χ (isCompat_of₀ D hχ)]
    have : A = (aeval (θ' D (χ := χ) θ₀)).range := Algebra.adjoin_singleton_eq_range_aeval _ _
    rw [this]
    exact ⟨_, rfl⟩
  have hroot : AdjoinRoot.root (g₁ D χ) ∈ A := by
    have : AdjoinRoot.root (g₁ D χ) = algebraMap (RatFunc D.F) (F₀' D χ)
        (algebraMap D.F (RatFunc D.F) D.r) := by
      rw [algRat_algebraMap_C]
      exact (AdjoinRoot.lift_root _).symm
    rw [this]
    exact A.algebraMap_mem _
  rw [eq_top_iff]
  intro z _
  obtain ⟨p, rfl⟩ := AdjoinRoot.mk_surjective z
  induction p using Polynomial.induction_on with
  | C a => rw [AdjoinRoot.mk_C]; exact hof a
  | add p q hp hq => rw [map_add]; exact A.add_mem (hp trivial) (hq trivial)
  | monomial n a _ =>
    rw [map_mul, map_pow, AdjoinRoot.mk_C, AdjoinRoot.mk_X]
    exact A.mul_mem (hof a) (A.pow_mem hroot _)

/-- `F₀'` is finite over `E'(x)` of degree `[F' : C(x)]`. -/
theorem finiteDimensional_and_finrank (hχ : IsCompat φ χ)
    (hdeg : Module.finrank (RatFunc E) F₀ = Module.finrank (RatFunc C) F')
    {θ₀ : F₀} (hθ : Algebra.adjoin (RatFunc C) {χ θ₀} = ⊤) :
    letI := algRat D hχ
    FiniteDimensional (RatFunc D.F) (F₀' D χ) ∧
      Module.finrank (RatFunc D.F) (F₀' D χ) = Module.finrank (RatFunc C) F' := by
  letI := algRat D hχ
  obtain ⟨hfin, hfr⟩ := finiteDimensional_and_finrank_of_adjoin (isIntegral_θ' D hχ θ₀)
    (adjoin_θ' D hχ hdeg hθ)
  refine ⟨hfin, le_antisymm ?_ ?_⟩
  · rw [hfr, ← natDegree_minpoly_θ₀ hχ hdeg hθ]
    refine (natDegree_le_of_dvd (minpoly.dvd _ _ (aeval_θ' D hχ θ₀)) ?_).trans
      (natDegree_map_le)
    exact ((minpoly.monic (Algebra.IsIntegral.isIntegral θ₀)).map _).ne_zero
  · have hint : IsIntegral (RatFunc C) (χ θ₀) := Algebra.IsIntegral.isIntegral _
    rw [(finiteDimensional_and_finrank_of_adjoin hint hθ).2, hfr]
    have hχθ : χ θ₀ = χ' D χ (θ' D (χ := χ) θ₀) := (χ'_of₀ D χ θ₀).symm
    rw [hχθ]
    refine (natDegree_le_of_dvd (q := (minpoly (RatFunc D.F) (θ' D (χ := χ) θ₀)).map
      (ratFuncMap D.φ')) (minpoly.dvd _ _ ?_) ?_).trans natDegree_map_le
    · rw [aeval_map_χ (isCompat D hχ), minpoly.aeval, map_zero]
    · exact ((minpoly.monic (isIntegral_θ' D hχ θ₀)).map _).ne_zero

end Degree

section Chart

variable [FiniteDimensional (RatFunc E) F₀]

/-- The vertex chart over `O_{E'}`: the integral closure of `O_{E'}[x]` in `F₀'`. -/
noncomputable abbrev BD' (hχ : IsCompat φ χ) : Type w :=
  letI := algRat D hχ; BD D.F (F₀' D χ)

/-- The map of vertex charts `BD E F₀ → BD E' F₀'`. -/
noncomputable def j (hχ : IsCompat φ χ) : BD E F₀ →+* BD' D hχ :=
  letI := algRat D hχ
  ιD (of₀ D χ) D.norm_algebraMap (isCompat_of₀ D hχ)

lemma coe_j (hχ : IsCompat φ χ) (z : BD E F₀) :
    ((j D hχ z : BD' D hχ) : F₀' D χ) = of₀ D χ z := rfl

/-- The root as an element of `BD E' F₀'`. -/
noncomputable def rr (hχ : IsCompat φ χ) : BD' D hχ :=
  letI := algRat D hχ
  cstD (E := D.F) (F₀ := F₀' D χ) D.rI

lemma coe_rr (hχ : IsCompat φ χ) :
    ((rr D hχ : BD' D hχ) : F₀' D χ) = AdjoinRoot.root (g₁ D χ) := by
  letI := algRat D hχ
  change algebraMap (RatFunc D.F) (F₀' D χ) (algebraMap D.F (RatFunc D.F) D.r) = _
  rw [algRat_algebraMap_C]
  exact AdjoinRoot.lift_root _

end Chart


section Etale

variable [FiniteDimensional (RatFunc E) F₀] [Algebra.IsSeparable (RatFunc E) F₀]

set_option maxHeartbeats 1000000 in
-- the proof juggles several algebra structures on the charts
/-- **The map of vertex charts `BD E F₀ → BD E' F₀'` is étale**: `BD E' F₀'` is
`BD[X] ⧸ (g₁)` (`g₁` has coefficients in `BD` and `g₁' p₁ + g₁ p₂` is a unit at the root), and
this étale `BD`-algebra is integrally closed in `F₀'`. -/
theorem etale_j_and_adjoin (hχ : IsCompat φ χ) : (j D hχ).Etale ∧
    letI := algRat D hχ
    letI : Algebra (BD E F₀) (BD' D hχ) := (j D hχ).toAlgebra
    ∀ z : BD' D hχ, z ∈ Algebra.adjoin (BD E F₀) {rr D hχ} := by
  letI := algRat D hχ
  letI := bdAlgebra (E := E) (F₀ := F₀)
  letI := bdAlgebra (E := D.F) (F₀ := F₀' D χ)
  set R := BD E F₀
  set S' := BD' D hχ
  letI : Algebra R S' := (j D hχ).toAlgebra
  haveI := isFractionRing_discRing (a := (0 : E)) (c := (1 : E)) one_ne_zero
  haveI : IsIntegrallyClosed R := integralClosure.isIntegrallyClosedOfFiniteExtension (RatFunc E)
  haveI : IsFractionRing R F₀ :=
    integralClosure.isFractionRing_of_finite_extension (RatFunc E) F₀
  haveI : IsScalarTower R F₀ (F₀' D χ) := inferInstance
  set root := AdjoinRoot.root (g₁ D χ)
  have hRF : ∀ r : R, algebraMap R (F₀' D χ) r = of₀ D χ (r : F₀) := fun r ↦ rfl
  haveI : Module.IsTorsionFree R (F₀' D χ) := Module.isTorsionFree_iff_algebraMap_injective.2 (by
    intro a b hab
    rw [hRF, hRF] at hab
    exact Subtype.ext ((of₀ D χ).injective hab))
  -- constants of `O_E` in `R`
  let cR : O_E →+* R := (algebraMap (discRing (0 : E) 1) R).comp intDisc
  have hcR : ∀ e : O_E, ((cR e : R) : F₀) = cE (e : E) := fun e ↦ rfl
  set gR : R[X] := D.g.map cR
  have haeval : ∀ q : O_E[X], aeval root (q.map cR) =
      (q.map (cE.comp (O_E).subtype)).eval₂ (of₀ D χ) root := by
    intro q
    rw [aeval_def, eval₂_map, eval₂_map]
    congr 1
  have hgR : aeval root gR = 0 := by rw [haeval]; exact eval₂_root_gF D hχ
  have hint : IsIntegral R root := ⟨gR, D.monic.map _, hgR⟩
  set f := minpoly R root
  have hfm : f.Monic := minpoly.monic hint
  have hg₁ : f.map (algebraMap R F₀) = g₁ D χ := by
    rw [← minpoly.isIntegrallyClosed_eq_field_fractions' F₀ hint,
      AdjoinRoot.minpoly_root (monic_g₁ D hχ).ne_zero, (monic_g₁ D hχ).leadingCoeff, inv_one,
      map_one, mul_one]
  obtain ⟨f₂, hf₂⟩ := minpoly.isIntegrallyClosed_dvd hint hgR
  set p₁' : R[X] := D.p₁.map cR * f₂
  set p₂' : R[X] := D.p₁.map cR * derivative f₂ + D.p₂.map cR * f₂
  have hcomb : derivative f * p₁' + f * p₂' =
      (derivative D.g * D.p₁ + D.g * D.p₂).map cR := by
    have hd : derivative gR = derivative f * f₂ + f * derivative f₂ := by
      rw [hf₂, derivative_mul]
    rw [Polynomial.map_add, Polynomial.map_mul, Polynomial.map_mul, ← derivative_map]
    change _ = derivative gR * _ + gR * _
    rw [hd, hf₂]
    ring
  -- evaluation at the root of `BD'`
  have hcoe : ∀ q : R[X], ((aeval (rr D hχ) q : S') : F₀' D χ) = aeval root q := by
    intro q
    rw [aeval_def, ← (BD D.F (F₀' D χ)).val_apply, ← AlgHom.coe_toRingHom, hom_eval₂,
      aeval_def]
    refine congrArg₂ (fun g x ↦ eval₂ g x q) (RingHom.ext fun r ↦ (hRF r).symm) (coe_rr D hχ)
  have hconst : ∀ q : O_E[X], algebraMap (HenselComplete.integers D.F) S' (aeval D.rI q) =
      aeval (rr D hχ) (q.map cR) := by
    intro q
    apply Subtype.ext
    rw [hcoe, haeval]
    change algebraMap (RatFunc D.F) (F₀' D χ) (algebraMap D.F (RatFunc D.F)
      ((aeval D.rI q : HenselComplete.integers D.F) : D.F)) = _
    rw [algRat_algebraMap_C, UnrData.coe_aeval_rI, aeval_def, hom_eval₂, eval₂_map, eval₂_map]
    congr 1
    · ext e
      simp only [RingHom.coe_comp, Function.comp_apply]
      exact ιE_algebraMap D hχ e
    · exact AdjoinRoot.lift_root _
  have hx : aeval (rr D hχ) f = 0 := Subtype.ext (by rw [hcoe]; exact minpoly.aeval R root)
  have hunit : IsUnit (aeval (rr D hχ) (derivative f * p₁' + f * p₂')) := by
    rw [hcomb, ← hconst]
    exact D.isUnit_aeval_rI.map _
  have hinj : ∀ q : R[X], q.degree < f.degree → aeval (rr D hχ) q = 0 → q = 0 := by
    intro q hq h0
    have h1 : aeval root (q.map (algebraMap R F₀)) = 0 := by
      rw [aeval_map_algebraMap, ← hcoe, h0]; rfl
    have hdvd : g₁ D χ ∣ q.map (algebraMap R F₀) := by
      rw [← hg₁, ← minpoly.isIntegrallyClosed_eq_field_fractions' F₀ hint]
      exact minpoly.dvd F₀ root h1
    have hq0 : q.map (algebraMap R F₀) = 0 := by
      refine eq_zero_of_dvd_of_degree_lt hdvd ?_
      rw [← hg₁, degree_map_eq_of_injective (IsFractionRing.injective R F₀),
        degree_map_eq_of_injective (IsFractionRing.injective R F₀)]
      exact hq
    exact Polynomial.map_injective _ (IsFractionRing.injective R F₀)
      (hq0.trans (Polynomial.map_zero _).symm)
  -- the étale subalgebra `T = R[root]`
  set T := Algebra.adjoin R {rr D hχ}
  letI : Algebra R T := Subalgebra.algebra T
  have hrrT : rr D hχ ∈ T := Algebra.self_mem_adjoin_singleton R _
  have haevalT : ∀ q : R[X], aeval (rr D hχ) q ∈ T := by
    intro q
    have : T = (aeval (rr D hχ)).range := Algebra.adjoin_singleton_eq_range_aeval R _
    rw [this]
    exact ⟨q, rfl⟩
  have hTcoe : ∀ q : R[X], ((aeval (⟨rr D hχ, hrrT⟩ : T) q : T) : S') = aeval (rr D hχ) q :=
    fun q ↦ (Polynomial.aeval_algHom_apply T.val _ q).symm
  haveI hTet : Algebra.Etale R T := by
    refine etale_of_aeval_eq_zero hfm p₁' p₂' (x := (⟨rr D hχ, hrrT⟩ : T))
      (Subtype.ext (by rw [hTcoe, hx]; rfl)) ?_ ?_ ?_
    · -- the unit has its inverse in `T`
      obtain ⟨u, hu⟩ := D.isUnit_aeval_rI
      obtain ⟨q', -, hq'⟩ := D.exists_aeval_rI (↑u⁻¹ : HenselComplete.integers D.F)
      refine IsUnit.of_mul_eq_one (b := aeval (⟨rr D hχ, hrrT⟩ : T) (q'.map cR)) (Subtype.ext ?_)
      rw [Subalgebra.coe_mul, hTcoe, hTcoe, hcomb, ← hconst, ← hconst, ← map_mul, ← hq', ← hu,
        Units.mul_inv, map_one]
      rfl
    · have h := Algebra.adjoin_adjoin_coe_preimage (R := R) (s := ({rr D hχ} : Set S'))
      have hs : ((↑) ⁻¹' ({rr D hχ} : Set S') : Set T) = {⟨rr D hχ, hrrT⟩} := by
        ext ⟨y, hy⟩
        simp
      rw [hs] at h
      exact h
    · intro q hq h0
      exact hinj q hq (by rw [← hTcoe, h0]; rfl)
  -- `T` is all of `BD'`
  haveI : IsDomain T := inferInstance
  letI : Algebra T (F₀' D χ) := ((BD D.F (F₀' D χ)).val.toRingHom.comp T.val.toRingHom).toAlgebra
  have hTinj : Function.Injective (algebraMap T (F₀' D χ)) := fun a b hab ↦
    Subtype.ext (Subtype.ext hab)
  have hdisc : ∀ a : discRing (0 : D.F) 1,
      algebraMap (discRing (0 : D.F) 1) S' a ∈ T := by
    rintro ⟨a, ha⟩
    obtain ⟨Q, hQ, rfl⟩ := mem_discRing_iff.1 ha
    have hc : ∀ i, Q.coeff i ∈ HenselComplete.integers D.F := fun i ↦
      coeff_le_one_of_sup_le_one hQ i
    have hcT : ∀ c : HenselComplete.integers D.F,
        algebraMap (HenselComplete.integers D.F) S' c ∈ T := by
      intro c
      obtain ⟨q, -, rfl⟩ := D.exists_aeval_rI c
      rw [hconst]
      exact haevalT _
    have hxT : algebraMap R S' xD ∈ T := T.algebraMap_mem _
    set w : S' := ∑ i ∈ Finset.range (Q.natDegree + 1),
      algebraMap (HenselComplete.integers D.F) S' ⟨Q.coeff i, hc i⟩ * (algebraMap R S' xD) ^ i
    have hw : w ∈ T := T.sum_mem fun i _ ↦ T.mul_mem (hcT _) (T.pow_mem hxT _)
    convert hw using 1
    apply Subtype.ext
    change algebraMap (RatFunc D.F) (F₀' D χ) (algebraMap D.F[X] (RatFunc D.F) Q) = _
    rw [algRat_algebraMap_poly, polyMap, coe_eval₂RingHom, eval₂_eq_sum_range,
      ← (BD D.F (F₀' D χ)).val_apply, map_sum]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [map_mul, map_pow]
    congr 1
    change _ = algebraMap (RatFunc D.F) (F₀' D χ) (algebraMap D.F (RatFunc D.F) (Q.coeff i))
    rw [algRat_algebraMap_C]
  have hTall : ∀ z : S', z ∈ T := by
    intro z
    let ψT : discRing (0 : D.F) 1 →+* T :=
      (algebraMap (discRing (0 : D.F) 1) S').codRestrict T.toSubsemiring hdisc
    have hz2 : IsIntegral (discRing (0 : D.F) 1) (z : F₀' D χ) := z.2
    have hzT : IsIntegral T (z : F₀' D χ) :=
      IsIntegral.map_of_comp_eq (R := discRing (0 : D.F) 1) (S := F₀' D χ) (T := T)
        (U := F₀' D χ) ψT (RingHom.id _) (RingHom.ext fun _ ↦ rfl) hz2
    obtain ⟨P, hP⟩ := AdjoinRoot.mk_surjective (z : F₀' D χ)
    obtain ⟨b, hb, hbP⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors R) P
    set N := IsLocalization.integerNormalization (nonZeroDivisors R) P
    have hbT : algebraMap R T b ≠ 0 := by
      intro h
      have : (b : F₀) = 0 := by
        have := congrArg (fun t : T ↦ ((t : S') : F₀' D χ)) h
        simp only [ZeroMemClass.coe_zero] at this
        exact (of₀ D χ).injective (by rw [map_zero]; exact this)
      exact nonZeroDivisors.coe_ne_zero ⟨b, hb⟩ (Subtype.ext this)
    obtain ⟨t, ht⟩ := mem_of_etale_of_isIntegral (R := R) hTinj hbT
      (a := aeval (⟨rr D hχ, hrrT⟩ : T) N) (by
        change ((aeval (⟨rr D hχ, hrrT⟩ : T) N : T) : S').val = _
        rw [hTcoe, hcoe, ← aeval_map_algebraMap F₀, hbP, Algebra.smul_def,
          Polynomial.algebraMap_apply, map_mul, aeval_C, AdjoinRoot.aeval_eq, hP]
        rfl) hzT
    have : (t : S') = z := Subtype.ext ht
    rw [← this]
    exact t.2
  have htop : T = ⊤ := eq_top_iff.2 fun z _ ↦ hTall z
  let e : T ≃ₐ[R] S' := (Subalgebra.equivOfEq T ⊤ htop).trans Subalgebra.topEquiv
  have hTR := (RingHom.etale_algebraMap (R := R) (S := T)).mpr hTet
  have hj : j D hχ = e.toRingHom.comp (algebraMap R T) := RingHom.ext fun r ↦ rfl
  refine ⟨?_, hTall⟩
  rw [hj]
  exact RingHom.Etale.stableUnderComposition _ _ hTR (RingHom.Etale.of_bijective e.bijective)

/-- **The map of vertex charts `BD E F₀ → BD E' F₀'` is étale.** -/
theorem etale_j (hχ : IsCompat φ χ) : (j D hχ).Etale := (etale_j_and_adjoin D hχ).1

/-- `BD E' F₀' = BD[root]`. -/
theorem mem_adjoin_rr (hχ : IsCompat φ χ) :
    letI := algRat D hχ
    letI : Algebra (BD E F₀) (BD' D hχ) := (j D hχ).toAlgebra
    ∀ z : BD' D hχ, z ∈ Algebra.adjoin (BD E F₀) {rr D hχ} := (etale_j_and_adjoin D hχ).2


end Etale

end UnrChart

end Unramified

end SemistableReduction
