/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.FundamentalInequality

/-!
# Roots with irreducible reduction, and Kummer extensions of degree prime to `p`

Blueprint §9.4, C2/D2. Let `u` be a valuation on `M`, extended by a valuation `w` on a finite
extension `N`.

* `natDegree_le_inertiaDeg`: if `y` in the valuation ring of `w` is a root of a monic `f` over the
  valuation ring of `u` whose reduction is irreducible, then `deg f ≤ f(w | u)`.
* `unramified_of_root`: if moreover `[N : M] ≤ deg f` (e.g. `N = M(y)`), then `e(w | u) = 1` and
  `f(w | u) = [N : M]`: the extension is defectless, unramified, generated by a lift of a
  residue generator.
* `kummer_unramified` (the Kummer step of D2): if the valuation ring of `u` is Henselian, `ℓ` is
  a prime invertible in the residue field, `a ∈ M` is a unit that is not an `ℓ`-th power, and
  `θ ∈ N` with `θ ^ ℓ = a` and `[N : M] ≤ ℓ`, then `N / M` is unramified of degree `ℓ` with
  residue field generated by `θ̄` (whose minimal polynomial is `X ^ ℓ - ā`).
-/

open IsLocalRing Valuation Polynomial

namespace SemistableReduction

namespace FundamentalInequality

variable {M N : Type*} [Field M] [Field N] [Algebra M N]
  {Γ₀ Γ₁ : Type*} [LinearOrderedCommGroupWithZero Γ₀] [LinearOrderedCommGroupWithZero Γ₁]
  {u : Valuation M Γ₀} {w : Valuation N Γ₁} [u.HasExtension w]

local notation "O_u" => u.valuationSubring
local notation "O_w" => w.valuationSubring

/-- Reduction commutes with evaluation. -/
lemma residue_aeval (f : O_u[X]) (y : O_w) :
    residue O_w (aeval y f) = aeval (residue O_w y) (f.map (residue O_u)) := by
  rw [aeval_def, aeval_def, eval₂_map, hom_eval₂]
  rfl

/-- If `y` is a root of a monic polynomial over the valuation ring whose reduction is irreducible,
then the residue `ȳ` has this reduction as minimal polynomial. -/
lemma minpoly_residue_eq {f : O_u[X]} (hf : f.Monic) (hirr : Irreducible (f.map (residue O_u)))
    {y : O_w} (hy : aeval y f = 0) :
    minpoly (ResidueField O_u) (residue O_w y) = f.map (residue O_u) := by
  refine (minpoly.eq_of_irreducible_of_monic hirr ?_ (hf.map _)).symm
  rw [← residue_aeval, hy, map_zero]

/-- A root `y` of a monic `f` with irreducible reduction gives `deg f ≤ f(w | u)`. -/
theorem natDegree_le_inertiaDeg [FiniteDimensional M N] {f : O_u[X]} (hf : f.Monic)
    (hirr : Irreducible (f.map (residue O_u))) {y : O_w} (hy : aeval y f = 0) :
    f.natDegree ≤ inertiaDeg u w := by
  have : Module.Finite (ResidueField O_u) (ResidueField O_w) := finite_residueField
  have hint : IsIntegral (ResidueField O_u) (residue O_w y) := Algebra.IsIntegral.isIntegral _
  rw [← hf.natDegree_map (residue O_u), ← minpoly_residue_eq hf hirr hy,
    ← IntermediateField.adjoin.finrank hint, inertiaDeg]
  exact IntermediateField.finrank_le_of_le_right le_top |>.trans_eq
    IntermediateField.finrank_top'

/-- **Unramified extensions generated by a root.** If `y` is a root of a monic `f` with
irreducible reduction and `[N : M] ≤ deg f`, then `e(w | u) = 1` and `f(w | u) = [N : M]`. -/
theorem unramified_of_root [FiniteDimensional M N] {f : O_u[X]} (hf : f.Monic)
    (hirr : Irreducible (f.map (residue O_u))) {y : O_w} (hy : aeval y f = 0)
    (hdeg : Module.finrank M N ≤ f.natDegree) :
    ramificationIdx M w = 1 ∧ inertiaDeg u w = Module.finrank M N := by
  have h₁ := natDegree_le_inertiaDeg hf hirr hy
  have h₂ : ramificationIdx M w * inertiaDeg u w ≤ Module.finrank M N :=
    ramificationIdx_mul_inertiaDeg_le
  have he := Nat.pos_of_ne_zero (ramificationIdx_ne_zero (K := M) w)
  have hn : 0 < Module.finrank M N := Module.finrank_pos
  have hfn : inertiaDeg u w ≤ Module.finrank M N :=
    le_trans (Nat.le_mul_of_pos_left _ he) h₂
  have hf' : inertiaDeg u w = Module.finrank M N := le_antisymm hfn (hdeg.trans h₁)
  refine ⟨?_, hf'⟩
  rw [hf'] at h₂
  exact le_antisymm ((Nat.le_div_iff_mul_le hn).2 h₂ |>.trans (Nat.div_self hn).le) he

/-- **Kummer extensions of degree prime to the residue characteristic are unramified.** Let the
valuation ring of `u` be Henselian, `ℓ` a prime invertible in the valuation ring, `a ∈ M` with
`u a = 1` not an `ℓ`-th power in `M`, and `θ ∈ N` with `θ ^ ℓ = a`, `[N : M] ≤ ℓ`. Then
`e(w | u) = 1` and `f(w | u) = [N : M] = ℓ`. -/
theorem kummer_unramified [HenselianLocalRing O_u] [FiniteDimensional M N] {ℓ : ℕ}
    (hℓ : ℓ.Prime) (hℓunit : IsUnit (ℓ : O_u)) {a : M}
    (ha : u a = 1) (hpow : ∀ b : M, b ^ ℓ ≠ a) {θ : N} (hθ : θ ^ ℓ = algebraMap M N a)
    (hdeg : Module.finrank M N ≤ ℓ) :
    ramificationIdx M w = 1 ∧ inertiaDeg u w = Module.finrank M N ∧ Module.finrank M N = ℓ := by
  have hℓ0 : ℓ ≠ 0 := hℓ.ne_zero
  -- `θ` is a unit of the valuation ring
  have hwθ : w θ = 1 := by
    have h1 : w θ ^ ℓ = 1 := by
      rw [← map_pow, hθ]
      exact (HasExtension.val_map_eq_one_iff u w a).2 ha
    exact (pow_left_inj hℓ0).1 (by rw [h1, one_pow])
  let a' : O_u := ⟨a, (le_of_eq ha : u a ≤ 1)⟩
  let θ' : O_w := ⟨θ, (le_of_eq hwθ : w θ ≤ 1)⟩
  set f : O_u[X] := X ^ ℓ - C a' with hf
  have hfm : f.Monic := monic_X_pow_sub_C _ hℓ0
  have hfdeg : f.natDegree = ℓ := natDegree_X_pow_sub_C
  have hroot : aeval θ' f = 0 := by
    apply Subtype.val_injective
    have : ((aeval θ' f : O_w) : N) = θ ^ ℓ - algebraMap M N a := by
      simp [hf, θ', a', HasExtension.coe_algebraMap_valuationSubring_eq]
    rw [this, hθ, sub_self, ZeroMemClass.coe_zero]
  -- the reduction `X ^ ℓ - ā` is irreducible: an `ℓ`-th root of `ā` would lift by Hensel
  have hirr : Irreducible (f.map (residue O_u)) := by
    rw [hf, Polynomial.map_sub, Polynomial.map_pow, map_X, map_C]
    refine X_pow_sub_C_irreducible_of_prime hℓ fun b hb ↦ ?_
    obtain ⟨b₀, rfl⟩ := IsLocalRing.residue_surjective b
    have ha' : IsUnit a' := by
      rw [(Valuation.valuationSubring.integers u).isUnit_iff_valuation_eq_one]
      exact ha
    have hb₀ : IsUnit b₀ := by
      rw [← residue_ne_zero_iff_isUnit]
      intro h0
      rw [h0, zero_pow hℓ0, eq_comm, residue_eq_zero_iff] at hb
      exact (mem_maximalIdeal _ |>.1 hb) ha'
    obtain ⟨b, hbroot, -⟩ := HenselianLocalRing.is_henselian f hfm b₀
      (by
        rw [← residue_eq_zero_iff]
        simp [hf, ← hb])
      (by
        simp only [hf, derivative_sub, derivative_X_pow, derivative_C, sub_zero, eval_mul,
          eval_C, eval_pow, eval_X]
        simpa using hℓunit.mul (hb₀.pow (ℓ - 1)))
    apply hpow b
    have := hbroot
    simp only [hf, IsRoot, eval_sub, eval_pow, eval_X, eval_C, sub_eq_zero] at this
    exact congrArg Subtype.val this
  obtain ⟨he, hf'⟩ := unramified_of_root hfm hirr hroot (hfdeg ▸ hdeg)
  refine ⟨he, hf', le_antisymm hdeg ?_⟩
  rw [← hfdeg]
  exact (natDegree_le_inertiaDeg hfm hirr hroot).trans hf'.le

end FundamentalInequality

end SemistableReduction
