/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.SemistableReduction.WModel

/-!
# Charts of W-models have fraction field `L` (W8′, XL1, H6 glue)

Blueprint §9.7 (XL1, `NodeGerm.frac`). The charts `R[g j / g i]` of the projective model of a
W-model of `L` generate `L` as a field (`subfield_closure_projChart_eq_top`): the generic point
`localAt (projChart i) ⊤` is a point of the projective model, hence of the normalization of a
Gauss-tree model, so it contains a chart of the normalization, whose fraction field is `L`
(`L` is algebraic over `K'(x)`, and the Gauss charts have fraction field `K'(x)`,
`subfield_closure_gaussChart_eq_top`).
-/

universe u

open Polynomial

namespace TemperedFundamentalGroups.SemistableReduction

open _root_.SemistableReduction

section Gauss

variable {K : Type*} [Field K] {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
  {v : Valuation K Γ₀}

/-- **Gauss charts have fraction field `K(X)`.** -/
theorem subfield_closure_gaussChart_eq_top {ι : Type*} [Fintype ι] [Nonempty ι] {a b : ι → K}
    (hb : ∀ i, b i ≠ 0) {A : Subring (RatFunc K)} (hA : A ∈ (gaussJoinModel v a b).charts) :
    Subfield.closure (A : Set (RatFunc K)) = ⊤ := by
  classical
  obtain ⟨f, hf, rfl⟩ := ZariskiModel.mem_iJoin_charts.mp hA
  obtain ⟨i₀⟩ := ‹Nonempty ι›
  set y := gaussCoord (a i₀) (b i₀)
  set S := Subfield.closure ((baseRing (RatFunc K) v.valuationSubring ⊔ ⨆ i, f i :
    Subring (RatFunc K)) : Set (RatFunc K))
  have hle : ∀ z ∈ f i₀, z ∈ S := fun z hz ↦ Subfield.subset_closure
    (le_sup_of_le_right (le_iSup f i₀) hz)
  have hy : y ∈ S := by
    have := hf i₀
    simp only [ZariskiModel.line, Finset.mem_insert, Finset.mem_singleton] at this
    rcases this with h | h
    · exact hle y (h ▸ self_mem_polyChart y)
    · have : y⁻¹ ∈ S := hle y⁻¹ (h ▸ self_mem_polyChart y⁻¹)
      simpa using S.inv_mem this
  have hK : ∀ k : K, algebraMap K (RatFunc K) k ∈ S := by
    intro k
    have hbase : ∀ k ∈ v.valuationSubring, algebraMap K (RatFunc K) k ∈ S := fun k hk ↦
      Subfield.subset_closure ((le_sup_left : baseRing (RatFunc K) v.valuationSubring ≤ _)
        ⟨k, hk, rfl⟩)
    rcases v.valuationSubring.mem_or_inv_mem k with h | h
    · exact hbase k h
    · have := S.inv_mem (hbase k⁻¹ h)
      simpa using this
  let T : IntermediateField K (RatFunc K) := S.toIntermediateField hK
  have hr : v (b i₀) ≠ 0 := (v.ne_zero_iff).mpr (hb i₀)
  have hG := isGaussCoord_gaussCoord (v := v) (a := a i₀) (r := Units.mk0 _ hr) rfl
  have : IntermediateField.adjoin K {y} ≤ T := by
    rw [IntermediateField.adjoin_simple_le_iff]; exact hy
  rw [hG.adjoin_eq_top, top_le_iff] at this
  rw [eq_top_iff]
  intro z _
  have hz : z ∈ T := by rw [this]; trivial
  exact hz

end Gauss

section Proj

variable {K' : Type u} [Field K'] {O' : ValuationSubring K'} {L : Type u} [Field L]
  [Algebra K' L]

/-- **Charts of W-models generate the function field.** -/
theorem subfield_closure_projChart_eq_top {x : L} (hx : Transcendental K' x) {ι : Type}
    [Fintype ι] [Nonempty ι] {a b : ι → K'} (hb : ∀ i, b i ≠ 0) {n : ℕ} {g : Fin (n + 1) → L}
    (halg : letI := xLineAlgebra L hx; Algebra.IsAlgebraic (RatFunc K') L)
    (hpts : letI := xLineAlgebra L hx
      haveI : IsScalarTower K' (RatFunc K') L := IsScalarTower.of_algebraMap_eq fun k ↦ by
        change algebraMap K' L k = RatFunc.liftAlgHom _ _ (algebraMap K' (RatFunc K') k)
        rw [AlgHom.commutes]
      (ZariskiModel.projModel (baseRing L O'.valuation.valuationSubring) g).points =
        ((gaussJoinModel O'.valuation a b).normalization L).points)
    (i : Fin (n + 1)) :
    Subfield.closure (projChart (baseRing L O'.valuation.valuationSubring) g i : Set L) = ⊤ := by
  classical
  letI := xLineAlgebra L hx
  haveI : IsScalarTower K' (RatFunc K') L := IsScalarTower.of_algebraMap_eq fun k ↦ by
    change algebraMap K' L k = RatFunc.liftAlgHom _ _ (algebraMap K' (RatFunc K') k)
    rw [AlgHom.commutes]
  set R := baseRing L O'.valuation.valuationSubring
  set Fr := localAt (projChart R g i) ⊤
  have hFr : Fr ∈ (ZariskiModel.projModel R g).points :=
    ⟨projChart R g i, ZariskiModel.mem_projModel_charts.mpr ⟨i, rfl⟩, ⊤, le_top, rfl⟩
  rw [hpts] at hFr
  obtain ⟨C, hC, W', hCW', hloc⟩ := hFr
  obtain ⟨A, hA, rfl⟩ := ZariskiModel.mem_normalization_charts.mp hC
  -- `Fr` lies in the field generated by the chart
  have hFr_le : (Fr : Set L) ⊆ Subfield.closure (projChart R g i : Set L) := by
    rintro z ⟨s, hs, hsW, hzs⟩
    have hs0 : s ≠ 0 := by rintro rfl; simp at hsW
    have : z = (z * s) / s := by rw [mul_div_cancel_right₀ _ hs0]
    rw [this]
    exact Subfield.div_mem _ (Subfield.subset_closure hzs) (Subfield.subset_closure hs)
  have hC_le : (normChart L A : Set L) ⊆ Subfield.closure (projChart R g i : Set L) := by
    intro z hz
    apply hFr_le
    rw [← hloc]
    exact le_localAt hz
  -- the normalization chart generates `L`
  rw [eq_top_iff]
  intro f _
  -- `A` has fraction field `K'(x)`
  haveI : IsFractionRing A (RatFunc K') := by
    refine IsFractionRing.of_field _ _ fun z ↦ ?_
    have hz : z ∈ Subfield.closure (A : Set (RatFunc K')) := by
      rw [subfield_closure_gaussChart_eq_top hb hA]; trivial
    obtain ⟨p, hp, q, hq, rfl⟩ := Subfield.mem_closure_iff.mp hz
    rw [Subring.closure_eq] at hp hq
    exact ⟨⟨p, hp⟩, ⟨q, hq⟩, rfl⟩
  let φ := algebraMap (RatFunc K') L
  letI : Algebra A L := (φ.comp A.subtype).toAlgebra
  haveI : IsScalarTower A (RatFunc K') L := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
  have hfA : IsAlgebraic A f := (IsFractionRing.isAlgebraic_iff A (RatFunc K') L).mpr
    (halg.isAlgebraic f)
  obtain ⟨d, hd0, hdi⟩ := hfA.exists_integral_multiple
  -- integrality over `A.map φ`
  let ψ : A →+* A.map φ := (φ.comp A.subtype).codRestrict (A.map φ) fun z ↦ ⟨z, z.2, rfl⟩
  letI : Algebra A (A.map φ) := ψ.toAlgebra
  haveI : IsScalarTower A (A.map φ) L := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
  have hint : IsIntegral (A.map φ) (d • f) := hdi.tower_top
  have hmem : d • f ∈ normChart L A := hint
  have hdmem : φ d ∈ normChart L A := map_le_normChart A ⟨d, d.2, rfl⟩
  have hd0' : φ d ≠ 0 := by
    rw [map_ne_zero_iff _ φ.injective]
    exact fun h ↦ hd0 (Subtype.ext h)
  have : f = (d • f) / φ d := by
    rw [Algebra.smul_def]
    change f = (φ d * f) / φ d
    rw [mul_div_cancel_left₀ _ hd0']
  rw [this]
  exact Subfield.div_mem _ (hC_le hmem) (hC_le hdmem)

end Proj

section FiniteType

variable {K' : Type u} [Field K'] {O' : ValuationSubring K'} {L : Type u} [Field L]
  [Algebra O' L]

/-- **Charts of projective models are of finite type.** -/
theorem finiteType_projChart {R : Subring L} (hR : (algebraMap O' L).range = R) {n : ℕ}
    (g : Fin (n + 1) → L) (i : Fin (n + 1)) :
    letI := ProjScheme.projChartAlgebra (O := O') (f := g) R hR i
    Algebra.FiniteType O' (projChart R g i) := by
  letI := ProjScheme.projChartAlgebra (O := O') (f := g) R hR i
  classical
  let gens : Finset (projChart R g i) :=
    Finset.univ.image fun j ↦ ⟨g j / g i, div_mem_projChart i j⟩
  refine ⟨⟨gens, ?_⟩⟩
  rw [eq_top_iff]
  rintro ⟨z, hz⟩ -
  -- the subalgebra generated by the generators, viewed in `L`
  let S : Subring L := (Algebra.adjoin O' (gens : Set (projChart R g i))).toSubring.map
    (projChart R g i).subtype
  have hle : projChart R g i ≤ S := by
    refine projChart_le ?_ fun j ↦ ?_
    · intro w hw
      rw [← hR] at hw
      obtain ⟨o, rfl⟩ := hw
      exact ⟨algebraMap O' _ o, Subalgebra.algebraMap_mem _ o, rfl⟩
    · exact ⟨⟨g j / g i, div_mem_projChart i j⟩, Algebra.subset_adjoin
        (Finset.mem_image.mpr ⟨j, Finset.mem_univ _, rfl⟩), rfl⟩
  obtain ⟨w, hw, hwz⟩ := hle hz
  have : w = ⟨z, hz⟩ := Subtype.ext hwz
  rw [← this]; exact hw

end FiniteType

end TemperedFundamentalGroups.SemistableReduction
