/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib

/-!
# Zariski models of function fields

Blueprint §9.6 (W5), layer M1. A ring-level (birational) formulation of models of a function
field, after Zariski's abstract varieties: a model of a field `F` over a subring `R ⊆ F` is a
finite set of *charts*, subrings `A ⊆ F` containing `R`; the points of the model are the local
rings `A_𝔭 ⊆ F` of the charts at their primes, and two charts are glued along their common local
rings. Every prime of a chart is the center `𝔪_W ∩ A` of a valuation subring `W ⊇ A`, so the
points are the rings `localAt A W` (`A ≤ W`).

* `localAt A W = {x | ∃ s ∈ A, W(s) = 1, x s ∈ A}`: the localization of `A` at the center of `W`
  (the local ring of the point of `Spec A` at which `W` is centered);
  `localAt_eq_localSubringOfPrime` identifies it with Mathlib's `LocalSubring.ofPrime`.
* `localAt_eq_of_le` (**gluing lemma**): if `A ≤ B ≤ localAt A W`, then
  `localAt B W = localAt A W`.
* `ZariskiModel R`: a finite set of charts containing `R`; `IsSeparated` (Zariski's
  irredundance: a valuation ring dominates at most one point, equivalently
  `B ≤ localAt A W` for charts `A, B ≤ W`), `IsProper` (every valuation subring `W ⊇ R` contains a
  chart: the valuative criterion of properness), `IsNormal`, `IsFiniteType`.
* `center M W`: the **specialization** (reduction) of a valuation subring `W ⊇ R` of `F`: the point
  of the model at which `W` is centered (`center_eq`: computed in any chart contained in `W`).
* `iJoin M`: the **join** of finitely many models (charts `R ⊔ ⨆ i, A i`); joins of proper,
  separated, finite type models are proper, separated, of finite type.
* For `R = baseRing O F` (`O` a valuation subring of a field `K ⊆ F`): `IsResidueTranscendental`
  and `IsTypeTwo` (residue field transcendental over that of `O`;
  `isResidueTranscendental_iff`), `specialFibre`, the points whose maximal ideal contains `𝔪_O`,
  and `vertexSet`, the type-2 valuation subrings `W` of `F` over `O` (`W ∩ K = O`) which are points
  of the model — the local rings of the generic points of the components of the special fibre
  (`mem_vertexSet_iff`: type 2, `W ∩ K = O` and `center W = W`).
* `exists_isResidueTranscendental_of_localAt_eq` (**residue generation**): if a type-2 `W` is the
  local ring of a chart generated by a set `S`, some element of `S` has transcendental residue.
-/

open IsLocalRing

namespace SemistableReduction

variable {F : Type*} [Field F]

lemma one_le_of_inv_le_one {Γ : Type*} [LinearOrderedCommGroupWithZero Γ] {a : Γ} (ha : a ≠ 0)
    (h : a⁻¹ ≤ 1) : 1 ≤ a := by
  simpa using (inv_le_one₀ (zero_lt_iff.2 ha)).1 h

/-! ### Local rings at centers of valuations -/

/-- The local ring of the subring `A` at the center of the valuation subring `W`: the elements
`x` with `x s ∈ A` for some `s ∈ A` which is a unit of `W`. For `A ≤ W` it is the localization of
`A` at the prime `𝔪_W ∩ A` (`localAt_eq_localSubringOfPrime`). -/
def localAt (A : Subring F) (W : ValuationSubring F) : Subring F where
  carrier := {x | ∃ s ∈ A, W.valuation s = 1 ∧ x * s ∈ A}
  mul_mem' {x y} := by
    rintro ⟨s, hs, hsW, hxs⟩ ⟨s', hs', hs'W, hys'⟩
    refine ⟨s * s', A.mul_mem hs hs', by rw [map_mul, hsW, hs'W, one_mul], ?_⟩
    rw [show x * y * (s * s') = (x * s) * (y * s') by ring]
    exact A.mul_mem hxs hys'
  one_mem' := ⟨1, A.one_mem, map_one _, by simp⟩
  add_mem' {x y} := by
    rintro ⟨s, hs, hsW, hxs⟩ ⟨s', hs', hs'W, hys'⟩
    refine ⟨s * s', A.mul_mem hs hs', by rw [map_mul, hsW, hs'W, one_mul], ?_⟩
    rw [show (x + y) * (s * s') = (x * s) * s' + (y * s') * s by ring]
    exact A.add_mem (A.mul_mem hxs hs') (A.mul_mem hys' hs)
  zero_mem' := ⟨1, A.one_mem, map_one _, by simp⟩
  neg_mem' {x} := by
    rintro ⟨s, hs, hsW, hxs⟩
    exact ⟨s, hs, hsW, by simpa [neg_mul] using A.neg_mem hxs⟩

variable {A B : Subring F} {W : ValuationSubring F}

lemma mem_localAt {x : F} : x ∈ localAt A W ↔ ∃ s ∈ A, W.valuation s = 1 ∧ x * s ∈ A :=
  Iff.rfl

lemma le_localAt : A ≤ localAt A W := fun x hx ↦
  ⟨1, A.one_mem, map_one _, by simpa using hx⟩

/-- Inverses of the `W`-units of `A` lie in the local ring of `A` at the center of `W`. -/
lemma inv_mem_localAt {s : F} (hs : s ∈ A) (hsW : W.valuation s = 1) : s⁻¹ ∈ localAt A W := by
  have hs0 : s ≠ 0 := by
    rintro rfl
    simp at hsW
  exact ⟨s, hs, hsW, by simp [inv_mul_cancel₀ hs0]⟩

lemma localAt_mono (h : A ≤ B) : localAt A W ≤ localAt B W := by
  rintro x ⟨s, hs, hsW, hxs⟩
  exact ⟨s, h hs, hsW, h hxs⟩

/-- The local ring at the center of `W` is contained in `W`. -/
lemma localAt_le (h : A ≤ W.toSubring) : localAt A W ≤ W.toSubring := by
  rintro x ⟨s, hs, hsW, hxs⟩
  have hs0 : s ≠ 0 := by
    rintro rfl
    simp at hsW
  have hx : x = (x * s) * s⁻¹ := by field_simp
  rw [hx]
  refine W.mul_mem _ _ (h hxs) ?_
  rw [← W.valuation_le_one_iff, map_inv₀, hsW, inv_one]

/-- **Gluing lemma.** If `A ≤ B ≤ localAt A W`, the local rings of `A` and `B` at the center of `W`
coincide. -/
lemma localAt_eq_of_le (hAB : A ≤ B) (hB : B ≤ localAt A W) : localAt B W = localAt A W := by
  refine le_antisymm ?_ (localAt_mono hAB)
  rintro x ⟨s, hs, hsW, hxs⟩
  obtain ⟨s₁, hs₁, hs₁W, h₁⟩ := hB hs
  obtain ⟨s₂, hs₂, hs₂W, h₂⟩ := hB hxs
  refine ⟨s * s₁ * s₂, A.mul_mem h₁ hs₂, by rw [map_mul, map_mul, hsW, hs₁W, hs₂W, one_mul,
    one_mul], ?_⟩
  rw [show x * (s * s₁ * s₂) = (x * s * s₂) * s₁ by ring]
  exact A.mul_mem h₂ hs₁

/-- The local ring of a valuation subring at its own center is itself. -/
lemma localAt_self : localAt W.toSubring W = W.toSubring :=
  le_antisymm (localAt_le le_rfl) le_localAt

/-- If the valuation subring `W` is the local ring of `A` at the center of some `W' ⊇ A`, then it
is the local ring of `A` at its own center. -/
lemma localAt_eq_of_localAt_eq {W' : ValuationSubring F} (hA : A ≤ W'.toSubring)
    (h : localAt A W' = W.toSubring) : localAt A W = W.toSubring := by
  have hW : W.toSubring ≤ W'.toSubring := h ▸ localAt_le hA
  have hAW : A ≤ W.toSubring := h ▸ le_localAt
  refine le_antisymm (localAt_le hAW) (h ▸ ?_)
  rintro x ⟨s, hs, hsW, hxs⟩
  refine ⟨s, hs, ?_, hxs⟩
  have hs0 : s ≠ 0 := by
    rintro rfl
    simp at hsW
  refine le_antisymm ((W.valuation_le_one_iff s).2 (hAW hs)) ?_
  have hinv : s⁻¹ ∈ W := by
    rw [← ValuationSubring.mem_toSubring, ← h]
    exact inv_mem_localAt hs hsW
  rw [← W.valuation_le_one_iff, map_inv₀] at hinv
  exact one_le_of_inv_le_one (by simpa using hs0) hinv

/-! #### Comparison with `LocalSubring.ofPrime` -/

/-- The prime `𝔪_W ∩ A` of `A` at which `W ⊇ A` is centered. -/
def centerIdeal (A : Subring F) (W : ValuationSubring F) (h : A ≤ W.toSubring) : Ideal A :=
  (maximalIdeal W).comap (Subring.inclusion h)

instance (h : A ≤ W.toSubring) : (centerIdeal A W h).IsPrime :=
  Ideal.comap_isPrime _ _

lemma mem_centerIdeal_iff (h : A ≤ W.toSubring) (a : A) :
    a ∈ centerIdeal A W h ↔ W.valuation (a : F) < 1 := by
  rw [centerIdeal, Ideal.mem_comap, ValuationSubring.valuation_lt_one_iff]
  rfl

lemma valuation_eq_one_iff_notMem_centerIdeal (h : A ≤ W.toSubring) (a : A) :
    W.valuation (a : F) = 1 ↔ a ∉ centerIdeal A W h := by
  rw [mem_centerIdeal_iff, not_lt]
  exact ⟨fun h' ↦ h'.ge, fun h' ↦ le_antisymm ((W.valuation_le_one_iff _).2 (h a.2)) h'⟩

/-- `localAt A W` is the localization of `A` at the center `𝔪_W ∩ A` of `W`, as in Mathlib's
`LocalSubring.ofPrime`. -/
theorem localAt_eq_localSubringOfPrime (h : A ≤ W.toSubring) :
    localAt A W = (LocalSubring.ofPrime A (centerIdeal A W h)).toSubring := by
  set P := centerIdeal A W h
  have hloc : IsLocalization.AtPrime (LocalSubring.ofPrime A P).toSubring P := inferInstance
  ext x
  constructor
  · rintro ⟨s, hs, hsW, hxs⟩
    have hsP : (⟨s, hs⟩ : A) ∈ P.primeCompl :=
      (valuation_eq_one_iff_notMem_centerIdeal h ⟨s, hs⟩).1 hsW
    have hs0 : s ≠ 0 := by
      rintro rfl
      simp at hsW
    have hunit := IsLocalization.map_units (LocalSubring.ofPrime A P).toSubring
      (⟨⟨s, hs⟩, hsP⟩ : P.primeCompl)
    obtain ⟨u, hu⟩ := hunit
    have hmem : (x * s) * (u⁻¹ : (LocalSubring.ofPrime A P).toSubring ˣ).1.1 = x := by
      have hu' : (u : (LocalSubring.ofPrime A P).toSubring).1 = s := congrArg Subtype.val hu
      have : ((u⁻¹ : (LocalSubring.ofPrime A P).toSubring ˣ) : _).1 * s = 1 := by
        rw [← hu']
        exact congrArg Subtype.val u.inv_mul
      rw [mul_assoc, mul_comm s, this, mul_one]
    rw [← hmem]
    exact Subring.mul_mem _ (LocalSubring.le_ofPrime A P hxs) (Subtype.prop _)
  · intro hx
    obtain ⟨⟨a, s⟩, hs⟩ := IsLocalization.surj P.primeCompl (⟨x, hx⟩ :
      (LocalSubring.ofPrime A P).toSubring)
    have hs' := congrArg Subtype.val hs
    refine ⟨(s : A), (s : A).2, (valuation_eq_one_iff_notMem_centerIdeal h s).2 s.2, ?_⟩
    have : x * ((s : A) : F) = ((a : A) : F) := hs'
    rw [this]
    exact a.2

/-! ### Models -/

/-- A **Zariski model** of the field `F` over the subring `R`: a finite set of charts, subrings
of `F` containing `R`. The points of the model are the local rings `localAt A W` of the charts at
the centers of valuation subrings `W ⊇ A`. -/
structure ZariskiModel (R : Subring F) where
  /-- The affine charts. -/
  charts : Finset (Subring F)
  /-- Every chart contains the base ring. -/
  le_chart : ∀ A ∈ charts, R ≤ A

namespace ZariskiModel

variable {R : Subring F} (M : ZariskiModel R)

/-- The points of the model: local rings of the charts at centers of valuation subrings. -/
def points : Set (Subring F) :=
  {B | ∃ A ∈ M.charts, ∃ W : ValuationSubring F, A ≤ W.toSubring ∧ localAt A W = B}

/-- The model is **separated** (Zariski's irredundance: no valuation subring dominates two
distinct points): for charts `A, B ⊆ W`, `B` lies in the local ring of `A` at the center of `W`. -/
def IsSeparated : Prop :=
  ∀ A ∈ M.charts, ∀ B ∈ M.charts, ∀ W : ValuationSubring F, A ≤ W.toSubring →
    B ≤ W.toSubring → B ≤ localAt A W

/-- The model is **proper** (complete, in Zariski's terminology; the existence part of the
valuative criterion): every valuation subring of `F` containing `R` contains a chart. -/
def IsProper : Prop :=
  ∀ W : ValuationSubring F, R ≤ W.toSubring → ∃ A ∈ M.charts, A ≤ W.toSubring

/-- The model is **normal**: every chart is integrally closed in `F`. -/
def IsNormal : Prop :=
  ∀ A ∈ M.charts, ∀ x : F, IsIntegral A x → x ∈ A

/-- The model is **of finite type** over `R`: every chart is generated by `R` and finitely many
elements. -/
def IsFiniteType : Prop :=
  ∀ A ∈ M.charts, ∃ s : Finset F, A = Subring.closure ((R : Set F) ∪ s)

variable {M}

/-- In a separated model the local rings of two charts at the center of `W` coincide. -/
theorem IsSeparated.localAt_eq (hM : M.IsSeparated) {A B : Subring F} (hA : A ∈ M.charts)
    (hB : B ∈ M.charts) (hAW : A ≤ W.toSubring) (hBW : B ≤ W.toSubring) :
    localAt A W = localAt B W := by
  have h₁ : A ⊔ B ≤ localAt A W := sup_le le_localAt (hM A hA B hB W hAW hBW)
  have h₂ : A ⊔ B ≤ localAt B W := sup_le (hM B hB A hA W hBW hAW) le_localAt
  rw [← localAt_eq_of_le le_sup_left h₁, localAt_eq_of_le le_sup_right h₂]

/-- A criterion for separatedness: for charts `A, B ⊆ W`, `B` is contained in the local ring of
`A`, which holds when the generators of `B` are in it. -/
theorem isSeparated_iff : M.IsSeparated ↔ ∀ A ∈ M.charts, ∀ B ∈ M.charts,
    ∀ W : ValuationSubring F, A ≤ W.toSubring → B ≤ W.toSubring → B ≤ localAt A W :=
  Iff.rfl

/-- The **specialization** (center, reduction) of a valuation subring `W ⊇ R` of `F` on a proper
model: the local ring of a chart contained in `W` at the center of `W`. -/
noncomputable def center (hM : M.IsProper) (W : ValuationSubring F) (hW : R ≤ W.toSubring) :
    Subring F :=
  localAt (hM W hW).choose W

/-- The specialization is computed in any chart contained in `W` (for separated models). -/
theorem center_eq (hM : M.IsProper) (hs : M.IsSeparated) {W : ValuationSubring F}
    (hW : R ≤ W.toSubring) {A : Subring F} (hA : A ∈ M.charts) (hAW : A ≤ W.toSubring) :
    M.center hM W hW = localAt A W :=
  hs.localAt_eq (hM W hW).choose_spec.1 hA (hM W hW).choose_spec.2 hAW

theorem center_mem_points (hM : M.IsProper) (W : ValuationSubring F) (hW : R ≤ W.toSubring) :
    M.center hM W hW ∈ M.points :=
  ⟨_, (hM W hW).choose_spec.1, W, (hM W hW).choose_spec.2, rfl⟩

/-- The specialization of `W` is dominated by `W`. -/
theorem center_le (hM : M.IsProper) (W : ValuationSubring F) (hW : R ≤ W.toSubring) :
    M.center hM W hW ≤ W.toSubring :=
  localAt_le (hM W hW).choose_spec.2

/-- The points of a proper separated model are exactly the specializations of the valuation
subrings of `F` containing `R`. -/
theorem mem_points_iff (hM : M.IsProper) (hs : M.IsSeparated) {B : Subring F} :
    B ∈ M.points ↔ ∃ (W : ValuationSubring F) (hW : R ≤ W.toSubring), M.center hM W hW = B := by
  constructor
  · rintro ⟨A, hA, W, hAW, rfl⟩
    exact ⟨W, (M.le_chart A hA).trans hAW, center_eq hM hs _ hA hAW⟩
  · rintro ⟨W, hW, rfl⟩
    exact center_mem_points hM W hW

end ZariskiModel

/-! ### Joins of models -/

namespace ZariskiModel

variable {R : Subring F}

open scoped Classical in
/-- The **join** of a finite family of models (the closure of the diagonal in their product):
its charts are the subrings `R ⊔ ⨆ i, A i` generated by a choice of a chart `A i` of each model. -/
noncomputable def iJoin {ι : Type*} [Fintype ι] (M : ι → ZariskiModel R) : ZariskiModel R where
  charts := Finset.univ.image fun f : (∀ i, (M i).charts) ↦ R ⊔ ⨆ i, ((f i : Subring F))
  le_chart A hA := by
    obtain ⟨f, -, rfl⟩ := Finset.mem_image.1 hA
    exact le_sup_left

variable {ι : Type*} [Fintype ι] {M : ι → ZariskiModel R}

lemma mem_iJoin_charts {A : Subring F} :
    A ∈ (iJoin M).charts ↔ ∃ f : ι → Subring F, (∀ i, f i ∈ (M i).charts) ∧ A = R ⊔ ⨆ i, f i := by
  classical
  simp only [iJoin, Finset.mem_image, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨f, rfl⟩
    exact ⟨fun i ↦ f i, fun i ↦ (f i).2, rfl⟩
  · rintro ⟨f, hf, rfl⟩
    exact ⟨fun i ↦ ⟨f i, hf i⟩, rfl⟩

/-- A join of proper models is proper. -/
theorem iJoin_isProper (hM : ∀ i, (M i).IsProper) : (iJoin M).IsProper := by
  intro W hW
  refine ⟨R ⊔ ⨆ i, (hM i W hW).choose,
    mem_iJoin_charts.2 ⟨_, fun i ↦ (hM i W hW).choose_spec.1, rfl⟩,
    sup_le hW (iSup_le fun i ↦ (hM i W hW).choose_spec.2)⟩

/-- A join of separated models is separated. -/
theorem iJoin_isSeparated (hM : ∀ i, (M i).IsSeparated) : (iJoin M).IsSeparated := by
  intro A hA B hB W hAW hBW
  obtain ⟨f, hf, rfl⟩ := mem_iJoin_charts.1 hA
  obtain ⟨g, hg, rfl⟩ := mem_iJoin_charts.1 hB
  have hfA (i : ι) : f i ≤ R ⊔ ⨆ i, f i := (le_iSup f i).trans le_sup_right
  have hgB (i : ι) : g i ≤ R ⊔ ⨆ i, g i := (le_iSup g i).trans le_sup_right
  refine sup_le (le_sup_left.trans le_localAt) (iSup_le fun i ↦ ?_)
  exact (hM i (f i) (hf i) (g i) (hg i) W ((hfA i).trans hAW) ((hgB i).trans hBW)).trans
    (localAt_mono (hfA i))

omit [Fintype ι] in
/-- The subring generated by `R` and the union of sets `s i` is `R ⊔ ⨆ i, closure (R ∪ s i)`. -/
lemma closure_union_iUnion (s : ι → Set F) :
    Subring.closure ((R : Set F) ∪ ⋃ i, s i) = R ⊔ ⨆ i, Subring.closure ((R : Set F) ∪ s i) := by
  refine le_antisymm (Subring.closure_le.2 (Set.union_subset ?_ ?_)) (sup_le ?_ (iSup_le ?_))
  · exact fun x hx ↦ (le_sup_left : R ≤ _) hx
  · refine Set.iUnion_subset fun i x hx ↦ ?_
    exact (le_iSup (fun i ↦ Subring.closure ((R : Set F) ∪ s i)) i).trans le_sup_right
      (Subring.subset_closure (Or.inr hx))
  · exact fun x hx ↦ Subring.subset_closure (Or.inl hx)
  · exact fun i ↦ Subring.closure_mono (Set.union_subset_union_right _ (Set.subset_iUnion s i))

/-- A join of models of finite type is of finite type. -/
theorem iJoin_isFiniteType (hM : ∀ i, (M i).IsFiniteType) : (iJoin M).IsFiniteType := by
  classical
  intro A hA
  obtain ⟨f, hf, rfl⟩ := mem_iJoin_charts.1 hA
  choose s hs using fun i ↦ hM i (f i) (hf i)
  refine ⟨Finset.univ.biUnion s, ?_⟩
  rw [Finset.coe_biUnion, Finset.coe_univ, Set.biUnion_univ, closure_union_iUnion]
  simp_rw [← hs]

end ZariskiModel

/-! ### Models over a valuation ring: special fibre and vertex set -/

section Base

variable {K : Type*} [Field K] [Algebra K F]

variable (F) in
/-- The image of the valuation subring `O ⊆ K` in `F`: the base ring of models over `O`. -/
def baseRing (O : ValuationSubring K) : Subring F :=
  O.toSubring.map (algebraMap K F)

lemma algebraMap_mem_baseRing {O : ValuationSubring K} {o : K} (ho : o ∈ O) :
    algebraMap K F o ∈ baseRing F O :=
  ⟨o, ho, rfl⟩

/-- A valuation subring `W` of `F` contains the base ring iff `O ≤ W ∩ K`. -/
lemma baseRing_le_iff {O : ValuationSubring K} {W : ValuationSubring F} :
    baseRing F O ≤ W.toSubring ↔ O ≤ W.comap (algebraMap K F) := by
  constructor
  · intro h o ho
    exact h ⟨o, ho, rfl⟩
  · rintro h _ ⟨o, ho, rfl⟩
    exact h ho

/-- If `W ∩ K = O`, the elements of `𝔪_O` have `W`-valuation `< 1`. -/
lemma valuation_lt_one_of_comap_eq {O : ValuationSubring K} {W : ValuationSubring F}
    (hW : W.comap (algebraMap K F) = O) {o : K} (ho : o ∈ O) (hno : o⁻¹ ∉ O) :
    W.valuation (algebraMap K F o) < 1 := by
  have h₁ : algebraMap K F o ∈ W := by
    rw [← ValuationSubring.mem_comap, hW]
    exact ho
  have h₂ : (algebraMap K F o)⁻¹ ∉ W := by
    rw [← map_inv₀, ← ValuationSubring.mem_comap, hW]
    exact hno
  rw [← W.valuation_le_one_iff] at h₁
  refine lt_of_le_of_ne h₁ fun h ↦ h₂ ?_
  rw [← W.valuation_le_one_iff, map_inv₀, h, inv_one]

/-- If `W ∩ K = O`, the units of `O` are `W`-units. -/
lemma valuation_eq_one_of_comap_eq {O : ValuationSubring K} {W : ValuationSubring F}
    (hW : W.comap (algebraMap K F) = O) {o : K} (ho0 : o ≠ 0) (ho : o ∈ O) (hno : o⁻¹ ∈ O) :
    W.valuation (algebraMap K F o) = 1 := by
  have h₁ : algebraMap K F o ∈ W := by
    rw [← ValuationSubring.mem_comap, hW]
    exact ho
  have h₂ : (algebraMap K F o)⁻¹ ∈ W := by
    rw [← map_inv₀, ← ValuationSubring.mem_comap, hW]
    exact hno
  rw [← W.valuation_le_one_iff] at h₁ h₂
  rw [map_inv₀] at h₂
  exact le_antisymm h₁ (one_le_of_inv_le_one (by simpa using ho0) h₂)

/-! #### Type-2 valuations -/

section Residue

open Polynomial

variable {O : ValuationSubring K} {W : ValuationSubring F}

/-- `z ∈ W` has **residue transcendental** over the residue field of `O`: `P(z)` is a `W`-unit
for every polynomial `P` over `O` with nonzero reduction (`isResidueTranscendental_iff`). -/
def IsResidueTranscendental (O : ValuationSubring K) (W : ValuationSubring F) (z : F) : Prop :=
  z ∈ W ∧ ∀ P : O[X], P.map (residue O) ≠ 0 →
    W.valuation (aeval z (P.map (algebraMap O K))) = 1

/-- `W` is of **type 2** over `O`: its residue field is transcendental over that of `O`. -/
def IsTypeTwo (O : ValuationSubring K) (W : ValuationSubring F) : Prop :=
  ∃ z, IsResidueTranscendental O W z

/-- The local homomorphism `O → W` when `W ∩ K = O`. -/
def toVal (hW : W.comap (algebraMap K F) = O) : O →+* W :=
  ((algebraMap K F).comp O.subtype).codRestrict W.toSubring fun o ↦ by
    have h : (o : K) ∈ W.comap (algebraMap K F) := by rw [hW]; exact o.2
    exact h

@[simp]
lemma coe_toVal (hW : W.comap (algebraMap K F) = O) (o : O) :
    (toVal hW o : F) = algebraMap K F o :=
  rfl

instance (hW : W.comap (algebraMap K F) = O) : IsLocalHom (toVal hW) := by
  refine ⟨fun o ho ↦ ?_⟩
  obtain ⟨u, hu⟩ := ho.exists_left_inv
  have hu' : (u : F) * algebraMap K F o = 1 := congrArg Subtype.val hu
  have ho0 : (o : K) ≠ 0 := by
    rintro h
    simp [h] at hu'
  have hinv : (o : K)⁻¹ ∈ W.comap (algebraMap K F) := by
    rw [ValuationSubring.mem_comap, map_inv₀, ← eq_inv_of_mul_eq_one_left hu']
    exact u.2
  rw [hW] at hinv
  exact isUnit_iff_exists_inv.mpr ⟨⟨_, hinv⟩, Subtype.ext (mul_inv_cancel₀ ho0)⟩

variable (hW : W.comap (algebraMap K F) = O)

/-- The residue field of `W` as an algebra over that of `O`. -/
noncomputable abbrev residueAlgebra : Algebra (ResidueField O) (ResidueField W) :=
  (ResidueField.map (toVal hW)).toAlgebra

lemma coe_eval₂_toVal {z : F} (hz : z ∈ W) (P : O[X]) :
    ((eval₂ (toVal hW) ⟨z, hz⟩ P : W) : F) = aeval z (P.map (algebraMap O K)) := by
  rw [aeval_map_algebraMap, aeval_def, ← W.coe_subtype, hom_eval₂]
  rfl

include hW in
lemma aeval_residue {z : F} (hz : z ∈ W) (P : O[X]) :
    letI := residueAlgebra hW
    aeval (residue W ⟨z, hz⟩) (P.map (residue O)) =
      residue W (eval₂ (toVal hW) ⟨z, hz⟩ P) := by
  letI := residueAlgebra hW
  rw [aeval_def, eval₂_map, hom_eval₂]
  congr 1

include hW in
/-- Residue transcendence is transcendence of the residue over the residue field of `O`. -/
theorem isResidueTranscendental_iff {z : F} (hz : z ∈ W) :
    IsResidueTranscendental O W z ↔
      letI := residueAlgebra hW
      Transcendental (ResidueField O) (residue W ⟨z, hz⟩) := by
  letI := residueAlgebra hW
  have key (P : O[X]) : aeval (residue W ⟨z, hz⟩) (P.map (residue O)) ≠ 0 ↔
      W.valuation (aeval z (P.map (algebraMap O K))) = 1 := by
    rw [aeval_residue hW hz, residue_ne_zero_iff_isUnit, W.valuation_eq_one_iff,
      coe_eval₂_toVal]
  constructor
  · rintro ⟨-, h⟩ ⟨p, hp, hroot⟩
    obtain ⟨P, rfl⟩ := map_surjective _ (residue_surjective (R := O)) p
    exact (key P).2 (h P hp) hroot
  · intro h
    refine ⟨hz, fun P hP ↦ (key P).1 fun hroot ↦ h ⟨_, hP, hroot⟩⟩

include hW in
/-- **Residue generation.** If `W ∩ K = O`, `W` is of type 2 and `W` is the local ring at its
center of a chart generated over `O` by a set `S`, then some element of `S` has residue
transcendental over the residue field of `O` (the residue field of the local ring is generated by
the residues of `S`). -/
theorem exists_isResidueTranscendental_of_localAt_eq {S : Set F}
    (hloc : localAt (Subring.closure ((baseRing F O : Set F) ∪ S)) W = W.toSubring)
    (hT : IsTypeTwo O W) : ∃ s ∈ S, IsResidueTranscendental O W s := by
  letI := residueAlgebra hW
  set A := Subring.closure ((baseRing F O : Set F) ∪ S)
  have hAW : A ≤ W.toSubring := hloc ▸ le_localAt
  by_contra hcon
  push Not at hcon
  set L := algebraicClosure (ResidueField O) (ResidueField W)
  let T : Subring F := (L.toSubalgebra.toSubring.comap (residue W)).map W.subtype
  have hmemT {x : F} (hx : x ∈ W) (h : residue W ⟨x, hx⟩ ∈ L) : x ∈ T :=
    ⟨⟨x, hx⟩, h, rfl⟩
  have hTmem {x : F} (h : x ∈ T) : ∃ hx : x ∈ W, residue W ⟨x, hx⟩ ∈ L := by
    obtain ⟨y, hy, rfl⟩ := h
    exact ⟨y.2, hy⟩
  have hAT : A ≤ T := by
    refine Subring.closure_le.2 (Set.union_subset ?_ ?_)
    · rintro _ ⟨o, ho, rfl⟩
      refine hmemT (toVal hW ⟨o, ho⟩).2 ?_
      have : residue W (toVal hW ⟨o, ho⟩) =
          algebraMap (ResidueField O) (ResidueField W) (residue O ⟨o, ho⟩) :=
        (ResidueField.map_residue (toVal hW) _).symm
      rw [show (⟨algebraMap K F o, (toVal hW ⟨o, ho⟩).2⟩ : W) = toVal hW ⟨o, ho⟩ from rfl, this]
      exact L.algebraMap_mem _
    · intro s hs
      have hsW : s ∈ W := hAW (Subring.subset_closure (Or.inr hs))
      refine hmemT hsW ?_
      rw [mem_algebraicClosure_iff]
      by_contra htr
      exact hcon s hs ((isResidueTranscendental_iff hW hsW).2 htr)
  obtain ⟨z, hzt⟩ := hT
  have hz := hzt.1
  have hzA : z ∈ localAt A W := by rw [hloc]; exact hz
  obtain ⟨s, hs, hsW, hzs⟩ := hzA
  obtain ⟨hsW', hsL⟩ := hTmem (hAT hs)
  obtain ⟨hzsW, hzsL⟩ := hTmem (hAT hzs)
  have hunit : IsUnit (⟨s, hsW'⟩ : W) := (W.valuation_eq_one_iff _).2 hsW
  have hres0 : residue W ⟨s, hsW'⟩ ≠ 0 := (residue_ne_zero_iff_isUnit _).2 hunit
  have hprod : residue W ⟨z, hz⟩ * residue W ⟨s, hsW'⟩ = residue W ⟨z * s, hzsW⟩ := by
    rw [← map_mul]
    rfl
  have hzL : residue W ⟨z, hz⟩ ∈ L := by
    rw [eq_div_of_mul_eq hres0 hprod]
    exact div_mem hzsL hsL
  rw [mem_algebraicClosure_iff] at hzL
  exact (isResidueTranscendental_iff hW hz).1 hzt hzL

end Residue

namespace ZariskiModel

variable {O : ValuationSubring K} (M : ZariskiModel (baseRing F O))

/-- The **special fibre**: the points whose maximal ideal contains `𝔪_O`, i.e. in which no
non-unit of `O` becomes invertible. -/
def specialFibre : Set (Subring F) :=
  {B | B ∈ M.points ∧ ∀ o ∈ O, o⁻¹ ∉ O → (algebraMap K F o)⁻¹ ∉ B}

/-- The **vertex set** of the model: the type-2 valuation subrings `W` of `F` over `O`
(`W ∩ K = O`, residue field transcendental over that of `O`) that are points of the model: the
local rings at the generic points of the irreducible components of the special fibre (for normal
models of finite type over a discrete valuation ring the type-2 condition is automatic by
dimension theory, which is not formalized). -/
def vertexSet : Set (ValuationSubring F) :=
  {W | W.comap (algebraMap K F) = O ∧ IsTypeTwo O W ∧ W.toSubring ∈ M.points}

variable {M}

/-- A vertex lies in the special fibre. -/
theorem toSubring_mem_specialFibre {W : ValuationSubring F} (hW : W ∈ M.vertexSet) :
    W.toSubring ∈ M.specialFibre := by
  refine ⟨hW.2.2, fun o ho hno h ↦ hno ?_⟩
  have h' : (algebraMap K F o)⁻¹ ∈ W := h
  rw [← map_inv₀, ← ValuationSubring.mem_comap, hW.1] at h'
  exact h'

/-- **Vertices are the type-2 valuation subrings over `O` that are their own specialization.** -/
theorem mem_vertexSet_iff (hM : M.IsProper) (hs : M.IsSeparated) {W : ValuationSubring F} :
    W ∈ M.vertexSet ↔ IsTypeTwo O W ∧ ∃ h : W.comap (algebraMap K F) = O,
      M.center hM W (baseRing_le_iff.2 h.ge) = W.toSubring := by
  constructor
  · rintro ⟨hW, hT, A, hA, W', hAW', hloc⟩
    refine ⟨hT, hW, ?_⟩
    have hAW : A ≤ W.toSubring := hloc ▸ le_localAt
    rw [center_eq hM hs _ hA hAW]
    exact localAt_eq_of_localAt_eq hAW' hloc
  · rintro ⟨hT, hW, h⟩
    exact ⟨hW, hT, h ▸ center_mem_points hM W _⟩

/-- A type-2 valuation subring `W` over `O` with `localAt A W = W` for a chart `A ⊆ W` is a
vertex. -/
theorem mem_vertexSet_of_localAt_eq {W : ValuationSubring F}
    (hW : W.comap (algebraMap K F) = O) (hT : IsTypeTwo O W) {A : Subring F} (hA : A ∈ M.charts)
    (hAW : A ≤ W.toSubring) (h : localAt A W = W.toSubring) : W ∈ M.vertexSet :=
  ⟨hW, hT, A, hA, W, hAW, h⟩

/-- A vertex is the local ring at its own center of some chart. -/
theorem exists_localAt_eq_of_mem_vertexSet {W : ValuationSubring F} (hW : W ∈ M.vertexSet) :
    ∃ A ∈ M.charts, A ≤ W.toSubring ∧ localAt A W = W.toSubring := by
  obtain ⟨-, -, A, hA, W', hAW', hloc⟩ := hW
  exact ⟨A, hA, hloc ▸ le_localAt, localAt_eq_of_localAt_eq hAW' hloc⟩

/-- Conversely, a vertex is the local ring at its own center of every chart it contains (for
separated models). -/
theorem localAt_eq_of_mem_vertexSet (hs : M.IsSeparated) {W : ValuationSubring F}
    (hW : W ∈ M.vertexSet) {A : Subring F} (hA : A ∈ M.charts) (hAW : A ≤ W.toSubring) :
    localAt A W = W.toSubring := by
  obtain ⟨B, hB, hBW, hloc⟩ := exists_localAt_eq_of_mem_vertexSet hW
  rw [hs.localAt_eq hA hB hAW hBW, hloc]

end ZariskiModel

end Base

end SemistableReduction
