/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.Orbicurve.GenericPoint

/-!
# The coordinate ring of an elliptic curve minus finitely many fibres of `x`

For a set `T ⊆ k`, `ringOfX W T` is the `k`-subalgebra of the function field `k(W)` generated
by the coordinates `x, y` of the generic point and the inverses `(x - a)⁻¹` for `a ∈ T`. It is
the coordinate ring of `W ∖ ({0} ∪ {P : x(P) ∈ T})`. For a set `S` of rational points,
`ringOf W S = ringOfX W (xSet S)` (with `xSet S` the `x`-coordinates of the affine points of `S`)
is the coordinate ring of `W ∖ ({0} ∪ S ∪ -S)`.

A `k`-algebra map `χ : ringOfX W T →ₐ[k] L` into a field is a point `pointOf χ = (χ x, χ y)` of
`W(L)` whose `x`-coordinate avoids `T`. The main computation of this file
(`act_pointOf`, `act_pointOf_of_m_eq_zero`) expresses the coordinates of `g(pointOf χ)`, for an
affine automorphism `g = (ε, m)` with `x(m) ∈ T`, as the images under `χ` of explicit elements
`AffAut.xR`, `AffAut.yR` of `ringOfX W T` (the addition formula, whose denominator `x - x(m)` is
inverted in `ringOfX W T`). For `χ` the inclusion into `k(W)` this shows that the coordinates of
`g(genericPoint W)` lie in `ringOfX W T` (`xOf_act_genericPoint_mem`).
-/

universe u

open Polynomial WeierstrassCurve WeierstrassCurve.Affine
open scoped Polynomial.Bivariate

namespace TemperedFundamentalGroups.Orbicurve

noncomputable section

variable {k : Type u} [Field k] (W : WeierstrassCurve k)

/-! ### Coordinates under negation and addition -/

section Formulas

variable {L : Type*} [Field L] [DecidableEq L] {V : Affine L}

lemma units_smul_ne_zero (ε : ℤˣ) {Q : V.Point} (hQ : Q ≠ 0) : ε • Q ≠ 0 := by
  rcases Int.units_eq_one_or ε with rfl | rfl
  · rwa [one_smul]
  · rwa [Units.neg_smul, one_smul, neg_ne_zero]

lemma xOf_units_smul (ε : ℤˣ) (Q : V.Point) : xOf (ε • Q) = xOf Q := by
  rcases Int.units_eq_one_or ε with rfl | rfl
  · rw [one_smul]
  · rw [Units.neg_smul, one_smul]
    cases Q with
    | zero => rfl
    | some x y h => rfl

lemma yOf_units_smul (ε : ℤˣ) (Q : V.Point) (hQ : Q ≠ 0) :
    yOf (ε • Q) = if ε = 1 then yOf Q else V.negY (xOf Q) (yOf Q) := by
  rcases Int.units_eq_one_or ε with rfl | rfl
  · rw [one_smul, if_pos rfl]
  · rw [Units.neg_smul, one_smul, if_neg (by decide)]
    cases Q with
    | zero => exact absurd rfl hQ
    | some x y h => rfl

lemma add_of_xOf_ne {P R : V.Point} (hP : P ≠ 0) (hR : R ≠ 0) (hx : xOf P ≠ xOf R) :
    P + R ≠ 0 ∧
      xOf (P + R) = V.addX (xOf P) (xOf R) ((yOf P - yOf R) / (xOf P - xOf R)) ∧
      yOf (P + R) = V.addY (xOf P) (xOf R) (yOf P) ((yOf P - yOf R) / (xOf P - xOf R)) := by
  rw [eq_some_xOf_yOf hP, eq_some_xOf_yOf hR, Point.add_of_X_ne hx]
  refine ⟨Point.some_ne_zero _, ?_, ?_⟩
  · rw [xOf_some, slope_of_X_ne hx]
    rfl
  · rw [yOf_some, slope_of_X_ne hx]
    rfl

end Formulas

/-! ### The rings -/

/-- The `k`-subalgebra of `k(W)` generated by `x`, `y` and `(x - a)⁻¹` for `a ∈ T`: the
coordinate ring of `W ∖ ({0} ∪ {P : x(P) ∈ T})`. -/
def ringOfX (T : Set k) : Subalgebra k (funField W) :=
  Algebra.adjoin k ({xGen W, yGen W} ∪ (fun a => (xGen W - algebraMap k (funField W) a)⁻¹) '' T)

/-- The `x`-coordinates of the affine points of a set of rational points. -/
def xSet [DecidableEq k] (S : Set W.toAffine.Point) : Set k :=
  xOf '' (S \ {0})

/-- The coordinate ring of `W ∖ ({0} ∪ S ∪ -S)`: the `k`-subalgebra of `k(W)` generated by the
coordinates `x`, `y` of the generic point and `(x - x(P))⁻¹` for the affine `P ∈ S`. -/
def ringOf [DecidableEq k] (S : Set W.toAffine.Point) : Subalgebra k (funField W) :=
  ringOfX W (xSet W S)

variable {W}

lemma xOf_mem_xSet [DecidableEq k] {S : Set W.toAffine.Point} {P : W.toAffine.Point}
    (hPS : P ∈ S) (hP : P ≠ 0) : xOf P ∈ xSet W S :=
  ⟨P, ⟨hPS, hP⟩, rfl⟩

lemma xSet_finite [DecidableEq k] {S : Set W.toAffine.Point} (hS : S.Finite) :
    (xSet W S).Finite :=
  (hS.sdiff).image _

variable {T T' : Set k}

lemma xGen_mem_ringOfX : xGen W ∈ ringOfX W T :=
  Algebra.subset_adjoin (Or.inl (Set.mem_insert _ _))

lemma yGen_mem_ringOfX : yGen W ∈ ringOfX W T :=
  Algebra.subset_adjoin (Or.inl (Set.mem_insert_of_mem _ rfl))

lemma inv_mem_ringOfX {a : k} (ha : a ∈ T) :
    (xGen W - algebraMap k (funField W) a)⁻¹ ∈ ringOfX W T :=
  Algebra.subset_adjoin (Or.inr ⟨a, ha, rfl⟩)

lemma ringOfX_mono (h : T ⊆ T') : ringOfX W T ≤ ringOfX W T' :=
  Algebra.adjoin_mono (Set.union_subset_union_right _ (Set.image_mono h))

lemma ringOfX_fg (hT : T.Finite) : (ringOfX W T).FG :=
  Subalgebra.fg_def.mpr ⟨_, ((Set.toFinite _).union (hT.image _)), rfl⟩

lemma ringOf_fg [DecidableEq k] {S : Set W.toAffine.Point} (hS : S.Finite) : (ringOf W S).FG :=
  ringOfX_fg (xSet_finite hS)

variable (W) in
lemma xGen_sub_ne_zero (a : k) : xGen W - algebraMap k (funField W) a ≠ 0 := fun h => by
  apply transcendental_xGen W
  rw [sub_eq_zero.mp h]
  exact isAlgebraic_algebraMap a

/-- The image of the coordinate ring `k[W]` lies in `ringOfX W T`. -/
lemma algebraMap_mem_ringOfX (c : W.toAffine.CoordinateRing) :
    algebraMap W.toAffine.CoordinateRing (funField W) c ∈ ringOfX W T := by
  obtain ⟨p, rfl⟩ := AdjoinRoot.mk_surjective c
  induction p using Polynomial.induction_on with
  | C q =>
    induction q using Polynomial.induction_on with
    | C a =>
      rw [← algebraMap_funField]
      exact Subalgebra.algebraMap_mem _ a
    | add p q hp hq =>
      rw [C_add, map_add, map_add]
      exact add_mem hp hq
    | monomial n a ih =>
      rw [pow_succ, ← mul_assoc, C_mul, map_mul, map_mul]
      exact mul_mem ih xGen_mem_ringOfX
  | add p q hp hq =>
    rw [map_add, map_add]
    exact add_mem hp hq
  | monomial n q ih =>
    rw [pow_succ, ← mul_assoc, map_mul, map_mul]
    exact mul_mem ih yGen_mem_ringOfX

/-! ### Elements of `ringOfX W T` -/

variable (W T) in
/-- The `x`-coordinate of the generic point as an element of `ringOfX W T`. -/
def xR : ringOfX W T := ⟨xGen W, xGen_mem_ringOfX⟩

variable (W T) in
/-- The `y`-coordinate of the generic point as an element of `ringOfX W T`. -/
def yR : ringOfX W T := ⟨yGen W, yGen_mem_ringOfX⟩

/-- The element `(x - a)⁻¹` of `ringOfX W T`, for `a ∈ T`. -/
def invR {a : k} (ha : a ∈ T) : ringOfX W T := ⟨_, inv_mem_ringOfX ha⟩

@[simp] lemma coe_xR : (xR W T : funField W) = xGen W := rfl

@[simp] lemma coe_yR : (yR W T : funField W) = yGen W := rfl

lemma invR_mul {a : k} (ha : a ∈ T) : invR ha * (xR W T - algebraMap k _ a) = 1 :=
  Subtype.ext (inv_mul_cancel₀ (xGen_sub_ne_zero W a))

lemma isUnit_xR_sub {a : k} (ha : a ∈ T) : IsUnit (xR W T - algebraMap k _ a) :=
  isUnit_iff_exists_inv'.mpr ⟨invR ha, invR_mul ha⟩

variable (W T) in
lemma equation_R : (W.toAffine⁄(ringOfX W T)).Equation (xR W T) (yR W T) :=
  (W.toAffine.baseChange_equation (f := (ringOfX W T).val) Subtype.val_injective _ _).mp
    (equation_gen W)

variable (T) in
/-- The `y`-coordinate of `ε • (x, y)` as an element of `ringOfX W T`. -/
def yεR (ε : ℤˣ) : ringOfX W T :=
  if ε = 1 then yR W T else (W.toAffine⁄(ringOfX W T)).negY (xR W T) (yR W T)

namespace AffAut

variable [DecidableEq k]

/-- The slope `(y(ε • gen) - y(m)) / (x - x(m))` as an element of `ringOfX W T`. -/
def slopeR (g : AffAut W) (hm : xOf g.m ∈ T) : ringOfX W T :=
  (yεR T g.ε - algebraMap k _ (yOf g.m)) * invR hm

/-- The `x`-coordinate of `g(genericPoint W) = ε • gen + m` as an element of `ringOfX W T`, for
`m ≠ 0` with `x(m) ∈ T`. -/
def xR (g : AffAut W) (hm : xOf g.m ∈ T) : ringOfX W T :=
  (W.toAffine⁄(ringOfX W T)).addX (Orbicurve.xR W T) (algebraMap k _ (xOf g.m)) (slopeR g hm)

/-- The `y`-coordinate of `g(genericPoint W) = ε • gen + m` as an element of `ringOfX W T`, for
`m ≠ 0` with `x(m) ∈ T`. -/
def yR (g : AffAut W) (hm : xOf g.m ∈ T) : ringOfX W T :=
  (W.toAffine⁄(ringOfX W T)).addY (Orbicurve.xR W T) (algebraMap k _ (xOf g.m)) (yεR T g.ε)
    (slopeR g hm)

end AffAut

/-! ### Points given by algebra maps out of `ringOfX W T` -/

section PointOf

variable [W.IsElliptic] {L : Type*} [Field L] [Algebra k L]

/-- The point `(χ x, χ y) ∈ W(L)` given by a `k`-algebra map `χ : ringOfX W T → L`. -/
def pointOf (χ : ringOfX W T →ₐ[k] L) : (W.toAffine⁄L).Point :=
  .some (χ (xR W T)) (χ (yR W T)) (nonsingular_of_equation ((equation_R W T).baseChange χ))

@[simp] lemma pointOf_ne_zero (χ : ringOfX W T →ₐ[k] L) : pointOf χ ≠ 0 := Point.some_ne_zero _

@[simp] lemma xOf_pointOf (χ : ringOfX W T →ₐ[k] L) : xOf (pointOf χ) = χ (xR W T) := rfl

@[simp] lemma yOf_pointOf (χ : ringOfX W T →ₐ[k] L) : yOf (pointOf χ) = χ (yR W T) := rfl

lemma pointOf_val : pointOf (ringOfX W T).val = genericPoint W := rfl

lemma xOf_pointOf_ne (χ : ringOfX W T →ₐ[k] L) {a : k} (ha : a ∈ T) :
    xOf (pointOf χ) ≠ algebraMap k L a := fun h => by
  have := congrArg χ (invR_mul ha)
  rw [map_mul, map_sub, AlgHom.commutes, map_one, ← xOf_pointOf, h, sub_self, mul_zero] at this
  exact zero_ne_one this

variable [DecidableEq L]

lemma yOf_units_smul_pointOf (χ : ringOfX W T →ₐ[k] L) (ε : ℤˣ) :
    yOf (ε • pointOf χ) = χ (yεR T ε) := by
  rw [yOf_units_smul _ _ (pointOf_ne_zero χ), yεR]
  split_ifs
  · rfl
  · exact (W.toAffine.baseChange_negY χ _ _)

variable [DecidableEq k]

/-- The coordinates of `g(pointOf χ)` for `g = (ε, m)` with `m ≠ 0`, `x(m) ∈ T`. -/
theorem act_pointOf (χ : ringOfX W T →ₐ[k] L) (g : AffAut W) (hm0 : g.m ≠ 0)
    (hm : xOf g.m ∈ T) :
    g.act L (pointOf χ) ≠ 0 ∧ xOf (g.act L (pointOf χ)) = χ (g.xR hm) ∧
      yOf (g.act L (pointOf χ)) = χ (g.yR hm) := by
  have hP := units_smul_ne_zero g.ε (pointOf_ne_zero χ)
  have hR : bc W L g.m ≠ 0 := by rwa [Ne, bc_eq_zero_iff]
  have hxP : xOf (g.ε • pointOf χ) = χ (xR W T) := by rw [xOf_units_smul, xOf_pointOf]
  have hyP := yOf_units_smul_pointOf χ g.ε
  have hxR : xOf (bc W L g.m) = χ (algebraMap k _ (xOf g.m)) := by
    rw [xOf_bc, AlgHom.commutes]
  have hyR : yOf (bc W L g.m) = χ (algebraMap k _ (yOf g.m)) := by
    rw [yOf_bc, AlgHom.commutes]
  have hne : xOf (g.ε • pointOf χ) ≠ xOf (bc W L g.m) := by
    rw [xOf_units_smul, xOf_bc]
    exact xOf_pointOf_ne χ hm
  have hslope : (yOf (g.ε • pointOf χ) - yOf (bc W L g.m)) /
      (xOf (g.ε • pointOf χ) - xOf (bc W L g.m)) = χ (g.slopeR hm) := by
    have hinv := congrArg χ (invR_mul hm)
    rw [map_mul, map_one] at hinv
    rw [AffAut.slopeR, map_mul, hyP, hyR, hxP, hxR, ← map_sub, ← map_sub,
      eq_inv_of_mul_eq_one_left hinv, div_eq_mul_inv]
  obtain ⟨h0, hx, hy⟩ := add_of_xOf_ne hP hR hne
  rw [hslope, hxP, hxR] at hx
  rw [hslope, hxP, hxR, hyP] at hy
  refine ⟨h0, ?_, ?_⟩
  · rw [AffAut.act_def, hx, AffAut.xR, baseChange_addX]
  · rw [AffAut.act_def, hy, AffAut.yR, baseChange_addY]

/-- The coordinates of `g(pointOf χ)` for `g = (ε, 0)`. -/
theorem act_pointOf_of_m_eq_zero (χ : ringOfX W T →ₐ[k] L) (g : AffAut W) (hm0 : g.m = 0) :
    g.act L (pointOf χ) ≠ 0 ∧ xOf (g.act L (pointOf χ)) = χ (xR W T) ∧
      yOf (g.act L (pointOf χ)) = χ (yεR T g.ε) := by
  rw [AffAut.act_def, hm0, map_zero, add_zero]
  exact ⟨units_smul_ne_zero g.ε (pointOf_ne_zero χ), by rw [xOf_units_smul, xOf_pointOf],
    yOf_units_smul_pointOf χ g.ε⟩

/-- The coordinates of `g(genericPoint W)` lie in `ringOfX W T` if `x(m) ∈ T` for `m ≠ 0`. -/
theorem coords_act_genericPoint_mem (g : AffAut W) (hm : g.m ≠ 0 → xOf g.m ∈ T) :
    xOf (g.act _ (genericPoint W)) ∈ ringOfX W T ∧
      yOf (g.act _ (genericPoint W)) ∈ ringOfX W T := by
  rw [← pointOf_val (T := T)]
  by_cases hm0 : g.m = 0
  · obtain ⟨-, hx, hy⟩ := act_pointOf_of_m_eq_zero (ringOfX W T).val g hm0
    rw [hx, hy]
    exact ⟨Subtype.prop _, Subtype.prop _⟩
  · obtain ⟨-, hx, hy⟩ := act_pointOf (ringOfX W T).val g hm0 (hm hm0)
    rw [hx, hy]
    exact ⟨Subtype.prop _, Subtype.prop _⟩

lemma pullback_xGen_mem (g : AffAut W) (hm : g.m ≠ 0 → xOf g.m ∈ T) :
    pullback W g (xGen W) ∈ ringOfX W T := by
  rw [pullback_xGen]
  exact (coords_act_genericPoint_mem g hm).1

lemma pullback_yGen_mem (g : AffAut W) (hm : g.m ≠ 0 → xOf g.m ∈ T) :
    pullback W g (yGen W) ∈ ringOfX W T := by
  rw [pullback_yGen]
  exact (coords_act_genericPoint_mem g hm).2

end PointOf

end

end TemperedFundamentalGroups.Orbicurve
