/-
Copyright (c) 2026 The tempered-fundamental-groups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import TemperedFundamentalGroups.Orbicurve.Ring

/-!
# Geometric zero sets and the ring of functions regular away from a set of `k̄`-points

Let `W` be an elliptic curve over a field `k`, `k̄ = AlgebraicClosure k` and `k[W]` the affine
coordinate ring. An affine point `Q ∈ W(k̄)` gives the evaluation `evalPt hQ : k[W] →ₐ[k] k̄`, and
every `k`-algebra map `k[W] → k̄` is of this form (`eq_evalHom`). The *geometric zero set*
`zeroSet W h ⊆ W(k̄)` of `h ∈ k[W]` is the set of affine points `Q` with `h(Q) = 0`.

For a set `𝒮 ⊆ W(k̄)` of geometric points, `ringAway W 𝒮` is the `k`-subalgebra of the function
field generated by `k[W]` and the inverses `h⁻¹` of the `h ∈ k[W]` with `zeroSet W h ⊆ 𝒮`: the
ring of functions regular on `W ∖ ({0} ∪ 𝒮)`. Unlike `ringOf W S` (which only removes rational
points), it removes arbitrary closed points, e.g. non-rational torsion points.

We also set up the localizations `Localization.Away D` of `k[W]` as subrings of `k(W)`
(`locMap`) together with their evaluations at points `Q` with `D(Q) ≠ 0` (`evalLoc`).

## Main definitions

* `GeomPoint W`: the points `W(k̄)`.
* `evalPt hQ`: evaluation `k[W] →ₐ[k] L` at an affine point `Q ≠ 0` of `W(L)`.
* `zeroSet W h`: the geometric zero set of `h ∈ k[W]`.
* `ringAway W 𝒮`: the ring of functions regular away from `{0} ∪ 𝒮`.
* `locMap D hD`: the embedding `k[W][D⁻¹] → k(W)`.
-/

universe u

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

namespace TemperedFundamentalGroups.Orbicurve

noncomputable section

/-- A (classical) decidable equality on the algebraic closure, needed for its group of points. -/
instance decidableEqAlgebraicClosure (k : Type*) [Field k] :
    DecidableEq (AlgebraicClosure k) :=
  Classical.decEq _

variable {k : Type u} [Field k] (W : WeierstrassCurve k)

/-- The geometric points `W(k̄)`, `k̄ = AlgebraicClosure k`. -/
abbrev GeomPoint : Type u := (W.toAffine⁄(AlgebraicClosure k)).Point

/-- The coordinate `x` as an element of the coordinate ring `k[W]`. -/
def xC : W.toAffine.CoordinateRing := AdjoinRoot.mk W.toAffine.polynomial (C X)

/-- The coordinate `y` as an element of the coordinate ring `k[W]`. -/
def yC : W.toAffine.CoordinateRing := AdjoinRoot.mk W.toAffine.polynomial X

@[simp] lemma algebraMap_xC : algebraMap _ (funField W) (xC W) = xGen W := rfl

@[simp] lemma algebraMap_yC : algebraMap _ (funField W) (yC W) = yGen W := rfl

lemma injective_algebraMap_funField :
    Function.Injective (algebraMap W.toAffine.CoordinateRing (funField W)) :=
  IsFractionRing.injective _ _

/-! ### Algebra maps out of `k[W]` -/

section AlgHom

variable {W} {A B : Type*} [CommRing A] [CommRing B] [Algebra k A] [Algebra k B]

/-- A `k`-algebra map out of `k[W]` is determined by the images of `x` and `y`. -/
lemma coordRing_algHom_ext {φ ψ : W.toAffine.CoordinateRing →ₐ[k] A}
    (hx : φ (xC W) = ψ (xC W)) (hy : φ (yC W) = ψ (yC W)) : φ = ψ := by
  refine AdjoinRoot.algHom_ext' (Polynomial.algHom_ext ?_) hy
  simpa [xC, AdjoinRoot.mk_C] using hx

lemma evalHom_xC (x y : A) (h : (W.toAffine⁄A).Equation x y) : evalHom W x y h (xC W) = x :=
  evalHom_x x y h

lemma evalHom_yC (x y : A) (h : (W.toAffine⁄A).Equation x y) : evalHom W x y h (yC W) = y :=
  evalHom_y x y h

lemma comp_evalHom (φ : A →ₐ[k] B) (x y : A) (h : (W.toAffine⁄A).Equation x y) :
    φ.comp (evalHom W x y h) = evalHom W (φ x) (φ y) (h.baseChange φ) :=
  coordRing_algHom_ext (by simp [evalHom_xC]) (by simp [evalHom_yC])

variable (W) in
lemma equation_C : (W.toAffine⁄W.toAffine.CoordinateRing).Equation (xC W) (yC W) :=
  (W.toAffine.baseChange_equation (f := IsScalarTower.toAlgHom k _ (funField W))
    (injective_algebraMap_funField W) _ _).mp (equation_gen W)

/-- Every `k`-algebra map out of `k[W]` is the evaluation at the images of `x` and `y`. -/
lemma eq_evalHom (φ : W.toAffine.CoordinateRing →ₐ[k] A) :
    φ = evalHom W (φ (xC W)) (φ (yC W)) ((equation_C W).baseChange φ) :=
  coordRing_algHom_ext (by rw [evalHom_xC]) (by rw [evalHom_yC])

end AlgHom

/-! ### Evaluation at points and zero sets -/

section ZeroSet

variable {W} {L : Type*} [Field L] [Algebra k L]

/-- The evaluation `k[W] →ₐ[k] L` at an affine point `Q ≠ 0` of `W(L)`. -/
def evalPt {Q : (W.toAffine⁄L).Point} (hQ : Q ≠ 0) : W.toAffine.CoordinateRing →ₐ[k] L :=
  evalHom W (xOf Q) (yOf Q) (equation_xOf_yOf hQ)

@[simp] lemma evalPt_xC {Q : (W.toAffine⁄L).Point} (hQ : Q ≠ 0) : evalPt hQ (xC W) = xOf Q :=
  evalHom_xC _ _ _

@[simp] lemma evalPt_yC {Q : (W.toAffine⁄L).Point} (hQ : Q ≠ 0) : evalPt hQ (yC W) = yOf Q :=
  evalHom_yC _ _ _

@[simp] lemma evalPt_algebraMap_polynomial {Q : (W.toAffine⁄L).Point} (hQ : Q ≠ 0) (p : k[X]) :
    evalPt hQ (algebraMap k[X] W.toAffine.CoordinateRing p) = aeval (xOf Q) p := by
  rw [AdjoinRoot.algebraMap_eq]
  exact evalHom_of _ _ _ p

/-- The affine point of `W(L)` given by a `k`-algebra map `k[W] → L`. -/
def pointOfC [W.IsElliptic] (φ : W.toAffine.CoordinateRing →ₐ[k] L) : (W.toAffine⁄L).Point :=
  .some (φ (xC W)) (φ (yC W)) (nonsingular_of_equation ((equation_C W).baseChange φ))

lemma pointOfC_ne_zero [W.IsElliptic] (φ : W.toAffine.CoordinateRing →ₐ[k] L) :
    pointOfC φ ≠ 0 :=
  Point.some_ne_zero _

lemma evalPt_pointOfC [W.IsElliptic] (φ : W.toAffine.CoordinateRing →ₐ[k] L) :
    evalPt (pointOfC_ne_zero φ) = φ :=
  coordRing_algHom_ext (by rw [evalPt_xC]; rfl) (by rw [evalPt_yC]; rfl)

lemma evalPt_congr {Q Q' : (W.toAffine⁄L).Point} (hQ : Q ≠ 0) (h : Q = Q') :
    evalPt hQ = evalPt (h ▸ hQ) := by
  subst h
  rfl

variable (W) in
/-- The geometric zero set of `h ∈ k[W]`: the affine points `Q ∈ W(k̄)` with `h(Q) = 0`. -/
def zeroSet (h : W.toAffine.CoordinateRing) : Set (GeomPoint W) :=
  {Q | ∃ hQ : Q ≠ 0, evalPt hQ h = 0}

lemma mem_zeroSet {h : W.toAffine.CoordinateRing} {Q : GeomPoint W} :
    Q ∈ zeroSet W h ↔ ∃ hQ : Q ≠ 0, evalPt hQ h = 0 :=
  Iff.rfl

lemma ne_zero_of_mem_zeroSet {h : W.toAffine.CoordinateRing} {Q : GeomPoint W}
    (hQ : Q ∈ zeroSet W h) : Q ≠ 0 :=
  hQ.1

lemma zero_notMem_zeroSet (h : W.toAffine.CoordinateRing) : (0 : GeomPoint W) ∉ zeroSet W h :=
  fun hQ => hQ.1 rfl

lemma zeroSet_mul (a b : W.toAffine.CoordinateRing) :
    zeroSet W (a * b) = zeroSet W a ∪ zeroSet W b := by
  ext Q
  simp only [Set.mem_union, mem_zeroSet, map_mul, mul_eq_zero]
  constructor
  · rintro ⟨hQ, h | h⟩
    exacts [Or.inl ⟨hQ, h⟩, Or.inr ⟨hQ, h⟩]
  · rintro (⟨hQ, h⟩ | ⟨hQ, h⟩)
    exacts [⟨hQ, Or.inl h⟩, ⟨hQ, Or.inr h⟩]

lemma zeroSet_pow (a : W.toAffine.CoordinateRing) {n : ℕ} (hn : n ≠ 0) :
    zeroSet W (a ^ n) = zeroSet W a := by
  ext Q
  simp only [mem_zeroSet, map_pow, pow_eq_zero_iff hn]

lemma zeroSet_one : zeroSet W 1 = ∅ := by
  ext Q
  simp [mem_zeroSet]

lemma mem_zeroSet_xC_sub (a : k) {Q : GeomPoint W} :
    Q ∈ zeroSet W (xC W - algebraMap k _ a) ↔ Q ≠ 0 ∧ xOf Q = algebraMap k _ a := by
  simp only [mem_zeroSet, map_sub, AlgHom.commutes, evalPt_xC, sub_eq_zero, exists_prop]

end ZeroSet

/-! ### The ring of functions regular away from a set of geometric points -/

section RingAway

/-- The ring of functions regular on `W ∖ ({0} ∪ 𝒮)`, for a set `𝒮 ⊆ W(k̄)` of geometric points:
the `k`-subalgebra of `k(W)` generated by `k[W]` and the inverses `h⁻¹` of the `h ∈ k[W]` all
of whose geometric zeros lie in `𝒮`. -/
def ringAway (𝒮 : Set (GeomPoint W)) : Subalgebra k (funField W) :=
  Algebra.adjoin k (Set.range (algebraMap W.toAffine.CoordinateRing (funField W)) ∪
    {f | ∃ h, zeroSet W h ⊆ 𝒮 ∧ f = (algebraMap _ (funField W) h)⁻¹})

variable {W} {𝒮 𝒮' : Set (GeomPoint W)}

lemma algebraMap_mem_ringAway (c : W.toAffine.CoordinateRing) :
    algebraMap _ (funField W) c ∈ ringAway W 𝒮 :=
  Algebra.subset_adjoin (Or.inl ⟨c, rfl⟩)

lemma inv_mem_ringAway {h : W.toAffine.CoordinateRing} (hh : zeroSet W h ⊆ 𝒮) :
    (algebraMap _ (funField W) h)⁻¹ ∈ ringAway W 𝒮 :=
  Algebra.subset_adjoin (Or.inr ⟨h, hh, rfl⟩)

lemma ringAway_mono (h : 𝒮 ⊆ 𝒮') : ringAway W 𝒮 ≤ ringAway W 𝒮' := by
  refine Algebra.adjoin_mono (Set.union_subset_union_right _ ?_)
  rintro _ ⟨g, hg, rfl⟩
  exact ⟨g, hg.trans h, rfl⟩

/-- A subalgebra containing `k[W]` and the inverses of the functions vanishing only on `𝒮`
contains `ringAway W 𝒮`. -/
lemma ringAway_le {B : Subalgebra k (funField W)}
    (h₁ : ∀ c, algebraMap W.toAffine.CoordinateRing (funField W) c ∈ B)
    (h₂ : ∀ h, zeroSet W h ⊆ 𝒮 → (algebraMap _ (funField W) h)⁻¹ ∈ B) : ringAway W 𝒮 ≤ B := by
  refine Algebra.adjoin_le ?_
  rintro _ (⟨c, rfl⟩ | ⟨h, hh, rfl⟩)
  exacts [h₁ c, h₂ h hh]

lemma xGen_mem_ringAway : xGen W ∈ ringAway W 𝒮 := algebraMap_mem_ringAway (xC W)

lemma yGen_mem_ringAway : yGen W ∈ ringAway W 𝒮 := algebraMap_mem_ringAway (yC W)

end RingAway

/-! ### Localizations of `k[W]` inside `k(W)` -/

section Localization

variable {W} (D : W.toAffine.CoordinateRing)

lemma isUnit_algebraMap_of_mem_powers {D : W.toAffine.CoordinateRing} (hD : D ≠ 0)
    (y : Submonoid.powers D) :
    IsUnit (IsScalarTower.toAlgHom k W.toAffine.CoordinateRing (funField W) y) := by
  obtain ⟨n, hn⟩ := y.2
  rw [IsScalarTower.coe_toAlgHom', ← hn, map_pow]
  exact (IsUnit.mk0 _ ((map_ne_zero_iff _ (injective_algebraMap_funField W)).mpr hD)).pow n

/-- The embedding `k[W][D⁻¹] → k(W)` of the localization of `k[W]` away from `D ≠ 0`. -/
def locMap (hD : D ≠ 0) : Localization.Away D →ₐ[k] funField W :=
  IsLocalization.liftAlgHom (M := Submonoid.powers D) (isUnit_algebraMap_of_mem_powers hD)

variable {D}

@[simp] lemma locMap_algebraMap (hD : D ≠ 0) (c : W.toAffine.CoordinateRing) :
    locMap D hD (algebraMap _ _ c) = algebraMap _ (funField W) c := by
  rw [locMap, IsLocalization.liftAlgHom_apply, IsLocalization.lift_eq]
  rfl

lemma locMap_mk' (hD : D ≠ 0) (a : W.toAffine.CoordinateRing) (n : ℕ) :
    locMap D hD (IsLocalization.mk' _ a (⟨D ^ n, n, rfl⟩ : Submonoid.powers D)) =
      algebraMap _ (funField W) a * (algebraMap _ (funField W) D)⁻¹ ^ n := by
  have hD' : algebraMap _ (funField W) D ≠ 0 :=
    (map_ne_zero_iff _ (injective_algebraMap_funField W)).mpr hD
  have h := IsLocalization.mk'_spec (Localization.Away D) a
    (⟨D ^ n, n, rfl⟩ : Submonoid.powers D)
  have h' := congrArg (locMap D hD) h
  rw [map_mul, locMap_algebraMap, locMap_algebraMap, map_pow] at h'
  rw [inv_pow, eq_mul_inv_iff_mul_eq₀ (pow_ne_zero _ hD'), h']

lemma exists_mk' (z : Localization.Away D) :
    ∃ (a : W.toAffine.CoordinateRing) (n : ℕ),
      z = IsLocalization.mk' _ a (⟨D ^ n, n, rfl⟩ : Submonoid.powers D) := by
  obtain ⟨⟨a, ⟨_, n, rfl⟩⟩, rfl⟩ := IsLocalization.mk'_surjective (Submonoid.powers D) z
  exact ⟨a, n, rfl⟩

lemma injective_locMap (hD : D ≠ 0) : Function.Injective (locMap D hD) := by
  refine (injective_iff_map_eq_zero _).mpr fun z hz => ?_
  obtain ⟨a, n, rfl⟩ := exists_mk' z
  have hD' : algebraMap _ (funField W) D ≠ 0 :=
    (map_ne_zero_iff _ (injective_algebraMap_funField W)).mpr hD
  rw [locMap_mk', mul_eq_zero, _root_.map_eq_zero_iff _ (injective_algebraMap_funField W)] at hz
  rcases hz with rfl | hz
  · exact IsLocalization.mk'_zero _
  · exact absurd hz (pow_ne_zero _ (inv_ne_zero hD'))

lemma mem_range_locMap (hD : D ≠ 0) {f : funField W} :
    f ∈ (locMap D hD).range ↔ ∃ (a : W.toAffine.CoordinateRing) (n : ℕ),
      f = algebraMap _ (funField W) a * (algebraMap _ (funField W) D)⁻¹ ^ n := by
  constructor
  · rintro ⟨z, rfl⟩
    obtain ⟨a, n, rfl⟩ := exists_mk' z
    exact ⟨a, n, locMap_mk' hD a n⟩
  · rintro ⟨a, n, rfl⟩
    exact ⟨_, locMap_mk' hD a n⟩

lemma algebraMap_mem_range_locMap (hD : D ≠ 0) (c : W.toAffine.CoordinateRing) :
    algebraMap _ (funField W) c ∈ (locMap D hD).range :=
  ⟨_, locMap_algebraMap hD c⟩

lemma inv_mem_range_locMap (hD : D ≠ 0) :
    (algebraMap _ (funField W) D)⁻¹ ∈ (locMap D hD).range :=
  (mem_range_locMap hD).mpr ⟨1, 1, by rw [map_one, one_mul, pow_one]⟩

/-- The inverse of `locMap` on its range. -/
def locMapInv (hD : D ≠ 0) : (locMap D hD).range →ₐ[k] Localization.Away D :=
  (AlgEquiv.ofInjective _ (injective_locMap hD)).symm.toAlgHom

@[simp] lemma locMap_locMapInv (hD : D ≠ 0) (f : (locMap D hD).range) :
    locMap D hD (locMapInv hD f) = f :=
  congrArg Subtype.val ((AlgEquiv.ofInjective _ (injective_locMap hD)).apply_symm_apply f)

section Eval

variable {L : Type*} [Field L] [Algebra k L]

lemma isUnit_of_mem_powers {φ : W.toAffine.CoordinateRing →ₐ[k] L} (hφ : φ D ≠ 0)
    (y : Submonoid.powers D) : IsUnit (φ y) := by
  obtain ⟨n, hn⟩ := y.2
  rw [← hn, map_pow]
  exact (IsUnit.mk0 _ hφ).pow n

/-- The extension of a `k`-algebra map `φ : k[W] → L` with `φ D ≠ 0` to `k[W][D⁻¹]`. -/
def evalLoc (φ : W.toAffine.CoordinateRing →ₐ[k] L) (hφ : φ D ≠ 0) :
    Localization.Away D →ₐ[k] L :=
  IsLocalization.liftAlgHom (M := Submonoid.powers D) (isUnit_of_mem_powers hφ)

@[simp] lemma evalLoc_algebraMap (φ : W.toAffine.CoordinateRing →ₐ[k] L) (hφ : φ D ≠ 0)
    (c : W.toAffine.CoordinateRing) : evalLoc φ hφ (algebraMap _ _ c) = φ c := by
  rw [evalLoc, IsLocalization.liftAlgHom_apply, IsLocalization.lift_eq]
  rfl

lemma evalLoc_mk'_mul (φ : W.toAffine.CoordinateRing →ₐ[k] L) (hφ : φ D ≠ 0)
    (a : W.toAffine.CoordinateRing) (n : ℕ) :
    evalLoc φ hφ (IsLocalization.mk' _ a (⟨D ^ n, n, rfl⟩ : Submonoid.powers D)) * φ D ^ n =
      φ a := by
  have h := congrArg (evalLoc φ hφ) (IsLocalization.mk'_spec (Localization.Away D) a
    (⟨D ^ n, n, rfl⟩ : Submonoid.powers D))
  rwa [map_mul, evalLoc_algebraMap, evalLoc_algebraMap, map_pow] at h

end Eval

end Localization

end

end TemperedFundamentalGroups.Orbicurve
